export const regions: Record<string, string[]> = {
  Italy: [
    'Toscana',
    'Piemonte',
    'Veneto',
    'Lombardia',
    'Sicilia',
    'Puglia',
    'Emilia-Romagna',
    'Marche',
    'Campania',
    'Trentino-Alto Adige',
    'Umbria',
    'Abruzzo',
    'Friuli-Venezia Giulia',
    'Sardegna',
    'Lazio',
    'Calabria',
    'Basilicata',
    'Liguria',
    'Molise',
    'Valle d\'Aosta'
  ],
  France: [
    'Bordeaux',
    'Bourgogne',
    'Champagne',
    'Alsace',
    'Loire',
    'Rhône',
    'Languedoc-Roussillon',
    'Provence',
    'Sud-Ouest',
    'Beaujolais',
    'Jura',
    'Savoie',
    'Corse'
  ],
  Spain: [
    'Rioja',
    'Ribera del Duero',
    'Priorat',
    'Rías Baixas',
    'Jerez',
    'Penedès',
    'Rueda',
    'Toro',
    'Navarra',
    'Somontano',
    'Jumilla',
    'La Mancha',
    'Valencia',
    'Catalonia'
  ],
  USA: [
    'Napa Valley',
    'Sonoma',
    'Paso Robles',
    'Willamette Valley',
    'Santa Barbara',
    'Russian River Valley',
    'Walla Walla',
    'Finger Lakes',
    'Columbia Valley',
    'Mendocino',
    'Central Coast',
    'Alexander Valley'
  ],
  Argentina: [
    'Mendoza',
    'Salta',
    'Patagonia',
    'San Juan',
    'La Rioja',
    'Catamarca',
    'Neuquén'
  ],
  Australia: [
    'Barossa Valley',
    'Margaret River',
    'Hunter Valley',
    'Yarra Valley',
    'McLaren Vale',
    'Coonawarra',
    'Clare Valley',
    'Adelaide Hills',
    'Tasmania'
  ],
  Germany: [
    'Mosel',
    'Rheingau',
    'Pfalz',
    'Rheinhessen',
    'Baden',
    'Franken',
    'Nahe',
    'Württemberg',
    'Ahr'
  ],
  Portugal: [
    'Douro',
    'Dão',
    'Alentejo',
    'Vinho Verde',
    'Bairrada',
    'Setúbal',
    'Madeira',
    'Azores'
  ],
  'South Africa': [
    'Stellenbosch',
    'Paarl',
    'Franschhoek',
    'Constantia',
    'Swartland',
    'Walker Bay',
    'Elgin',
    'Robertson'
  ],
  Chile: [
    'Maipo Valley',
    'Colchagua Valley',
    'Casablanca Valley',
    'Aconcagua Valley',
    'Cachapoal Valley',
    'Curicó Valley',
    'Limarí Valley',
    'Elqui Valley'
  ]
};