import { Wine } from '@/types/wine';

export const testWines: Wine[] = [
  {
    id: 'test-001',
    name: 'Brunello di Montalcino - Biondi Santi',
    year: 2015,
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    grapeVariety: 'Sangiovese',
    supplier: 'Italian Wine Imports',
    purchasePrice: 85,
    sellingPrice: 180,
    quantity: 12,
    minQuantity: 6,
    quantityTarget: 18,
    averageWeeklySales: 2,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Premium Brunello, excellent vintage',
    sales: []
  },
  {
    id: 'test-002',
    name: 'Barolo - Giacomo Conterno',
    year: 2016,
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    grapeVariety: 'Nebbiolo',
    supplier: 'Piedmont Wines Ltd',
    purchasePrice: 95,
    sellingPrice: 210,
    quantity: 8,
    minQuantity: 4,
    quantityTarget: 12,
    averageWeeklySales: 1.5,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Classic Barolo, needs decanting',
    sales: []
  },
  {
    id: 'test-003',
    name: 'Chianti Classico Riserva - Antinori',
    year: 2018,
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    grapeVariety: 'Sangiovese',
    supplier: 'Tuscan Selections',
    purchasePrice: 28,
    sellingPrice: 65,
    quantity: 24,
    minQuantity: 12,
    quantityTarget: 36,
    averageWeeklySales: 4,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Popular choice, high turnover',
    sales: []
  },
  {
    id: 'test-004',
    name: 'Amarone della Valpolicella - Allegrini',
    year: 2017,
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    supplier: 'Veneto Direct',
    purchasePrice: 55,
    sellingPrice: 125,
    quantity: 15,
    minQuantity: 8,
    quantityTarget: 24,
    averageWeeklySales: 2.5,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Rich and full-bodied',
    sales: []
  },
  {
    id: 'test-005',
    name: 'Barbaresco - Gaja',
    year: 2018,
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    grapeVariety: 'Nebbiolo',
    supplier: 'Piedmont Wines Ltd',
    purchasePrice: 78,
    sellingPrice: 165,
    quantity: 6,
    minQuantity: 6,
    quantityTarget: 12,
    averageWeeklySales: 1,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Elegant and refined',
    sales: []
  },
  {
    id: 'test-006',
    name: 'Sassicaia - Tenuta San Guido',
    year: 2019,
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    grapeVariety: 'Cabernet Sauvignon, Cabernet Franc',
    supplier: 'Super Tuscan Imports',
    purchasePrice: 180,
    sellingPrice: 380,
    quantity: 3,
    minQuantity: 2,
    quantityTarget: 6,
    averageWeeklySales: 0.5,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Iconic Super Tuscan',
    sales: []
  },
  {
    id: 'test-007',
    name: 'Prosecco Superiore - Bisol',
    year: 2022,
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    grapeVariety: 'Glera',
    supplier: 'Sparkling Selections',
    purchasePrice: 18,
    sellingPrice: 42,
    quantity: 36,
    minQuantity: 24,
    quantityTarget: 48,
    averageWeeklySales: 6,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Best-seller, reorder frequently',
    sales: []
  },
  {
    id: 'test-008',
    name: "Franciacorta - Ca' del Bosco",
    year: 2019,
    type: 'Sparkling',
    country: 'Italy',
    region: 'Lombardy',
    grapeVariety: 'Chardonnay, Pinot Noir',
    supplier: 'Lombardy Wines',
    purchasePrice: 42,
    sellingPrice: 95,
    quantity: 18,
    minQuantity: 12,
    quantityTarget: 24,
    averageWeeklySales: 2,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Italian champagne alternative',
    sales: []
  },
  {
    id: 'test-009',
    name: 'Gavi di Gavi - La Scolca',
    year: 2021,
    type: 'White',
    country: 'Italy',
    region: 'Piedmont',
    grapeVariety: 'Cortese',
    supplier: 'Piedmont Wines Ltd',
    purchasePrice: 22,
    sellingPrice: 52,
    quantity: 20,
    minQuantity: 12,
    quantityTarget: 30,
    averageWeeklySales: 3,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Crisp and refreshing',
    sales: []
  },
  {
    id: 'test-010',
    name: 'Tignanello - Antinori',
    year: 2018,
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    grapeVariety: 'Sangiovese, Cabernet Sauvignon',
    supplier: 'Super Tuscan Imports',
    purchasePrice: 95,
    sellingPrice: 210,
    quantity: 9,
    minQuantity: 6,
    quantityTarget: 12,
    averageWeeklySales: 1,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'First Super Tuscan',
    sales: []
  },
  {
    id: 'test-011',
    name: 'Châteauneuf-du-Pape - Château de Beaucastel',
    year: 2019,
    type: 'Red',
    country: 'France',
    region: 'Rhône Valley',
    grapeVariety: 'Grenache, Syrah, Mourvèdre',
    supplier: 'French Wine Co',
    purchasePrice: 68,
    sellingPrice: 145,
    quantity: 12,
    minQuantity: 6,
    quantityTarget: 18,
    averageWeeklySales: 1.5,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Complex Rhône blend',
    sales: []
  },
  {
    id: 'test-012',
    name: 'Bordeaux - Château Margaux',
    year: 2016,
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    supplier: 'Bordeaux Direct',
    purchasePrice: 450,
    sellingPrice: 950,
    quantity: 2,
    minQuantity: 1,
    quantityTarget: 3,
    averageWeeklySales: 0.2,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'First Growth, special occasions',
    sales: []
  },
  {
    id: 'test-013',
    name: 'Champagne Brut - Dom Pérignon',
    year: 2012,
    type: 'Sparkling',
    country: 'France',
    region: 'Champagne',
    grapeVariety: 'Chardonnay, Pinot Noir',
    supplier: 'Champagne House',
    purchasePrice: 145,
    sellingPrice: 320,
    quantity: 8,
    minQuantity: 4,
    quantityTarget: 12,
    averageWeeklySales: 1,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Prestige cuvée',
    sales: []
  },
  {
    id: 'test-014',
    name: 'Sancerre - Domaine Vacheron',
    year: 2021,
    type: 'White',
    country: 'France',
    region: 'Loire Valley',
    grapeVariety: 'Sauvignon Blanc',
    supplier: 'Loire Selections',
    purchasePrice: 32,
    sellingPrice: 72,
    quantity: 18,
    minQuantity: 12,
    quantityTarget: 24,
    averageWeeklySales: 2.5,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Mineral and fresh',
    sales: []
  },
  {
    id: 'test-015',
    name: 'Etna Rosso - Passopisciaro',
    year: 2019,
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    grapeVariety: 'Nerello Mascalese',
    supplier: 'Sicilian Wines',
    purchasePrice: 42,
    sellingPrice: 92,
    quantity: 10,
    minQuantity: 6,
    quantityTarget: 12,
    averageWeeklySales: 1,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Volcanic terroir',
    sales: []
  },
  {
    id: 'test-016',
    name: "Nero d'Avola - Planeta",
    year: 2020,
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    grapeVariety: "Nero d'Avola",
    supplier: 'Sicilian Selections',
    purchasePrice: 24,
    sellingPrice: 55,
    quantity: 20,
    minQuantity: 12,
    quantityTarget: 24,
    averageWeeklySales: 2,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Sicilian classic',
    sales: []
  },
  {
    id: 'test-017',
    name: 'Taurasi - Mastroberardino',
    year: 2016,
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    grapeVariety: 'Aglianico',
    supplier: 'Southern Italian Wines',
    purchasePrice: 38,
    sellingPrice: 85,
    quantity: 11,
    minQuantity: 6,
    quantityTarget: 15,
    averageWeeklySales: 1,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Barolo of the South',
    sales: []
  },
  {
    id: 'test-018',
    name: 'Fiano di Avellino - Feudi di San Gregorio',
    year: 2021,
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    grapeVariety: 'Fiano',
    supplier: 'Campanian Wines',
    purchasePrice: 26,
    sellingPrice: 58,
    quantity: 16,
    minQuantity: 10,
    quantityTarget: 20,
    averageWeeklySales: 2,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Aromatic white',
    sales: []
  },
  {
    id: 'test-019',
    name: 'Valpolicella Ripasso - Masi',
    year: 2019,
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    grapeVariety: 'Corvina, Rondinella',
    supplier: 'Veneto Direct',
    purchasePrice: 28,
    sellingPrice: 65,
    quantity: 18,
    minQuantity: 12,
    quantityTarget: 24,
    averageWeeklySales: 2,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Baby Amarone',
    sales: []
  },
  {
    id: 'test-020',
    name: 'Soave Classico - Pieropan',
    year: 2021,
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    grapeVariety: 'Garganega',
    supplier: 'Veneto Whites',
    purchasePrice: 20,
    sellingPrice: 48,
    quantity: 20,
    minQuantity: 12,
    quantityTarget: 30,
    averageWeeklySales: 3,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Classic Soave',
    sales: []
  },
  {
    id: 'test-021',
    name: "Barbera d'Alba - Aldo Conterno",
    year: 2020,
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    grapeVariety: 'Barbera',
    supplier: 'Piedmont Wines Ltd',
    purchasePrice: 28,
    sellingPrice: 65,
    quantity: 15,
    minQuantity: 10,
    quantityTarget: 20,
    averageWeeklySales: 2,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Everyday Piedmont red',
    sales: []
  },
  {
    id: 'test-022',
    name: "Moscato d'Asti - Michele Chiarlo",
    year: 2022,
    type: 'Sparkling',
    country: 'Italy',
    region: 'Piedmont',
    grapeVariety: 'Moscato',
    supplier: 'Piedmont Sparkling',
    purchasePrice: 16,
    sellingPrice: 38,
    quantity: 24,
    minQuantity: 15,
    quantityTarget: 36,
    averageWeeklySales: 3,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Sweet and fizzy',
    sales: []
  },
  {
    id: 'test-023',
    name: 'Burgundy Pinot Noir - Domaine Drouhin',
    year: 2018,
    type: 'Red',
    country: 'France',
    region: 'Burgundy',
    grapeVariety: 'Pinot Noir',
    supplier: 'Burgundy Imports',
    purchasePrice: 65,
    sellingPrice: 140,
    quantity: 8,
    minQuantity: 4,
    quantityTarget: 12,
    averageWeeklySales: 1,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Elegant Burgundy',
    sales: []
  },
  {
    id: 'test-024',
    name: 'Rosso di Montalcino - Il Poggione',
    year: 2020,
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    grapeVariety: 'Sangiovese',
    supplier: 'Montalcino Wines',
    purchasePrice: 28,
    sellingPrice: 65,
    quantity: 18,
    minQuantity: 12,
    quantityTarget: 24,
    averageWeeklySales: 2.5,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Baby Brunello',
    sales: []
  },
  {
    id: 'test-025',
    name: "Ornellaia - Tenuta dell'Ornellaia",
    year: 2018,
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    supplier: 'Super Tuscan Imports',
    purchasePrice: 165,
    sellingPrice: 350,
    quantity: 4,
    minQuantity: 2,
    quantityTarget: 6,
    averageWeeklySales: 0.5,
    lastUpdated: '2025-01-07T00:00:00.000Z',
    notes: 'Super Tuscan icon',
    sales: []
  }
];
