import { WineTemplate } from '@/types/wineDatabase';

/**
 * BORDEAUX RIGHT BANK - Part 3 of 6 (Wines 51-75)
 * Focus: Lalande-de-Pomerol, Fronsac, Canon-Fronsac
 * Updated: January 2025
 */

export const bordeauxRightBankPart3: WineTemplate[] = [
  // LALANDE-DE-POMEROL
  {
    id: 'bordeaux-chateau-les-cruzelles',
    name: 'Château Les Cruzelles',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Lalande-de-Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'AOC Lalande-de-Pomerol',
    minVintage: 1865,
    avgPrice: 45,
    producers: ['Château Les Cruzelles'],
    aliases: ['Les Cruzelles']
  },
  {
    id: 'bordeaux-chateau-bertineau-st-vincent',
    name: 'Château Bertineau St-Vincent',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Lalande-de-Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Lalande-de-Pomerol',
    minVintage: 1986,
    avgPrice: 42,
    producers: ['Château Bertineau St-Vincent'],
    aliases: ['Bertineau St-Vincent']
  },
  {
    id: 'bordeaux-chateau-siaurac',
    name: 'Château Siaurac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Lalande-de-Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'AOC Lalande-de-Pomerol',
    minVintage: 1832,
    avgPrice: 38,
    producers: ['Château Siaurac'],
    aliases: ['Siaurac']
  },
  {
    id: 'bordeaux-chateau-sergant',
    name: 'Château Sergant',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Lalande-de-Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Lalande-de-Pomerol',
    minVintage: 1750,
    avgPrice: 40,
    producers: ['Château Sergant'],
    aliases: ['Sergant']
  },
  {
    id: 'bordeaux-chateau-garraud',
    name: 'Château Garraud',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Lalande-de-Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc, Malbec',
    classification: 'AOC Lalande-de-Pomerol',
    minVintage: 1850,
    avgPrice: 35,
    producers: ['Château Garraud'],
    aliases: ['Garraud']
  },
  {
    id: 'bordeaux-chateau-belles-graves',
    name: 'Château Belles-Graves',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Lalande-de-Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Lalande-de-Pomerol',
    minVintage: 1850,
    avgPrice: 35,
    producers: ['Château Belles-Graves'],
    aliases: ['Belles-Graves']
  },
  {
    id: 'bordeaux-chateau-tournefeuille',
    name: 'Château Tournefeuille',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Lalande-de-Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'AOC Lalande-de-Pomerol',
    minVintage: 1900,
    avgPrice: 40,
    producers: ['Château Tournefeuille'],
    aliases: ['Tournefeuille']
  },
  {
    id: 'bordeaux-chateau-haut-chaigneau',
    name: 'Château Haut-Chaigneau',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Lalande-de-Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'AOC Lalande-de-Pomerol',
    minVintage: 1967,
    avgPrice: 38,
    producers: ['Château Haut-Chaigneau'],
    aliases: ['Haut-Chaigneau']
  },
  
  // CANON-FRONSAC
  {
    id: 'bordeaux-chateau-canon-de-brem',
    name: 'Château Canon de Brem',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Canon-Fronsac',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Canon-Fronsac',
    minVintage: 1760,
    avgPrice: 40,
    producers: ['Château Canon de Brem'],
    aliases: ['Canon de Brem']
  },
  {
    id: 'bordeaux-chateau-moulin-pey-labrie',
    name: 'Château Moulin Pey-Labrie',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Canon-Fronsac',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Canon-Fronsac',
    minVintage: 1868,
    avgPrice: 38,
    producers: ['Château Moulin Pey-Labrie'],
    aliases: ['Moulin Pey-Labrie']
  },
  {
    id: 'bordeaux-chateau-cassagne-haut-canon',
    name: 'Château Cassagne Haut-Canon',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Canon-Fronsac',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Canon-Fronsac',
    minVintage: 1741,
    avgPrice: 42,
    producers: ['Château Cassagne Haut-Canon'],
    aliases: ['Cassagne Haut-Canon']
  },
  {
    id: 'bordeaux-chateau-vrai-canon-bouche',
    name: 'Château Vrai Canon Bouché',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Canon-Fronsac',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Canon-Fronsac',
    minVintage: 1820,
    avgPrice: 40,
    producers: ['Château Vrai Canon Bouché'],
    aliases: ['Vrai Canon Bouché']
  },
  {
    id: 'bordeaux-chateau-grand-renouil',
    name: 'Château Grand Renouil',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Canon-Fronsac',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Canon-Fronsac',
    minVintage: 1860,
    avgPrice: 35,
    producers: ['Château Grand Renouil'],
    aliases: ['Grand Renouil']
  },
  
  // FRONSAC
  {
    id: 'bordeaux-chateau-de-la-riviere',
    name: 'Château de la Rivière',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Fronsac',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Fronsac',
    minVintage: 1577,
    avgPrice: 35,
    producers: ['Château de la Rivière'],
    aliases: ['de la Rivière']
  },
  {
    id: 'bordeaux-chateau-dalem',
    name: 'Château Dalem',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Fronsac',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'AOC Fronsac',
    minVintage: 1610,
    avgPrice: 38,
    producers: ['Château Dalem'],
    aliases: ['Dalem']
  },
  {
    id: 'bordeaux-chateau-villars',
    name: 'Château Villars',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Fronsac',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Fronsac',
    minVintage: 1595,
    avgPrice: 32,
    producers: ['Château Villars'],
    aliases: ['Villars']
  },
  {
    id: 'bordeaux-chateau-la-vieille-cure',
    name: 'Château La Vieille Cure',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Fronsac',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'AOC Fronsac',
    minVintage: 1986,
    avgPrice: 35,
    producers: ['Château La Vieille Cure'],
    aliases: ['La Vieille Cure']
  },
  {
    id: 'bordeaux-chateau-moulin-haut-laroque',
    name: 'Château Moulin Haut-Laroque',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Fronsac',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Fronsac',
    minVintage: 1850,
    avgPrice: 38,
    producers: ['Château Moulin Haut-Laroque'],
    aliases: ['Moulin Haut-Laroque']
  },
  {
    id: 'bordeaux-chateau-haut-carles',
    name: 'Château Haut-Carles',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Fronsac',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Fronsac',
    minVintage: 1983,
    avgPrice: 40,
    producers: ['Château Haut-Carles'],
    aliases: ['Haut-Carles']
  },
  {
    id: 'bordeaux-chateau-les-trois-croix',
    name: 'Château Les Trois Croix',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Fronsac',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Fronsac',
    minVintage: 1850,
    avgPrice: 35,
    producers: ['Château Les Trois Croix'],
    aliases: ['Les Trois Croix']
  },
  {
    id: 'bordeaux-chateau-fontenil',
    name: 'Château Fontenil',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Fronsac',
    grapeVariety: 'Merlot, Cabernet Sauvignon',
    classification: 'AOC Fronsac',
    minVintage: 1986,
    avgPrice: 42,
    producers: ['Château Fontenil'],
    aliases: ['Fontenil']
  },
  {
    id: 'bordeaux-chateau-richelieu',
    name: 'Château Richelieu',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Fronsac',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'AOC Fronsac',
    minVintage: 1964,
    avgPrice: 35,
    producers: ['Château Richelieu'],
    aliases: ['Richelieu']
  },
  {
    id: 'bordeaux-chateau-plain-point',
    name: 'Château Plain-Point',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Fronsac',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'AOC Fronsac',
    minVintage: 1850,
    avgPrice: 32,
    producers: ['Château Plain-Point'],
    aliases: ['Plain-Point']
  },
  {
    id: 'bordeaux-chateau-de-carles',
    name: 'Château de Carles',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Fronsac',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon, Malbec',
    classification: 'AOC Fronsac',
    minVintage: 1407,
    avgPrice: 35,
    producers: ['Château de Carles'],
    aliases: ['de Carles']
  },
];
