import { WineTemplate } from '@/types/wineDatabase';

/**
 * BORDEAUX LEFT BANK - Part 6 of 6 (Wines 126-150)
 * Focus: Additional Médoc producers, Value selections, White Bordeaux
 * Updated: January 2025
 */

export const bordeauxLeftBankPart6: WineTemplate[] = [
  // MÉDOC - ADDITIONAL PRODUCERS
  {
    id: 'bordeaux-chateau-griviere',
    name: 'Château Grivière',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: 'Cru Bourgeois',
    minVintage: 1872,
    avgPrice: 22,
    producers: ['Château Grivière'],
    aliases: ['Grivière']
  },
  {
    id: 'bordeaux-chateau-les-bertins',
    name: 'Château Les Bertins',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Merlot, Cabernet Sauvignon',
    classification: 'Cru Bourgeois',
    minVintage: 1998,
    avgPrice: 20,
    producers: ['Château Les Bertins'],
    aliases: ['Les Bertins']
  },
  {
    id: 'bordeaux-chateau-noaillac',
    name: 'Château Noaillac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1850,
    avgPrice: 24,
    producers: ['Château Noaillac'],
    aliases: ['Noaillac']
  },
  {
    id: 'bordeaux-chateau-les-tuileries',
    name: 'Château Les Tuileries',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1850,
    avgPrice: 20,
    producers: ['Château Les Tuileries'],
    aliases: ['Les Tuileries']
  },
  {
    id: 'bordeaux-chateau-haut-canteloup',
    name: 'Château Haut-Canteloup',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1875,
    avgPrice: 22,
    producers: ['Château Haut-Canteloup'],
    aliases: ['Haut-Canteloup']
  },
  
  // HAUT-MÉDOC - VALUE SELECTIONS
  {
    id: 'bordeaux-chateau-tour-du-haut-moulin',
    name: 'Château Tour du Haut-Moulin',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1289,
    avgPrice: 35,
    producers: ['Château Tour du Haut-Moulin'],
    aliases: ['Tour du Haut-Moulin']
  },
  {
    id: 'bordeaux-chateau-larose-trintaudon',
    name: 'Château Larose-Trintaudon',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1838,
    avgPrice: 30,
    producers: ['Château Larose-Trintaudon'],
    aliases: ['Larose-Trintaudon']
  },
  {
    id: 'bordeaux-chateau-peyrabon',
    name: 'Château Peyrabon',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1895,
    avgPrice: 38,
    producers: ['Château Peyrabon'],
    aliases: ['Peyrabon']
  },
  {
    id: 'bordeaux-chateau-malescasse',
    name: 'Château Malescasse',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1824,
    avgPrice: 34,
    producers: ['Château Malescasse'],
    aliases: ['Malescasse']
  },
  {
    id: 'bordeaux-chateau-hanteillan',
    name: 'Château Hanteillan',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1972,
    avgPrice: 28,
    producers: ['Château Hanteillan'],
    aliases: ['Hanteillan']
  },
  
  // WHITE BORDEAUX FROM LEFT BANK
  {
    id: 'bordeaux-pavillon-blanc-margaux',
    name: 'Pavillon Blanc du Château Margaux',
    type: 'White',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'AOC Bordeaux Blanc',
    minVintage: 1920,
    avgPrice: 280,
    producers: ['Château Margaux'],
    aliases: ['Pavillon Blanc']
  },
  {
    id: 'bordeaux-blanc-de-lynch-bages',
    name: 'Blanc de Lynch-Bages',
    type: 'White',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Sauvignon Blanc, Sémillon, Muscadelle',
    classification: 'AOC Bordeaux Blanc',
    minVintage: 1990,
    avgPrice: 65,
    producers: ['Château Lynch-Bages'],
    aliases: ['Lynch-Bages Blanc']
  },
  {
    id: 'bordeaux-aile-d-argent',
    name: 'Aile d\'Argent',
    type: 'White',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Sauvignon Blanc, Sémillon, Muscadelle',
    classification: 'AOC Bordeaux Blanc',
    minVintage: 1991,
    avgPrice: 95,
    producers: ['Château Mouton Rothschild'],
    aliases: ['Mouton Blanc']
  },
  
  // SAINT-ESTÈPHE - ADDITIONAL PRODUCERS
  {
    id: 'bordeaux-chateau-segur-de-cabanac',
    name: 'Château Ségur de Cabanac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: 'Cru Bourgeois',
    minVintage: 1985,
    avgPrice: 28,
    producers: ['Château Ségur de Cabanac'],
    aliases: ['Ségur de Cabanac']
  },
  {
    id: 'bordeaux-chateau-beau-site',
    name: 'Château Beau-Site',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1850,
    avgPrice: 35,
    producers: ['Château Beau-Site'],
    aliases: ['Beau-Site']
  },
  {
    id: 'bordeaux-chateau-le-boscq',
    name: 'Château Le Boscq',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1749,
    avgPrice: 38,
    producers: ['Château Le Boscq'],
    aliases: ['Le Boscq']
  },
  {
    id: 'bordeaux-chateau-le-crock',
    name: 'Château Le Crock',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1815,
    avgPrice: 42,
    producers: ['Château Le Crock'],
    aliases: ['Le Crock']
  },
  {
    id: 'bordeaux-chateau-tour-de-pez',
    name: 'Château Tour de Pez',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1452,
    avgPrice: 32,
    producers: ['Château Tour de Pez'],
    aliases: ['Tour de Pez']
  },
  {
    id: 'bordeaux-chateau-tour-des-termes',
    name: 'Château Tour des Termes',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1875,
    avgPrice: 28,
    producers: ['Château Tour des Termes'],
    aliases: ['Tour des Termes']
  },
  
  // PAUILLAC - ADDITIONAL VALUE SELECTIONS
  {
    id: 'bordeaux-chateau-pibran-reserve',
    name: 'Réserve de Pibran',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Second Vin',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Château Pibran'],
    aliases: ['Réserve Pibran']
  },
  {
    id: 'bordeaux-chateau-belle-rose',
    name: 'Château Belle-Rose',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: 'AOC Pauillac',
    minVintage: 1995,
    avgPrice: 32,
    producers: ['Château Belle-Rose'],
    aliases: ['Belle-Rose']
  },
  
  // MARGAUX - ADDITIONAL VALUE SELECTIONS
  {
    id: 'bordeaux-chateau-la-gurgue',
    name: 'Château La Gurgue',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: 'Cru Bourgeois',
    minVintage: 1860,
    avgPrice: 42,
    producers: ['Château La Gurgue'],
    aliases: ['La Gurgue']
  },
  {
    id: 'bordeaux-chateau-martinens',
    name: 'Château Martinens',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1767,
    avgPrice: 38,
    producers: ['Château Martinens'],
    aliases: ['Martinens']
  },
  {
    id: 'bordeaux-chateau-tayac',
    name: 'Château Tayac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1870,
    avgPrice: 35,
    producers: ['Château Tayac'],
    aliases: ['Tayac']
  },
  {
    id: 'bordeaux-chateau-paveil-de-luze',
    name: 'Château Paveil de Luze',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1862,
    avgPrice: 40,
    producers: ['Château Paveil de Luze'],
    aliases: ['Paveil de Luze']
  },
];
