import { WineTemplate } from '@/types/wineDatabase';

/**
 * CAMPANIA WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Taurasi DOCG, Aglianico del Taburno
 * Updated: January 2025
 */

export const campaniaPart1: WineTemplate[] = [
  // TAURASI DOCG (Red - Aglianico)
  {
    id: 'taurasi-mastroberardino-radici',
    name: 'Taurasi Riserva Radici',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1986,
    avgPrice: 95,
    producers: ['Mastroberardino'],
    aliases: ['Radici']
  },
  {
    id: 'taurasi-mastroberardino',
    name: 'Taurasi',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1928,
    avgPrice: 42,
    producers: ['Mastroberardino'],
    aliases: ['Mastroberardino Taurasi']
  },
  {
    id: 'taurasi-feudi-san-gregorio-piano-cerrato',
    name: 'Taurasi Piano di Montevergine',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1986,
    avgPrice: 75,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Piano di Montevergine']
  },
  {
    id: 'taurasi-feudi-san-gregorio',
    name: 'Taurasi',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1986,
    avgPrice: 45,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Feudi Taurasi']
  },
  {
    id: 'taurasi-terredora-fatica-contadina',
    name: 'Taurasi Fatica Contadina',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1994,
    avgPrice: 65,
    producers: ['Terredora'],
    aliases: ['Fatica Contadina']
  },
  {
    id: 'taurasi-terredora',
    name: 'Taurasi',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 38,
    producers: ['Terredora'],
    aliases: ['Terredora Taurasi']
  },
  {
    id: 'taurasi-antonio-caggiano-vigna-macchia-dei-goti',
    name: 'Taurasi Vigna Macchia dei Goti',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 85,
    producers: ['Antonio Caggiano'],
    aliases: ['Macchia dei Goti']
  },
  {
    id: 'taurasi-antonio-caggiano',
    name: 'Taurasi',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 42,
    producers: ['Antonio Caggiano'],
    aliases: ['Caggiano Taurasi']
  },
  {
    id: 'taurasi-quintodecimo-vigna-quintodecimo',
    name: 'Taurasi Vigna Quintodecimo',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2001,
    avgPrice: 120,
    producers: ['Quintodecimo', 'Luigi Moio'],
    aliases: ['Vigna Quintodecimo']
  },
  {
    id: 'taurasi-quintodecimo',
    name: 'Taurasi',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2001,
    avgPrice: 55,
    producers: ['Quintodecimo'],
    aliases: ['Quintodecimo Taurasi']
  },
  {
    id: 'taurasi-molettieri-vigna-cinque-querce',
    name: 'Taurasi Vigna Cinque Querce Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1994,
    avgPrice: 75,
    producers: ['Salvatore Molettieri'],
    aliases: ['Vigna Cinque Querce']
  },
  {
    id: 'taurasi-molettieri',
    name: 'Taurasi',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1994,
    avgPrice: 45,
    producers: ['Salvatore Molettieri'],
    aliases: ['Molettieri Taurasi']
  },
  {
    id: 'taurasi-guastaferro-nima',
    name: 'Taurasi Nima',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2001,
    avgPrice: 65,
    producers: ['Guastaferro'],
    aliases: ['Nima']
  },
  {
    id: 'taurasi-villa-raiano',
    name: 'Taurasi',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1996,
    avgPrice: 38,
    producers: ['Villa Raiano'],
    aliases: ['Villa Raiano Taurasi']
  },
  {
    id: 'taurasi-cantine-lonardo',
    name: 'Taurasi',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1999,
    avgPrice: 42,
    producers: ['Cantine Lonardo'],
    aliases: ['Lonardo Taurasi']
  },
  
  // AGLIANICO DEL TABURNO DOCG & DOC
  {
    id: 'aglianico-taburno-ocone-vigna-pezza-la-corte',
    name: 'Aglianico del Taburno Vigna Pezza La Corte',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taburno',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1998,
    avgPrice: 32,
    producers: ['Ocone'],
    aliases: ['Pezza La Corte']
  },
  {
    id: 'aglianico-taburno-fontanavecchia',
    name: 'Aglianico del Taburno',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taburno',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 22,
    producers: ['Fontanavecchia'],
    aliases: ['Fontanavecchia Aglianico']
  },
  {
    id: 'aglianico-taburno-torre-gaia',
    name: 'Aglianico del Taburno',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taburno',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1998,
    avgPrice: 24,
    producers: ['Torre Gaia'],
    aliases: ['Torre Gaia']
  },
  
  // IRPINIA AGLIANICO DOC
  {
    id: 'irpinia-aglianico-feudi-san-gregorio-serpico',
    name: 'Serpico Irpinia Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1994,
    avgPrice: 95,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Serpico']
  },
  {
    id: 'irpinia-aglianico-terredora-campore',
    name: 'CampoRe Irpinia Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Terredora'],
    aliases: ['CampoRe']
  },
  {
    id: 'irpinia-aglianico-quintodecimo-terra-dassio',
    name: 'Terra d\'Eclano Irpinia Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 35,
    producers: ['Quintodecimo'],
    aliases: ['Terra d\'Eclano']
  },
  {
    id: 'irpinia-aglianico-molettieri',
    name: 'Irpinia Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1994,
    avgPrice: 24,
    producers: ['Salvatore Molettieri'],
    aliases: ['Molettieri Aglianico']
  },
  {
    id: 'irpinia-aglianico-cantine-lonardo-donna-chiara',
    name: 'Donna Chiara Irpinia Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 26,
    producers: ['Cantine Lonardo'],
    aliases: ['Donna Chiara']
  },
  
  // ADDITIONAL AGLIANICO-BASED WINES
  {
    id: 'campania-galardi-terra-di-lavoro',
    name: 'Terra di Lavoro Roccamonfina IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Roccamonfina',
    grapeVariety: 'Aglianico, Piedirosso',
    classification: 'IGT',
    minVintage: 1994,
    avgPrice: 85,
    producers: ['Galardi'],
    aliases: ['Terra di Lavoro']
  },
  {
    id: 'campania-montevetrano',
    name: 'Montevetrano Colli di Salerno IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Salerno',
    grapeVariety: 'Cabernet Sauvignon, Aglianico, Merlot',
    classification: 'IGT',
    minVintage: 1991,
    avgPrice: 120,
    producers: ['Montevetrano', 'Silvia Imparato'],
    aliases: ['Montevetrano']
  },
  {
    id: 'campania-montevetrano-core',
    name: 'Core Colli di Salerno IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Salerno',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2007,
    avgPrice: 48,
    producers: ['Montevetrano'],
    aliases: ['Core']
  },
  {
    id: 'campania-villa-matilde-cecubo',
    name: 'Cecubo Falerno del Massico Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Falerno del Massico',
    grapeVariety: 'Aglianico, Piedirosso',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 32,
    producers: ['Villa Matilde'],
    aliases: ['Cecubo']
  },
  {
    id: 'campania-villa-matilde-vigna-camarato',
    name: 'Vigna Camarato Falerno del Massico Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Falerno del Massico',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 55,
    producers: ['Villa Matilde'],
    aliases: ['Vigna Camarato']
  },
  {
    id: 'campania-mustilli-vigna-segreta',
    name: 'Vigna Segreta Sant\'Agata dei Goti Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Sant\'Agata dei Goti',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1991,
    avgPrice: 32,
    producers: ['Mustilli'],
    aliases: ['Vigna Segreta']
  },
  {
    id: 'campania-luigi-maffini-kleos',
    name: 'Kleos Paestum Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Paestum',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['Luigi Maffini'],
    aliases: ['Kleos']
  },
  {
    id: 'campania-luigi-maffini-cenito',
    name: 'Cenito Paestum Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Paestum',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2007,
    avgPrice: 26,
    producers: ['Luigi Maffini'],
    aliases: ['Cenito']
  },
  {
    id: 'campania-de-conciliis-naima',
    name: 'Naima Paestum Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Paestum',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 38,
    producers: ['De Conciliis'],
    aliases: ['Naima']
  },
  {
    id: 'campania-de-conciliis-donnaluna',
    name: 'Donnaluna Paestum Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Paestum',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 28,
    producers: ['De Conciliis'],
    aliases: ['Donnaluna']
  },
  {
    id: 'campania-san-salvatore-vetere',
    name: 'Vetere Paestum Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Paestum',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2003,
    avgPrice: 35,
    producers: ['San Salvatore'],
    aliases: ['Vetere']
  },
  {
    id: 'campania-vestini-campagnano',
    name: 'Aglianico Campania IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Vestini Campagnano'],
    aliases: ['Vestini Aglianico']
  },
  {
    id: 'campania-rocca-del-principe-taurasi',
    name: 'Taurasi',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1994,
    avgPrice: 45,
    producers: ['Rocca del Principe'],
    aliases: ['Rocca del Principe']
  },
  {
    id: 'campania-benito-ferrara-vigna-cicogna',
    name: 'Vigna Cicogna Irpinia Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2007,
    avgPrice: 28,
    producers: ['Benito Ferrara'],
    aliases: ['Vigna Cicogna']
  },
  {
    id: 'campania-cantine-dell-angelo-donnachiara',
    name: 'Aglianico Irpinia',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 24,
    producers: ['Cantine dell\'Angelo'],
    aliases: ['Cantine dell\'Angelo Aglianico']
  },
  {
    id: 'campania-perillo-taurasi',
    name: 'Taurasi',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2002,
    avgPrice: 42,
    producers: ['Perillo'],
    aliases: ['Perillo Taurasi']
  },
  {
    id: 'campania-borgodangelo-taurasi',
    name: 'Taurasi',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taurasi',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 38,
    producers: ['Borgodangelo'],
    aliases: ['Borgodangelo Taurasi']
  },
  {
    id: 'campania-feudi-di-san-gregorio-rubrato',
    name: 'Rubrato Irpinia Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1997,
    avgPrice: 26,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Rubrato']
  },
  {
    id: 'campania-antonio-caggiano-tauri',
    name: 'Tauri Irpinia Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 28,
    producers: ['Antonio Caggiano'],
    aliases: ['Tauri']
  },
];
