import { WineTemplate } from '@/types/wineDatabase';

/**
 * VENETO WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Prosecco, Bardolino, Lugana
 * Updated: January 2025
 */

export const venetoPart3: WineTemplate[] = [
  // PROSECCO DOCG & DOC (Sparkling)
  {
    id: 'prosecco-valdobbiadene-nino-franco-primo-franco',
    name: 'Valdobbiadene Prosecco Superiore DOCG Primo Franco',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valdobbiadene',
    grapeVariety: 'Glera',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 28,
    producers: ['Nino Franco'],
    aliases: ['Primo Franco']
  },
  {
    id: 'prosecco-valdobbiadene-nino-franco-rustico',
    name: 'Valdobbiadene Prosecco Superiore DOCG Rustico',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valdobbiadene',
    grapeVariety: 'Glera',
    classification: 'DOCG',
    minVintage: 1970,
    avgPrice: 18,
    producers: ['Nino Franco'],
    aliases: ['Rustico']
  },
  {
    id: 'prosecco-valdobbiadene-bisol-crede',
    name: 'Valdobbiadene Prosecco Superiore DOCG Crede',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valdobbiadene',
    grapeVariety: 'Glera',
    classification: 'DOCG',
    minVintage: 1542,
    avgPrice: 22,
    producers: ['Bisol'],
    aliases: ['Crede']
  },
  {
    id: 'prosecco-valdobbiadene-bisol-jeio',
    name: 'Valdobbiadene Prosecco Superiore DOCG Jeio',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valdobbiadene',
    grapeVariety: 'Glera',
    classification: 'DOCG',
    minVintage: 2009,
    avgPrice: 16,
    producers: ['Bisol'],
    aliases: ['Jeio']
  },
  {
    id: 'prosecco-valdobbiadene-adami-bosco-di-gica',
    name: 'Valdobbiadene Prosecco Superiore DOCG Bosco di Gica',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valdobbiadene',
    grapeVariety: 'Glera',
    classification: 'DOCG',
    minVintage: 1920,
    avgPrice: 24,
    producers: ['Adami'],
    aliases: ['Bosco di Gica']
  },
  {
    id: 'prosecco-valdobbiadene-adami-giardino',
    name: 'Valdobbiadene Prosecco Superiore DOCG Giardino Rive di Colbertaldo',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valdobbiadene',
    grapeVariety: 'Glera',
    classification: 'DOCG',
    minVintage: 2009,
    avgPrice: 28,
    producers: ['Adami'],
    aliases: ['Giardino']
  },
  {
    id: 'prosecco-cartizze-nino-franco',
    name: 'Superiore di Cartizze DOCG',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Cartizze',
    grapeVariety: 'Glera',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 42,
    producers: ['Nino Franco'],
    aliases: ['Cartizze Nino Franco']
  },
  {
    id: 'prosecco-cartizze-bisol',
    name: 'Superiore di Cartizze DOCG',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Cartizze',
    grapeVariety: 'Glera',
    classification: 'DOCG',
    minVintage: 1875,
    avgPrice: 38,
    producers: ['Bisol'],
    aliases: ['Cartizze Bisol']
  },
  {
    id: 'prosecco-cartizze-adami',
    name: 'Superiore di Cartizze DOCG',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Cartizze',
    grapeVariety: 'Glera',
    classification: 'DOCG',
    minVintage: 1920,
    avgPrice: 40,
    producers: ['Adami'],
    aliases: ['Cartizze Adami']
  },
  {
    id: 'prosecco-valdobbiadene-ruggeri-giustino',
    name: 'Valdobbiadene Prosecco Superiore DOCG Giustino B.',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valdobbiadene',
    grapeVariety: 'Glera',
    classification: 'DOCG',
    minVintage: 1950,
    avgPrice: 26,
    producers: ['Ruggeri'],
    aliases: ['Giustino B.']
  },
  {
    id: 'prosecco-valdobbiadene-sorelle-bronca',
    name: 'Valdobbiadene Prosecco Superiore DOCG Particella 68',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valdobbiadene',
    grapeVariety: 'Glera',
    classification: 'DOCG',
    minVintage: 1979,
    avgPrice: 22,
    producers: ['Sorelle Bronca'],
    aliases: ['Particella 68']
  },
  {
    id: 'prosecco-valdobbiadene-bortolomiol',
    name: 'Valdobbiadene Prosecco Superiore DOCG',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valdobbiadene',
    grapeVariety: 'Glera',
    classification: 'DOCG',
    minVintage: 1949,
    avgPrice: 18,
    producers: ['Bortolomiol'],
    aliases: ['Bortolomiol']
  },
  {
    id: 'prosecco-conegliano-bellenda',
    name: 'Conegliano Prosecco Superiore DOCG',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Conegliano',
    grapeVariety: 'Glera',
    classification: 'DOCG',
    minVintage: 1986,
    avgPrice: 16,
    producers: ['Bellenda'],
    aliases: ['Bellenda Prosecco']
  },
  {
    id: 'prosecco-doc-zardetto',
    name: 'Prosecco DOC',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Treviso',
    grapeVariety: 'Glera',
    classification: 'DOC',
    minVintage: 1969,
    avgPrice: 14,
    producers: ['Zardetto'],
    aliases: ['Zardetto Prosecco']
  },
  {
    id: 'prosecco-doc-la-marca',
    name: 'Prosecco DOC',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Treviso',
    grapeVariety: 'Glera',
    classification: 'DOC',
    minVintage: 2007,
    avgPrice: 12,
    producers: ['La Marca'],
    aliases: ['La Marca']
  },
  {
    id: 'prosecco-doc-mionetto',
    name: 'Prosecco DOC',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Treviso',
    grapeVariety: 'Glera',
    classification: 'DOC',
    minVintage: 1887,
    avgPrice: 12,
    producers: ['Mionetto'],
    aliases: ['Mionetto']
  },
  {
    id: 'prosecco-doc-riondo',
    name: 'Prosecco DOC',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Treviso',
    grapeVariety: 'Glera',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 11,
    producers: ['Riondo'],
    aliases: ['Riondo']
  },
  
  // BARDOLINO DOC
  {
    id: 'bardolino-guerrieri-rizzardi',
    name: 'Bardolino Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Bardolino',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOC',
    minVintage: 1913,
    avgPrice: 14,
    producers: ['Guerrieri Rizzardi'],
    aliases: ['Guerrieri Rizzardi Bardolino']
  },
  {
    id: 'bardolino-zenato',
    name: 'Bardolino',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Bardolino',
    grapeVariety: 'Corvina, Rondinella',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 12,
    producers: ['Zenato'],
    aliases: ['Zenato Bardolino']
  },
  {
    id: 'bardolino-cavalchina',
    name: 'Bardolino Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Bardolino',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOC',
    minVintage: 1948,
    avgPrice: 13,
    producers: ['Cavalchina'],
    aliases: ['Cavalchina Bardolino']
  },
  {
    id: 'bardolino-le-fraghe',
    name: 'Bardolino Chiaretto',
    type: 'Rosé',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Bardolino',
    grapeVariety: 'Corvina, Rondinella',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 14,
    producers: ['Le Fraghe'],
    aliases: ['Le Fraghe Chiaretto']
  },
  {
    id: 'bardolino-chiaretto-zenato',
    name: 'Bardolino Chiaretto',
    type: 'Rosé',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Bardolino',
    grapeVariety: 'Corvina, Rondinella',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 12,
    producers: ['Zenato'],
    aliases: ['Zenato Chiaretto']
  },
  
  // LUGANA DOC (White - on border with Lombardy)
  {
    id: 'lugana-ca-dei-frati-i-frati',
    name: 'Lugana I Frati',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Lugana',
    grapeVariety: 'Turbiana (Trebbiano di Lugana)',
    classification: 'DOC',
    minVintage: 1939,
    avgPrice: 18,
    producers: ['Cà dei Frati'],
    aliases: ['I Frati']
  },
  {
    id: 'lugana-ca-dei-frati-brolettino',
    name: 'Lugana Brolettino',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Lugana',
    grapeVariety: 'Turbiana',
    classification: 'DOC',
    minVintage: 1969,
    avgPrice: 28,
    producers: ['Cà dei Frati'],
    aliases: ['Brolettino']
  },
  {
    id: 'lugana-zenato-sergio-zenato',
    name: 'Lugana Sergio Zenato Riserva',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Lugana',
    grapeVariety: 'Turbiana',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 32,
    producers: ['Zenato'],
    aliases: ['Sergio Zenato']
  },
  {
    id: 'lugana-zenato-san-benedetto',
    name: 'Lugana San Benedetto',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Lugana',
    grapeVariety: 'Turbiana',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 16,
    producers: ['Zenato'],
    aliases: ['San Benedetto']
  },
  {
    id: 'lugana-ottella',
    name: 'Lugana',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Lugana',
    grapeVariety: 'Turbiana',
    classification: 'DOC',
    minVintage: 1979,
    avgPrice: 16,
    producers: ['Ottella'],
    aliases: ['Ottella Lugana']
  },
  {
    id: 'lugana-ottella-molceo',
    name: 'Lugana Le Creete Riserva',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Lugana',
    grapeVariety: 'Turbiana',
    classification: 'DOC',
    minVintage: 2009,
    avgPrice: 26,
    producers: ['Ottella'],
    aliases: ['Le Creete']
  },
  {
    id: 'lugana-provenza',
    name: 'Lugana',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Lugana',
    grapeVariety: 'Turbiana',
    classification: 'DOC',
    minVintage: 1991,
    avgPrice: 14,
    producers: ['Provenza'],
    aliases: ['Provenza Lugana']
  },
  
  // CUSTOZA DOC (White)
  {
    id: 'custoza-cavalchina',
    name: 'Bianco di Custoza',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Custoza',
    grapeVariety: 'Garganega, Trebbiano, Cortese',
    classification: 'DOC',
    minVintage: 1948,
    avgPrice: 12,
    producers: ['Cavalchina'],
    aliases: ['Cavalchina Custoza']
  },
  {
    id: 'custoza-gorgo',
    name: 'Bianco di Custoza',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Custoza',
    grapeVariety: 'Garganega, Trebbiano, Cortese',
    classification: 'DOC',
    minVintage: 1973,
    avgPrice: 11,
    producers: ['Gorgo'],
    aliases: ['Gorgo Custoza']
  },
  {
    id: 'custoza-le-vigne-di-san-pietro',
    name: 'Bianco di Custoza Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Custoza',
    grapeVariety: 'Garganega, Trebbiano, Cortese',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 14,
    processors: ['Le Vigne di San Pietro'],
    aliases: ['Le Vigne di San Pietro']
  },
  
  // ADDITIONAL VENETO WINES
  {
    id: 'veneto-allegrini-la-poja',
    name: 'La Poja Veronese IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina',
    classification: 'IGT',
    minVintage: 1983,
    avgPrice: 75,
    producers: ['Allegrini'],
    aliases: ['La Poja']
  },
  {
    id: 'veneto-quintarelli-alzero',
    name: 'Alzero Veneto IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Cabernet Sauvignon, Cabernet Franc, Merlot',
    classification: 'IGT',
    minVintage: 1981,
    avgPrice: 280,
    producers: ['Giuseppe Quintarelli'],
    aliases: ['Alzero']
  },
  {
    id: 'veneto-quintarelli-primofiore',
    name: 'Primofiore Veneto IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Cabernet',
    classification: 'IGT',
    minVintage: 1984,
    avgPrice: 95,
    producers: ['Giuseppe Quintarelli'],
    aliases: ['Primofiore']
  },
  {
    id: 'veneto-dal-forno-vigneto-monte-lodoletta',
    name: 'Vigneto Monte Lodoletta Veneto IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Croatina, Oseleta',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 280,
    producers: ['Dal Forno Romano'],
    aliases: ['Vigneto Monte Lodoletta']
  },
  {
    id: 'veneto-maculan-torcolato',
    name: 'Torcolato di Breganze',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Breganze',
    grapeVariety: 'Vespaiola',
    classification: 'DOCG',
    minVintage: 1969,
    avgPrice: 48,
    producers: ['Maculan'],
    aliases: ['Torcolato']
  },
  {
    id: 'veneto-maculan-acininobili',
    name: 'Acininobili',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Breganze',
    grapeVariety: 'Vespaiola',
    classification: 'IGT',
    minVintage: 1975,
    avgPrice: 85,
    producers: ['Maculan'],
    aliases: ['Acininobili']
  },
  {
    id: 'veneto-maculan-fratta',
    name: 'Fratta Veneto IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Breganze',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'IGT',
    minVintage: 1982,
    avgPrice: 55,
    producers: ['Maculan'],
    aliases: ['Fratta']
  },
  {
    id: 'veneto-maculan-palazzotto',
    name: 'Palazzotto Veneto IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Breganze',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 42,
    producers: ['Maculan'],
    aliases: ['Palazzotto']
  },
  {
    id: 'veneto-masi-toar',
    name: 'Toar Amarone Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOCG',
    minVintage: 1987,
    avgPrice: 180,
    producers: ['Masi'],
    aliases: ['Toar']
  },
  {
    id: 'veneto-bertani-recioto-ognisanti',
    name: 'Recioto della Valpolicella Classico Ognisanti',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella',
    classification: 'DOCG',
    minVintage: 2009,
    avgPrice: 65,
    producers: ['Bertani'],
    aliases: ['Ognisanti']
  },
];
