import { WineTemplate } from '@/types/wineDatabase';

/**
 * LAZIO WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Cesanese del Piglio DOCG, Cesanese di Olevano Romano, Red wines
 * Updated: January 2025
 */

export const lazioPart2: WineTemplate[] = [
  // CESANESE DEL PIGLIO DOCG (Red)
  {
    id: 'cesanese-piglio-casale-della-ioria-hernicus',
    name: 'Cesanese del Piglio Superiore Hernicus',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Piglio',
    grapeVariety: 'Cesanese',
    classification: 'DOCG',
    minVintage: 1999,
    avgPrice: 32,
    producers: ['Casale della Ioria'],
    aliases: ['Hernicus']
  },
  {
    id: 'cesanese-piglio-casale-della-ioria',
    name: 'Cesanese del Piglio',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Piglio',
    grapeVariety: 'Cesanese',
    classification: 'DOCG',
    minVintage: 1999,
    avgPrice: 18,
    producers: ['Casale della Ioria'],
    aliases: ['Casale della Ioria Cesanese']
  },
  {
    id: 'cesanese-piglio-damiano-ciolli-silene',
    name: 'Cesanese del Piglio Superiore Silene',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Piglio',
    grapeVariety: 'Cesanese',
    classification: 'DOCG',
    minVintage: 2003,
    avgPrice: 35,
    producers: ['Damiano Ciolli'],
    aliases: ['Silene']
  },
  {
    id: 'cesanese-piglio-damiano-ciolli',
    name: 'Cesanese del Piglio',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Piglio',
    grapeVariety: 'Cesanese',
    classification: 'DOCG',
    minVintage: 2003,
    avgPrice: 20,
    producers: ['Damiano Ciolli'],
    aliases: ['Damiano Ciolli Cesanese']
  },
  {
    id: 'cesanese-piglio-cincinnato',
    name: 'Cesanese del Piglio',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Piglio',
    grapeVariety: 'Cesanese',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Cincinnato'],
    aliases: ['Cincinnato Cesanese Piglio']
  },
  {
    id: 'cesanese-piglio-coletti-conti',
    name: 'Cesanese del Piglio Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Piglio',
    grapeVariety: 'Cesanese',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 26,
    producers: ['Coletti Conti'],
    aliases: ['Coletti Conti Cesanese']
  },
  {
    id: 'cesanese-piglio-terenzi',
    name: 'Cesanese del Piglio',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Piglio',
    grapeVariety: 'Cesanese',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Terenzi'],
    aliases: ['Terenzi Cesanese']
  },
  
  // CESANESE DI OLEVANO ROMANO DOC (Red)
  {
    id: 'cesanese-olevano-damiano-ciolli-cirsium',
    name: 'Cesanese di Olevano Romano Cirsium',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Olevano Romano',
    grapeVariety: 'Cesanese',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Damiano Ciolli'],
    aliases: ['Cirsium']
  },
  {
    id: 'cesanese-olevano-coletti-conti',
    name: 'Cesanese di Olevano Romano',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Olevano Romano',
    grapeVariety: 'Cesanese',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Coletti Conti'],
    aliases: ['Coletti Conti Olevano']
  },
  
  // CESANESE DI AFFILE DOC (Red)
  {
    id: 'cesanese-affile-coletti-conti',
    name: 'Cesanese di Affile',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Affile',
    grapeVariety: 'Cesanese',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Coletti Conti'],
    aliases: ['Coletti Conti Affile']
  },
  {
    id: 'cesanese-affile-casale-della-ioria',
    name: 'Cesanese di Affile',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Affile',
    grapeVariety: 'Cesanese',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Casale della Ioria'],
    aliases: ['Casale della Ioria Affile']
  },
  
  // CIRCEO DOC (Red)
  {
    id: 'circeo-casale-del-giglio-mater-matuta',
    name: 'Circeo Rosso Mater Matuta',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Sabaudia',
    grapeVariety: 'Merlot, Cabernet Sauvignon',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 42,
    producers: ['Casale del Giglio'],
    aliases: ['Mater Matuta']
  },
  {
    id: 'circeo-casale-del-giglio',
    name: 'Circeo Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Sabaudia',
    grapeVariety: 'Merlot, Sangiovese',
    classification: 'DOC',
    minVintage: 1967,
    avgPrice: 14,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Circeo']
  },
  
  // PREMIUM RED BLENDS (Lazio IGT)
  {
    id: 'lazio-castel-de-paolis-quattro-mori-rosso',
    name: 'Quattro Mori Rosso Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Syrah, Merlot, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 1993,
    avgPrice: 48,
    producers: ['Castel De Paolis'],
    aliases: ['Quattro Mori Rosso']
  },
  {
    id: 'lazio-castel-de-paolis-frascati-rosso',
    name: 'Frascati Rosso Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Syrah, Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Castel De Paolis'],
    aliases: ['Frascati Rosso']
  },
  {
    id: 'lazio-falesco-montiano',
    name: 'Montiano Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Viterbo',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 1993,
    avgPrice: 38,
    producers: ['Falesco'],
    aliases: ['Montiano']
  },
  {
    id: 'lazio-falesco-marciliano',
    name: 'Marciliano Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Viterbo',
    grapeVariety: 'Cabernet Sauvignon, Cabernet Franc',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Falesco'],
    aliases: ['Marciliano']
  },
  {
    id: 'lazio-casale-del-giglio-syrah',
    name: 'Syrah Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Syrah',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 28,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Syrah']
  },
  {
    id: 'lazio-casale-del-giglio-petit-verdot',
    name: 'Petit Verdot Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Petit Verdot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Petit Verdot']
  },
  {
    id: 'lazio-casale-del-giglio-shiraz',
    name: 'Shiraz Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Shiraz',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Shiraz']
  },
  {
    id: 'lazio-poggio-le-volpi-calliope',
    name: 'Calliope Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Syrah, Petit Verdot',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 38,
    producers: ['Poggio Le Volpi'],
    aliases: ['Calliope']
  },
  {
    id: 'lazio-colle-picchioni-vigna-del-vassallo',
    name: 'Vigna del Vassallo Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Marino',
    grapeVariety: 'Merlot, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 1992,
    avgPrice: 45,
    producers: ['Colle Picchioni'],
    aliases: ['Vigna del Vassallo']
  },
  {
    id: 'lazio-sergio-mottura-poggio-della-costa',
    name: 'Poggio della Costa Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Viterbo',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Sergio Mottura'],
    aliases: ['Poggio della Costa']
  },
  
  // ALEATICO DI GRADOLI DOC (Sweet red)
  {
    id: 'aleatico-gradoli-sergio-mottura',
    name: 'Aleatico di Gradoli',
    type: 'Dessert',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Gradoli',
    grapeVariety: 'Aleatico',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 32,
    producers: ['Sergio Mottura'],
    aliases: ['Sergio Mottura Aleatico']
  },
  {
    id: 'aleatico-gradoli-cantina-sociale',
    name: 'Aleatico di Gradoli',
    type: 'Dessert',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Gradoli',
    grapeVariety: 'Aleatico',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Cantina Sociale di Gradoli'],
    aliases: ['Gradoli Aleatico']
  },
  
  // INTERNATIONAL VARIETIES
  {
    id: 'merlot-casale-del-giglio',
    name: 'Merlot Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 1967,
    avgPrice: 18,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Merlot']
  },
  {
    id: 'cabernet-sauvignon-falesco',
    name: 'Cabernet Sauvignon Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Viterbo',
    grapeVariety: 'Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 20,
    producers: ['Falesco'],
    aliases: ['Falesco Cabernet']
  },
  {
    id: 'pinot-nero-casale-del-giglio',
    name: 'Pinot Nero Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Pinot Noir',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 24,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Pinot Nero']
  },
  {
    id: 'sangiovese-lazio-colle-picchioni',
    name: 'Sangiovese Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Marino',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 18,
    producers: ['Colle Picchioni'],
    aliases: ['Colle Picchioni Sangiovese']
  },
  {
    id: 'chardonnay-casale-del-giglio',
    name: 'Chardonnay Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 1967,
    avgPrice: 16,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Chardonnay']
  },
  {
    id: 'sauvignon-blanc-casale-del-giglio',
    name: 'Sauvignon Blanc Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 16,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Sauvignon']
  },
  {
    id: 'viognier-casale-del-giglio',
    name: 'Viognier Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Viognier',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Viognier']
  },
  
  // ROSÉ WINES
  {
    id: 'rosato-casale-del-giglio',
    name: 'Rosato Lazio IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Syrah',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Rosato']
  },
  {
    id: 'rosato-poggio-le-volpi',
    name: 'Rosato Lazio IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Syrah, Sangiovese',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Poggio Le Volpi'],
    aliases: ['Poggio Le Volpi Rosato']
  },
  
  // ATINA DOC (Red - Cabernet)
  {
    id: 'atina-coletti-conti',
    name: 'Atina Cabernet',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Atina',
    grapeVariety: 'Cabernet Sauvignon, Cabernet Franc',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Coletti Conti'],
    aliases: ['Coletti Conti Atina']
  },
  
  // ADDITIONAL WINES
  {
    id: 'lazio-cincinnato-polluce',
    name: 'Polluce Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Cori',
    grapeVariety: 'Nero Buono, Montepulciano',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Cincinnato'],
    aliases: ['Polluce']
  },
  {
    id: 'lazio-cincinnato-capolemole',
    name: 'Capolemole Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Cori',
    grapeVariety: 'Nero Buono',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 28,
    producers: ['Cincinnato'],
    aliases: ['Capolemole']
  },
];
