import { WineTemplate } from '@/types/wineDatabase';

/**
 * TRENTINO-ALTO ADIGE WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Gewürztraminer, Pinot Grigio, Pinot Bianco (Alto Adige)
 * Updated: January 2025
 */

export const trentinoAltoAdigePart1: WineTemplate[] = [
  // GEWÜRZTRAMINER - ALTO ADIGE DOC
  {
    id: 'gewurztraminer-elena-walch-kastelaz',
    name: 'Gewürztraminer Alto Adige Kastelaz',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Gewürztraminer',
    classification: 'DOC',
    minVintage: 1869,
    avgPrice: 32,
    producers: ['Elena Walch'],
    aliases: ['Kastelaz']
  },
  {
    id: 'gewurztraminer-elena-walch',
    name: 'Gewürztraminer Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Gewürztraminer',
    classification: 'DOC',
    minVintage: 1869,
    avgPrice: 22,
    producers: ['Elena Walch'],
    aliases: ['Elena Walch Gewürztraminer']
  },
  {
    id: 'gewurztraminer-abbazia-novacella-praepositus',
    name: 'Gewürztraminer Alto Adige Praepositus',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Gewürztraminer',
    classification: 'DOC',
    minVintage: 1142,
    avgPrice: 35,
    producers: ['Abbazia di Novacella'],
    aliases: ['Praepositus']
  },
  {
    id: 'gewurztraminer-abbazia-novacella',
    name: 'Gewürztraminer Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Gewürztraminer',
    classification: 'DOC',
    minVintage: 1142,
    avgPrice: 24,
    producers: ['Abbazia di Novacella'],
    aliases: ['Abbazia Gewürztraminer']
  },
  {
    id: 'gewurztraminer-alois-lageder-benefizium-porer',
    name: 'Gewürztraminer Alto Adige Benefizium Porer',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Gewürztraminer',
    classification: 'DOC',
    minVintage: 1855,
    avgPrice: 42,
    producers: ['Alois Lageder'],
    aliases: ['Benefizium Porer']
  },
  {
    id: 'gewurztraminer-alois-lageder',
    name: 'Gewürztraminer Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Gewürztraminer',
    classification: 'DOC',
    minVintage: 1855,
    avgPrice: 26,
    producers: ['Alois Lageder'],
    aliases: ['Lageder Gewürztraminer']
  },
  {
    id: 'gewurztraminer-cantina-tramin-nussbaumer',
    name: 'Gewürztraminer Alto Adige Nussbaumer',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Termeno',
    grapeVariety: 'Gewürztraminer',
    classification: 'DOC',
    minVintage: 1898,
    avgPrice: 38,
    producers: ['Cantina Tramin'],
    aliases: ['Nussbaumer']
  },
  {
    id: 'gewurztraminer-cantina-tramin-epokale',
    name: 'Gewürztraminer Alto Adige Epokale',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Termeno',
    grapeVariety: 'Gewürztraminer',
    classification: 'DOC',
    minVintage: 2003,
    avgPrice: 55,
    producers: ['Cantina Tramin'],
    aliases: ['Epokale']
  },
  {
    id: 'gewurztraminer-cantina-tramin',
    name: 'Gewürztraminer Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Termeno',
    grapeVariety: 'Gewürztraminer',
    classification: 'DOC',
    minVintage: 1898,
    avgPrice: 20,
    producers: ['Cantina Tramin'],
    aliases: ['Tramin Gewürztraminer']
  },
  {
    id: 'gewurztraminer-st-michael-eppan-sanct-valentin',
    name: 'Gewürztraminer Alto Adige Sanct Valentin',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Appiano',
    grapeVariety: 'Gewürztraminer',
    classification: 'DOC',
    minVintage: 1907,
    avgPrice: 45,
    producers: ['St. Michael-Eppan'],
    aliases: ['Sanct Valentin Gewürztraminer']
  },
  {
    id: 'gewurztraminer-st-michael-eppan',
    name: 'Gewürztraminer Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Appiano',
    grapeVariety: 'Gewürztraminer',
    classification: 'DOC',
    minVintage: 1907,
    avgPrice: 22,
    producers: ['St. Michael-Eppan'],
    aliases: ['St. Michael Gewürztraminer']
  },
  {
    id: 'gewurztraminer-j-hofstatter-kolbenhof',
    name: 'Gewürztraminer Alto Adige Kolbenhof',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Termeno',
    grapeVariety: 'Gewürztraminer',
    classification: 'DOC',
    minVintage: 1907,
    avgPrice: 42,
    producers: ['J. Hofstätter'],
    aliases: ['Kolbenhof']
  },
  {
    id: 'gewurztraminer-peter-dipoli',
    name: 'Gewürztraminer Alto Adige Voglar',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Gewürztraminer',
    classification: 'DOC',
    minVintage: 1993,
    avgPrice: 32,
    producers: ['Peter Dipoli'],
    aliases: ['Voglar']
  },
  
  // PINOT GRIGIO - ALTO ADIGE DOC
  {
    id: 'pinot-grigio-alois-lageder',
    name: 'Pinot Grigio Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1855,
    avgPrice: 22,
    producers: ['Alois Lageder'],
    aliases: ['Lageder Pinot Grigio']
  },
  {
    id: 'pinot-grigio-elena-walch',
    name: 'Pinot Grigio Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1869,
    avgPrice: 20,
    producers: ['Elena Walch'],
    aliases: ['Elena Walch Pinot Grigio']
  },
  {
    id: 'pinot-grigio-st-michael-eppan',
    name: 'Pinot Grigio Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Appiano',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1907,
    avgPrice: 18,
    producers: ['St. Michael-Eppan'],
    aliases: ['St. Michael Pinot Grigio']
  },
  {
    id: 'pinot-grigio-cantina-tramin',
    name: 'Pinot Grigio Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Termeno',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1898,
    avgPrice: 16,
    producers: ['Cantina Tramin'],
    aliases: ['Tramin Pinot Grigio']
  },
  {
    id: 'pinot-grigio-abbazia-novacella',
    name: 'Pinot Grigio Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1142,
    avgPrice: 18,
    producers: ['Abbazia di Novacella'],
    aliases: ['Abbazia Pinot Grigio']
  },
  {
    id: 'pinot-grigio-terlan-quarz',
    name: 'Pinot Grigio Alto Adige Quarz',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Terlano',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1893,
    avgPrice: 42,
    producers: ['Cantina Terlano'],
    aliases: ['Quarz']
  },
  {
    id: 'pinot-grigio-terlan',
    name: 'Pinot Grigio Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Terlano',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1893,
    avgPrice: 22,
    producers: ['Cantina Terlano'],
    aliases: ['Terlano Pinot Grigio']
  },
  {
    id: 'pinot-grigio-nals-margreid',
    name: 'Pinot Grigio Alto Adige Punggl',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Nalles-Magrè',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1932,
    avgPrice: 28,
    producers: ['Nals Margreid'],
    aliases: ['Punggl']
  },
  {
    id: 'pinot-grigio-franz-haas',
    name: 'Pinot Grigio Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Montagna',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1880,
    avgPrice: 24,
    producers: ['Franz Haas'],
    aliases: ['Franz Haas Pinot Grigio']
  },
  
  // PINOT BIANCO - ALTO ADIGE DOC
  {
    id: 'pinot-bianco-terlan-vorberg',
    name: 'Pinot Bianco Alto Adige Vorberg Riserva',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Terlano',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 1993,
    avgPrice: 65,
    producers: ['Cantina Terlano'],
    aliases: ['Vorberg']
  },
  {
    id: 'pinot-bianco-terlan-winkl',
    name: 'Pinot Bianco Alto Adige Winkl',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Terlano',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 48,
    producers: ['Cantina Terlano'],
    aliases: ['Winkl']
  },
  {
    id: 'pinot-bianco-terlan',
    name: 'Pinot Bianco Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Terlano',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 1893,
    avgPrice: 24,
    producers: ['Cantina Terlano'],
    aliases: ['Terlano Pinot Bianco']
  },
  {
    id: 'pinot-bianco-st-michael-eppan-schulthauser',
    name: 'Pinot Bianco Alto Adige Schulthauser',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Appiano',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 1986,
    avgPrice: 38,
    producers: ['St. Michael-Eppan'],
    aliases: ['Schulthauser']
  },
  {
    id: 'pinot-bianco-st-michael-eppan',
    name: 'Pinot Bianco Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Appiano',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 1907,
    avgPrice: 20,
    producers: ['St. Michael-Eppan'],
    aliases: ['St. Michael Pinot Bianco']
  },
  {
    id: 'pinot-bianco-alois-lageder',
    name: 'Pinot Bianco Alto Adige Haberle',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 32,
    producers: ['Alois Lageder'],
    aliases: ['Haberle']
  },
  {
    id: 'pinot-bianco-abbazia-novacella',
    name: 'Pinot Bianco Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 1142,
    avgPrice: 22,
    producers: ['Abbazia di Novacella'],
    aliases: ['Abbazia Pinot Bianco']
  },
  {
    id: 'pinot-bianco-nals-margreid-sirmian',
    name: 'Pinot Bianco Alto Adige Sirmian',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Nalles-Magrè',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 35,
    producers: ['Nals Margreid'],
    aliases: ['Sirmian']
  },
  {
    id: 'pinot-bianco-nals-margreid',
    name: 'Pinot Bianco Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Nalles-Magrè',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 1932,
    avgPrice: 20,
    producers: ['Nals Margreid'],
    aliases: ['Nals Margreid Pinot Bianco']
  },
  {
    id: 'pinot-bianco-elena-walch',
    name: 'Pinot Bianco Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 1869,
    avgPrice: 18,
    producers: ['Elena Walch'],
    aliases: ['Elena Walch Pinot Bianco']
  },
  {
    id: 'pinot-bianco-cantina-tramin',
    name: 'Pinot Bianco Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Termeno',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 1898,
    avgPrice: 16,
    producers: ['Cantina Tramin'],
    aliases: ['Tramin Pinot Bianco']
  },
  {
    id: 'pinot-bianco-j-hofstatter',
    name: 'Pinot Bianco Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Termeno',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 1907,
    avgPrice: 22,
    producers: ['J. Hofstätter'],
    aliases: ['Hofstätter Pinot Bianco']
  },
  {
    id: 'pinot-bianco-franz-haas',
    name: 'Pinot Bianco Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Montagna',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 1880,
    avgPrice: 20,
    producers: ['Franz Haas'],
    aliases: ['Franz Haas Pinot Bianco']
  },
  {
    id: 'pinot-bianco-manincor',
    name: 'Pinot Bianco Alto Adige Mason di Mason',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Caldaro',
    grapeVariety: 'Pinot Bianco',
    classification: 'DOC',
    minVintage: 1608,
    avgPrice: 32,
    producers: ['Manincor'],
    aliases: ['Mason di Mason']
  },
];
