import { WineTemplate } from '@/types/wineDatabase';

/**
 * VALLE D'AOSTA WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Chardonnay, Pinot Noir, Mayolet, Cornalin, Additional varieties
 * Updated: January 2025
 */

export const valleDaostaPart2: WineTemplate[] = [
  // CHARDONNAY
  {
    id: 'vda-chardonnay-les-cretes-cuvee-bois',
    name: 'Valle d\'Aosta Chardonnay Cuvée Bois',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 28,
    producers: ['Les Cretes'],
    aliases: ['Cuvée Bois']
  },
  {
    id: 'vda-chardonnay-les-cretes',
    name: 'Valle d\'Aosta Chardonnay',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1989,
    avgPrice: 20,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Chardonnay']
  },
  {
    id: 'vda-chardonnay-grosjean',
    name: 'Valle d\'Aosta Chardonnay',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Grosjean'],
    aliases: ['Grosjean Chardonnay']
  },
  {
    id: 'vda-chardonnay-anselmet',
    name: 'Valle d\'Aosta Chardonnay',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Villeneuve',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Anselmet'],
    aliases: ['Anselmet Chardonnay']
  },
  {
    id: 'vda-chardonnay-cave-des-onze-communes',
    name: 'Valle d\'Aosta Chardonnay',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Cave des Onze Communes'],
    aliases: ['Cave des Onze Communes Chardonnay']
  },
  {
    id: 'vda-chardonnay-di-barro',
    name: 'Valle d\'Aosta Chardonnay',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 22,
    producers: ['Di Barrò'],
    aliases: ['Di Barrò Chardonnay']
  },
  
  // PINOT NOIR
  {
    id: 'vda-pinot-noir-les-cretes',
    name: 'Valle d\'Aosta Pinot Noir',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 28,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Pinot Noir']
  },
  {
    id: 'vda-pinot-noir-grosjean',
    name: 'Valle d\'Aosta Pinot Noir',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 30,
    producers: ['Grosjean'],
    aliases: ['Grosjean Pinot Noir']
  },
  {
    id: 'vda-pinot-noir-anselmet',
    name: 'Valle d\'Aosta Pinot Noir',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Villeneuve',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Anselmet'],
    aliases: ['Anselmet Pinot Noir']
  },
  {
    id: 'vda-pinot-noir-cave-des-onze-communes',
    name: 'Valle d\'Aosta Pinot Noir',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 24,
    producers: ['Cave des Onze Communes'],
    aliases: ['Cave des Onze Communes Pinot Noir']
  },
  
  // MAYOLET (Indigenous red)
  {
    id: 'vda-mayolet-grosjean',
    name: 'Valle d\'Aosta Mayolet',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Mayolet',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Grosjean'],
    aliases: ['Grosjean Mayolet']
  },
  {
    id: 'vda-mayolet-les-cretes',
    name: 'Valle d\'Aosta Mayolet',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Mayolet',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 28,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Mayolet']
  },
  {
    id: 'vda-mayolet-anselmet',
    name: 'Valle d\'Aosta Mayolet',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Villeneuve',
    grapeVariety: 'Mayolet',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 30,
    producers: ['Anselmet'],
    aliases: ['Anselmet Mayolet']
  },
  
  // CORNALIN (Indigenous red)
  {
    id: 'vda-cornalin-grosjean',
    name: 'Valle d\'Aosta Cornalin',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Cornalin',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Grosjean'],
    aliases: ['Grosjean Cornalin']
  },
  {
    id: 'vda-cornalin-les-cretes',
    name: 'Valle d\'Aosta Cornalin',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Cornalin',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 35,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Cornalin']
  },
  {
    id: 'vda-cornalin-anselmet',
    name: 'Valle d\'Aosta Cornalin',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Villeneuve',
    grapeVariety: 'Cornalin',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 38,
    producers: ['Anselmet'],
    aliases: ['Anselmet Cornalin']
  },
  {
    id: 'vda-cornalin-di-barro',
    name: 'Valle d\'Aosta Cornalin',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Cornalin',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 32,
    producers: ['Di Barrò'],
    aliases: ['Di Barrò Cornalin']
  },
  
  // GAMAY
  {
    id: 'vda-gamay-grosjean',
    name: 'Valle d\'Aosta Gamay',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Gamay',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Grosjean'],
    aliases: ['Grosjean Gamay']
  },
  {
    id: 'vda-gamay-les-cretes',
    name: 'Valle d\'Aosta Gamay',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Gamay',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Gamay']
  },
  {
    id: 'vda-gamay-cave-des-onze-communes',
    name: 'Valle d\'Aosta Gamay',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Gamay',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Cave des Onze Communes'],
    aliases: ['Cave des Onze Communes Gamay']
  },
  
  // MÜLLER-THURGAU
  {
    id: 'vda-muller-thurgau-les-cretes',
    name: 'Valle d\'Aosta Müller-Thurgau',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'La Salle',
    grapeVariety: 'Müller-Thurgau',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Müller-Thurgau']
  },
  {
    id: 'vda-muller-thurgau-cave-du-vin-blanc',
    name: 'Valle d\'Aosta Müller-Thurgau',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Morgex',
    grapeVariety: 'Müller-Thurgau',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Cave du Vin Blanc de Morgex et de La Salle'],
    aliases: ['Morgex Müller-Thurgau']
  },
  
  // PINOT GRIS (Dry version)
  {
    id: 'vda-pinot-gris-grosjean',
    name: 'Valle d\'Aosta Pinot Gris',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Pinot Gris',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Grosjean'],
    aliases: ['Grosjean Pinot Gris']
  },
  {
    id: 'vda-pinot-gris-les-cretes',
    name: 'Valle d\'Aosta Pinot Gris',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Pinot Gris',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 26,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Pinot Gris']
  },
  {
    id: 'vda-pinot-gris-anselmet',
    name: 'Valle d\'Aosta Pinot Gris',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Villeneuve',
    grapeVariety: 'Pinot Gris',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 28,
    producers: ['Anselmet'],
    aliases: ['Anselmet Pinot Gris']
  },
  
  // PREMIUM RED BLENDS
  {
    id: 'vda-les-cretes-coteau-la-tour',
    name: 'Coteau La Tour Valle d\'Aosta DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Syrah, Fumin, Cornalin',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 42,
    producers: ['Les Cretes'],
    aliases: ['Coteau La Tour']
  },
  {
    id: 'vda-grosjean-vigne-rovettaz',
    name: 'Vigne Rovettaz Valle d\'Aosta DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Fumin, Cornalin, Mayolet',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Grosjean'],
    aliases: ['Vigne Rovettaz']
  },
  {
    id: 'vda-anselmet-la-tour',
    name: 'La Tour Valle d\'Aosta DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Villeneuve',
    grapeVariety: 'Petit Rouge, Fumin',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 35,
    producers: ['Anselmet'],
    aliases: ['La Tour']
  },
  
  // SYRAH
  {
    id: 'vda-syrah-les-cretes',
    name: 'Valle d\'Aosta Syrah',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Syrah',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Syrah']
  },
  {
    id: 'vda-syrah-grosjean',
    name: 'Valle d\'Aosta Syrah',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Syrah',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Grosjean'],
    aliases: ['Grosjean Syrah']
  },
  {
    id: 'vda-syrah-anselmet',
    name: 'Valle d\'Aosta Syrah',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Villeneuve',
    grapeVariety: 'Syrah',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Anselmet'],
    aliases: ['Anselmet Syrah']
  },
  
  // ROSÉ WINES
  {
    id: 'vda-rosato-grosjean',
    name: 'Valle d\'Aosta Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Grosjean'],
    aliases: ['Grosjean Rosato']
  },
  {
    id: 'vda-rosato-les-cretes',
    name: 'Valle d\'Aosta Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Petit Rouge, Fumin',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 20,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Rosato']
  },
  {
    id: 'vda-rosato-cave-des-onze-communes',
    name: 'Valle d\'Aosta Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Cave des Onze Communes'],
    aliases: ['Cave des Onze Communes Rosato']
  },
  {
    id: 'vda-rosato-anselmet',
    name: 'Valle d\'Aosta Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Villeneuve',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 20,
    producers: ['Anselmet'],
    aliases: ['Anselmet Rosato']
  },
  
  // SPARKLING WINES
  {
    id: 'vda-spumante-cave-du-vin-blanc-brut',
    name: 'Blanc de Morgex et de La Salle Brut Metodo Classico',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Morgex',
    grapeVariety: 'Prié Blanc',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Cave du Vin Blanc de Morgex et de La Salle'],
    aliases: ['Morgex Brut']
  },
  {
    id: 'vda-spumante-cave-du-vin-blanc-extra-brut',
    name: 'Blanc de Morgex et de La Salle Extra Brut',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Morgex',
    grapeVariety: 'Prié Blanc',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 38,
    producers: ['Cave du Vin Blanc de Morgex et de La Salle'],
    aliases: ['Morgex Extra Brut']
  },
  {
    id: 'vda-spumante-les-cretes-brut',
    name: 'Valle d\'Aosta Spumante Brut',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Chardonnay, Pinot Noir',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 32,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Spumante']
  },
];
