import { WineTemplate } from '@/types/wineDatabase';

/**
 * CAMPANIA WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Falanghina, Piedirosso, Lacryma Christi, Asprinio
 * Updated: January 2025
 */

export const campaniaPart3: WineTemplate[] = [
  // FALANGHINA (Various DOCs)
  {
    id: 'falanghina-campi-flegrei-grotta-del-sole',
    name: 'Falanghina Campi Flegrei',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Campi Flegrei',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 1994,
    avgPrice: 18,
    producers: ['Grotta del Sole'],
    aliases: ['Grotta del Sole']
  },
  {
    id: 'falanghina-campi-flegrei-astroni',
    name: 'Falanghina Campi Flegrei Vigna Astroni',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Campi Flegrei',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 24,
    producers: ['Astroni'],
    aliases: ['Vigna Astroni']
  },
  {
    id: 'falanghina-costa-amalfi-marisa-cuomo',
    name: 'Falanghina Costa d\'Amalfi',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Furore',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 28,
    producers: ['Marisa Cuomo'],
    aliases: ['Marisa Cuomo Falanghina']
  },
  {
    id: 'falanghina-costa-amalfi-fiorduva',
    name: 'Fiorduva Costa d\'Amalfi',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Furore',
    grapeVariety: 'Falanghina, Biancolella',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 38,
    producers: ['Marisa Cuomo'],
    aliases: ['Fiorduva']
  },
  {
    id: 'falanghina-sannio-fontanavecchia',
    name: 'Falanghina del Sannio',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Benevento',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 14,
    producers: ['Fontanavecchia'],
    aliases: ['Fontanavecchia Falanghina']
  },
  {
    id: 'falanghina-sannio-la-guardiense',
    name: 'Falanghina del Sannio',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Guardia Sanframondi',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 12,
    producers: ['La Guardiense'],
    aliases: ['La Guardiense Falanghina']
  },
  {
    id: 'falanghina-sannio-ocone',
    name: 'Falanghina del Taburno',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taburno',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 14,
    producers: ['Ocone'],
    aliases: ['Ocone Falanghina']
  },
  {
    id: 'falanghina-taburno-antica-masseria-venditti',
    name: 'Falanghina del Taburno',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Taburno',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Antica Masseria Venditti'],
    aliases: ['Venditti Falanghina']
  },
  {
    id: 'falanghina-villa-matilde',
    name: 'Falanghina del Massico',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Falerno del Massico',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 16,
    producers: ['Villa Matilde'],
    aliases: ['Villa Matilde Falanghina']
  },
  {
    id: 'falanghina-villa-matilde-falerno-bianco',
    name: 'Falerno del Massico Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Falerno del Massico',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 18,
    producers: ['Villa Matilde'],
    aliases: ['Falerno Bianco']
  },
  
  // PIEDIROSSO (Red - Campanian variety)
  {
    id: 'piedirosso-campi-flegrei-grotta-del-sole',
    name: 'Piedirosso Campi Flegrei',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Campi Flegrei',
    grapeVariety: 'Piedirosso',
    classification: 'DOC',
    minVintage: 1994,
    avgPrice: 20,
    producers: ['Grotta del Sole'],
    aliases: ['Grotta del Sole Piedirosso']
  },
  {
    id: 'piedirosso-campi-flegrei-contrada-salandra',
    name: 'Piedirosso Campi Flegrei Contrada Salandra',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Campi Flegrei',
    grapeVariety: 'Piedirosso',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Contrada Salandra'],
    aliases: ['Contrada Salandra']
  },
  {
    id: 'piedirosso-costa-amalfi-marisa-cuomo',
    name: 'Furore Rosso Costa d\'Amalfi',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Furore',
    grapeVariety: 'Piedirosso, Aglianico',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 32,
    producers: ['Marisa Cuomo'],
    aliases: ['Furore Rosso']
  },
  {
    id: 'piedirosso-villa-matilde',
    name: 'Piedirosso Campania IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Caserta',
    grapeVariety: 'Piedirosso',
    classification: 'IGT',
    minVintage: 1985,
    avgPrice: 18,
    producers: ['Villa Matilde'],
    aliases: ['Villa Matilde Piedirosso']
  },
  {
    id: 'piedirosso-mustilli',
    name: 'Piedirosso Sant\'Agata dei Goti',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Sant\'Agata dei Goti',
    grapeVariety: 'Piedirosso',
    classification: 'DOC',
    minVintage: 1991,
    avgPrice: 16,
    producers: ['Mustilli'],
    aliases: ['Mustilli Piedirosso']
  },
  
  // LACRYMA CHRISTI DEL VESUVIO DOC
  {
    id: 'lacryma-christi-vesuvio-rosso-mastroberardino',
    name: 'Lacryma Christi del Vesuvio Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Vesuvio',
    grapeVariety: 'Piedirosso, Aglianico',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 18,
    producers: ['Mastroberardino'],
    aliases: ['Lacryma Christi Rosso']
  },
  {
    id: 'lacryma-christi-vesuvio-bianco-mastroberardino',
    name: 'Lacryma Christi del Vesuvio Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Vesuvio',
    grapeVariety: 'Coda di Volpe, Falanghina',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 16,
    producers: ['Mastroberardino'],
    aliases: ['Lacryma Christi Bianco']
  },
  {
    id: 'lacryma-christi-vesuvio-rosso-sorrentino',
    name: 'Lacryma Christi del Vesuvio Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Vesuvio',
    grapeVariety: 'Piedirosso',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 16,
    producers: ['Sorrentino'],
    aliases: ['Sorrentino Lacryma Christi']
  },
  {
    id: 'lacryma-christi-vesuvio-bianco-sorrentino',
    name: 'Lacryma Christi del Vesuvio Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Vesuvio',
    grapeVariety: 'Coda di Volpe',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 14,
    producers: ['Sorrentino'],
    aliases: ['Sorrentino Lacryma Bianco']
  },
  
  // ASPRINIO (Sparkling/White)
  {
    id: 'asprinio-aversa-grotta-del-sole',
    name: 'Asprinio di Aversa',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Aversa',
    grapeVariety: 'Asprinio',
    classification: 'DOC',
    minVintage: 1994,
    avgPrice: 14,
    producers: ['Grotta del Sole'],
    aliases: ['Grotta del Sole Asprinio']
  },
  {
    id: 'asprinio-aversa-vestini-campagnano',
    name: 'Asprinio di Aversa',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Aversa',
    grapeVariety: 'Asprinio',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Vestini Campagnano'],
    aliases: ['Vestini Asprinio']
  },
  
  // COSTA D'AMALFI & PENINSULA WINES
  {
    id: 'costa-amalfi-montevetrano-bianco',
    name: 'Montevetrano Bianco Colli di Salerno IGT',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Salerno',
    grapeVariety: 'Fiano, Falanghina, Greco',
    classification: 'IGT',
    minVintage: 2007,
    avgPrice: 42,
    producers: ['Montevetrano'],
    aliases: ['Montevetrano Bianco']
  },
  {
    id: 'costa-amalfi-luigi-maffini-kratos',
    name: 'Kratos Paestum Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Paestum',
    grapeVariety: 'Fiano',
    classification: 'DOC',
    minVintage: 2007,
    avgPrice: 28,
    producers: ['Luigi Maffini'],
    aliases: ['Kratos']
  },
  {
    id: 'costa-amalfi-luigi-maffini-pietraincatenata',
    name: 'Pietraincatenata Paestum Fiano',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Paestum',
    grapeVariety: 'Fiano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Luigi Maffini'],
    aliases: ['Pietraincatenata']
  },
  {
    id: 'costa-amalfi-de-conciliis-selim',
    name: 'Selim Paestum Fiano',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Paestum',
    grapeVariety: 'Fiano',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 24,
    producers: ['De Conciliis'],
    aliases: ['Selim']
  },
  {
    id: 'costa-amalfi-san-salvatore-jungano',
    name: 'Jungano Paestum Fiano',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Paestum',
    grapeVariety: 'Fiano',
    classification: 'DOC',
    minVintage: 2003,
    avgPrice: 26,
    producers: ['San Salvatore'],
    aliases: ['Jungano']
  },
  {
    id: 'costa-amalfi-san-salvatore-pian-di-stio',
    name: 'Pian di Stio Paestum Greco',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Paestum',
    grapeVariety: 'Greco',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 28,
    producers: ['San Salvatore'],
    aliases: ['Pian di Stio']
  },
  
  // ADDITIONAL CAMPANIAN WINES
  {
    id: 'campania-feudi-san-gregorio-greco-grottolella',
    name: 'Greco Grottolella Campania IGT',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Greco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 24,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Greco Grottolella']
  },
  {
    id: 'campania-feudi-san-gregorio-dubl',
    name: 'Dubl Campania IGT',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Greco, Fiano',
    classification: 'IGT',
    minVintage: 2009,
    avgPrice: 35,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Dubl']
  },
  {
    id: 'campania-terredora-pago',
    name: 'Pago Campania IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Aglianico, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2002,
    avgPrice: 38,
    producers: ['Terredora'],
    aliases: ['Pago']
  },
  {
    id: 'campania-antonio-caggiano-salae-domini',
    name: 'Salae Domini Irpinia Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Antonio Caggiano'],
    aliases: ['Salae Domini']
  },
  {
    id: 'campania-antonio-caggiano-mel',
    name: 'Mel Irpinia Greco',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Greco',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Antonio Caggiano'],
    aliases: ['Mel']
  },
  {
    id: 'campania-quintodecimo-vigna-della-congregazione',
    name: 'Vigna della Congregazione Campania IGT',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Fiano, Greco',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 55,
    producers: ['Quintodecimo'],
    aliases: ['Vigna della Congregazione']
  },
  {
    id: 'campania-villa-matilde-camarato-bianco',
    name: 'Camarato Bianco Falerno del Massico',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Falerno del Massico',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Villa Matilde'],
    aliases: ['Camarato Bianco']
  },
  {
    id: 'campania-cantine-astroni-falanghina-passito',
    name: 'Falanghina Passito Campi Flegrei',
    type: 'Dessert',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Campi Flegrei',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Astroni'],
    aliases: ['Falanghina Passito']
  },
  {
    id: 'campania-marisa-cuomo-ravello-bianco',
    name: 'Ravello Bianco Costa d\'Amalfi',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Ravello',
    grapeVariety: 'Biancolella, Falanghina',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 26,
    producers: ['Marisa Cuomo'],
    aliases: ['Ravello Bianco']
  },
  {
    id: 'campania-marisa-cuomo-ravello-rosso',
    name: 'Ravello Rosso Costa d\'Amalfi',
    type: 'Red',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Ravello',
    grapeVariety: 'Piedirosso, Aglianico',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Marisa Cuomo'],
    aliases: ['Ravello Rosso']
  },
  {
    id: 'campania-terredora-aminea',
    name: 'Aminea Campania IGT',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Coda di Volpe',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Terredora'],
    aliases: ['Aminea']
  },
  {
    id: 'campania-mustilli-asprinio',
    name: 'Asprinio Spumante',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Sant\'Agata dei Goti',
    grapeVariety: 'Asprinio',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Mustilli'],
    aliases: ['Mustilli Asprinio Spumante']
  },
  {
    id: 'campania-cantine-lonardo-fiano',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 1999,
    avgPrice: 20,
    producers: ['Cantine Lonardo'],
    aliases: ['Lonardo Fiano']
  },
  {
    id: 'campania-vadiaperti-greco',
    name: 'Greco di Tufo',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 2004,
    avgPrice: 18,
    producers: ['Vadiaperti'],
    aliases: ['Vadiaperti Greco']
  },
  {
    id: 'campania-perillo-fiano',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 2002,
    avgPrice: 20,
    producers: ['Perillo'],
    aliases: ['Perillo Fiano']
  },
  {
    id: 'campania-borgodangelo-greco',
    name: 'Greco di Tufo',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Borgodangelo'],
    aliases: ['Borgodangelo Greco']
  },
  {
    id: 'campania-feudi-san-gregorio-falanghina-sannio',
    name: 'Falanghina del Sannio',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Sannio',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 1997,
    avgPrice: 16,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Feudi Falanghina Sannio']
  },
];
