import { WineTemplate } from '@/types/wineDatabase';

/**
 * BASILICATA WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Additional producers, Dessert wines, Regional blends, Passito
 * Updated: January 2025
 */

export const basilicataPart3: WineTemplate[] = [
  // ADDITIONAL AGLIANICO PRODUCERS
  {
    id: 'basilicata-cantine-dipalma-riserva',
    name: 'Aglianico del Vulture Superiore Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Cantine Di Palma'],
    aliases: ['Di Palma Riserva']
  },
  {
    id: 'basilicata-armando-martino-riserva',
    name: 'Aglianico del Vulture Superiore Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 42,
    producers: ['Armando Martino'],
    aliases: ['Martino Riserva']
  },
  {
    id: 'basilicata-bisceglia-riserva',
    name: 'Aglianico del Vulture Superiore Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Bisceglia'],
    aliases: ['Bisceglia Riserva']
  },
  {
    id: 'basilicata-tenuta-le-querce-riserva',
    name: 'Aglianico del Vulture Superiore Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2010,
    avgPrice: 45,
    producers: ['Tenuta Le Querce'],
    aliases: ['Tenuta Le Querce Riserva']
  },
  {
    id: 'basilicata-eubea-riserva',
    name: 'Aglianico del Vulture Superiore Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2012,
    avgPrice: 48,
    producers: ['Eubea'],
    aliases: ['Eubea Riserva']
  },
  {
    id: 'basilicata-macarico-riserva',
    name: 'Aglianico del Vulture Superiore Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2010,
    avgPrice: 42,
    producers: ['Macarico'],
    aliases: ['Macarico Riserva']
  },
  {
    id: 'basilicata-botte-piccola-riserva',
    name: 'Aglianico del Vulture Superiore Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2012,
    avgPrice: 45,
    producers: ['Botte Piccola'],
    aliases: ['Botte Piccola Riserva']
  },
  {
    id: 'basilicata-solagna-del-titolo-riserva',
    name: 'Aglianico del Vulture Superiore Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2010,
    avgPrice: 52,
    producers: ['Solagna del Titolo'],
    aliases: ['Solagna Riserva']
  },
  
  // AGLIANICO PASSITO (Dessert)
  {
    id: 'aglianico-passito-paternoster',
    name: 'Aglianico del Vulture Passito',
    type: 'Dessert',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 48,
    producers: ['Paternoster'],
    aliases: ['Paternoster Passito']
  },
  {
    id: 'aglianico-passito-cantine-del-notaio',
    name: 'Aglianico Passito Basilicata IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 55,
    producers: ['Cantine del Notaio'],
    aliases: ['Notaio Passito']
  },
  {
    id: 'aglianico-passito-donato-d-angelo',
    name: 'Aglianico Passito Basilicata IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 52,
    producers: ['Donato D\'Angelo'],
    aliases: ['D\'Angelo Passito']
  },
  
  // MALVASIA PASSITO (Dessert)
  {
    id: 'malvasia-passito-cantine-del-notaio',
    name: 'Malvasia Passito Basilicata IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Malvasia',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 42,
    producers: ['Cantine del Notaio'],
    aliases: ['Notaio Malvasia Passito']
  },
  {
    id: 'malvasia-passito-paternoster',
    name: 'Malvasia Passito Basilicata IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Malvasia',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Paternoster'],
    aliases: ['Paternoster Malvasia Passito']
  },
  
  // ADDITIONAL REGIONAL BLENDS
  {
    id: 'basilicata-cantine-strapellum-rosso',
    name: 'Rosso Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico, Primitivo',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 24,
    producers: ['Cantine Strapellum'],
    aliases: ['Strapellum Rosso']
  },
  {
    id: 'basilicata-re-manfredi-rosso',
    name: 'Rosso Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 28,
    producers: ['Re Manfredi'],
    aliases: ['Re Manfredi Rosso']
  },
  {
    id: 'basilicata-consorzio-viticoltori-rosso',
    name: 'Rosso Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico, Sangiovese',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Consorzio Viticoltori Vulture'],
    aliases: ['Consorzio Rosso']
  },
  {
    id: 'basilicata-cantina-cooperativa-barile-rosso',
    name: 'Rosso Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico, Primitivo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Cantina Cooperativa di Barile'],
    aliases: ['Barile Rosso']
  },
  
  // GRECO (White variety)
  {
    id: 'greco-basilicata-elena-fucci',
    name: 'Greco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 22,
    producers: ['Elena Fucci'],
    aliases: ['Elena Fucci Greco']
  },
  {
    id: 'greco-basilicata-terre-degli-svevi',
    name: 'Greco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Terre degli Svevi'],
    aliases: ['Terre degli Svevi Greco']
  },
  {
    id: 'greco-basilicata-donato-d-angelo',
    name: 'Greco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Donato D\'Angelo'],
    aliases: ['D\'Angelo Greco']
  },
  
  // FIANO (White variety)
  {
    id: 'fiano-basilicata-paternoster',
    name: 'Fiano Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Fiano',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Paternoster'],
    aliases: ['Paternoster Fiano']
  },
  {
    id: 'fiano-basilicata-grifalco',
    name: 'Fiano Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Fiano',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 20,
    producers: ['Grifalco della Lucania'],
    aliases: ['Grifalco Fiano']
  },
  {
    id: 'fiano-basilicata-terre-degli-svevi',
    name: 'Fiano Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Fiano',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Terre degli Svevi'],
    aliases: ['Terre degli Svevi Fiano']
  },
  
  // SANGIOVESE BLENDS
  {
    id: 'sangiovese-basilicata-paternoster',
    name: 'Sangiovese Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Matera',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Paternoster'],
    aliases: ['Paternoster Sangiovese']
  },
  {
    id: 'sangiovese-basilicata-grifalco',
    name: 'Sangiovese Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Matera',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 14,
    producers: ['Grifalco della Lucania'],
    aliases: ['Grifalco Sangiovese']
  },
  
  // ADDITIONAL PRODUCERS & WINES
  {
    id: 'basilicata-michele-laluce-rosato',
    name: 'Rosato Basilicata IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Michele Laluce'],
    aliases: ['Michele Laluce Rosato']
  },
  {
    id: 'basilicata-musto-carmelitano-rosato',
    name: 'Rosato Basilicata IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 14,
    producers: ['Musto Carmelitano'],
    aliases: ['Musto Carmelitano Rosato']
  },
  {
    id: 'basilicata-basilisco-rosato',
    name: 'Rosato Basilicata IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Basilisco'],
    aliases: ['Basilisco Rosato']
  },
  {
    id: 'basilicata-vigneti-del-vulture-rosato',
    name: 'Rosato Basilicata IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 14,
    producers: ['Vigneti del Vulture'],
    aliases: ['Vigneti del Vulture Rosato']
  },
  {
    id: 'basilicata-donato-d-angelo-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Fiano',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Donato D\'Angelo'],
    aliases: ['D\'Angelo Bianco']
  },
  {
    id: 'basilicata-cantine-dipalma-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Malvasia',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 14,
    producers: ['Cantine Di Palma'],
    aliases: ['Di Palma Bianco']
  },
  {
    id: 'basilicata-armando-martino-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Armando Martino'],
    aliases: ['Martino Bianco']
  },
  {
    id: 'basilicata-bisceglia-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Malvasia',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 14,
    producers: ['Bisceglia'],
    aliases: ['Bisceglia Bianco']
  },
  {
    id: 'basilicata-botte-piccola-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Fiano',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 18,
    producers: ['Botte Piccola'],
    aliases: ['Botte Piccola Bianco']
  },
  {
    id: 'basilicata-solagna-del-titolo-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 20,
    producers: ['Solagna del Titolo'],
    aliases: ['Solagna Bianco']
  },
  {
    id: 'basilicata-cantine-strapellum-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Malvasia',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 16,
    producers: ['Cantine Strapellum'],
    aliases: ['Strapellum Bianco']
  },
  {
    id: 'basilicata-re-manfredi-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Fiano',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Re Manfredi'],
    aliases: ['Re Manfredi Bianco']
  },
  {
    id: 'basilicata-consorzio-viticoltori-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Malvasia',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 12,
    producers: ['Consorzio Viticoltori Vulture'],
    aliases: ['Consorzio Bianco']
  },
  {
    id: 'basilicata-cantina-cooperativa-barile-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Malvasia',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 11,
    producers: ['Cantina Cooperativa di Barile'],
    aliases: ['Barile Bianco']
  },
  {
    id: 'basilicata-cantina-di-venosa-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Malvasia',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 12,
    producers: ['Cantina di Venosa'],
    aliases: ['Cantina di Venosa Bianco']
  },
];
