import { WineTemplate } from '@/types/wineDatabase';

/**
 * LIGURIA WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Additional regional wines, Albarola, Bosco, Sparkling, Blends
 * Updated: January 2025
 */

export const liguriapart3: WineTemplate[] = [
  // ADDITIONAL CINQUE TERRE PRODUCERS
  {
    id: 'cinque-terre-d-arte',
    name: 'Cinque Terre',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['D\'Arte'],
    aliases: ['D\'Arte Cinque Terre']
  },
  {
    id: 'cinque-terre-samuele-heydi',
    name: 'Cinque Terre',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 24,
    producers: ['Samuele Heydi'],
    aliases: ['Samuele Heydi Cinque Terre']
  },
  {
    id: 'sciacchetra-d-arte',
    name: 'Cinque Terre Sciacchetrà',
    type: 'Dessert',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 80,
    producers: ['D\'Arte'],
    aliases: ['D\'Arte Sciacchetrà']
  },
  {
    id: 'sciacchetra-samuele-heydi',
    name: 'Cinque Terre Sciacchetrà',
    type: 'Dessert',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 78,
    producers: ['Samuele Heydi'],
    aliases: ['Samuele Heydi Sciacchetrà']
  },
  
  // ALBAROLA (Indigenous white grape)
  {
    id: 'albarola-bisson-u-megu',
    name: 'U Megu Albarola Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Albarola',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Bisson'],
    aliases: ['U Megu']
  },
  {
    id: 'albarola-walter-de-batte',
    name: 'Albarola Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Albarola',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 32,
    producers: ['Walter De Batté'],
    aliases: ['De Batté Albarola']
  },
  
  // BOSCO (Indigenous white grape)
  {
    id: 'bosco-bisson',
    name: 'Bosco Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Bosco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 26,
    producers: ['Bisson'],
    aliases: ['Bisson Bosco']
  },
  
  // CILIEGIOLO
  {
    id: 'ciliegiolo-bisson-ciliegiolo-del-golfo',
    name: 'Ciliegiolo del Golfo Liguria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Ciliegiolo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Bisson'],
    aliases: ['Ciliegiolo del Golfo']
  },
  
  // MASSARETTA (Indigenous red grape)
  {
    id: 'massaretta-bisson',
    name: 'Massaretta Liguria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Massaretta',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 32,
    producers: ['Bisson'],
    aliases: ['Bisson Massaretta']
  },
  
  // SPARKLING WINES
  {
    id: 'spumante-bisson-abissi-metodo-classico',
    name: 'Abissi Spumante Metodo Classico',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Vermentino, Bianchetta Genovese',
    classification: 'IGT',
    minVintage: 2007,
    avgPrice: 65,
    producers: ['Bisson'],
    aliases: ['Abissi']
  },
  {
    id: 'spumante-bisson-brut',
    name: 'Spumante Brut Metodo Classico',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Bisson'],
    aliases: ['Bisson Spumante']
  },
  {
    id: 'spumante-cantine-lunae-brut',
    name: 'Spumante Brut Metodo Classico',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Cantine Lunae Bosoni'],
    aliases: ['Lunae Spumante']
  },
  
  // ROSÉ WINES
  {
    id: 'rosato-terre-bianche',
    name: 'Rosato Liguria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Terre Bianche'],
    aliases: ['Terre Bianche Rosato']
  },
  {
    id: 'rosato-lupi',
    name: 'Rosato Liguria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pieve di Teco',
    grapeVariety: 'Rossese, Ormeasco',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Lupi'],
    aliases: ['Lupi Rosato']
  },
  {
    id: 'rosato-bisson',
    name: 'Rosato Liguria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Ciliegiolo',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Bisson'],
    aliases: ['Bisson Rosato']
  },
  
  // ADDITIONAL PREMIUM BLENDS
  {
    id: 'liguria-bisson-portofino',
    name: 'Portofino Bianco Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Vermentino, Bianchetta Genovese',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Bisson'],
    aliases: ['Portofino Bianco']
  },
  {
    id: 'liguria-cantine-lunae-cavagino',
    name: 'Cavagino Colli di Luni',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Sangiovese, Canaiolo, Pollera Nera',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Cantine Lunae Bosoni'],
    aliases: ['Cavagino']
  },
  {
    id: 'liguria-la-felce-pollera-nera',
    name: 'Pollera Nera Colli di Luni',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Pollera Nera',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['La Felce'],
    aliases: ['La Felce Pollera Nera']
  },
  {
    id: 'liguria-terenzuola-montebello',
    name: 'Montebello Colli di Luni',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Sangiovese, Canaiolo',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Terenzuola'],
    aliases: ['Montebello']
  },
  {
    id: 'liguria-durin-pigato-passito',
    name: 'Pigato Passito Liguria IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ortovero',
    grapeVariety: 'Pigato',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 42,
    producers: ['Durin'],
    aliases: ['Durin Pigato Passito']
  },
  {
    id: 'liguria-bruna-pigato-passito',
    name: 'Pigato Passito Liguria IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Pigato',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 45,
    producers: ['Bruna'],
    aliases: ['Bruna Pigato Passito']
  },
  {
    id: 'liguria-vis-amoris-pigato-passito',
    name: 'Pigato Passito Liguria IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Pigato',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 48,
    producers: ['Vis Amoris'],
    aliases: ['Vis Amoris Pigato Passito']
  },
  {
    id: 'liguria-ottaviano-lambruschi-sangiovese',
    name: 'Sangiovese Colli di Luni',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Sangiovese',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Ottaviano Lambruschi'],
    aliases: ['Lambruschi Sangiovese']
  },
  {
    id: 'liguria-cascina-nirasca-granaccia',
    name: 'Granaccia Liguria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pornassio',
    grapeVariety: 'Grenache',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 22,
    producers: ['Cascina Nirasca'],
    aliases: ['Cascina Nirasca Granaccia']
  },
  {
    id: 'liguria-maccario-dringenberg-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 20,
    producers: ['Maccario Dringenberg'],
    aliases: ['Maccario Dringenberg Vermentino']
  },
  {
    id: 'liguria-la-vecchia-cantina-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['La Vecchia Cantina'],
    aliases: ['La Vecchia Cantina Vermentino']
  },
  {
    id: 'liguria-claudio-vio-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Claudio Vio'],
    aliases: ['Claudio Vio Vermentino']
  },
  {
    id: 'liguria-cascina-delle-terre-rosse-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 20,
    producers: ['Cascina delle Terre Rosse'],
    aliases: ['Cascina delle Terre Rosse Vermentino']
  },
  {
    id: 'liguria-guglierame-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Guglierame'],
    aliases: ['Guglierame Vermentino']
  },
  {
    id: 'liguria-tenuta-giunche-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 20,
    producers: ['Tenuta Giunche'],
    aliases: ['Tenuta Giunche Vermentino']
  },
  {
    id: 'liguria-nico-daneri-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 20,
    producers: ['Nico Daneri'],
    aliases: ['Nico Daneri Vermentino']
  },
  {
    id: 'liguria-terre-rosse-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Terre Rosse'],
    aliases: ['Terre Rosse Vermentino']
  },
  {
    id: 'liguria-cascina-praie-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Cascina Praie'],
    aliases: ['Cascina Praie Vermentino']
  },
  {
    id: 'liguria-la-zerba-pigato',
    name: 'Pigato Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Pigato',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 22,
    producers: ['La Zerba'],
    aliases: ['La Zerba Pigato']
  },
  {
    id: 'liguria-buranco-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Buranco'],
    aliases: ['Buranco Vermentino']
  },
  {
    id: 'liguria-forlini-capellini-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Forlini Capellini'],
    aliases: ['Forlini Capellini Vermentino']
  },
  {
    id: 'liguria-arrigoni-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Arrigoni'],
    aliases: ['Arrigoni Vermentino']
  },
  {
    id: 'liguria-cooperativa-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Cooperativa Agricoltura Cinque Terre'],
    aliases: ['Cooperativa Vermentino']
  },
  {
    id: 'liguria-d-arte-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 24,
    producers: ['D\'Arte'],
    aliases: ['D\'Arte Vermentino']
  },
  {
    id: 'liguria-samuele-heydi-vermentino',
    name: 'Vermentino Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Samuele Heydi'],
    aliases: ['Samuele Heydi Vermentino']
  },
];
