import { WineTemplate } from '@/types/wineDatabase';

/**
 * FRIULI-VENEZIA GIULIA WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Ribolla Gialla, Chardonnay, Verduzzo, Malvasia Istriana
 * Updated: January 2025
 */

export const friuliPart2: WineTemplate[] = [
  // RIBOLLA GIALLA - COLLIO & ORANGE WINES
  {
    id: 'ribolla-gialla-gravner',
    name: 'Ribolla Gialla Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Ribolla Gialla',
    classification: 'IGT',
    minVintage: 1973,
    avgPrice: 95,
    producers: ['Gravner'],
    aliases: ['Gravner Ribolla']
  },
  {
    id: 'ribolla-gialla-radikon',
    name: 'Ribolla Gialla Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Ribolla Gialla',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 75,
    producers: ['Radikon'],
    aliases: ['Radikon Ribolla']
  },
  {
    id: 'ribolla-gialla-damijan-podversic',
    name: 'Ribolla Gialla Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Ribolla Gialla',
    classification: 'IGT',
    minVintage: 1988,
    avgPrice: 72,
    producers: ['Damijan Podversic'],
    aliases: ['Podversic Ribolla']
  },
  {
    id: 'ribolla-gialla-la-castellada',
    name: 'Ribolla Gialla Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Ribolla Gialla',
    classification: 'IGT',
    minVintage: 1985,
    avgPrice: 78,
    producers: ['La Castellada'],
    aliases: ['La Castellada Ribolla']
  },
  {
    id: 'ribolla-gialla-dario-princic',
    name: 'Ribolla Gialla Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Ribolla Gialla',
    classification: 'IGT',
    minVintage: 1993,
    avgPrice: 65,
    producers: ['Dario Princic'],
    aliases: ['Princic Ribolla']
  },
  {
    id: 'ribolla-gialla-edi-keber',
    name: 'Ribolla Gialla Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Ribolla Gialla',
    classification: 'DOC',
    minVintage: 1957,
    avgPrice: 38,
    producers: ['Edi Keber'],
    aliases: ['Keber Ribolla']
  },
  {
    id: 'ribolla-gialla-venica',
    name: 'Ribolla Gialla Collio Petris',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Ribolla Gialla',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 42,
    producers: ['Venica & Venica'],
    aliases: ['Petris']
  },
  {
    id: 'ribolla-gialla-marco-felluga',
    name: 'Ribolla Gialla Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Ribolla Gialla',
    classification: 'DOC',
    minVintage: 1956,
    avgPrice: 26,
    producers: ['Marco Felluga'],
    aliases: ['Marco Felluga Ribolla']
  },
  {
    id: 'ribolla-gialla-borgo-del-tiglio',
    name: 'Ribolla Gialla Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Ribolla Gialla',
    classification: 'DOC',
    minVintage: 1981,
    avgPrice: 52,
    producers: ['Borgo del Tiglio'],
    aliases: ['Borgo del Tiglio Ribolla']
  },
  {
    id: 'ribolla-gialla-zidarich',
    name: 'Ribolla Gialla Carso',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Carso',
    grapeVariety: 'Ribolla Gialla',
    classification: 'DOC',
    minVintage: 1988,
    avgPrice: 42,
    producers: ['Zidarich'],
    aliases: ['Zidarich Ribolla']
  },
  {
    id: 'ribolla-gialla-vodopivec',
    name: 'Ribolla Gialla Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Carso',
    grapeVariety: 'Ribolla Gialla',
    classification: 'IGT',
    minVintage: 1997,
    avgPrice: 85,
    producers: ['Vodopivec', 'Paolo Vodopivec'],
    aliases: ['Vodopivec Ribolla']
  },
  {
    id: 'ribolla-gialla-skerk',
    name: 'Ribolla Gialla Carso',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Carso',
    grapeVariety: 'Ribolla Gialla',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 45,
    producers: ['Skerk', 'Sandi Skerk'],
    aliases: ['Skerk Ribolla']
  },
  
  // CHARDONNAY - COLLIO & COLLI ORIENTALI
  {
    id: 'chardonnay-jermann-vintage-tunina',
    name: 'Vintage Tunina Venezia Giulia IGT',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Chardonnay, Sauvignon Blanc, Ribolla Gialla, Malvasia',
    classification: 'IGT',
    minVintage: 1975,
    avgPrice: 72,
    producers: ['Jermann'],
    aliases: ['Vintage Tunina']
  },
  {
    id: 'chardonnay-jermann',
    name: 'Chardonnay Venezia Giulia IGT',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 1975,
    avgPrice: 26,
    producers: ['Jermann'],
    aliases: ['Jermann Chardonnay']
  },
  {
    id: 'chardonnay-vie-di-romans-ciampagnis',
    name: 'Chardonnay Isonzo Ciampagnis Vieris',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Isonzo',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 62,
    producers: ['Vie di Romans'],
    aliases: ['Ciampagnis Vieris']
  },
  {
    id: 'chardonnay-venica',
    name: 'Chardonnay Collio Ronco Bernizza',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 38,
    producers: ['Venica & Venica'],
    aliases: ['Ronco Bernizza Chardonnay']
  },
  {
    id: 'chardonnay-villa-russiz',
    name: 'Chardonnay Collio Gräfin de la Tour',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 42,
    producers: ['Villa Russiz'],
    aliases: ['Gräfin de la Tour']
  },
  {
    id: 'chardonnay-livio-felluga',
    name: 'Chardonnay Colli Orientali del Friuli',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1956,
    avgPrice: 28,
    producers: ['Livio Felluga'],
    aliases: ['Livio Felluga Chardonnay']
  },
  {
    id: 'chardonnay-borgo-del-tiglio',
    name: 'Chardonnay Collio Studio di Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1981,
    avgPrice: 58,
    producers: ['Borgo del Tiglio'],
    aliases: ['Studio di Bianco']
  },
  {
    id: 'chardonnay-ronco-del-gnemiz',
    name: 'Chardonnay Colli Orientali del Friuli',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1964,
    avgPrice: 32,
    producers: ['Ronco del Gnemiz'],
    aliases: ['Gnemiz Chardonnay']
  },
  
  // MALVASIA ISTRIANA
  {
    id: 'malvasia-istriana-zidarich',
    name: 'Malvasia Carso',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Carso',
    grapeVariety: 'Malvasia Istriana',
    classification: 'DOC',
    minVintage: 1988,
    avgPrice: 48,
    producers: ['Zidarich'],
    aliases: ['Zidarich Malvasia']
  },
  {
    id: 'malvasia-istriana-skerk',
    name: 'Malvasia Carso',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Carso',
    grapeVariety: 'Malvasia Istriana',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 52,
    producers: ['Skerk'],
    aliases: ['Skerk Malvasia']
  },
  {
    id: 'malvasia-istriana-vodopivec',
    name: 'Malvasia Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Carso',
    grapeVariety: 'Malvasia Istriana',
    classification: 'IGT',
    minVintage: 1997,
    avgPrice: 95,
    producers: ['Vodopivec'],
    aliases: ['Vodopivec Malvasia']
  },
  {
    id: 'malvasia-istriana-edi-keber',
    name: 'Malvasia Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Malvasia Istriana',
    classification: 'DOC',
    minVintage: 1957,
    avgPrice: 42,
    producers: ['Edi Keber'],
    aliases: ['Keber Malvasia']
  },
  {
    id: 'malvasia-istriana-radikon',
    name: 'Malvasia Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Malvasia Istriana',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 68,
    producers: ['Radikon'],
    aliases: ['Radikon Malvasia']
  },
  {
    id: 'malvasia-istriana-gravner',
    name: 'Malvasia Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Malvasia Istriana',
    classification: 'IGT',
    minVintage: 1973,
    avgPrice: 88,
    producers: ['Gravner'],
    aliases: ['Gravner Malvasia']
  },
  
  // VERDUZZO FRIULANO (Sweet wine)
  {
    id: 'verduzzo-livio-felluga',
    name: 'Verduzzo Colli Orientali del Friuli',
    type: 'Dessert',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Verduzzo Friulano',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 42,
    producers: ['Livio Felluga'],
    aliases: ['Livio Felluga Verduzzo']
  },
  {
    id: 'verduzzo-ronco-del-gnemiz',
    name: 'Verduzzo Ramandolo',
    type: 'Dessert',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Ramandolo',
    grapeVariety: 'Verduzzo Friulano',
    classification: 'DOCG',
    minVintage: 1964,
    avgPrice: 48,
    producers: ['Ronco del Gnemiz'],
    aliases: ['Ramandolo']
  },
  {
    id: 'verduzzo-le-vigne-di-zamo',
    name: 'Verduzzo Ramandolo',
    type: 'Dessert',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Ramandolo',
    grapeVariety: 'Verduzzo Friulano',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 38,
    producers: ['Le Vigne di Zamò'],
    aliases: ['Zamò Ramandolo']
  },
  {
    id: 'verduzzo-giovanni-dri',
    name: 'Verduzzo Ramandolo',
    type: 'Dessert',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Ramandolo',
    grapeVariety: 'Verduzzo Friulano',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 35,
    producers: ['Giovanni Dri'],
    aliases: ['Dri Ramandolo']
  },
  
  // PREMIUM WHITE BLENDS
  {
    id: 'white-blend-livio-felluga-terre-alte',
    name: 'Terre Alte Colli Orientali del Friuli',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Friulano, Pinot Bianco, Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1981,
    avgPrice: 65,
    producers: ['Livio Felluga'],
    aliases: ['Terre Alte']
  },
  {
    id: 'white-blend-marco-felluga-mongris',
    name: 'Mongris Pinot Grigio Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 35,
    producers: ['Marco Felluga'],
    aliases: ['Mongris']
  },
  {
    id: 'white-blend-marco-felluga-molamatta',
    name: 'Molamatta Collio Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Pinot Grigio, Friulano, Ribolla Gialla',
    classification: 'DOC',
    minVintage: 1997,
    avgPrice: 28,
    producers: ['Marco Felluga'],
    aliases: ['Molamatta']
  },
  {
    id: 'white-blend-russiz-superiore-bianco',
    name: 'Collio Bianco Russiz Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Pinot Bianco, Friulano, Ribolla Gialla, Sauvignon',
    classification: 'DOC',
    minVintage: 1967,
    avgPrice: 38,
    producers: ['Russiz Superiore'],
    aliases: ['Russiz Superiore Bianco']
  },
  {
    id: 'white-blend-schiopetto-blanc-dei-rossi',
    name: 'Blanc dei Rossi Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Friulano, Sauvignon Blanc, Pinot Bianco',
    classification: 'DOC',
    minVintage: 1975,
    avgPrice: 48,
    producers: ['Schiopetto'],
    aliases: ['Blanc dei Rossi']
  },
  {
    id: 'white-blend-ronco-del-gnemiz-bianco-sot-lis-rivis',
    name: 'Bianco Sot Lis Rivis Colli Orientali del Friuli',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Pinot Bianco, Chardonnay, Malvasia',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 42,
    producers: ['Ronco del Gnemiz'],
    aliases: ['Sot Lis Rivis']
  },
  {
    id: 'white-blend-vie-di-romans-flors-di-uis',
    name: 'Flors di Uis Isonzo Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Isonzo',
    grapeVariety: 'Malvasia Istriana, Riesling',
    classification: 'DOC',
    minVintage: 1992,
    avgPrice: 68,
    producers: ['Vie di Romans'],
    aliases: ['Flors di Uis']
  },
  {
    id: 'white-blend-borgo-del-tiglio-malvasia',
    name: 'Malvasia Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Malvasia Istriana',
    classification: 'DOC',
    minVintage: 1981,
    avgPrice: 55,
    producers: ['Borgo del Tiglio'],
    aliases: ['Borgo del Tiglio Malvasia']
  },
  {
    id: 'white-blend-le-vigne-di-zamo-tullio-zamo',
    name: 'Tullio Zamò Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Friulano, Chardonnay, Sauvignon',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Le Vigne di Zamò'],
    aliases: ['Tullio Zamò']
  },
  {
    id: 'white-blend-villa-russiz-sauvignon-de-la-tour',
    name: 'Sauvignon de la Tour Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 38,
    producers: ['Villa Russiz'],
    aliases: ['Sauvignon de la Tour']
  },
];
