import { WineTemplate } from '@/types/wineDatabase';

/**
 * MARCHE WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Rosso Conero DOC & DOCG, Rosso Piceno DOC
 * Updated: January 2025
 */

export const marchePart2: WineTemplate[] = [
  // CONERO DOCG (Red - Montepulciano)
  {
    id: 'conero-umani-ronchi-cùmaro-riserva',
    name: 'Conero Riserva Cùmaro',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 42,
    producers: ['Umani Ronchi'],
    aliases: ['Cùmaro']
  },
  {
    id: 'conero-umani-ronchi-campo-san-giorgio',
    name: 'Conero Riserva Campo San Giorgio',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 55,
    producers: ['Umani Ronchi'],
    aliases: ['Campo San Giorgio']
  },
  {
    id: 'conero-umani-ronchi',
    name: 'Rosso Conero',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1957,
    avgPrice: 16,
    producers: ['Umani Ronchi'],
    aliases: ['Umani Ronchi Rosso Conero']
  },
  {
    id: 'conero-garofoli-grosso-agontano',
    name: 'Conero Riserva Grosso Agontano',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 38,
    producers: ['Garofoli'],
    aliases: ['Grosso Agontano']
  },
  {
    id: 'conero-garofoli-piancarda',
    name: 'Rosso Conero Piancarda',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 22,
    producers: ['Garofoli'],
    aliases: ['Piancarda']
  },
  {
    id: 'conero-garofoli',
    name: 'Rosso Conero',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1901,
    avgPrice: 14,
    producers: ['Garofoli'],
    aliases: ['Garofoli Rosso Conero']
  },
  {
    id: 'conero-lanari-fibbio',
    name: 'Conero Riserva Fibbio',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 35,
    producers: ['Lanari'],
    aliases: ['Fibbio']
  },
  {
    id: 'conero-lanari',
    name: 'Rosso Conero',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 18,
    producers: ['Lanari'],
    aliases: ['Lanari Rosso Conero']
  },
  {
    id: 'conero-moroder-dorico',
    name: 'Conero Riserva Dorico',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 1984,
    avgPrice: 42,
    producers: ['Moroder'],
    aliases: ['Dorico']
  },
  {
    id: 'conero-moroder',
    name: 'Rosso Conero',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 18,
    producers: ['Moroder'],
    aliases: ['Moroder Rosso Conero']
  },
  {
    id: 'conero-fattoria-le-terrazze-sassi-neri',
    name: 'Conero Riserva Sassi Neri',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 1994,
    avgPrice: 48,
    producers: ['Fattoria Le Terrazze'],
    aliases: ['Sassi Neri']
  },
  {
    id: 'conero-fattoria-le-terrazze-visions',
    name: 'Rosso Conero Visions of J',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Fattoria Le Terrazze'],
    aliases: ['Visions of J']
  },
  {
    id: 'conero-fattoria-le-terrazze',
    name: 'Rosso Conero',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1994,
    avgPrice: 18,
    producers: ['Fattoria Le Terrazze'],
    aliases: ['Le Terrazze Rosso Conero']
  },
  {
    id: 'conero-monte-schiavo-adeodato',
    name: 'Conero Riserva Adeodato',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Monte Schiavo'],
    aliases: ['Adeodato']
  },
  {
    id: 'conero-monte-schiavo',
    name: 'Rosso Conero',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1994,
    avgPrice: 14,
    producers: ['Monte Schiavo'],
    aliases: ['Monte Schiavo Rosso Conero']
  },
  {
    id: 'conero-Alessandro-moroder-il-cantico',
    name: 'Conero Riserva Il Cantico della Croce',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 45,
    producers: ['Alessandro Moroder'],
    aliases: ['Il Cantico della Croce']
  },
  
  // ROSSO PICENO DOC & SUPERIORE
  {
    id: 'rosso-piceno-umani-ronchi-san-lorenzo',
    name: 'Rosso Piceno Superiore San Lorenzo',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Umani Ronchi'],
    aliases: ['San Lorenzo']
  },
  {
    id: 'rosso-piceno-umani-ronchi',
    name: 'Rosso Piceno',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1957,
    avgPrice: 12,
    producers: ['Umani Ronchi'],
    aliases: ['Umani Ronchi Rosso Piceno']
  },
  {
    id: 'rosso-piceno-velenosi-brecciarolo',
    name: 'Rosso Piceno Superiore Brecciarolo',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 22,
    producers: ['Velenosi'],
    aliases: ['Brecciarolo']
  },
  {
    id: 'rosso-piceno-velenosi-roggio-del-filare',
    name: 'Rosso Piceno Superiore Roggio del Filare',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 35,
    producers: ['Velenosi'],
    aliases: ['Roggio del Filare']
  },
  {
    id: 'rosso-piceno-velenosi',
    name: 'Rosso Piceno',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 11,
    producers: ['Velenosi'],
    aliases: ['Velenosi Rosso Piceno']
  },
  {
    id: 'rosso-piceno-saladini-pilastri-vigna-monteprandone',
    name: 'Rosso Piceno Superiore Vigna Monteprandone',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Saladini Pilastri'],
    aliases: ['Vigna Monteprandone']
  },
  {
    id: 'rosso-piceno-saladini-pilastri',
    name: 'Rosso Piceno',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 12,
    producers: ['Saladini Pilastri'],
    aliases: ['Saladini Pilastri Rosso Piceno']
  },
  {
    id: 'rosso-piceno-ciu-ciu-bacchus',
    name: 'Rosso Piceno Superiore Bacchus',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 24,
    producers: ['Ciu Ciu'],
    aliases: ['Bacchus']
  },
  {
    id: 'rosso-piceno-ciu-ciu',
    name: 'Rosso Piceno',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 11,
    producers: ['Ciu Ciu'],
    aliases: ['Ciu Ciu Rosso Piceno']
  },
  {
    id: 'rosso-piceno-oasi-degli-angeli-kurni',
    name: 'Kurni Marche IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano',
    classification: 'IGT',
    minVintage: 1998,
    avgPrice: 125,
    producers: ['Oasi degli Angeli'],
    aliases: ['Kurni']
  },
  {
    id: 'rosso-piceno-oasi-degli-angeli',
    name: 'Rosso Piceno',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 18,
    producers: ['Oasi degli Angeli'],
    aliases: ['Oasi degli Angeli Rosso Piceno']
  },
  {
    id: 'rosso-piceno-aurora',
    name: 'Rosso Piceno Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Aurora'],
    aliases: ['Aurora Rosso Piceno']
  },
  {
    id: 'rosso-piceno-tenuta-cocci-grifoni-vigna-messieri',
    name: 'Rosso Piceno Superiore Vigna Messieri',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1969,
    avgPrice: 26,
    producers: ['Tenuta Cocci Grifoni'],
    aliases: ['Vigna Messieri']
  },
  {
    id: 'rosso-piceno-tenuta-cocci-grifoni',
    name: 'Rosso Piceno',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1969,
    avgPrice: 12,
    producers: ['Tenuta Cocci Grifoni'],
    aliases: ['Cocci Grifoni Rosso Piceno']
  },
  {
    id: 'rosso-piceno-la-canestraia',
    name: 'Rosso Piceno',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['La Canestraia'],
    aliases: ['La Canestraia Rosso Piceno']
  },
  
  // LACRIMA DI MORRO D'ALBA DOC (Red)
  {
    id: 'lacrima-marotti-campi-orgiolo',
    name: 'Lacrima di Morro d\'Alba Superiore Orgiolo',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Morro d\'Alba',
    grapeVariety: 'Lacrima',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Marotti Campi'],
    aliases: ['Orgiolo']
  },
  {
    id: 'lacrima-marotti-campi',
    name: 'Lacrima di Morro d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Morro d\'Alba',
    grapeVariety: 'Lacrima',
    classification: 'DOC',
    minVintage: 1999,
    avgPrice: 16,
    producers: ['Marotti Campi'],
    aliases: ['Marotti Campi Lacrima']
  },
  {
    id: 'lacrima-stefano-mancinelli',
    name: 'Lacrima di Morro d\'Alba Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Morro d\'Alba',
    grapeVariety: 'Lacrima',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 22,
    producers: ['Stefano Mancinelli'],
    aliases: ['Mancinelli Lacrima']
  },
  {
    id: 'lacrima-vignamato',
    name: 'Lacrima di Morro d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Morro d\'Alba',
    grapeVariety: 'Lacrima',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Vignamato'],
    aliases: ['Vignamato Lacrima']
  },
  {
    id: 'lacrima-fattoria-coroncino',
    name: 'Lacrima di Morro d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Morro d\'Alba',
    grapeVariety: 'Lacrima',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Fattoria Coroncino'],
    aliases: ['Coroncino Lacrima']
  },
  {
    id: 'lacrima-monte-schiavo',
    name: 'Lacrima di Morro d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Morro d\'Alba',
    grapeVariety: 'Lacrima',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Monte Schiavo'],
    aliases: ['Monte Schiavo Lacrima']
  },
  
  // VERNACCIA DI SERRAPETRONA DOCG (Sparkling red)
  {
    id: 'vernaccia-serrapetrona-fontezoppa',
    name: 'Vernaccia di Serrapetrona',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Serrapetrona',
    grapeVariety: 'Vernaccia Nera',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 28,
    producers: ['Fontezoppa'],
    aliases: ['Fontezoppa Vernaccia']
  },
  {
    id: 'vernaccia-serrapetrona-alberto-quacquarini',
    name: 'Vernaccia di Serrapetrona',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Serrapetrona',
    grapeVariety: 'Vernaccia Nera',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 32,
    producers: ['Alberto Quacquarini'],
    aliases: ['Quacquarini Vernaccia']
  },
  {
    id: 'vernaccia-serrapetrona-colleluce',
    name: 'Vernaccia di Serrapetrona',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Serrapetrona',
    grapeVariety: 'Vernaccia Nera',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 26,
    producers: ['Colleluce'],
    aliases: ['Colleluce Vernaccia']
  },
];
