import { WineTemplate } from '@/types/wineDatabase';

/**
 * CAMPANIA WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Fiano di Avellino DOCG, Greco di Tufo DOCG
 * Updated: January 2025
 */

export const campaniaPart2: WineTemplate[] = [
  // FIANO DI AVELLINO DOCG (White)
  {
    id: 'fiano-avellino-mastroberardino-radici',
    name: 'Fiano di Avellino Radici',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 2001,
    avgPrice: 45,
    producers: ['Mastroberardino'],
    aliases: ['Radici Fiano']
  },
  {
    id: 'fiano-avellino-mastroberardino',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 1928,
    avgPrice: 22,
    producers: ['Mastroberardino'],
    aliases: ['Mastroberardino Fiano']
  },
  {
    id: 'fiano-avellino-feudi-san-gregorio-pietracalda',
    name: 'Fiano di Avellino Pietracalda',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 1996,
    avgPrice: 32,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Pietracalda']
  },
  {
    id: 'fiano-avellino-feudi-san-gregorio',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 1986,
    avgPrice: 20,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Feudi Fiano']
  },
  {
    id: 'fiano-avellino-terredora-terre-degli-angeli',
    name: 'Fiano di Avellino Terre degli Angeli',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 1994,
    avgPrice: 28,
    producers: ['Terredora'],
    aliases: ['Terre degli Angeli']
  },
  {
    id: 'fiano-avellino-terredora',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 18,
    producers: ['Terredora'],
    aliases: ['Terredora Fiano']
  },
  {
    id: 'fiano-avellino-colli-di-lapio',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 1994,
    avgPrice: 24,
    producers: ['Colli di Lapio', 'Clelia Romano'],
    aliases: ['Colli di Lapio']
  },
  {
    id: 'fiano-avellino-benito-ferrara-vigna-cicogna',
    name: 'Fiano di Avellino Vigna Cicogna',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 2007,
    avgPrice: 26,
    producers: ['Benito Ferrara'],
    aliases: ['Vigna Cicogna Fiano']
  },
  {
    id: 'fiano-avellino-villa-raiano',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 1996,
    avgPrice: 18,
    producers: ['Villa Raiano'],
    aliases: ['Villa Raiano Fiano']
  },
  {
    id: 'fiano-avellino-pietracupa',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 2002,
    avgPrice: 22,
    producers: ['Pietracupa'],
    aliases: ['Pietracupa Fiano']
  },
  {
    id: 'fiano-avellino-donnachiara',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Donnachiara'],
    aliases: ['Donnachiara Fiano']
  },
  {
    id: 'fiano-avellino-cantine-dell-angelo',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Cantine dell\'Angelo'],
    aliases: ['Cantine dell\'Angelo Fiano']
  },
  {
    id: 'fiano-avellino-quintodecimo-giallo-darbis',
    name: 'Fiano di Avellino Giallo d\'Arles',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 2004,
    avgPrice: 35,
    producers: ['Quintodecimo'],
    aliases: ['Giallo d\'Arles']
  },
  {
    id: 'fiano-avellino-rocca-del-principe',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 1994,
    avgPrice: 22,
    producers: ['Rocca del Principe'],
    aliases: ['Rocca del Principe Fiano']
  },
  {
    id: 'fiano-avellino-antonio-caggiano-bechar',
    name: 'Fiano di Avellino Béchar',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 1995,
    avgPrice: 24,
    producers: ['Antonio Caggiano'],
    aliases: ['Béchar']
  },
  {
    id: 'fiano-avellino-guastaferro',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 2001,
    avgPrice: 20,
    producers: ['Guastaferro'],
    aliases: ['Guastaferro Fiano']
  },
  {
    id: 'fiano-avellino-vadiaperti',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 2004,
    avgPrice: 22,
    producers: ['Vadiaperti'],
    aliases: ['Vadiaperti Fiano']
  },
  
  // GRECO DI TUFO DOCG (White)
  {
    id: 'greco-tufo-mastroberardino-novaserra',
    name: 'Greco di Tufo Novaserra',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 2001,
    avgPrice: 28,
    producers: ['Mastroberardino'],
    aliases: ['Novaserra']
  },
  {
    id: 'greco-tufo-mastroberardino',
    name: 'Greco di Tufo',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 1928,
    avgPrice: 18,
    producers: ['Mastroberardino'],
    aliases: ['Mastroberardino Greco']
  },
  {
    id: 'greco-tufo-feudi-san-gregorio-cutizzi',
    name: 'Greco di Tufo Cutizzi',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 1996,
    avgPrice: 26,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Cutizzi']
  },
  {
    id: 'greco-tufo-feudi-san-gregorio',
    name: 'Greco di Tufo',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 1986,
    avgPrice: 18,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Feudi Greco']
  },
  {
    id: 'greco-tufo-terredora-loggia-della-serra',
    name: 'Greco di Tufo Loggia della Serra',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 1994,
    avgPrice: 24,
    producers: ['Terredora'],
    aliases: ['Loggia della Serra']
  },
  {
    id: 'greco-tufo-terredora',
    name: 'Greco di Tufo',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 16,
    producers: ['Terredora'],
    aliases: ['Terredora Greco']
  },
  {
    id: 'greco-tufo-benito-ferrara',
    name: 'Greco di Tufo',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 2007,
    avgPrice: 20,
    producers: ['Benito Ferrara'],
    aliases: ['Benito Ferrara Greco']
  },
  {
    id: 'greco-tufo-villa-raiano',
    name: 'Greco di Tufo',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 1996,
    avgPrice: 16,
    producers: ['Villa Raiano'],
    aliases: ['Villa Raiano Greco']
  },
  {
    id: 'greco-tufo-donnachiara',
    name: 'Greco di Tufo',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Donnachiara'],
    aliases: ['Donnachiara Greco']
  },
  {
    id: 'greco-tufo-cantine-dell-angelo',
    name: 'Greco di Tufo',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Cantine dell\'Angelo'],
    aliases: ['Cantine dell\'Angelo Greco']
  },
  {
    id: 'greco-tufo-rocca-del-principe',
    name: 'Greco di Tufo',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 1994,
    avgPrice: 20,
    producers: ['Rocca del Principe'],
    aliases: ['Rocca del Principe Greco']
  },
  {
    id: 'greco-tufo-antonio-caggiano-tauri',
    name: 'Greco di Tufo Tauri',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 1995,
    avgPrice: 22,
    producers: ['Antonio Caggiano'],
    aliases: ['Tauri Greco']
  },
  {
    id: 'greco-tufo-vadiaperti',
    name: 'Greco di Tufo',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 2004,
    avgPrice: 18,
    producers: ['Vadiaperti'],
    aliases: ['Vadiaperti Greco']
  },
  {
    id: 'greco-tufo-pietracupa',
    name: 'Greco di Tufo',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 2002,
    avgPrice: 20,
    producers: ['Pietracupa'],
    aliases: ['Pietracupa Greco']
  },
  {
    id: 'greco-tufo-quintodecimo-exultet',
    name: 'Greco di Tufo Exultet',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Tufo',
    grapeVariety: 'Greco',
    classification: 'DOCG',
    minVintage: 2004,
    avgPrice: 32,
    producers: ['Quintodecimo'],
    aliases: ['Exultet']
  },
  
  // IRPINIA BIANCO & OTHER WHITE WINES
  {
    id: 'irpinia-bianco-feudi-san-gregorio-campanaro',
    name: 'Campanaro Irpinia Fiano',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Fiano',
    classification: 'DOC',
    minVintage: 1997,
    avgPrice: 22,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Campanaro']
  },
  {
    id: 'irpinia-greco-feudi-san-gregorio-serrocielo',
    name: 'Serrocielo Irpinia Greco',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Greco',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Serrocielo']
  },
  {
    id: 'irpinia-coda-di-volpe-feudi-san-gregorio',
    name: 'Irpinia Coda di Volpe',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Coda di Volpe',
    classification: 'DOC',
    minVintage: 1997,
    avgPrice: 16,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Feudi Coda di Volpe']
  },
  {
    id: 'campania-feudi-san-gregorio-privilegio',
    name: 'Privilegio Irpinia Falanghina',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Feudi di San Gregorio'],
    aliases: ['Privilegio']
  },
  {
    id: 'campania-terredora-fiano-amphora',
    name: 'Fiano Campania IGT Amphora',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'IGT',
    minVintage: 2011,
    avgPrice: 45,
    producers: ['Terredora'],
    aliases: ['Amphora']
  },
  {
    id: 'campania-quintodecimo-via-del-campo',
    name: 'Via del Campo Irpinia Falanghina',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 2007,
    avgPrice: 22,
    producers: ['Quintodecimo'],
    aliases: ['Via del Campo']
  },
  {
    id: 'campania-mustilli-falanghina',
    name: 'Falanghina del Sannio',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Sant\'Agata dei Goti',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 1991,
    avgPrice: 14,
    producers: ['Mustilli'],
    aliases: ['Mustilli Falanghina']
  },
  {
    id: 'campania-mustilli-vigna-segreta-falanghina',
    name: 'Falanghina del Sannio Vigna Segreta',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Sant\'Agata dei Goti',
    grapeVariety: 'Falanghina',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 20,
    producers: ['Mustilli'],
    aliases: ['Vigna Segreta Falanghina']
  },
  {
    id: 'campania-vestini-campagnano-fiano',
    name: 'Fiano Irpinia',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Irpinia',
    grapeVariety: 'Fiano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Vestini Campagnano'],
    aliases: ['Vestini Fiano']
  },
  {
    id: 'campania-borgodangelo-fiano',
    name: 'Fiano di Avellino',
    type: 'White',
    country: 'Italy',
    region: 'Campania',
    subRegion: 'Avellino',
    grapeVariety: 'Fiano',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Borgodangelo'],
    aliases: ['Borgodangelo Fiano']
  },
];
