import { WineTemplate } from '@/types/wineDatabase';

/**
 * LIGURIA WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Vermentino (Colli di Luni), Pigato (Riviera Ligure di Ponente)
 * Updated: January 2025
 */

export const liguriapart1: WineTemplate[] = [
  // COLLI DI LUNI VERMENTINO DOC (White)
  {
    id: 'vermentino-luni-la-felce-sarticola',
    name: 'Colli di Luni Vermentino Sarticola',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 28,
    producers: ['La Felce'],
    aliases: ['Sarticola']
  },
  {
    id: 'vermentino-luni-la-felce',
    name: 'Colli di Luni Vermentino',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 16,
    producers: ['La Felce'],
    aliases: ['La Felce Vermentino']
  },
  {
    id: 'vermentino-luni-cantine-lunae-etichetta-nera',
    name: 'Colli di Luni Vermentino Etichetta Nera',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1966,
    avgPrice: 32,
    producers: ['Cantine Lunae Bosoni'],
    aliases: ['Etichetta Nera']
  },
  {
    id: 'vermentino-luni-cantine-lunae-etichetta-grigia',
    name: 'Colli di Luni Vermentino Etichetta Grigia',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1966,
    avgPrice: 22,
    producers: ['Cantine Lunae Bosoni'],
    aliases: ['Etichetta Grigia']
  },
  {
    id: 'vermentino-luni-cantine-lunae',
    name: 'Colli di Luni Vermentino',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1966,
    avgPrice: 14,
    producers: ['Cantine Lunae Bosoni'],
    aliases: ['Lunae Vermentino']
  },
  {
    id: 'vermentino-luni-ottaviano-lambruschi-costa-marina',
    name: 'Colli di Luni Vermentino Costa Marina',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 24,
    producers: ['Ottaviano Lambruschi'],
    aliases: ['Costa Marina']
  },
  {
    id: 'vermentino-luni-ottaviano-lambruschi',
    name: 'Colli di Luni Vermentino',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 16,
    producers: ['Ottaviano Lambruschi'],
    aliases: ['Lambruschi Vermentino']
  },
  {
    id: 'vermentino-luni-terenzuola-fosso-di-corsano',
    name: 'Colli di Luni Vermentino Fosso di Corsano',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1993,
    avgPrice: 28,
    producers: ['Terenzuola'],
    aliases: ['Fosso di Corsano']
  },
  {
    id: 'vermentino-luni-terenzuola',
    name: 'Colli di Luni Vermentino',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1993,
    avgPrice: 18,
    producers: ['Terenzuola'],
    aliases: ['Terenzuola Vermentino']
  },
  
  // RIVIERA LIGURE DI PONENTE PIGATO DOC (White)
  {
    id: 'pigato-bruna-vigna-u-munte',
    name: 'Riviera Ligure di Ponente Pigato Vigna U Munte',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 32,
    producers: ['Bruna'],
    aliases: ['Vigna U Munte']
  },
  {
    id: 'pigato-bruna',
    name: 'Riviera Ligure di Ponente Pigato',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 18,
    producers: ['Bruna'],
    aliases: ['Bruna Pigato']
  },
  {
    id: 'pigato-lupi-majolo',
    name: 'Riviera Ligure di Ponente Pigato Majolo',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pieve di Teco',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 1968,
    avgPrice: 28,
    producers: ['Lupi'],
    aliases: ['Majolo']
  },
  {
    id: 'pigato-lupi',
    name: 'Riviera Ligure di Ponente Pigato',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pieve di Teco',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 1968,
    avgPrice: 16,
    producers: ['Lupi'],
    aliases: ['Lupi Pigato']
  },
  {
    id: 'pigato-vis-amoris-vigneto-casa-del-lupo',
    name: 'Riviera Ligure di Ponente Pigato Vigneto Casa del Lupo',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Vis Amoris'],
    aliases: ['Casa del Lupo']
  },
  {
    id: 'pigato-vis-amoris',
    name: 'Riviera Ligure di Ponente Pigato',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Vis Amoris'],
    aliases: ['Vis Amoris Pigato']
  },
  {
    id: 'pigato-terre-bianche-arcagna',
    name: 'Riviera Ligure di Ponente Pigato Arcagna',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Terre Bianche'],
    aliases: ['Arcagna']
  },
  {
    id: 'pigato-terre-bianche',
    name: 'Riviera Ligure di Ponente Pigato',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Terre Bianche'],
    aliases: ['Terre Bianche Pigato']
  },
  {
    id: 'pigato-durin-pian-del-vescovo',
    name: 'Riviera Ligure di Ponente Pigato Pian del Vescovo',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ortovero',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 26,
    producers: ['Durin'],
    aliases: ['Pian del Vescovo']
  },
  {
    id: 'pigato-durin',
    name: 'Riviera Ligure di Ponente Pigato',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ortovero',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 16,
    producers: ['Durin'],
    aliases: ['Durin Pigato']
  },
  {
    id: 'pigato-maccario-dringenberg',
    name: 'Riviera Ligure di Ponente Pigato',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Maccario Dringenberg'],
    aliases: ['Maccario Dringenberg Pigato']
  },
  {
    id: 'pigato-la-vecchia-cantina',
    name: 'Riviera Ligure di Ponente Pigato',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 18,
    producers: ['La Vecchia Cantina'],
    aliases: ['La Vecchia Cantina Pigato']
  },
  {
    id: 'pigato-claudio-vio',
    name: 'Riviera Ligure di Ponente Pigato',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Claudio Vio'],
    aliases: ['Claudio Vio Pigato']
  },
  {
    id: 'pigato-cascina-delle-terre-rosse',
    name: 'Riviera Ligure di Ponente Pigato',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Pigato',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Cascina delle Terre Rosse'],
    aliases: ['Cascina delle Terre Rosse Pigato']
  },
  
  // RIVIERA LIGURE DI PONENTE VERMENTINO DOC (White)
  {
    id: 'vermentino-ponente-lupi',
    name: 'Riviera Ligure di Ponente Vermentino',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pieve di Teco',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1968,
    avgPrice: 16,
    producers: ['Lupi'],
    aliases: ['Lupi Vermentino Ponente']
  },
  {
    id: 'vermentino-ponente-durin',
    name: 'Riviera Ligure di Ponente Vermentino',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ortovero',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 14,
    producers: ['Durin'],
    aliases: ['Durin Vermentino Ponente']
  },
  {
    id: 'vermentino-ponente-terre-bianche',
    name: 'Riviera Ligure di Ponente Vermentino',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Terre Bianche'],
    aliases: ['Terre Bianche Vermentino Ponente']
  },
  {
    id: 'vermentino-ponente-bruna',
    name: 'Riviera Ligure di Ponente Vermentino',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 16,
    producers: ['Bruna'],
    aliases: ['Bruna Vermentino Ponente']
  },
  
  // CINQUE TERRE DOC (White)
  {
    id: 'cinque-terre-walter-de-batte',
    name: 'Cinque Terre',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 1988,
    avgPrice: 28,
    producers: ['Walter De Batté'],
    aliases: ['De Batté Cinque Terre']
  },
  {
    id: 'cinque-terre-buranco',
    name: 'Cinque Terre',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 24,
    producers: ['Buranco'],
    aliases: ['Buranco Cinque Terre']
  },
  {
    id: 'cinque-terre-forlini-capellini',
    name: 'Cinque Terre',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 1982,
    avgPrice: 22,
    producers: ['Forlini Capellini'],
    aliases: ['Forlini Capellini Cinque Terre']
  },
  {
    id: 'cinque-terre-arrigoni',
    name: 'Cinque Terre',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 24,
    producers: ['Arrigoni'],
    aliases: ['Arrigoni Cinque Terre']
  },
  {
    id: 'cinque-terre-cooperativa',
    name: 'Cinque Terre',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 1973,
    avgPrice: 18,
    producers: ['Cooperativa Agricoltura Cinque Terre'],
    aliases: ['Cooperativa Cinque Terre']
  },
  
  // CINQUE TERRE SCIACCHETRÀ DOC (Sweet/Passito)
  {
    id: 'sciacchetra-walter-de-batte',
    name: 'Cinque Terre Sciacchetrà',
    type: 'Dessert',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 1988,
    avgPrice: 85,
    producers: ['Walter De Batté'],
    aliases: ['De Batté Sciacchetrà']
  },
  {
    id: 'sciacchetra-buranco',
    name: 'Cinque Terre Sciacchetrà',
    type: 'Dessert',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 75,
    producers: ['Buranco'],
    aliases: ['Buranco Sciacchetrà']
  },
  {
    id: 'sciacchetra-forlini-capellini',
    name: 'Cinque Terre Sciacchetrà',
    type: 'Dessert',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 72,
    producers: ['Forlini Capellini'],
    aliases: ['Forlini Capellini Sciacchetrà']
  },
  {
    id: 'sciacchetra-arrigoni',
    name: 'Cinque Terre Sciacchetrà',
    type: 'Dessert',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 78,
    producers: ['Arrigoni'],
    aliases: ['Arrigoni Sciacchetrà']
  },
  {
    id: 'sciacchetra-cooperativa',
    name: 'Cinque Terre Sciacchetrà',
    type: 'Dessert',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Cinque Terre',
    grapeVariety: 'Bosco, Albarola, Vermentino',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 65,
    producers: ['Cooperativa Agricoltura Cinque Terre'],
    aliases: ['Cooperativa Sciacchetrà']
  },
  
  // GOLFO DEL TIGULLIO VERMENTINO DOC (White)
  {
    id: 'vermentino-tigullio-bisson',
    name: 'Golfo del Tigullio Vermentino',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1983,
    avgPrice: 18,
    producers: ['Bisson'],
    aliases: ['Bisson Vermentino Tigullio']
  },
  {
    id: 'vermentino-tigullio-la-zerba',
    name: 'Golfo del Tigullio Vermentino',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['La Zerba'],
    aliases: ['La Zerba Vermentino']
  },
];
