import { WineTemplate } from '@/types/wineDatabase';

/**
 * MARCHE WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Pecorino, Passerina, Offida DOCG, Blends, International varieties
 * Updated: January 2025
 */

export const marchePart3: WineTemplate[] = [
  // OFFIDA PECORINO DOCG (White)
  {
    id: 'offida-pecorino-velenosi-sole',
    name: 'Offida Pecorino Solleone',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Offida',
    grapeVariety: 'Pecorino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Velenosi'],
    aliases: ['Solleone']
  },
  {
    id: 'offida-pecorino-velenosi',
    name: 'Offida Pecorino',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Offida',
    grapeVariety: 'Pecorino',
    classification: 'DOCG',
    minVintage: 1984,
    avgPrice: 16,
    producers: ['Velenosi'],
    aliases: ['Velenosi Pecorino']
  },
  {
    id: 'offida-pecorino-aurora-onirocanto',
    name: 'Offida Pecorino Onirocanto',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Offida',
    grapeVariety: 'Pecorino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Aurora'],
    aliases: ['Onirocanto']
  },
  {
    id: 'offida-pecorino-aurora',
    name: 'Offida Pecorino',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Offida',
    grapeVariety: 'Pecorino',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Aurora'],
    aliases: ['Aurora Pecorino']
  },
  {
    id: 'offida-pecorino-saladini-pilastri',
    name: 'Offida Pecorino',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Offida',
    grapeVariety: 'Pecorino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Saladini Pilastri'],
    aliases: ['Saladini Pilastri Pecorino']
  },
  {
    id: 'offida-pecorino-tenuta-cocci-grifoni',
    name: 'Offida Pecorino',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Offida',
    grapeVariety: 'Pecorino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Tenuta Cocci Grifoni'],
    aliases: ['Cocci Grifoni Pecorino']
  },
  {
    id: 'offida-pecorino-ciu-ciu',
    name: 'Offida Pecorino',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Offida',
    grapeVariety: 'Pecorino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Ciu Ciu'],
    aliases: ['Ciu Ciu Pecorino']
  },
  {
    id: 'offida-pecorino-la-canestraia',
    name: 'Offida Pecorino',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Offida',
    grapeVariety: 'Pecorino',
    classification: 'DOCG',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['La Canestraia'],
    aliases: ['La Canestraia Pecorino']
  },
  
  // OFFIDA PASSERINA DOCG (White)
  {
    id: 'offida-passerina-velenosi',
    name: 'Offida Passerina',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Offida',
    grapeVariety: 'Passerina',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Velenosi'],
    aliases: ['Velenosi Passerina']
  },
  {
    id: 'offida-passerina-aurora',
    name: 'Offida Passerina',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Offida',
    grapeVariety: 'Passerina',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Aurora'],
    aliases: ['Aurora Passerina']
  },
  {
    id: 'offida-passerina-saladini-pilastri',
    name: 'Offida Passerina',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Offida',
    grapeVariety: 'Passerina',
    classification: 'DOCG',
    minVintage: 2008,
    avgPrice: 14,
    producers: ['Saladini Pilastri'],
    aliases: ['Saladini Pilastri Passerina']
  },
  {
    id: 'offida-passerina-ciu-ciu',
    name: 'Offida Passerina',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Offida',
    grapeVariety: 'Passerina',
    classification: 'DOCG',
    minVintage: 2008,
    avgPrice: 14,
    producers: ['Ciu Ciu'],
    aliases: ['Ciu Ciu Passerina']
  },
  
  // PECORINO (Marche IGT - non-Offida)
  {
    id: 'pecorino-umani-ronchi-vellodoro',
    name: 'Pecorino Vellodoro Marche IGT',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Pecorino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Umani Ronchi'],
    aliases: ['Vellodoro']
  },
  {
    id: 'pecorino-garofoli',
    name: 'Pecorino Marche IGT',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ancona',
    grapeVariety: 'Pecorino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Garofoli'],
    aliases: ['Garofoli Pecorino']
  },
  
  // PASSERINA (Marche IGT)
  {
    id: 'passerina-garofoli',
    name: 'Passerina Marche IGT',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ancona',
    grapeVariety: 'Passerina',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Garofoli'],
    aliases: ['Garofoli Passerina']
  },
  
  // FALERIO DOC (White blend)
  {
    id: 'falerio-velenosi',
    name: 'Falerio',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Trebbiano, Passerina, Pecorino',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 12,
    producers: ['Velenosi'],
    aliases: ['Velenosi Falerio']
  },
  {
    id: 'falerio-saladini-pilastri',
    name: 'Falerio',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Trebbiano, Passerina, Pecorino',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 11,
    producers: ['Saladini Pilastri'],
    aliases: ['Saladini Pilastri Falerio']
  },
  {
    id: 'falerio-tenuta-cocci-grifoni',
    name: 'Falerio',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Trebbiano, Passerina, Pecorino',
    classification: 'DOC',
    minVintage: 1969,
    avgPrice: 11,
    producers: ['Tenuta Cocci Grifoni'],
    aliases: ['Cocci Grifoni Falerio']
  },
  {
    id: 'falerio-ciu-ciu',
    name: 'Falerio',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Trebbiano, Passerina',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 10,
    producers: ['Ciu Ciu'],
    aliases: ['Ciu Ciu Falerio']
  },
  
  // PREMIUM RED BLENDS (Marche IGT)
  {
    id: 'marche-umani-ronchi-pelago',
    name: 'Pelago Marche IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano, Cabernet Sauvignon, Merlot',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 48,
    producers: ['Umani Ronchi'],
    aliases: ['Pelago']
  },
  {
    id: 'marche-garofoli-komaros',
    name: 'Komaros Marche IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano, Syrah',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 42,
    producers: ['Garofoli'],
    aliases: ['Komaros']
  },
  {
    id: 'marche-fattoria-le-terrazze-chaos',
    name: 'Chaos Marche IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano, Merlot, Syrah',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 55,
    producers: ['Fattoria Le Terrazze'],
    aliases: ['Chaos']
  },
  {
    id: 'marche-velenosi-ludi',
    name: 'Ludi Marche IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Velenosi'],
    aliases: ['Ludi']
  },
  
  // INTERNATIONAL VARIETIES
  {
    id: 'chardonnay-umani-ronchi',
    name: 'Chardonnay Marche IGT',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Umani Ronchi'],
    aliases: ['Umani Ronchi Chardonnay']
  },
  {
    id: 'sauvignon-blanc-garofoli',
    name: 'Sauvignon Blanc Marche IGT',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 14,
    producers: ['Garofoli'],
    aliases: ['Garofoli Sauvignon']
  },
  {
    id: 'cabernet-sauvignon-umani-ronchi',
    name: 'Cabernet Sauvignon Marche IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 20,
    producers: ['Umani Ronchi'],
    aliases: ['Umani Ronchi Cabernet']
  },
  {
    id: 'merlot-garofoli',
    name: 'Merlot Marche IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 18,
    producers: ['Garofoli'],
    aliases: ['Garofoli Merlot']
  },
  {
    id: 'syrah-fattoria-le-terrazze',
    name: 'Syrah Marche IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Syrah',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Fattoria Le Terrazze'],
    aliases: ['Le Terrazze Syrah']
  },
  
  // ROSÉ WINES
  {
    id: 'rosato-umani-ronchi',
    name: 'Rosato Marche IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Umani Ronchi'],
    aliases: ['Umani Ronchi Rosato']
  },
  {
    id: 'rosato-velenosi',
    name: 'Rosato Marche IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 12,
    producers: ['Velenosi'],
    aliases: ['Velenosi Rosato']
  },
  {
    id: 'rosato-garofoli',
    name: 'Rosato Marche IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 12,
    producers: ['Garofoli'],
    aliases: ['Garofoli Rosato']
  },
  
  // SPARKLING WINES
  {
    id: 'spumante-garofoli-brut',
    name: 'Verdicchio Spumante Brut',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Garofoli'],
    aliases: ['Garofoli Spumante']
  },
  {
    id: 'spumante-umani-ronchi-brut',
    name: 'Verdicchio Spumante Brut',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Umani Ronchi'],
    aliases: ['Umani Ronchi Spumante']
  },
  {
    id: 'spumante-sartarelli-brut',
    name: 'Verdicchio Spumante Brut',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Sartarelli'],
    aliases: ['Sartarelli Spumante']
  },
  
  // ADDITIONAL WINES
  {
    id: 'marche-bucci-rosso-piceno',
    name: 'Rosso Piceno',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 16,
    producers: ['Bucci'],
    aliases: ['Bucci Rosso Piceno']
  },
  {
    id: 'marche-santa-barbara-le-vaglie',
    name: 'Le Vaglie Piceno Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Ascoli Piceno',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Santa Barbara'],
    aliases: ['Le Vaglie']
  },
  {
    id: 'marche-moncaro-nerone',
    name: 'Nerone Marche IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Conero',
    grapeVariety: 'Montepulciano',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Moncaro'],
    aliases: ['Nerone']
  },
  {
    id: 'marche-moncaro-eos',
    name: 'Eos Verdicchio dei Castelli di Jesi Classico Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 2008,
    avgPrice: 26,
    producers: ['Moncaro'],
    aliases: ['Eos']
  },
];
