import { WineTemplate } from '@/types/wineDatabase';

/**
 * BASILICATA WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Aglianico del Vulture DOCG & DOC
 * Updated: January 2025
 */

export const basilicataPart1: WineTemplate[] = [
  // AGLIANICO DEL VULTURE SUPERIORE DOCG (Red)
  {
    id: 'aglianico-vulture-paternoster-don-anselmo',
    name: 'Aglianico del Vulture Superiore Don Anselmo Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 65,
    producers: ['Paternoster'],
    aliases: ['Don Anselmo']
  },
  {
    id: 'aglianico-vulture-paternoster-rotondo',
    name: 'Aglianico del Vulture Superiore Rotondo',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['Paternoster'],
    aliases: ['Rotondo']
  },
  {
    id: 'aglianico-vulture-paternoster',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1925,
    avgPrice: 22,
    producers: ['Paternoster'],
    aliases: ['Paternoster Aglianico']
  },
  {
    id: 'aglianico-vulture-elena-fucci-titolo',
    name: 'Aglianico del Vulture Titolo',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 52,
    producers: ['Elena Fucci'],
    aliases: ['Titolo']
  },
  {
    id: 'aglianico-vulture-elena-fucci',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Elena Fucci'],
    aliases: ['Elena Fucci Aglianico']
  },
  {
    id: 'aglianico-vulture-cantine-del-notaio-il-repertorio',
    name: 'Aglianico del Vulture Superiore Il Repertorio Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1998,
    avgPrice: 55,
    producers: ['Cantine del Notaio'],
    aliases: ['Il Repertorio']
  },
  {
    id: 'aglianico-vulture-cantine-del-notaio-la-firma',
    name: 'Aglianico del Vulture La Firma',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 38,
    producers: ['Cantine del Notaio'],
    aliases: ['La Firma']
  },
  {
    id: 'aglianico-vulture-cantine-del-notaio-il-sigillo',
    name: 'Aglianico del Vulture Il Sigillo',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 28,
    producers: ['Cantine del Notaio'],
    aliases: ['Il Sigillo']
  },
  {
    id: 'aglianico-vulture-cantine-del-notaio',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 18,
    producers: ['Cantine del Notaio'],
    aliases: ['Cantine del Notaio Aglianico']
  },
  {
    id: 'aglianico-vulture-terre-degli-svevi-re-manfredi',
    name: 'Aglianico del Vulture Superiore Re Manfredi Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2001,
    avgPrice: 48,
    producers: ['Terre degli Svevi'],
    aliases: ['Re Manfredi']
  },
  {
    id: 'aglianico-vulture-terre-degli-svevi-serpara',
    name: 'Aglianico del Vulture Serpara',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 28,
    producers: ['Terre degli Svevi'],
    aliases: ['Serpara']
  },
  {
    id: 'aglianico-vulture-terre-degli-svevi',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 16,
    producers: ['Terre degli Svevi'],
    aliases: ['Terre degli Svevi Aglianico']
  },
  {
    id: 'aglianico-vulture-donato-d-angelo-canneto',
    name: 'Aglianico del Vulture Superiore Canneto Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1970,
    avgPrice: 62,
    producers: ['Donato D\'Angelo'],
    aliases: ['Canneto']
  },
  {
    id: 'aglianico-vulture-donato-d-angelo-vigna-caselle',
    name: 'Aglianico del Vulture Vigna Caselle',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 35,
    producers: ['Donato D\'Angelo'],
    aliases: ['Vigna Caselle']
  },
  {
    id: 'aglianico-vulture-donato-d-angelo',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 20,
    producers: ['Donato D\'Angelo'],
    aliases: ['D\'Angelo Aglianico']
  },
  {
    id: 'aglianico-vulture-michele-laluce-carpe-diem',
    name: 'Aglianico del Vulture Superiore Carpe Diem Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 45,
    producers: ['Michele Laluce'],
    aliases: ['Carpe Diem']
  },
  {
    id: 'aglianico-vulture-michele-laluce',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Michele Laluce'],
    aliases: ['Michele Laluce Aglianico']
  },
  {
    id: 'aglianico-vulture-musto-carmelitano-clivus',
    name: 'Aglianico del Vulture Clivus',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Musto Carmelitano'],
    aliases: ['Clivus']
  },
  {
    id: 'aglianico-vulture-musto-carmelitano',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Musto Carmelitano'],
    aliases: ['Musto Carmelitano Aglianico']
  },
  {
    id: 'aglianico-vulture-grifalco-gricos',
    name: 'Aglianico del Vulture Gricos',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Grifalco della Lucania'],
    aliases: ['Gricos']
  },
  {
    id: 'aglianico-vulture-grifalco-damaschito',
    name: 'Aglianico del Vulture Damaschito',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 28,
    producers: ['Grifalco della Lucania'],
    aliases: ['Damaschito']
  },
  {
    id: 'aglianico-vulture-grifalco',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Grifalco della Lucania'],
    aliases: ['Grifalco Aglianico']
  },
  {
    id: 'aglianico-vulture-vigneti-del-vulture',
    name: 'Aglianico del Vulture Superiore Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['Vigneti del Vulture'],
    aliases: ['Vigneti del Vulture Riserva']
  },
  {
    id: 'aglianico-vulture-vigneti-del-vulture-pipoli',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Vigneti del Vulture'],
    aliases: ['Vigneti del Vulture Aglianico']
  },
  {
    id: 'aglianico-vulture-cantine-dipalma',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Cantine Di Palma'],
    aliases: ['Di Palma Aglianico']
  },
  {
    id: 'aglianico-vulture-martino',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Armando Martino'],
    aliases: ['Martino Aglianico']
  },
  {
    id: 'aglianico-vulture-bisceglia',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Bisceglia'],
    aliases: ['Bisceglia Aglianico']
  },
  {
    id: 'aglianico-vulture-tenuta-le-querce',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 22,
    producers: ['Tenuta Le Querce'],
    aliases: ['Tenuta Le Querce Aglianico']
  },
  {
    id: 'aglianico-vulture-eubea',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 24,
    producers: ['Eubea'],
    aliases: ['Eubea Aglianico']
  },
  {
    id: 'aglianico-vulture-macarico',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 20,
    producers: ['Macarico'],
    aliases: ['Macarico Aglianico']
  },
  {
    id: 'aglianico-vulture-cantina-di-venosa',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1957,
    avgPrice: 14,
    producers: ['Cantina di Venosa'],
    aliases: ['Cantina di Venosa Aglianico']
  },
  {
    id: 'aglianico-vulture-cantina-di-venosa-riserva',
    name: 'Aglianico del Vulture Superiore Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 32,
    producers: ['Cantina di Venosa'],
    aliases: ['Cantina di Venosa Riserva']
  },
  {
    id: 'aglianico-vulture-cantina-cooperativa-barile',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1974,
    avgPrice: 14,
    producers: ['Cantina Cooperativa di Barile'],
    aliases: ['Barile Aglianico']
  },
  {
    id: 'aglianico-vulture-basilisco',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Basilisco'],
    aliases: ['Basilisco Aglianico']
  },
  {
    id: 'aglianico-vulture-basilisco-fontanelle',
    name: 'Aglianico del Vulture Fontanelle',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 38,
    producers: ['Basilisco'],
    aliases: ['Fontanelle']
  },
  {
    id: 'aglianico-vulture-consorzio-viticoltori',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 16,
    producers: ['Consorzio Viticoltori Vulture'],
    aliases: ['Consorzio Aglianico']
  },
  {
    id: 'aglianico-vulture-solagna-del-titolo',
    name: 'Aglianico del Vulture Solagna del Titolo',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 32,
    producers: ['Solagna del Titolo'],
    aliases: ['Solagna del Titolo']
  },
  {
    id: 'aglianico-vulture-cantine-strapellum',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 22,
    producers: ['Cantine Strapellum'],
    aliases: ['Strapellum Aglianico']
  },
  {
    id: 'aglianico-vulture-botte-piccola',
    name: 'Aglianico del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 24,
    producers: ['Botte Piccola'],
    aliases: ['Botte Piccola Aglianico']
  },
  {
    id: 'aglianico-vulture-re-manfredi-vigneti',
    name: 'Aglianico del Vulture Vigneti del Vulture',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Re Manfredi'],
    aliases: ['Re Manfredi Aglianico']
  },
];
