import { WineTemplate } from '@/types/wineDatabase';

/**
 * VENETO WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Amarone della Valpolicella, Valpolicella Ripasso
 * Updated: January 2025
 */

export const venetoPart1: WineTemplate[] = [
  // AMARONE DELLA VALPOLICELLA DOCG - Top Producers
  {
    id: 'amarone-dal-forno',
    name: 'Amarone della Valpolicella',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOCG',
    minVintage: 1983,
    avgPrice: 450,
    producers: ['Dal Forno Romano'],
    aliases: ['Dal Forno Amarone']
  },
  {
    id: 'amarone-dal-forno-monte-lodoletta',
    name: 'Amarone della Valpolicella Monte Lodoletta',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOCG',
    minVintage: 1995,
    avgPrice: 650,
    producers: ['Dal Forno Romano'],
    aliases: ['Monte Lodoletta']
  },
  {
    id: 'amarone-giuseppe-quintarelli',
    name: 'Amarone della Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOCG',
    minVintage: 1950,
    avgPrice: 380,
    producers: ['Giuseppe Quintarelli'],
    aliases: ['Quintarelli Amarone']
  },
  {
    id: 'amarone-quintarelli-riserva',
    name: 'Amarone della Valpolicella Classico Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOCG',
    minVintage: 1983,
    avgPrice: 550,
    producers: ['Giuseppe Quintarelli'],
    aliases: ['Quintarelli Riserva']
  },
  {
    id: 'amarone-bertani',
    name: 'Amarone della Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella',
    classification: 'DOCG',
    minVintage: 1958,
    avgPrice: 55,
    producers: ['Bertani'],
    aliases: ['Bertani Amarone']
  },
  {
    id: 'amarone-masi-costasera',
    name: 'Amarone della Valpolicella Classico Costasera',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOCG',
    minVintage: 1964,
    avgPrice: 65,
    producers: ['Masi'],
    aliases: ['Costasera']
  },
  {
    id: 'amarone-masi-mazzano',
    name: 'Amarone della Valpolicella Classico Mazzano',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOCG',
    minVintage: 1981,
    avgPrice: 120,
    producers: ['Masi'],
    aliases: ['Mazzano']
  },
  {
    id: 'amarone-masi-campolongo-torbe',
    name: 'Amarone della Valpolicella Classico Campolongo di Torbe',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOCG',
    minVintage: 1964,
    avgPrice: 140,
    producers: ['Masi'],
    aliases: ['Campolongo di Torbe']
  },
  {
    id: 'amarone-allegrini',
    name: 'Amarone della Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Oseleta',
    classification: 'DOCG',
    minVintage: 1979,
    avgPrice: 75,
    producers: ['Allegrini'],
    aliases: ['Allegrini Amarone']
  },
  {
    id: 'amarone-tommasi',
    name: 'Amarone della Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOCG',
    minVintage: 1902,
    avgPrice: 60,
    producers: ['Tommasi'],
    aliases: ['Tommasi Amarone']
  },
  {
    id: 'amarone-speri-vigneto-monte-sant-urbano',
    name: 'Amarone della Valpolicella Classico Vigneto Monte Sant\'Urbano',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOCG',
    minVintage: 1874,
    avgPrice: 85,
    producers: ['Speri'],
    aliases: ['Monte Sant\'Urbano']
  },
  {
    id: 'amarone-zenato',
    name: 'Amarone della Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Oseleta',
    classification: 'DOCG',
    minVintage: 1960,
    avgPrice: 55,
    producers: ['Zenato'],
    aliases: ['Zenato Amarone']
  },
  {
    id: 'amarone-zenato-riserva',
    name: 'Amarone della Valpolicella Classico Riserva Sergio Zenato',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Oseleta',
    classification: 'DOCG',
    minVintage: 1997,
    avgPrice: 95,
    producers: ['Zenato'],
    aliases: ['Sergio Zenato']
  },
  {
    id: 'amarone-tedeschi-capitel-monte-olmi',
    name: 'Amarone della Valpolicella Classico Capitel Monte Olmi',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOCG',
    minVintage: 1630,
    avgPrice: 95,
    producers: ['Tedeschi'],
    aliases: ['Capitel Monte Olmi']
  },
  {
    id: 'amarone-tedeschi-la-fabriseria',
    name: 'Amarone della Valpolicella Classico La Fabriseria',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella',
    classification: 'DOCG',
    minVintage: 1988,
    avgPrice: 65,
    producers: ['Tedeschi'],
    aliases: ['La Fabriseria']
  },
  {
    id: 'amarone-bussola-tb-vigneto-alto',
    name: 'Amarone della Valpolicella TB Vigneto Alto',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOCG',
    minVintage: 1977,
    avgPrice: 220,
    producers: ['Tommaso Bussola'],
    aliases: ['TB Vigneto Alto']
  },
  {
    id: 'amarone-bussola-tb',
    name: 'Amarone della Valpolicella TB',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOCG',
    minVintage: 1986,
    avgPrice: 140,
    producers: ['Tommaso Bussola'],
    aliases: ['TB Amarone']
  },
  {
    id: 'amarone-brigaldara-case-vecie',
    name: 'Amarone della Valpolicella Classico Case Vecie',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOCG',
    minVintage: 1929,
    avgPrice: 85,
    producers: ['Brigaldara'],
    aliases: ['Case Vecie']
  },
  {
    id: 'amarone-sartori-corte-bra',
    name: 'Amarone della Valpolicella Classico Corte Brà',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella',
    classification: 'DOCG',
    minVintage: 1898,
    avgPrice: 55,
    producers: ['Sartori'],
    aliases: ['Corte Brà']
  },
  {
    id: 'amarone-corte-sant-alda',
    name: 'Amarone della Valpolicella',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOCG',
    minVintage: 1986,
    avgPrice: 75,
    producers: ['Corte Sant\'Alda'],
    aliases: ['Corte Sant\'Alda']
  },
  {
    id: 'amarone-monte-dall-ora',
    name: 'Amarone della Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOCG',
    minVintage: 1995,
    avgPrice: 95,
    producers: ['Monte Dall\'Ora'],
    aliases: ['Monte Dall\'Ora']
  },
  {
    id: 'amarone-venturini',
    name: 'Amarone della Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOCG',
    minVintage: 1961,
    avgPrice: 65,
    producers: ['Venturini'],
    aliases: ['Venturini Amarone']
  },
  {
    id: 'amarone-musella',
    name: 'Amarone della Valpolicella',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 55,
    producers: ['Musella'],
    aliases: ['Musella Amarone']
  },
  {
    id: 'amarone-cantina-valpantena',
    name: 'Amarone della Valpolicella Torre del Falasco',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOCG',
    minVintage: 1958,
    avgPrice: 48,
    producers: ['Cantina Valpantena'],
    aliases: ['Torre del Falasco']
  },
  {
    id: 'amarone-corte-giara',
    name: 'Amarone della Valpolicella',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella',
    classification: 'DOCG',
    minVintage: 1989,
    avgPrice: 38,
    producers: ['Corte Giara', 'Allegrini'],
    aliases: ['Corte Giara']
  },
  
  // VALPOLICELLA RIPASSO DOC
  {
    id: 'ripasso-masi-campofiorin',
    name: 'Campofiorin Ripasso',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'IGT',
    minVintage: 1964,
    avgPrice: 28,
    producers: ['Masi'],
    aliases: ['Campofiorin']
  },
  {
    id: 'ripasso-masi-supervenetian',
    name: 'Valpolicella Ripasso Classico Superiore Supervenetian',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 35,
    producers: ['Masi'],
    aliases: ['Supervenetian']
  },
  {
    id: 'ripasso-allegrini-palazzo-torre',
    name: 'Valpolicella Superiore Palazzo della Torre',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Sangiovese',
    classification: 'DOC',
    minVintage: 1979,
    avgPrice: 32,
    producers: ['Allegrini'],
    aliases: ['Palazzo della Torre']
  },
  {
    id: 'ripasso-zenato',
    name: 'Valpolicella Ripasso Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Oseleta',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 26,
    producers: ['Zenato'],
    aliases: ['Zenato Ripasso']
  },
  {
    id: 'ripasso-tommasi',
    name: 'Valpolicella Ripasso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1997,
    avgPrice: 28,
    producers: ['Tommasi'],
    aliases: ['Tommasi Ripasso']
  },
  {
    id: 'ripasso-speri',
    name: 'Valpolicella Ripasso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 30,
    producers: ['Speri'],
    aliases: ['Speri Ripasso']
  },
  {
    id: 'ripasso-tedeschi',
    name: 'Valpolicella Ripasso Classico Superiore Capitel San Rocco',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1996,
    avgPrice: 32,
    producers: ['Tedeschi'],
    aliases: ['Capitel San Rocco']
  },
  {
    id: 'ripasso-brigaldara',
    name: 'Valpolicella Ripasso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Brigaldara'],
    aliases: ['Brigaldara Ripasso']
  },
  {
    id: 'ripasso-bertani',
    name: 'Valpolicella Ripasso Classico Superiore Secco Bertani',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 35,
    producers: ['Bertani'],
    aliases: ['Secco Bertani']
  },
  {
    id: 'ripasso-venturini',
    name: 'Valpolicella Ripasso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1992,
    avgPrice: 24,
    producers: ['Venturini'],
    aliases: ['Venturini Ripasso']
  },
  
  // VALPOLICELLA CLASSICO SUPERIORE DOC
  {
    id: 'valpolicella-quintarelli',
    name: 'Valpolicella Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 95,
    producers: ['Giuseppe Quintarelli'],
    aliases: ['Quintarelli Valpolicella']
  },
  {
    id: 'valpolicella-dal-forno',
    name: 'Valpolicella Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOC',
    minVintage: 1983,
    avgPrice: 180,
    producers: ['Dal Forno Romano'],
    aliases: ['Dal Forno Valpolicella']
  },
  {
    id: 'valpolicella-allegrini-la-poja',
    name: 'La Poja Veronese IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina',
    classification: 'IGT',
    minVintage: 1983,
    avgPrice: 75,
    producers: ['Allegrini'],
    aliases: ['La Poja']
  },
  {
    id: 'valpolicella-allegrini-la-grola',
    name: 'La Grola Veronese IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Oseleta, Syrah',
    classification: 'IGT',
    minVintage: 1979,
    avgPrice: 48,
    producers: ['Allegrini'],
    aliases: ['La Grola']
  },
  {
    id: 'valpolicella-tommasi-campo-fiorin',
    name: 'Valpolicella Classico Superiore Rafael',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 2002,
    avgPrice: 42,
    producers: ['Tommasi'],
    aliases: ['Rafael']
  },
  {
    id: 'valpolicella-masi-osar',
    name: 'Osar Valpolicella Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Oseleta',
    classification: 'DOC',
    minVintage: 2009,
    avgPrice: 38,
    producers: ['Masi'],
    aliases: ['Osar']
  },
  {
    id: 'valpolicella-tedeschi-classico',
    name: 'Valpolicella Classico Superiore Lucchine',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 22,
    producers: ['Tedeschi'],
    aliases: ['Lucchine']
  },
  {
    id: 'valpolicella-bussola',
    name: 'Valpolicella Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 35,
    producers: ['Tommaso Bussola'],
    aliases: ['Bussola Valpolicella']
  },
  {
    id: 'valpolicella-corte-sant-alda',
    name: 'Valpolicella Classico Superiore Mithas',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 28,
    producers: ['Corte Sant\'Alda'],
    aliases: ['Mithas']
  },
  {
    id: 'valpolicella-monte-dall-ora',
    name: 'Valpolicella Classico Superiore Stropa',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Monte Dall\'Ora'],
    aliases: ['Stropa']
  },
];
