import { WineTemplate } from '@/types/wineDatabase';

/**
 * CALABRIA WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Cirò DOC (Gaglioppo red & Greco Bianco white)
 * Updated: January 2025
 */

export const calabriaPart1: WineTemplate[] = [
  // CIRÒ ROSSO CLASSICO SUPERIORE DOC (Red - Gaglioppo)
  {
    id: 'ciro-rosso-librandi-duca-san-felice',
    name: 'Cirò Rosso Classico Superiore Duca San Felice Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 32,
    producers: ['Librandi'],
    aliases: ['Duca San Felice']
  },
  {
    id: 'ciro-rosso-librandi',
    name: 'Cirò Rosso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 16,
    producers: ['Librandi'],
    aliases: ['Librandi Cirò Rosso']
  },
  {
    id: 'ciro-rosso-ippolito-1845-colli-del-mancuso',
    name: 'Cirò Rosso Classico Superiore Colli del Mancuso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1845,
    avgPrice: 28,
    producers: ['Ippolito 1845'],
    aliases: ['Colli del Mancuso']
  },
  {
    id: 'ciro-rosso-ippolito-1845',
    name: 'Cirò Rosso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1845,
    avgPrice: 14,
    producers: ['Ippolito 1845'],
    aliases: ['Ippolito Cirò Rosso']
  },
  {
    id: 'ciro-rosso-caparra-cardini',
    name: 'Cirò Rosso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 18,
    producers: ['Caparra & Siciliani'],
    aliases: ['Caparra & Siciliani Cirò']
  },
  {
    id: 'ciro-rosso-sergio-arcuri-aris',
    name: 'Cirò Rosso Classico Superiore Aris Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 2006,
    avgPrice: 35,
    producers: ['Sergio Arcuri'],
    aliases: ['Aris']
  },
  {
    id: 'ciro-rosso-sergio-arcuri',
    name: 'Cirò Rosso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 2006,
    avgPrice: 20,
    producers: ['Sergio Arcuri'],
    aliases: ['Sergio Arcuri Cirò']
  },
  {
    id: 'ciro-rosso-a-vita',
    name: 'Cirò Rosso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 22,
    producers: ['A Vita'],
    aliases: ['A Vita Cirò']
  },
  {
    id: 'ciro-rosso-cataldo-calabretta',
    name: 'Cirò Rosso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 28,
    producers: ['Cataldo Calabretta'],
    aliases: ['Calabretta Cirò']
  },
  {
    id: 'ciro-rosso-odoardi',
    name: 'Cirò Rosso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1991,
    avgPrice: 18,
    producers: ['Odoardi'],
    aliases: ['Odoardi Cirò']
  },
  {
    id: 'ciro-rosso-santa-venere',
    name: 'Cirò Rosso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Santa Venere'],
    aliases: ['Santa Venere Cirò']
  },
  {
    id: 'ciro-rosso-tenuta-del-conte',
    name: 'Cirò Rosso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Tenuta del Conte'],
    aliases: ['Tenuta del Conte Cirò']
  },
  {
    id: 'ciro-rosso-tramontana',
    name: 'Cirò Rosso Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Tramontana'],
    aliases: ['Tramontana Cirò']
  },
  
  // CIRÒ ROSSO DOC (Regular)
  {
    id: 'ciro-rosso-doc-librandi',
    name: 'Cirò Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 12,
    producers: ['Librandi'],
    aliases: ['Librandi Cirò DOC']
  },
  {
    id: 'ciro-rosso-doc-ippolito',
    name: 'Cirò Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1845,
    avgPrice: 11,
    producers: ['Ippolito 1845'],
    aliases: ['Ippolito Cirò DOC']
  },
  {
    id: 'ciro-rosso-doc-caparra-siciliani',
    name: 'Cirò Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 11,
    producers: ['Caparra & Siciliani'],
    aliases: ['Caparra Cirò DOC']
  },
  
  // CIRÒ BIANCO DOC (White - Greco Bianco)
  {
    id: 'ciro-bianco-librandi',
    name: 'Cirò Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 14,
    producers: ['Librandi'],
    aliases: ['Librandi Cirò Bianco']
  },
  {
    id: 'ciro-bianco-ippolito',
    name: 'Cirò Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'DOC',
    minVintage: 1845,
    avgPrice: 12,
    producers: ['Ippolito 1845'],
    aliases: ['Ippolito Cirò Bianco']
  },
  {
    id: 'ciro-bianco-caparra-siciliani',
    name: 'Cirò Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 12,
    producers: ['Caparra & Siciliani'],
    aliases: ['Caparra Cirò Bianco']
  },
  {
    id: 'ciro-bianco-sergio-arcuri',
    name: 'Cirò Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'DOC',
    minVintage: 2006,
    avgPrice: 16,
    producers: ['Sergio Arcuri'],
    aliases: ['Sergio Arcuri Bianco']
  },
  {
    id: 'ciro-bianco-a-vita',
    name: 'Cirò Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 16,
    producers: ['A Vita'],
    aliases: ['A Vita Bianco']
  },
  {
    id: 'ciro-bianco-odoardi',
    name: 'Cirò Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'DOC',
    minVintage: 1991,
    avgPrice: 14,
    producers: ['Odoardi'],
    aliases: ['Odoardi Bianco']
  },
  {
    id: 'ciro-bianco-santa-venere',
    name: 'Cirò Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 13,
    producers: ['Santa Venere'],
    aliases: ['Santa Venere Bianco']
  },
  
  // CIRÒ ROSATO DOC (Rosé)
  {
    id: 'ciro-rosato-librandi',
    name: 'Cirò Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 13,
    producers: ['Librandi'],
    aliases: ['Librandi Rosato']
  },
  {
    id: 'ciro-rosato-ippolito',
    name: 'Cirò Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1845,
    avgPrice: 11,
    producers: ['Ippolito 1845'],
    aliases: ['Ippolito Rosato']
  },
  {
    id: 'ciro-rosato-caparra-siciliani',
    name: 'Cirò Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 11,
    producers: ['Caparra & Siciliani'],
    aliases: ['Caparra Rosato']
  },
  {
    id: 'ciro-rosato-sergio-arcuri',
    name: 'Cirò Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 2006,
    avgPrice: 14,
    producers: ['Sergio Arcuri'],
    aliases: ['Sergio Arcuri Rosato']
  },
  {
    id: 'ciro-rosato-a-vita',
    name: 'Cirò Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 14,
    producers: ['A Vita'],
    aliases: ['A Vita Rosato']
  },
  {
    id: 'ciro-rosato-odoardi',
    name: 'Cirò Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 1991,
    avgPrice: 13,
    producers: ['Odoardi'],
    aliases: ['Odoardi Rosato']
  },
  
  // PREMIUM GAGLIOPPO WINES (Calabria IGT)
  {
    id: 'gaglioppo-librandi-gravello',
    name: 'Gravello Val di Neto IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 1988,
    avgPrice: 38,
    producers: ['Librandi'],
    aliases: ['Gravello']
  },
  {
    id: 'gaglioppo-librandi-magno-megonio',
    name: 'Magno Megonio Terre di Cosenza IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Magliocco Canino',
    classification: 'IGT',
    minVintage: 1998,
    avgPrice: 42,
    producers: ['Librandi'],
    aliases: ['Magno Megonio']
  },
  {
    id: 'gaglioppo-ippolito-liber-pater',
    name: 'Liber Pater Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Ippolito 1845'],
    aliases: ['Liber Pater']
  },
  {
    id: 'gaglioppo-sergio-arcuri-pian-della-corte',
    name: 'Pian della Corte Val di Neto IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 45,
    producers: ['Sergio Arcuri'],
    aliases: ['Pian della Corte']
  },
  {
    id: 'gaglioppo-cataldo-calabretta-100-anni',
    name: '100 Anni Val di Neto IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 48,
    producers: ['Cataldo Calabretta'],
    aliases: ['100 Anni']
  },
  {
    id: 'gaglioppo-odoardi-vigna-garrone',
    name: 'Vigna Garrone Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Savuto',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Odoardi'],
    aliases: ['Vigna Garrone']
  },
  {
    id: 'gaglioppo-odoardi-scavigna',
    name: 'Scavigna Terre di Cosenza IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Savuto',
    grapeVariety: 'Gaglioppo, Magliocco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Odoardi'],
    aliases: ['Scavigna']
  },
  {
    id: 'gaglioppo-a-vita-u-castagnaro',
    name: 'U Castagnaro Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 35,
    producers: ['A Vita'],
    aliases: ['U Castagnaro']
  },
  {
    id: 'gaglioppo-tenuta-del-conte-rosso',
    name: 'Rosso Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 28,
    producers: ['Tenuta del Conte'],
    aliases: ['Tenuta del Conte Rosso']
  },
  {
    id: 'gaglioppo-tramontana-rosso',
    name: 'Rosso Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 24,
    producers: ['Tramontana'],
    aliases: ['Tramontana Rosso']
  },
];
