import { WineTemplate } from '@/types/wineDatabase';

/**
 * PIEDMONT WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Barolo DOCG
 * Updated: January 2025
 */

export const piedmontPart1: WineTemplate[] = [
  // BAROLO DOCG - Top Producers
  {
    id: 'barolo-giacomo-conterno-monfortino',
    name: 'Barolo Riserva Monfortino',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1912,
    avgPrice: 650,
    producers: ['Giacomo Conterno'],
    aliases: ['Monfortino', 'Giacomo Conterno Monfortino']
  },
  {
    id: 'barolo-giacomo-conterno-cascina-francia',
    name: 'Barolo Cascina Francia',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 220,
    producers: ['Giacomo Conterno'],
    aliases: ['Cascina Francia']
  },
  {
    id: 'barolo-bartolo-mascarello',
    name: 'Barolo',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1919,
    avgPrice: 180,
    producers: ['Bartolo Mascarello', 'Giuseppe Mascarello'],
    aliases: ['Bartolo Mascarello']
  },
  {
    id: 'barolo-giuseppe-rinaldi',
    name: 'Barolo',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1890,
    avgPrice: 140,
    producers: ['Giuseppe Rinaldi'],
    aliases: ['Rinaldi Barolo']
  },
  {
    id: 'barolo-giuseppe-rinaldi-brunate',
    name: 'Barolo Brunate',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 220,
    producers: ['Giuseppe Rinaldi'],
    aliases: ['Brunate Le Coste']
  },
  {
    id: 'barolo-bruno-giacosa-falletto',
    name: 'Barolo Falletto',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1961,
    avgPrice: 150,
    producers: ['Bruno Giacosa'],
    aliases: ['Falletto']
  },
  {
    id: 'barolo-bruno-giacosa-falletto-riserva',
    name: 'Barolo Falletto Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 350,
    producers: ['Bruno Giacosa'],
    aliases: ['Falletto Riserva', 'Red Label Bruno Giacosa']
  },
  {
    id: 'barolo-gaja-sperss',
    name: 'Barolo Sperss',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1988,
    avgPrice: 280,
    producers: ['Gaja', 'Angelo Gaja'],
    aliases: ['Sperss']
  },
  {
    id: 'barolo-gaja-conteisa',
    name: 'Barolo Conteisa',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 2013,
    avgPrice: 220,
    producers: ['Gaja'],
    aliases: ['Conteisa']
  },
  {
    id: 'barolo-gaja-dagromis',
    name: 'Barolo Dagromis',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 2015,
    avgPrice: 180,
    producers: ['Gaja'],
    aliases: ['Dagromis']
  },
  {
    id: 'barolo-luciano-sandrone-cannubi-boschis',
    name: 'Barolo Cannubi Boschis',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1977,
    avgPrice: 220,
    producers: ['Luciano Sandrone'],
    aliases: ['Cannubi Boschis']
  },
  {
    id: 'barolo-luciano-sandrone-le-vigne',
    name: 'Barolo Le Vigne',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 120,
    producers: ['Luciano Sandrone'],
    aliases: ['Le Vigne']
  },
  {
    id: 'barolo-paolo-scavino-bric-del-fiasc',
    name: 'Barolo Bric dël Fiasc',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 240,
    producers: ['Paolo Scavino'],
    aliases: ['Bric dël Fiasc']
  },
  {
    id: 'barolo-paolo-scavino-rocche-annunziata',
    name: 'Barolo Rocche dell\'Annunziata Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 180,
    producers: ['Paolo Scavino'],
    aliases: ['Rocche dell\'Annunziata']
  },
  {
    id: 'barolo-elio-altare',
    name: 'Barolo',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1976,
    avgPrice: 95,
    producers: ['Elio Altare'],
    aliases: ['Altare Barolo']
  },
  {
    id: 'barolo-elio-altare-brunate',
    name: 'Barolo Brunate',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 160,
    producers: ['Elio Altare'],
    aliases: ['Brunate Altare']
  },
  {
    id: 'barolo-roberto-voerzio-cerequio',
    name: 'Barolo Cerequio',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1986,
    avgPrice: 220,
    producers: ['Roberto Voerzio'],
    aliases: ['Cerequio']
  },
  {
    id: 'barolo-roberto-voerzio-brunate',
    name: 'Barolo Brunate',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1986,
    avgPrice: 260,
    producers: ['Roberto Voerzio'],
    aliases: ['Brunate Voerzio']
  },
  {
    id: 'barolo-aldo-conterno-cicala',
    name: 'Barolo Cicala',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1969,
    avgPrice: 140,
    producers: ['Aldo Conterno'],
    aliases: ['Cicala']
  },
  {
    id: 'barolo-aldo-conterno-colonello',
    name: 'Barolo Colonello',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 180,
    producers: ['Aldo Conterno'],
    aliases: ['Colonello']
  },
  {
    id: 'barolo-aldo-conterno-granbussia',
    name: 'Barolo Granbussia Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 320,
    producers: ['Aldo Conterno'],
    aliases: ['Granbussia']
  },
  {
    id: 'barolo-vietti-ravera',
    name: 'Barolo Ravera',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 2010,
    avgPrice: 110,
    producers: ['Vietti'],
    aliases: ['Ravera Vietti']
  },
  {
    id: 'barolo-vietti-rocche',
    name: 'Barolo Rocche di Castiglione',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1961,
    avgPrice: 140,
    producers: ['Vietti'],
    aliases: ['Rocche di Castiglione']
  },
  {
    id: 'barolo-vietti-lazzarito',
    name: 'Barolo Lazzarito',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 130,
    producers: ['Vietti'],
    aliases: ['Lazzarito']
  },
  {
    id: 'barolo-ceretto-brunate',
    name: 'Barolo Brunate',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 120,
    producers: ['Ceretto'],
    aliases: ['Brunate Ceretto']
  },
  {
    id: 'barolo-ceretto-bricco-rocche',
    name: 'Barolo Bricco Rocche',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 160,
    producers: ['Ceretto'],
    aliases: ['Bricco Rocche']
  },
  {
    id: 'barolo-pira-chiara-boschis',
    name: 'Barolo Chiara Boschis',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1980,
    avgPrice: 90,
    producers: ['E. Pira & Figli', 'Chiara Boschis'],
    aliases: ['Chiara Boschis']
  },
  {
    id: 'barolo-pira-cannubi',
    name: 'Barolo Cannubi',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 140,
    producers: ['E. Pira & Figli'],
    aliases: ['Cannubi Pira']
  },
  {
    id: 'barolo-roagna-pira',
    name: 'Barolo Pira',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1953,
    avgPrice: 150,
    producers: ['Roagna'],
    aliases: ['Pira Roagna']
  },
  {
    id: 'barolo-roagna-pajana',
    name: 'Barolo La Pira Vecchie Viti',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1989,
    avgPrice: 220,
    producers: ['Roagna'],
    aliases: ['La Pira']
  },
  {
    id: 'barolo-marcarini-brunate',
    name: 'Barolo Brunate',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1958,
    avgPrice: 95,
    producers: ['Marcarini'],
    aliases: ['Brunate Marcarini']
  },
  {
    id: 'barolo-massolino-parafada',
    name: 'Barolo Parafada',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1896,
    avgPrice: 110,
    producers: ['Massolino'],
    aliases: ['Parafada']
  },
  {
    id: 'barolo-massolino-margheria',
    name: 'Barolo Vigna Rionda Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 180,
    producers: ['Massolino'],
    aliases: ['Vigna Rionda']
  },
  {
    id: 'barolo-brovia-rocche',
    name: 'Barolo Rocche di Castiglione',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1953,
    avgPrice: 100,
    producers: ['Brovia'],
    aliases: ['Rocche Brovia']
  },
  {
    id: 'barolo-brovia-villero',
    name: 'Barolo Villero',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1989,
    avgPrice: 110,
    producers: ['Brovia'],
    aliases: ['Villero Brovia']
  },
  {
    id: 'barolo-cavallotto-bricco-boschis',
    name: 'Barolo Bricco Boschis Vigna San Giuseppe Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1946,
    avgPrice: 120,
    producers: ['Cavallotto'],
    aliases: ['Bricco Boschis']
  },
  {
    id: 'barolo-oddero-vigna-rionda',
    name: 'Barolo Vigna Rionda',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1878,
    avgPrice: 180,
    producers: ['Oddero'],
    aliases: ['Vigna Rionda Oddero']
  },
  {
    id: 'barolo-oddero-rocche-rivera',
    name: 'Barolo Rocche di Castiglione Vigna Rivera',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 110,
    producers: ['Oddero'],
    aliases: ['Rocche Rivera']
  },
  {
    id: 'barolo-borgogno',
    name: 'Barolo',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1761,
    avgPrice: 65,
    producers: ['Borgogno', 'Giacomo Borgogno & Figli'],
    aliases: ['Borgogno Barolo']
  },
  {
    id: 'barolo-borgogno-liste',
    name: 'Barolo Liste Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 150,
    producers: ['Borgogno'],
    aliases: ['Liste']
  },
  {
    id: 'barolo-poderi-colla-bussia-dardi',
    name: 'Barolo Bussia Dardi Le Rose',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1994,
    avgPrice: 90,
    producers: ['Poderi Colla'],
    aliases: ['Bussia Dardi Le Rose']
  },
  {
    id: 'barolo-comm-g-b-burlotto',
    name: 'Barolo Monvigliero',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1850,
    avgPrice: 95,
    producers: ['Comm. G.B. Burlotto'],
    aliases: ['Monvigliero']
  },
  {
    id: 'barolo-burlotto-cannubi',
    name: 'Barolo Cannubi',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 140,
    producers: ['Comm. G.B. Burlotto'],
    aliases: ['Cannubi Burlotto']
  },
  {
    id: 'barolo-cappellano-otin-fiorin',
    name: 'Barolo Otin Fiorin Pie Rupestris',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1870,
    avgPrice: 160,
    producers: ['Cappellano'],
    aliases: ['Otin Fiorin']
  },
  {
    id: 'barolo-revello-conca',
    name: 'Barolo Conca',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1967,
    avgPrice: 85,
    producers: ['Revello', 'Fratelli Revello'],
    aliases: ['Conca']
  },
  {
    id: 'barolo-revello-gattera',
    name: 'Barolo Gattera',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 95,
    producers: ['Revello'],
    aliases: ['Gattera']
  },
  {
    id: 'barolo-elvio-cogno-ravera',
    name: 'Barolo Ravera',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 100,
    producers: ['Elvio Cogno'],
    aliases: ['Ravera Cogno']
  },
  {
    id: 'barolo-cogno-bricco-pernice',
    name: 'Barolo Bricco Pernice Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barolo',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 2006,
    avgPrice: 140,
    producers: ['Elvio Cogno'],
    aliases: ['Bricco Pernice']
  },
];
