import { WineTemplate } from '@/types/wineDatabase';

/**
 * PUGLIA WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Primitivo di Manduria, Primitivo di Salento
 * Updated: January 2025
 */

export const pugliaPart1: WineTemplate[] = [
  // PRIMITIVO DI MANDURIA DOCG & DOC
  {
    id: 'primitivo-manduria-gianfranco-fino-es',
    name: 'Primitivo di Manduria Es',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Manduria',
    grapeVariety: 'Primitivo',
    classification: 'DOCG',
    minVintage: 2004,
    avgPrice: 55,
    producers: ['Gianfranco Fino'],
    aliases: ['Es']
  },
  {
    id: 'primitivo-manduria-gianfranco-fino-jo',
    name: 'Primitivo di Manduria Jo',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Manduria',
    grapeVariety: 'Primitivo',
    classification: 'DOCG',
    minVintage: 2012,
    avgPrice: 28,
    producers: ['Gianfranco Fino'],
    aliases: ['Jo']
  },
  {
    id: 'primitivo-manduria-felline-alberello',
    name: 'Primitivo di Manduria Alberello',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Manduria',
    grapeVariety: 'Primitivo',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 35,
    producers: ['Felline'],
    aliases: ['Alberello']
  },
  {
    id: 'primitivo-manduria-felline',
    name: 'Primitivo di Manduria',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Manduria',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Felline'],
    aliases: ['Felline Primitivo']
  },
  {
    id: 'primitivo-manduria-produttori-vini-manduria',
    name: 'Primitivo di Manduria Sessantanni',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Manduria',
    grapeVariety: 'Primitivo',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 45,
    producers: ['Produttori di Manduria'],
    aliases: ['Sessantanni']
  },
  {
    id: 'primitivo-manduria-produttori-zinfandel',
    name: 'Primitivo di Manduria Zinfandel',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Manduria',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 1932,
    avgPrice: 18,
    producers: ['Produttori di Manduria'],
    aliases: ['Zinfandel Primitivo']
  },
  {
    id: 'primitivo-manduria-mottura-oltreme',
    name: 'Primitivo di Manduria Oltremè',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Manduria',
    grapeVariety: 'Primitivo',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 48,
    producers: ['Masseria Li Veli'],
    aliases: ['Oltremè']
  },
  {
    id: 'primitivo-manduria-pervini',
    name: 'Primitivo di Manduria',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Manduria',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 14,
    producers: ['Pervini'],
    aliases: ['Pervini Primitivo']
  },
  {
    id: 'primitivo-manduria-masseria-pepe',
    name: 'Primitivo di Manduria',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Manduria',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 32,
    producers: ['Masseria Pepe'],
    aliases: ['Masseria Pepe']
  },
  {
    id: 'primitivo-manduria-morella',
    name: 'Primitivo di Manduria',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Manduria',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 22,
    producers: ['Morella'],
    aliases: ['Morella Primitivo']
  },
  
  // PRIMITIVO DI MANDURIA DOLCE NATURALE DOCG (Dessert)
  {
    id: 'primitivo-manduria-dolce-naturale-felline',
    name: 'Primitivo di Manduria Dolce Naturale',
    type: 'Dessert',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Manduria',
    grapeVariety: 'Primitivo',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Felline'],
    aliases: ['Felline Dolce Naturale']
  },
  {
    id: 'primitivo-manduria-dolce-naturale-produttori',
    name: 'Primitivo di Manduria Dolce Naturale',
    type: 'Dessert',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Manduria',
    grapeVariety: 'Primitivo',
    classification: 'DOCG',
    minVintage: 2008,
    avgPrice: 32,
    producers: ['Produttori di Manduria'],
    aliases: ['Produttori Dolce Naturale']
  },
  
  // PRIMITIVO DI SALENTO IGT
  {
    id: 'primitivo-salento-a-mano',
    name: 'A Mano Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['A Mano'],
    aliases: ['A Mano']
  },
  {
    id: 'primitivo-salento-torrevento-primitivo',
    name: 'Primitivo Puglia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Murge',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 1987,
    avgPrice: 14,
    producers: ['Torrevento'],
    aliases: ['Torrevento Primitivo']
  },
  {
    id: 'primitivo-salento-masseria-li-veli',
    name: 'Askos Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Masseria Li Veli'],
    aliases: ['Askos']
  },
  {
    id: 'primitivo-salento-apollonio-terragnolo',
    name: 'Terragnolo Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 22,
    producers: ['Apollonio'],
    aliases: ['Terragnolo']
  },
  {
    id: 'primitivo-salento-apollonio',
    name: 'Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 1870,
    avgPrice: 12,
    producers: ['Apollonio'],
    aliases: ['Apollonio Primitivo']
  },
  {
    id: 'primitivo-salento-cantine-due-palme',
    name: 'Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 1989,
    avgPrice: 11,
    producers: ['Cantine Due Palme'],
    aliases: ['Due Palme Primitivo']
  },
  {
    id: 'primitivo-salento-san-marzano-sessantanni',
    name: 'Sessantanni Primitivo di Manduria',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Manduria',
    grapeVariety: 'Primitivo',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['San Marzano'],
    aliases: ['San Marzano Sessantanni']
  },
  {
    id: 'primitivo-salento-san-marzano-talò',
    name: 'Talò Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 14,
    producers: ['San Marzano'],
    aliases: ['Talò']
  },
  {
    id: 'primitivo-salento-tormaresca-masseria-maime',
    name: 'Masseria Maìme Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Tormaresca', 'Antinori'],
    aliases: ['Masseria Maìme']
  },
  {
    id: 'primitivo-salento-serre-dei-cianci',
    name: 'Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 12,
    producers: ['Serre dei Cianci'],
    aliases: ['Serre dei Cianci Primitivo']
  },
  {
    id: 'primitivo-salento-leone-de-castris-donna-lisa',
    name: 'Donna Lisa Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Leone de Castris'],
    aliases: ['Donna Lisa']
  },
  {
    id: 'primitivo-salento-casa-vinicola-botter',
    name: 'Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 1928,
    avgPrice: 10,
    producers: ['Casa Vinicola Botter'],
    aliases: ['Botter Primitivo']
  },
  {
    id: 'primitivo-salento-varvaglione',
    name: 'Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 1921,
    avgPrice: 11,
    producers: ['Varvaglione'],
    aliases: ['Varvaglione Primitivo']
  },
  {
    id: 'primitivo-salento-masserie-del-porto',
    name: 'Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 12,
    producers: ['Masserie del Porto'],
    aliases: ['Masserie del Porto Primitivo']
  },
  {
    id: 'primitivo-salento-cantele',
    name: 'Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 1979,
    avgPrice: 13,
    producers: ['Cantele'],
    aliases: ['Cantele Primitivo']
  },
  {
    id: 'primitivo-salento-feudi-di-guagnano',
    name: 'Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2002,
    avgPrice: 11,
    producers: ['Feudi di Guagnano'],
    aliases: ['Feudi di Guagnano Primitivo']
  },
  {
    id: 'primitivo-salento-torcicoda',
    name: 'Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 14,
    producers: ['Tormaresca'],
    aliases: ['Torcicoda']
  },
  {
    id: 'primitivo-salento-masseria-altemura',
    name: 'Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Masseria Altemura'],
    aliases: ['Altemura Primitivo']
  },
  {
    id: 'primitivo-salento-schola-sarmenti',
    name: 'Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2003,
    avgPrice: 12,
    producers: ['Schola Sarmenti'],
    aliases: ['Schola Sarmenti Primitivo']
  },
  {
    id: 'primitivo-salento-cantina-sampietrana',
    name: 'Primitivo Gioia del Colle',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Gioia del Colle',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 15,
    producers: ['Cantina Sampietrana'],
    aliases: ['Sampietrana Primitivo']
  },
  {
    id: 'primitivo-gioia-del-colle-polvanera-17',
    name: 'Primitivo di Gioia del Colle 17',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Gioia del Colle',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Polvanera'],
    aliases: ['Polvanera 17']
  },
  {
    id: 'primitivo-gioia-del-colle-polvanera',
    name: 'Primitivo di Gioia del Colle',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Gioia del Colle',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Polvanera'],
    aliases: ['Polvanera Primitivo']
  },
  {
    id: 'primitivo-gioia-del-colle-coppi',
    name: 'Primitivo di Gioia del Colle',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Gioia del Colle',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 22,
    producers: ['Coppi'],
    aliases: ['Coppi Primitivo']
  },
  {
    id: 'primitivo-gioia-del-colle-plantamura',
    name: 'Primitivo di Gioia del Colle',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Gioia del Colle',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Plantamura'],
    aliases: ['Plantamura Primitivo']
  },
  {
    id: 'primitivo-gioia-del-colle-mille-una-notte',
    name: 'Primitivo di Gioia del Colle Mille Una Notte',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Gioia del Colle',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 2006,
    avgPrice: 35,
    producers: ['Mille Una Notte'],
    aliases: ['Mille Una Notte']
  },
  {
    id: 'primitivo-gioia-del-colle-pietraventosa',
    name: 'Primitivo di Gioia del Colle',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Gioia del Colle',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 2002,
    avgPrice: 18,
    producers: ['Pietraventosa'],
    aliases: ['Pietraventosa Primitivo']
  },
  {
    id: 'primitivo-gioia-del-colle-torrevento',
    name: 'Primitivo di Gioia del Colle',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Gioia del Colle',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 1987,
    avgPrice: 16,
    producers: ['Torrevento'],
    aliases: ['Torrevento Gioia']
  },
  {
    id: 'primitivo-gioia-del-colle-cardone',
    name: 'Primitivo di Gioia del Colle',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Gioia del Colle',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Cardone'],
    aliases: ['Cardone Primitivo']
  },
  {
    id: 'primitivo-gioia-del-colle-antica-enotria',
    name: 'Primitivo di Gioia del Colle',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Gioia del Colle',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 14,
    producers: ['Antica Enotria'],
    aliases: ['Antica Enotria Primitivo']
  },
  {
    id: 'primitivo-gioia-del-colle-tenute-chiaromonte',
    name: 'Primitivo di Gioia del Colle',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Gioia del Colle',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 1997,
    avgPrice: 18,
    producers: ['Tenute Chiaromonte'],
    aliases: ['Chiaromonte Primitivo']
  },
];
