import { WineTemplate } from '@/types/wineDatabase';

/**
 * SARDINIA WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Dessert wines (Moscato, Malvasia), Rosés, Sparkling, Additional varieties
 * Updated: January 2025
 */

export const sardiniaPart3: WineTemplate[] = [
  // MOSCATO DI CAGLIARI DOC & MOSCATO DI SORSO-SENNORI DOC (Dessert)
  {
    id: 'moscato-argiolas-angialis',
    name: 'Angialis Moscato di Cagliari',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Moscato',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 32,
    producers: ['Argiolas'],
    aliases: ['Angialis']
  },
  {
    id: 'moscato-pala',
    name: 'Moscato di Cagliari',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Serdiana',
    grapeVariety: 'Moscato',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 24,
    producers: ['Pala'],
    aliases: ['Pala Moscato']
  },
  {
    id: 'moscato-sella-mosca-sorso-sennori',
    name: 'Moscato di Sorso-Sennori',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sorso',
    grapeVariety: 'Moscato',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Sella & Mosca'],
    aliases: ['Sella & Mosca Moscato']
  },
  {
    id: 'moscato-alberto-loi',
    name: 'Moscato di Cagliari',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Cagliari',
    grapeVariety: 'Moscato',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Alberto Loi'],
    aliases: ['Alberto Loi Moscato']
  },
  
  // MALVASIA DI BOSA DOC (Dessert/Sweet)
  {
    id: 'malvasia-columbu',
    name: 'Malvasia di Bosa',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Bosa',
    grapeVariety: 'Malvasia di Sardegna',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 35,
    producers: ['Columbu'],
    aliases: ['Columbu Malvasia']
  },
  {
    id: 'malvasia-salvatore-deriu',
    name: 'Malvasia di Bosa',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Bosa',
    grapeVariety: 'Malvasia di Sardegna',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 32,
    producers: ['Salvatore Deriu'],
    aliases: ['Deriu Malvasia']
  },
  
  // MALVASIA DI CAGLIARI DOC (Sweet)
  {
    id: 'malvasia-cagliari-argiolas',
    name: 'Malvasia di Cagliari',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Malvasia di Sardegna',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Argiolas'],
    aliases: ['Argiolas Malvasia']
  },
  {
    id: 'malvasia-cagliari-pala',
    name: 'Malvasia di Cagliari',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Serdiana',
    grapeVariety: 'Malvasia di Sardegna',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 26,
    producers: ['Pala'],
    aliases: ['Pala Malvasia']
  },
  
  // GIRÒ DI CAGLIARI DOC (Sweet red)
  {
    id: 'giro-argiolas',
    name: 'Girò di Cagliari',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Girò',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Argiolas'],
    aliases: ['Argiolas Girò']
  },
  {
    id: 'giro-pala',
    name: 'Girò di Cagliari',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Serdiana',
    grapeVariety: 'Girò',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 26,
    producers: ['Pala'],
    aliases: ['Pala Girò']
  },
  
  // ROSÉS (CERASUOLO/ROSATO)
  {
    id: 'rosato-santadi',
    name: 'Rosato Carignano del Sulcis',
    type: 'Rosé',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Carignano',
    classification: 'DOC',
    minVintage: 1977,
    avgPrice: 14,
    producers: ['Cantina di Santadi'],
    aliases: ['Santadi Rosato']
  },
  {
    id: 'rosato-mesa',
    name: 'Rosato Carignano del Sulcis',
    type: 'Rosé',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sant\'Antioco',
    grapeVariety: 'Carignano',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 14,
    producers: ['Mesa'],
    aliases: ['Mesa Rosato']
  },
  {
    id: 'rosato-argiolas',
    name: 'Rosato Isola dei Nuraghi IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Cannonau',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 12,
    producers: ['Argiolas'],
    aliases: ['Argiolas Rosato']
  },
  {
    id: 'rosato-pala',
    name: 'Rosato Isola dei Nuraghi IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Serdiana',
    grapeVariety: 'Cannonau, Monica',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 12,
    producers: ['Pala'],
    aliases: ['Pala Rosato']
  },
  {
    id: 'rosato-agricola-punica',
    name: 'Samas Isola dei Nuraghi IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sant\'Antioco',
    grapeVariety: 'Carignano',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Agricola Punica'],
    aliases: ['Samas']
  },
  
  // SPARKLING WINES
  {
    id: 'sparkling-capichera-brut',
    name: 'Vermentino di Gallura Spumante Brut',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Capichera'],
    aliases: ['Capichera Spumante']
  },
  {
    id: 'sparkling-sella-mosca-spumante',
    name: 'Vermentino di Sardegna Spumante',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Alghero',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Sella & Mosca'],
    aliases: ['Sella & Mosca Spumante']
  },
  {
    id: 'sparkling-argiolas',
    name: 'Vermentino Spumante Isola dei Nuraghi IGT',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Argiolas'],
    aliases: ['Argiolas Spumante']
  },
  
  // ADDITIONAL RED VARIETIES
  {
    id: 'sardinia-cannonau-riserva-jerzu',
    name: 'Cannonau di Sardegna Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Jerzu',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 1979,
    avgPrice: 28,
    producers: ['Antichi Poderi Jerzu'],
    aliases: ['Jerzu Riserva']
  },
  {
    id: 'sardinia-cannonau-riserva-mesa',
    name: 'Cannonau di Sardegna Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sant\'Antioco',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 26,
    producers: ['Mesa'],
    aliases: ['Mesa Cannonau Riserva']
  },
  {
    id: 'sardinia-carignano-riserva-6mura',
    name: 'Carignano del Sulcis Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Carignano',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 28,
    producers: ['6Mura'],
    aliases: ['6Mura Riserva']
  },
  
  // SEMIDANO (Indigenous white variety)
  {
    id: 'semidano-argiolas',
    name: 'Semidano Isola dei Nuraghi IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Semidano',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Argiolas'],
    aliases: ['Argiolas Semidano']
  },
  {
    id: 'semidano-mogoro',
    name: 'Semidano di Mogoro',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Mogoro',
    grapeVariety: 'Semidano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Cantina di Mogoro'],
    aliases: ['Mogoro Semidano']
  },
  
  // TORBATO (White - Alghero specialty)
  {
    id: 'torbato-sella-mosca-cuvee-161',
    name: 'Cuvée 161 Torbato Alghero DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Alghero',
    grapeVariety: 'Torbato',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Sella & Mosca'],
    aliases: ['Cuvée 161']
  },
  
  // INTERNATIONAL VARIETIES
  {
    id: 'cabernet-sauvignon-sella-mosca',
    name: 'Cabernet Sauvignon Alghero DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Alghero',
    grapeVariety: 'Cabernet Sauvignon',
    classification: 'DOC',
    minVintage: 1899,
    avgPrice: 24,
    producers: ['Sella & Mosca'],
    aliases: ['Sella & Mosca Cabernet']
  },
  {
    id: 'merlot-argiolas',
    name: 'Merlot Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Argiolas'],
    aliases: ['Argiolas Merlot']
  },
  {
    id: 'syrah-mesa',
    name: 'Syrah Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sant\'Antioco',
    grapeVariety: 'Syrah',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 22,
    producers: ['Mesa'],
    aliases: ['Mesa Syrah']
  },
  {
    id: 'chardonnay-argiolas',
    name: 'Chardonnay Isola dei Nuraghi IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Argiolas'],
    aliases: ['Argiolas Chardonnay']
  },
  {
    id: 'sauvignon-blanc-pala',
    name: 'Sauvignon Blanc Isola dei Nuraghi IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Serdiana',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Pala'],
    aliases: ['Pala Sauvignon']
  },
  
  // ADDITIONAL PREMIUM WINES
  {
    id: 'sardinia-pala-s-arai-rosso',
    name: 'S\'Arai Rosso Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Serdiana',
    grapeVariety: 'Cannonau, Carignano, Syrah',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 35,
    producers: ['Pala'],
    aliases: ['S\'Arai Rosso']
  },
  {
    id: 'sardinia-alberto-loi-riserva',
    name: 'Cannonau di Sardegna Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Cagliari',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Alberto Loi'],
    aliases: ['Alberto Loi Riserva']
  },
  {
    id: 'sardinia-tenute-dettori-tenores',
    name: 'Tenores Romangia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Romangia',
    grapeVariety: 'Cannonau',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 55,
    producers: ['Tenute Dettori'],
    aliases: ['Tenores']
  },
  {
    id: 'sardinia-cantina-gallura-balajana',
    name: 'Balajana Vermentino di Gallura',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Cantina Gallura'],
    aliases: ['Balajana']
  },
  {
    id: 'sardinia-surrau-sincaru',
    name: 'Sincaru Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Cannonau, Syrah',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 32,
    producers: ['Cantina di Surrau'],
    aliases: ['Sincaru']
  },
  {
    id: 'sardinia-capichera-mantenghja',
    name: 'Mantenghja Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Carignano, Muristellu',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 45,
    producers: ['Capichera'],
    aliases: ['Mantenghja']
  },
  {
    id: 'sardinia-piero-mancini-cannonau',
    name: 'Cannonau di Sardegna',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 20,
    producers: ['Piero Mancini'],
    aliases: ['Piero Mancini Cannonau']
  },
  {
    id: 'sardinia-6mura-vermentino',
    name: 'Vermentino di Sardegna Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 22,
    producers: ['6Mura'],
    aliases: ['6Mura Vermentino Superiore']
  },
  {
    id: 'sardinia-sardus-pater-vermentino',
    name: 'Vermentino di Sardegna',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1949,
    avgPrice: 14,
    producers: ['Sardus Pater'],
    aliases: ['Sardus Pater Vermentino']
  },
  {
    id: 'sardinia-contini-nieddera',
    name: 'Nieddera Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Oristano',
    grapeVariety: 'Nieddera',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Contini'],
    aliases: ['Nieddera']
  },
  {
    id: 'sardinia-contini-karmis',
    name: 'Karmis Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Oristano',
    grapeVariety: 'Cannonau, Carignano, Bovale',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Contini'],
    aliases: ['Karmis']
  },
  {
    id: 'sardinia-columbu-cannonau',
    name: 'Cannonau di Sardegna',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Bosa',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Columbu'],
    aliases: ['Columbu Cannonau']
  },
  {
    id: 'sardinia-deriu-vermentino',
    name: 'Vermentino di Sardegna',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Bosa',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Salvatore Deriu'],
    aliases: ['Deriu Vermentino']
  },
];
