import { WineTemplate } from '@/types/wineDatabase';

/**
 * SARDINIA WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Cannonau di Sardegna DOC (Grenache), Carignano del Sulcis
 * Updated: January 2025
 */

export const sardiniaPart1: WineTemplate[] = [
  // CANNONAU DI SARDEGNA DOC (Red - Grenache)
  {
    id: 'cannonau-argiolas-turriga',
    name: 'Turriga Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Cannonau, Carignano, Bovale Sardo, Malvasia Nera',
    classification: 'IGT',
    minVintage: 1988,
    avgPrice: 95,
    producers: ['Argiolas'],
    aliases: ['Turriga']
  },
  {
    id: 'cannonau-argiolas-korem',
    name: 'Korem Cannonau di Sardegna Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 45,
    producers: ['Argiolas'],
    aliases: ['Korem']
  },
  {
    id: 'cannonau-argiolas-costera',
    name: 'Costera Cannonau di Sardegna',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 1938,
    avgPrice: 22,
    producers: ['Argiolas'],
    aliases: ['Costera']
  },
  {
    id: 'cannonau-sella-mosca-riserva',
    name: 'Cannonau di Sardegna Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Alghero',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 1899,
    avgPrice: 28,
    producers: ['Sella & Mosca'],
    aliases: ['Sella & Mosca Cannonau Riserva']
  },
  {
    id: 'cannonau-sella-mosca',
    name: 'Cannonau di Sardegna',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Alghero',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 1899,
    avgPrice: 16,
    producers: ['Sella & Mosca'],
    aliases: ['Sella & Mosca Cannonau']
  },
  {
    id: 'cannonau-santadi-grotta-rossa',
    name: 'Grotta Rossa Cannonau di Sardegna',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 1977,
    avgPrice: 24,
    producers: ['Cantina di Santadi'],
    aliases: ['Grotta Rossa']
  },
  {
    id: 'cannonau-giuseppe-gabbas-dule',
    name: 'Cannonau di Sardegna Dule',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Nuoro',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 1991,
    avgPrice: 38,
    producers: ['Giuseppe Gabbas'],
    aliases: ['Dule']
  },
  {
    id: 'cannonau-giuseppe-gabbas-arbùre',
    name: 'Cannonau di Sardegna Arbùre',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Nuoro',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Giuseppe Gabbas'],
    aliases: ['Arbùre']
  },
  {
    id: 'cannonau-tenute-dettori-dettori-rosso',
    name: 'Dettori Rosso Romangia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Romangia',
    grapeVariety: 'Cannonau',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 85,
    producers: ['Tenute Dettori'],
    aliases: ['Dettori Rosso']
  },
  {
    id: 'cannonau-tenute-dettori-tuderi',
    name: 'Tuderi Romangia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Romangia',
    grapeVariety: 'Cannonau',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 55,
    producers: ['Tenute Dettori'],
    aliases: ['Tuderi']
  },
  {
    id: 'cannonau-alberto-loi',
    name: 'Cannonau di Sardegna',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Cagliari',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Alberto Loi'],
    aliases: ['Alberto Loi Cannonau']
  },
  {
    id: 'cannonau-mesa',
    name: 'Cannonau di Sardegna',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sant\'Antioco',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 16,
    producers: ['Mesa'],
    aliases: ['Mesa Cannonau']
  },
  {
    id: 'cannonau-pala-cannonau-riserva',
    name: 'Cannonau di Sardegna Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Serdiana',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 32,
    producers: ['Pala'],
    aliases: ['Pala Cannonau Riserva']
  },
  {
    id: 'cannonau-pala',
    name: 'Cannonau di Sardegna',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Serdiana',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 18,
    producers: ['Pala'],
    aliases: ['Pala Cannonau']
  },
  {
    id: 'cannonau-puddu',
    name: 'Cannonau di Sardegna',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Jerzu',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 1979,
    avgPrice: 16,
    producers: ['Antichi Poderi Jerzu'],
    aliases: ['Jerzu Cannonau']
  },
  
  // CARIGNANO DEL SULCIS DOC (Red)
  {
    id: 'carignano-santadi-terre-brune',
    name: 'Terre Brune Carignano del Sulcis Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Carignano',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 55,
    producers: ['Cantina di Santadi'],
    aliases: ['Terre Brune']
  },
  {
    id: 'carignano-santadi-rocca-rubia',
    name: 'Rocca Rubia Carignano del Sulcis Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Carignano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 42,
    producers: ['Cantina di Santadi'],
    aliases: ['Rocca Rubia']
  },
  {
    id: 'carignano-santadi',
    name: 'Carignano del Sulcis',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Carignano',
    classification: 'DOC',
    minVintage: 1977,
    avgPrice: 18,
    producers: ['Cantina di Santadi'],
    aliases: ['Santadi Carignano']
  },
  {
    id: 'carignano-mesa-buio-buio',
    name: 'Buio Buio Carignano del Sulcis Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sant\'Antioco',
    grapeVariety: 'Carignano',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 45,
    producers: ['Mesa'],
    aliases: ['Buio Buio']
  },
  {
    id: 'carignano-mesa-giunco',
    name: 'Giunco Carignano del Sulcis',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sant\'Antioco',
    grapeVariety: 'Carignano',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 22,
    producers: ['Mesa'],
    aliases: ['Giunco']
  },
  {
    id: 'carignano-agricola-punica-barrua',
    name: 'Barrua Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sant\'Antioco',
    grapeVariety: 'Carignano, Cabernet Sauvignon, Merlot',
    classification: 'IGT',
    minVintage: 2002,
    avgPrice: 75,
    producers: ['Agricola Punica', 'Santadi'],
    aliases: ['Barrua']
  },
  {
    id: 'carignano-agricola-punica-montessu',
    name: 'Montessu Carignano del Sulcis',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sant\'Antioco',
    grapeVariety: 'Carignano',
    classification: 'DOC',
    minVintage: 2002,
    avgPrice: 28,
    producers: ['Agricola Punica'],
    aliases: ['Montessu']
  },
  {
    id: 'carignano-sardus-pater-superiore',
    name: 'Carignano del Sulcis Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Carignano',
    classification: 'DOC',
    minVintage: 1949,
    avgPrice: 32,
    producers: ['Sardus Pater'],
    aliases: ['Sardus Pater Superiore']
  },
  {
    id: 'carignano-sardus-pater',
    name: 'Carignano del Sulcis',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Carignano',
    classification: 'DOC',
    minVintage: 1949,
    avgPrice: 16,
    producers: ['Sardus Pater'],
    aliases: ['Sardus Pater Carignano']
  },
  {
    id: 'carignano-6mura',
    name: 'Carignano del Sulcis',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Carignano',
    classification: 'DOC',
    minVintage: 2006,
    avgPrice: 20,
    producers: ['6Mura'],
    aliases: ['6Mura Carignano']
  },
  
  // MONICA DI SARDEGNA DOC (Red)
  {
    id: 'monica-argiolas',
    name: 'Monica di Sardegna',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Monica',
    classification: 'DOC',
    minVintage: 1938,
    avgPrice: 14,
    producers: ['Argiolas'],
    aliases: ['Argiolas Monica']
  },
  {
    id: 'monica-pala',
    name: 'Monica di Sardegna',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Serdiana',
    grapeVariety: 'Monica',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 14,
    producers: ['Pala'],
    aliases: ['Pala Monica']
  },
  {
    id: 'monica-santadi',
    name: 'Monica di Sardegna',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Monica',
    classification: 'DOC',
    minVintage: 1977,
    avgPrice: 12,
    producers: ['Cantina di Santadi'],
    aliases: ['Santadi Monica']
  },
  
  // BOVALE (Indigenous red variety)
  {
    id: 'bovale-argiolas-perdera',
    name: 'Perdera Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Bovale Sardo, Carignano, Cannonau',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Argiolas'],
    aliases: ['Perdera']
  },
  
  // RED BLENDS & PREMIUM WINES
  {
    id: 'sardinia-argiolas-s-elegas',
    name: 'S\'Elegas Carignano del Sulcis',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Carignano, Bovale Sardo',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Argiolas'],
    aliases: ['S\'Elegas']
  },
  {
    id: 'sardinia-santadi-latinia',
    name: 'Latinia Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Carignano, Syrah, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Cantina di Santadi'],
    aliases: ['Latinia']
  },
  {
    id: 'sardinia-santadi-noras',
    name: 'Noras Carignano del Sulcis',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Carignano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Cantina di Santadi'],
    aliases: ['Noras']
  },
  {
    id: 'sardinia-pala-tre-pedras',
    name: 'Tre Pedras Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Serdiana',
    grapeVariety: 'Cannonau, Carignano, Bovale',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Pala'],
    aliases: ['Tre Pedras']
  },
  {
    id: 'sardinia-alberto-loi-s-arai',
    name: 'S\'Arai Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Cagliari',
    grapeVariety: 'Cannonau, Carignano',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Alberto Loi'],
    aliases: ['S\'Arai']
  },
  {
    id: 'sardinia-sella-mosca-marchese-di-villamarina',
    name: 'Marchese di Villamarina Alghero DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Alghero',
    grapeVariety: 'Cabernet Sauvignon',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 42,
    producers: ['Sella & Mosca'],
    aliases: ['Marchese di Villamarina']
  },
  {
    id: 'sardinia-sella-mosca-tanca-farra',
    name: 'Tanca Farrà Alghero DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Alghero',
    grapeVariety: 'Cannonau',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 35,
    producers: ['Sella & Mosca'],
    aliases: ['Tanca Farrà']
  },
  {
    id: 'sardinia-mesa-gabbro',
    name: 'Gabbro Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sant\'Antioco',
    grapeVariety: 'Cannonau, Carignano, Syrah',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 35,
    producers: ['Mesa'],
    aliases: ['Gabbro']
  },
  {
    id: 'sardinia-giuseppe-gabbas-lillove',
    name: 'Lillove Isola dei Nuraghi IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Nuoro',
    grapeVariety: 'Cannonau',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 45,
    producers: ['Giuseppe Gabbas'],
    aliases: ['Lillove']
  },
  {
    id: 'sardinia-tenute-dettori-renosu',
    name: 'Renosu Romangia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Romangia',
    grapeVariety: 'Cannonau, Pascale, Nieddera',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 65,
    producers: ['Tenute Dettori'],
    aliases: ['Renosu']
  },
];
