import { WineTemplate } from '@/types/wineDatabase';

/**
 * TRENTINO-ALTO ADIGE WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Sauvignon Blanc, Chardonnay, Riesling, Müller-Thurgau, Sylvaner
 * Updated: January 2025
 */

export const trentinoAltoAdigePart2: WineTemplate[] = [
  // SAUVIGNON BLANC - ALTO ADIGE DOC
  {
    id: 'sauvignon-terlan-quarz',
    name: 'Sauvignon Alto Adige Quarz',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Terlano',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1993,
    avgPrice: 48,
    producers: ['Cantina Terlano'],
    aliases: ['Quarz Sauvignon']
  },
  {
    id: 'sauvignon-terlan-winkl',
    name: 'Sauvignon Alto Adige Winkl',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Terlano',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['Cantina Terlano'],
    aliases: ['Winkl Sauvignon']
  },
  {
    id: 'sauvignon-terlan',
    name: 'Sauvignon Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Terlano',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1893,
    avgPrice: 26,
    producers: ['Cantina Terlano'],
    aliases: ['Terlano Sauvignon']
  },
  {
    id: 'sauvignon-st-michael-eppan-lahn',
    name: 'Sauvignon Alto Adige Lahn',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Appiano',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1986,
    avgPrice: 42,
    producers: ['St. Michael-Eppan'],
    aliases: ['Lahn']
  },
  {
    id: 'sauvignon-st-michael-eppan',
    name: 'Sauvignon Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Appiano',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1907,
    avgPrice: 22,
    producers: ['St. Michael-Eppan'],
    aliases: ['St. Michael Sauvignon']
  },
  {
    id: 'sauvignon-cantina-tramin',
    name: 'Sauvignon Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Termeno',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1898,
    avgPrice: 20,
    producers: ['Cantina Tramin'],
    aliases: ['Tramin Sauvignon']
  },
  {
    id: 'sauvignon-nals-margreid-mantele',
    name: 'Sauvignon Alto Adige Mantele',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Nalles-Magrè',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 38,
    producers: ['Nals Margreid'],
    aliases: ['Mantele']
  },
  {
    id: 'sauvignon-nals-margreid',
    name: 'Sauvignon Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Nalles-Magrè',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1932,
    avgPrice: 24,
    producers: ['Nals Margreid'],
    aliases: ['Nals Margreid Sauvignon']
  },
  {
    id: 'sauvignon-elena-walch',
    name: 'Sauvignon Alto Adige Castel Ringberg',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 32,
    producers: ['Elena Walch'],
    aliases: ['Castel Ringberg']
  },
  {
    id: 'sauvignon-alois-lageder',
    name: 'Sauvignon Alto Adige Lehenhof',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 35,
    producers: ['Alois Lageder'],
    aliases: ['Lehenhof']
  },
  {
    id: 'sauvignon-manincor',
    name: 'Sauvignon Alto Adige Lieben Aich',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Caldaro',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 38,
    producers: ['Manincor'],
    aliases: ['Lieben Aich']
  },
  
  // CHARDONNAY - ALTO ADIGE & TRENTINO DOC
  {
    id: 'chardonnay-st-michael-eppan-sanct-valentin',
    name: 'Chardonnay Alto Adige Sanct Valentin',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Appiano',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1986,
    avgPrice: 52,
    producers: ['St. Michael-Eppan'],
    aliases: ['Sanct Valentin Chardonnay']
  },
  {
    id: 'chardonnay-terlan-kreuth',
    name: 'Chardonnay Alto Adige Kreuth',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Terlano',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1988,
    avgPrice: 45,
    producers: ['Cantina Terlano'],
    aliases: ['Kreuth']
  },
  {
    id: 'chardonnay-terlan',
    name: 'Chardonnay Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Terlano',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1893,
    avgPrice: 26,
    producers: ['Cantina Terlano'],
    aliases: ['Terlano Chardonnay']
  },
  {
    id: 'chardonnay-alois-lageder-lowengang',
    name: 'Chardonnay Alto Adige Löwengang',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1986,
    avgPrice: 48,
    producers: ['Alois Lageder'],
    aliases: ['Löwengang']
  },
  {
    id: 'chardonnay-elena-walch',
    name: 'Chardonnay Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1869,
    avgPrice: 22,
    producers: ['Elena Walch'],
    aliases: ['Elena Walch Chardonnay']
  },
  {
    id: 'chardonnay-nals-margreid',
    name: 'Chardonnay Alto Adige',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Nalles-Magrè',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1932,
    avgPrice: 24,
    producers: ['Nals Margreid'],
    aliases: ['Nals Margreid Chardonnay']
  },
  {
    id: 'chardonnay-ferrari-perlé',
    name: 'Trento DOC Perlé',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Trento',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1902,
    avgPrice: 38,
    producers: ['Ferrari'],
    aliases: ['Perlé']
  },
  {
    id: 'chardonnay-ferrari-perlé-nero',
    name: 'Trento DOC Perlé Nero',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Trento',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 2006,
    avgPrice: 55,
    producers: ['Ferrari'],
    aliases: ['Perlé Nero']
  },
  {
    id: 'chardonnay-ferrari-maximum',
    name: 'Trento DOC Maximum Blanc de Blancs',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Trento',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1988,
    avgPrice: 85,
    producers: ['Ferrari'],
    aliases: ['Maximum']
  },
  {
    id: 'chardonnay-ferrari-giulio-ferrari-riserva',
    name: 'Trento DOC Giulio Ferrari Riserva del Fondatore',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Trento',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1972,
    avgPrice: 150,
    producers: ['Ferrari'],
    aliases: ['Giulio Ferrari']
  },
  
  // RIESLING - ALTO ADIGE (VALLE ISARCO)
  {
    id: 'riesling-abbazia-novacella',
    name: 'Riesling Valle Isarco',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Riesling',
    classification: 'DOC',
    minVintage: 1142,
    avgPrice: 28,
    producers: ['Abbazia di Novacella'],
    aliases: ['Abbazia Riesling']
  },
  {
    id: 'riesling-abbazia-novacella-praepositus',
    name: 'Riesling Valle Isarco Praepositus',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Riesling',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['Abbazia di Novacella'],
    aliases: ['Praepositus Riesling']
  },
  {
    id: 'riesling-kofererhof',
    name: 'Riesling Valle Isarco',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Riesling',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 32,
    producers: ['Köfererhof', 'Günther Kerschbaumer'],
    aliases: ['Köfererhof Riesling']
  },
  {
    id: 'riesling-kuenhof-kaiton',
    name: 'Riesling Valle Isarco Kaiton',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Riesling',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 38,
    producers: ['Kuenhof', 'Peter Pliger'],
    aliases: ['Kaiton']
  },
  {
    id: 'riesling-kuenhof',
    name: 'Riesling Valle Isarco',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Riesling',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Kuenhof'],
    aliases: ['Kuenhof Riesling']
  },
  {
    id: 'riesling-pacherhof',
    name: 'Riesling Valle Isarco',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Riesling',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Pacherhof', 'Andreas Huber'],
    aliases: ['Pacherhof Riesling']
  },
  
  // MÜLLER-THURGAU - VALLE ISARCO
  {
    id: 'muller-thurgau-abbazia-novacella',
    name: 'Müller-Thurgau Valle Isarco',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Müller-Thurgau',
    classification: 'DOC',
    minVintage: 1142,
    avgPrice: 22,
    producers: ['Abbazia di Novacella'],
    aliases: ['Abbazia Müller-Thurgau']
  },
  {
    id: 'muller-thurgau-kuenhof',
    name: 'Müller-Thurgau Valle Isarco',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Müller-Thurgau',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 24,
    producers: ['Kuenhof'],
    aliases: ['Kuenhof Müller-Thurgau']
  },
  {
    id: 'muller-thurgau-kofererhof',
    name: 'Müller-Thurgau Valle Isarco',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Müller-Thurgau',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 26,
    producers: ['Köfererhof'],
    aliases: ['Köfererhof Müller-Thurgau']
  },
  
  // SYLVANER - VALLE ISARCO
  {
    id: 'sylvaner-abbazia-novacella',
    name: 'Sylvaner Valle Isarco',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Sylvaner',
    classification: 'DOC',
    minVintage: 1142,
    avgPrice: 24,
    producers: ['Abbazia di Novacella'],
    aliases: ['Abbazia Sylvaner']
  },
  {
    id: 'sylvaner-abbazia-novacella-praepositus',
    name: 'Sylvaner Valle Isarco Praepositus',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Sylvaner',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 38,
    producers: ['Abbazia di Novacella'],
    aliases: ['Praepositus Sylvaner']
  },
  {
    id: 'sylvaner-kuenhof',
    name: 'Sylvaner Valle Isarco',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Sylvaner',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 26,
    producers: ['Kuenhof'],
    aliases: ['Kuenhof Sylvaner']
  },
  {
    id: 'sylvaner-kofererhof',
    name: 'Sylvaner Valle Isarco',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Valle Isarco',
    grapeVariety: 'Sylvaner',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 28,
    producers: ['Köfererhof'],
    aliases: ['Köfererhof Sylvaner']
  },
  
  // WHITE BLENDS & TERLANER CLASSICO
  {
    id: 'terlaner-terlan-nova-domus-riserva',
    name: 'Terlano Classico Nova Domus Riserva',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Terlano',
    grapeVariety: 'Pinot Bianco, Chardonnay, Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1996,
    avgPrice: 95,
    producers: ['Cantina Terlano'],
    aliases: ['Nova Domus']
  },
  {
    id: 'terlaner-terlan-lunare',
    name: 'Terlano Classico Lunare',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Terlano',
    grapeVariety: 'Pinot Bianco, Chardonnay, Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 2006,
    avgPrice: 55,
    producers: ['Cantina Terlano'],
    aliases: ['Lunare']
  },
  {
    id: 'terlaner-terlan-classico',
    name: 'Terlano Classico',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Terlano',
    grapeVariety: 'Pinot Bianco, Chardonnay, Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1893,
    avgPrice: 28,
    producers: ['Cantina Terlano'],
    aliases: ['Terlaner Classico']
  },
  {
    id: 'bianco-st-michael-eppan-appius',
    name: 'Appius Alto Adige Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Appiano',
    grapeVariety: 'Pinot Bianco, Chardonnay, Sauvignon',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 48,
    producers: ['St. Michael-Eppan'],
    aliases: ['Appius']
  },
  {
    id: 'bianco-alois-lageder-cor-romigberg',
    name: 'Cor Römigberg Alto Adige Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Chardonnay, Pinot Grigio, Pinot Bianco',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 55,
    producers: ['Alois Lageder'],
    aliases: ['Cor Römigberg']
  },
];
