import { WineTemplate } from '@/types/wineDatabase';

/**
 * SICILY WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Etna DOC (Red & White), Nero d'Avola
 * Updated: January 2025
 */

export const sicilyPart1: WineTemplate[] = [
  // ETNA DOC - Red
  {
    id: 'etna-rosso-passopisciaro-contrada-passopisc',
    name: 'Etna Rosso Contrada Porcaria',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 85,
    producers: ['Passopisciaro', 'Andrea Franchetti'],
    aliases: ['Porcaria', 'Passopisciaro Contrada']
  },
  {
    id: 'etna-rosso-passopisciaro-guardiola',
    name: 'Etna Rosso Contrada Guardiola',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 75,
    producers: ['Passopisciaro'],
    aliases: ['Guardiola']
  },
  {
    id: 'etna-rosso-passopisciaro-chiappemacine',
    name: 'Etna Rosso Contrada Chiappemacine',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 75,
    producers: ['Passopisciaro'],
    aliases: ['Chiappemacine']
  },
  {
    id: 'etna-rosso-passopisciaro-rampante',
    name: 'Etna Rosso Contrada Rampante',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 75,
    producers: ['Passopisciaro'],
    aliases: ['Rampante']
  },
  {
    id: 'etna-rosso-passopisciaro',
    name: 'Etna Rosso Passopisciaro',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['Passopisciaro'],
    aliases: ['Passopisciaro Etna']
  },
  {
    id: 'etna-rosso-benanti-rovittello',
    name: 'Etna Rosso Rovittello',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 1988,
    avgPrice: 52,
    producers: ['Benanti'],
    aliases: ['Rovittello']
  },
  {
    id: 'etna-rosso-benanti-serra-della-contessa',
    name: 'Etna Rosso Serra della Contessa',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 1988,
    avgPrice: 48,
    producers: ['Benanti'],
    aliases: ['Serra della Contessa']
  },
  {
    id: 'etna-rosso-tenuta-delle-terre-nere-prephylloxera',
    name: 'Etna Rosso Prephylloxera',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2002,
    avgPrice: 95,
    producers: ['Tenuta delle Terre Nere'],
    aliases: ['Prephylloxera']
  },
  {
    id: 'etna-rosso-tenuta-delle-terre-nere-feudo-di-mezzo',
    name: 'Etna Rosso Feudo di Mezzo',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 55,
    producers: ['Tenuta delle Terre Nere'],
    aliases: ['Feudo di Mezzo']
  },
  {
    id: 'etna-rosso-tenuta-delle-terre-nere-san-lorenzo',
    name: 'Etna Rosso San Lorenzo',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 55,
    producers: ['Tenuta delle Terre Nere'],
    aliases: ['San Lorenzo']
  },
  {
    id: 'etna-rosso-girolamo-russo-san-lorenzo',
    name: 'Etna Rosso Contrada San Lorenzo',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 75,
    producers: ['Girolamo Russo'],
    aliases: ['San Lorenzo Russo']
  },
  {
    id: 'etna-rosso-girolamo-russo-feudo',
    name: 'Etna Rosso Feudo',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 65,
    producers: ['Girolamo Russo'],
    aliases: ['Feudo']
  },
  {
    id: 'etna-rosso-graci-arcuria',
    name: 'Etna Rosso Contrada Arcuria',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 72,
    producers: ['Graci'],
    aliases: ['Arcuria']
  },
  {
    id: 'etna-rosso-graci-barbabecchi',
    name: 'Etna Rosso Contrada Barbabecchi',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 68,
    producers: ['Graci'],
    aliases: ['Barbabecchi']
  },
  {
    id: 'etna-rosso-pietradolce-vigna-barbagalli',
    name: 'Etna Rosso Vigna Barbagalli',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 55,
    producers: ['Pietradolce'],
    aliases: ['Vigna Barbagalli']
  },
  {
    id: 'etna-rosso-planeta-sciaranuova',
    name: 'Etna Rosso Sciaranuova',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 35,
    producers: ['Planeta'],
    aliases: ['Sciaranuova']
  },
  {
    id: 'etna-rosso-frank-cornelissen-munjebel',
    name: 'Munjebel Rosso Etna',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'Vino',
    minVintage: 2001,
    avgPrice: 120,
    producers: ['Frank Cornelissen'],
    aliases: ['Munjebel']
  },
  {
    id: 'etna-rosso-frank-cornelissen-magma',
    name: 'Magma Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese, Nerello Cappuccio',
    classification: 'Vino',
    minVintage: 2001,
    avgPrice: 220,
    producers: ['Frank Cornelissen'],
    aliases: ['Magma']
  },
  {
    id: 'etna-rosso-ciro-biondi-outis',
    name: 'Etna Rosso Outis',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 48,
    producers: ['Ciro Biondi'],
    aliases: ['Outis']
  },
  {
    id: 'etna-rosso-ciro-biondi-cisterna-fuori',
    name: 'Etna Rosso Cisterna Fuori',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 65,
    producers: ['Ciro Biondi'],
    aliases: ['Cisterna Fuori']
  },
  
  // ETNA DOC - White
  {
    id: 'etna-bianco-benanti-pietramarina',
    name: 'Etna Bianco Pietramarina',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Carricante',
    classification: 'DOC',
    minVintage: 1988,
    avgPrice: 38,
    producers: ['Benanti'],
    aliases: ['Pietramarina']
  },
  {
    id: 'etna-bianco-tenuta-delle-terre-nere',
    name: 'Etna Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Carricante',
    classification: 'DOC',
    minVintage: 2002,
    avgPrice: 32,
    producers: ['Tenuta delle Terre Nere'],
    aliases: ['Terre Nere Bianco']
  },
  {
    id: 'etna-bianco-graci',
    name: 'Etna Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Carricante',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 38,
    producers: ['Graci'],
    aliases: ['Graci Bianco']
  },
  {
    id: 'etna-bianco-pietradolce',
    name: 'Etna Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Carricante',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Pietradolce'],
    aliases: ['Pietradolce Bianco']
  },
  {
    id: 'etna-bianco-planeta',
    name: 'Etna Bianco Eruzione 1614',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Carricante',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 32,
    producers: ['Planeta'],
    aliases: ['Eruzione 1614']
  },
  {
    id: 'etna-bianco-frank-cornelissen-munjebel',
    name: 'Munjebel Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Carricante, Grecanico',
    classification: 'Vino',
    minVintage: 2005,
    avgPrice: 95,
    producers: ['Frank Cornelissen'],
    aliases: ['Munjebel Bianco']
  },
  
  // NERO D'AVOLA (Sicilia DOC & IGT)
  {
    id: 'nero-avola-planeta-santa-cecilia',
    name: 'Santa Cecilia Nero d\'Avola Sicilia DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Noto',
    grapeVariety: 'Nero d\'Avola',
    classification: 'DOC',
    minVintage: 1997,
    avgPrice: 42,
    producers: ['Planeta'],
    aliases: ['Santa Cecilia']
  },
  {
    id: 'nero-avola-planeta',
    name: 'Nero d\'Avola Sicilia DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Menfi',
    grapeVariety: 'Nero d\'Avola',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 18,
    producers: ['Planeta'],
    aliases: ['Planeta Nero d\'Avola']
  },
  {
    id: 'nero-avola-gulfi-nerojbleo',
    name: 'NeroJbleo Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Chiaramonte Gulfi',
    grapeVariety: 'Nero d\'Avola',
    classification: 'IGT',
    minVintage: 1996,
    avgPrice: 28,
    producers: ['Gulfi'],
    aliases: ['NeroJbleo']
  },
  {
    id: 'nero-avola-gulfi-nerosanlorenzo',
    name: 'NeroSanlorenzo Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Chiaramonte Gulfi',
    grapeVariety: 'Nero d\'Avola',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 45,
    producers: ['Gulfi'],
    aliases: ['NeroSanlorenzo']
  },
  {
    id: 'nero-avola-gulfi-nerobufaleffj',
    name: 'NeroBufaleffj Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Chiaramonte Gulfi',
    grapeVariety: 'Nero d\'Avola',
    classification: 'IGT',
    minVintage: 2001,
    avgPrice: 52,
    producers: ['Gulfi'],
    aliases: ['NeroBufaleffj']
  },
  {
    id: 'nero-avola-gulfi-neromaccarj',
    name: 'NeroMaccarj Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Chiaramonte Gulfi',
    grapeVariety: 'Nero d\'Avola',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 48,
    producers: ['Gulfi'],
    aliases: ['NeroMaccarj']
  },
  {
    id: 'nero-avola-feudo-maccari-saia',
    name: 'Saia Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Noto',
    grapeVariety: 'Nero d\'Avola',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 38,
    producers: ['Feudo Maccari'],
    aliases: ['Saia']
  },
  {
    id: 'nero-avola-feudo-maccari',
    name: 'Nero d\'Avola Sicilia DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Noto',
    grapeVariety: 'Nero d\'Avola',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Feudo Maccari'],
    aliases: ['Feudo Maccari Nero']
  },
  {
    id: 'nero-avola-donnafugata-mille-una-notte',
    name: 'Mille e Una Notte Contessa Entellina DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Contessa Entellina',
    grapeVariety: 'Nero d\'Avola, Petit Verdot, Syrah, Other grapes',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 75,
    producers: ['Donnafugata'],
    aliases: ['Mille e Una Notte']
  },
  {
    id: 'nero-avola-donnafugata-tancredi',
    name: 'Tancredi Sicilia DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Contessa Entellina',
    grapeVariety: 'Nero d\'Avola, Cabernet Sauvignon',
    classification: 'DOC',
    minVintage: 1992,
    avgPrice: 35,
    producers: ['Donnafugata'],
    aliases: ['Tancredi']
  },
  {
    id: 'nero-avola-cusumano-sagana',
    name: 'Sagana Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Partinico',
    grapeVariety: 'Nero d\'Avola',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 38,
    producers: ['Cusumano'],
    aliases: ['Sagana']
  },
  {
    id: 'nero-avola-cusumano-noa',
    name: 'Noà Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Partinico',
    grapeVariety: 'Nero d\'Avola',
    classification: 'IGT',
    minVintage: 2002,
    avgPrice: 28,
    producers: ['Cusumano'],
    aliases: ['Noà']
  },
  {
    id: 'nero-avola-firriato-harmonium',
    name: 'Harmonium Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Trapani',
    grapeVariety: 'Nero d\'Avola, Syrah, Petit Verdot',
    classification: 'IGT',
    minVintage: 1998,
    avgPrice: 48,
    producers: ['Firriato'],
    aliases: ['Harmonium']
  },
  {
    id: 'nero-avola-tasca-rosso-del-conte',
    name: 'Rosso del Conte Contea di Sclafani DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Regaleali',
    grapeVariety: 'Nero d\'Avola, Perricone',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 52,
    producers: ['Tasca d\'Almerita'],
    aliases: ['Rosso del Conte']
  },
  {
    id: 'nero-avola-morgante-don-antonio',
    name: 'Don Antonio Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Grotte',
    grapeVariety: 'Nero d\'Avola',
    classification: 'IGT',
    minVintage: 1994,
    avgPrice: 42,
    producers: ['Morgante'],
    aliases: ['Don Antonio']
  },
  {
    id: 'nero-avola-morgante',
    name: 'Nero d\'Avola Sicilia DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Grotte',
    grapeVariety: 'Nero d\'Avola',
    classification: 'DOC',
    minVintage: 1994,
    avgPrice: 18,
    producers: ['Morgante'],
    aliases: ['Morgante Nero']
  },
  {
    id: 'nero-avola-cos-pithos-rosso',
    name: 'Pithos Rosso Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Nero d\'Avola',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 48,
    producers: ['COS'],
    aliases: ['Pithos Rosso']
  },
  {
    id: 'nero-avola-arianna-occhipinti-siccagno',
    name: 'Siccagno Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Nero d\'Avola',
    classification: 'IGT',
    minVintage: 2004,
    avgPrice: 65,
    producers: ['Arianna Occhipinti'],
    aliases: ['Siccagno']
  },
];
