import { WineTemplate } from '@/types/wineDatabase';

/**
 * MOLISE WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Falanghina, Greco, White wines, International varieties
 * Updated: January 2025
 */

export const molisePart2: WineTemplate[] = [
  // FALANGHINA (White variety)
  {
    id: 'falanghina-di-maio-norante-san-giorgio',
    name: 'Falanghina San Giorgio Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Di Majo Norante'],
    aliases: ['San Giorgio']
  },
  {
    id: 'falanghina-di-maio-norante',
    name: 'Falanghina Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 14,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Falanghina']
  },
  {
    id: 'falanghina-borgo-di-colloredo',
    name: 'Falanghina Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Falanghina']
  },
  {
    id: 'falanghina-catabbo',
    name: 'Falanghina Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Catabbo'],
    aliases: ['Catabbo Falanghina']
  },
  {
    id: 'falanghina-tenimenti-grieco',
    name: 'Falanghina Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Falanghina']
  },
  {
    id: 'falanghina-cianfagna',
    name: 'Falanghina Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Cianfagna'],
    aliases: ['Cianfagna Falanghina']
  },
  {
    id: 'falanghina-vinica',
    name: 'Falanghina Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 14,
    producers: ['Vinica'],
    aliases: ['Vinica Falanghina']
  },
  {
    id: 'falanghina-fattoria-del-duca',
    name: 'Falanghina Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 16,
    producers: ['Fattoria del Duca'],
    aliases: ['Fattoria del Duca Falanghina']
  },
  
  // GRECO (White variety)
  {
    id: 'greco-di-maio-norante',
    name: 'Greco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Greco',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 16,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Greco']
  },
  {
    id: 'greco-borgo-di-colloredo',
    name: 'Greco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Greco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Greco']
  },
  {
    id: 'greco-tenimenti-grieco',
    name: 'Greco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Greco',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 18,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Greco']
  },
  
  // FIANO (White variety)
  {
    id: 'fiano-di-maio-norante',
    name: 'Fiano Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Fiano',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Fiano']
  },
  {
    id: 'fiano-borgo-di-colloredo',
    name: 'Fiano Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Fiano',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 18,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Fiano']
  },
  {
    id: 'fiano-catabbo',
    name: 'Fiano Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Fiano',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 18,
    producers: ['Catabbo'],
    aliases: ['Catabbo Fiano']
  },
  
  // MONTEPULCIANO (Red variety - standalone)
  {
    id: 'montepulciano-di-maio-norante',
    name: 'Montepulciano Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Montepulciano']
  },
  {
    id: 'montepulciano-borgo-di-colloredo',
    name: 'Montepulciano Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Montepulciano']
  },
  {
    id: 'montepulciano-catabbo',
    name: 'Montepulciano Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 18,
    producers: ['Catabbo'],
    aliases: ['Catabbo Montepulciano']
  },
  {
    id: 'montepulciano-tenimenti-grieco',
    name: 'Montepulciano Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 18,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Montepulciano']
  },
  
  // AGLIANICO (Red variety - standalone)
  {
    id: 'aglianico-di-maio-norante-contado',
    name: 'Aglianico Contado Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Di Majo Norante'],
    aliases: ['Contado']
  },
  {
    id: 'aglianico-di-maio-norante',
    name: 'Aglianico Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 18,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Aglianico']
  },
  {
    id: 'aglianico-borgo-di-colloredo',
    name: 'Aglianico Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 20,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Aglianico']
  },
  {
    id: 'aglianico-claudio-cipressi',
    name: 'Aglianico Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Claudio Cipressi'],
    aliases: ['Cipressi Aglianico']
  },
  {
    id: 'aglianico-tenimenti-grieco',
    name: 'Aglianico Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 22,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Aglianico']
  },
  
  // INTERNATIONAL VARIETIES
  {
    id: 'cabernet-sauvignon-di-maio-norante',
    name: 'Cabernet Sauvignon Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Cabernet']
  },
  {
    id: 'merlot-di-maio-norante',
    name: 'Merlot Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Merlot']
  },
  {
    id: 'chardonnay-di-maio-norante',
    name: 'Chardonnay Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Chardonnay']
  },
  {
    id: 'sauvignon-blanc-di-maio-norante',
    name: 'Sauvignon Blanc Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Sauvignon']
  },
  {
    id: 'chardonnay-borgo-di-colloredo',
    name: 'Chardonnay Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 14,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Chardonnay']
  },
  
  // ROSÉ WINES
  {
    id: 'rosato-molise-di-maio-norante',
    name: 'Rosato Molise IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Tintilia',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Rosato IGT']
  },
  {
    id: 'rosato-molise-borgo-di-colloredo',
    name: 'Rosato Molise IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 13,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Rosato IGT']
  },
  {
    id: 'rosato-molise-catabbo',
    name: 'Rosato Molise IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Tintilia',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 14,
    producers: ['Catabbo'],
    aliases: ['Catabbo Rosato IGT']
  },
  {
    id: 'rosato-molise-cianfagna',
    name: 'Rosato Molise IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 14,
    producers: ['Cianfagna'],
    aliases: ['Cianfagna Rosato IGT']
  },
  {
    id: 'rosato-molise-tenimenti-grieco',
    name: 'Rosato Molise IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 14,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Rosato IGT']
  },
  {
    id: 'rosato-molise-vinica',
    name: 'Rosato Molise IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 13,
    producers: ['Vinica'],
    aliases: ['Vinica Rosato IGT']
  },
  
  // ADDITIONAL WHITE WINES
  {
    id: 'bianco-molise-di-maio-norante',
    name: 'Bianco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Trebbiano, Falanghina',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 12,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Bianco IGT']
  },
  {
    id: 'bianco-molise-borgo-di-colloredo',
    name: 'Bianco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Trebbiano, Greco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 12,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Bianco IGT']
  },
  {
    id: 'bianco-molise-catabbo',
    name: 'Bianco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Trebbiano, Falanghina',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 12,
    producers: ['Catabbo'],
    aliases: ['Catabbo Bianco IGT']
  },
  {
    id: 'bianco-molise-cianfagna',
    name: 'Bianco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina, Greco',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 13,
    producers: ['Cianfagna'],
    aliases: ['Cianfagna Bianco IGT']
  },
  {
    id: 'bianco-molise-tenimenti-grieco',
    name: 'Bianco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Greco, Falanghina',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 14,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Bianco IGT']
  },
  {
    id: 'bianco-molise-vinica',
    name: 'Bianco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 12,
    producers: ['Vinica'],
    aliases: ['Vinica Bianco IGT']
  },
  {
    id: 'bianco-molise-fattoria-del-duca',
    name: 'Bianco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina, Trebbiano',
    classification: 'IGT',
    minVintage: 2014,
    avgPrice: 13,
    producers: ['Fattoria del Duca'],
    aliases: ['Fattoria del Duca Bianco IGT']
  },
];
