import { WineTemplate } from '@/types/wineDatabase';

/**
 * VALLE D'AOSTA WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Additional producers, Premium cuvées, Traditional blends, Regional selections
 * Updated: January 2025
 */

export const valleDaostaPart3: WineTemplate[] = [
  // ADDITIONAL PREMIUM WINES
  {
    id: 'vda-les-cretes-chardonnay-prestige',
    name: 'Chardonnay Prestige Valle d\'Aosta DOC',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 35,
    producers: ['Les Cretes'],
    aliases: ['Chardonnay Prestige']
  },
  {
    id: 'vda-grosjean-vigne-tzeriat',
    name: 'Vigne Tzeriat Valle d\'Aosta DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 32,
    producers: ['Grosjean'],
    aliases: ['Vigne Tzeriat']
  },
  {
    id: 'vda-grosjean-vigne-merletta',
    name: 'Vigne Merletta Valle d\'Aosta DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Fumin',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 42,
    producers: ['Grosjean'],
    aliases: ['Vigne Merletta']
  },
  {
    id: 'vda-anselmet-premium-selection',
    name: 'Premium Selection Valle d\'Aosta DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Villeneuve',
    grapeVariety: 'Fumin, Petit Rouge',
    classification: 'DOC',
    minVintage: 2014,
    avgPrice: 45,
    producers: ['Anselmet'],
    aliases: ['Anselmet Premium']
  },
  {
    id: 'vda-di-barro-premium',
    name: 'Premium Selection Valle d\'Aosta DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Fumin, Cornalin',
    classification: 'DOC',
    minVintage: 2014,
    avgPrice: 40,
    producers: ['Di Barrò'],
    aliases: ['Di Barrò Premium']
  },
  
  // CHAMBAVE ROUGE (Red)
  {
    id: 'vda-chambave-rouge-grosjean',
    name: 'Valle d\'Aosta Chambave Rouge',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Grosjean'],
    aliases: ['Grosjean Chambave Rouge']
  },
  {
    id: 'vda-chambave-rouge-les-cretes',
    name: 'Valle d\'Aosta Chambave Rouge',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 24,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Chambave Rouge']
  },
  {
    id: 'vda-chambave-rouge-la-crotta-di-vegneron',
    name: 'Valle d\'Aosta Chambave Rouge',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['La Crotta di Vegneron'],
    aliases: ['La Crotta Chambave Rouge']
  },
  
  // NUS ROSSO (Red)
  {
    id: 'vda-nus-rosso-grosjean',
    name: 'Valle d\'Aosta Nus Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Nus',
    grapeVariety: 'Vien de Nus, Petit Rouge',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 24,
    producers: ['Grosjean'],
    aliases: ['Grosjean Nus Rosso']
  },
  {
    id: 'vda-nus-rosso-la-crotta-di-vegneron',
    name: 'Valle d\'Aosta Nus Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Nus',
    grapeVariety: 'Vien de Nus, Petit Rouge',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['La Crotta di Vegneron'],
    aliases: ['La Crotta Nus Rosso']
  },
  
  // VIEN DE NUS (Indigenous red)
  {
    id: 'vda-vien-de-nus-grosjean',
    name: 'Valle d\'Aosta Vien de Nus',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Nus',
    grapeVariety: 'Vien de Nus',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 28,
    producers: ['Grosjean'],
    aliases: ['Grosjean Vien de Nus']
  },
  {
    id: 'vda-vien-de-nus-la-crotta-di-vegneron',
    name: 'Valle d\'Aosta Vien de Nus',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Nus',
    grapeVariety: 'Vien de Nus',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 26,
    producers: ['La Crotta di Vegneron'],
    aliases: ['La Crotta Vien de Nus']
  },
  
  // ADDITIONAL WHITE WINES
  {
    id: 'vda-blanc-grosjean',
    name: 'Valle d\'Aosta Blanc',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Petite Arvine, Chardonnay',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 22,
    producers: ['Grosjean'],
    aliases: ['Grosjean Blanc']
  },
  {
    id: 'vda-blanc-les-cretes',
    name: 'Valle d\'Aosta Blanc',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Prié Blanc, Petite Arvine',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 20,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Blanc']
  },
  {
    id: 'vda-blanc-cave-des-onze-communes',
    name: 'Valle d\'Aosta Blanc',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Chardonnay, Pinot Gris',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 18,
    producers: ['Cave des Onze Communes'],
    aliases: ['Cave des Onze Communes Blanc']
  },
  
  // ADDITIONAL RED WINES
  {
    id: 'vda-rouge-grosjean',
    name: 'Valle d\'Aosta Rouge',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Petit Rouge, Fumin, Mayolet',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 20,
    producers: ['Grosjean'],
    aliases: ['Grosjean Rouge']
  },
  {
    id: 'vda-rouge-les-cretes',
    name: 'Valle d\'Aosta Rouge',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Petit Rouge, Fumin',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Rouge']
  },
  {
    id: 'vda-rouge-cave-des-onze-communes',
    name: 'Valle d\'Aosta Rouge',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Petit Rouge, Gamay',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Cave des Onze Communes'],
    aliases: ['Cave des Onze Communes Rouge']
  },
  {
    id: 'vda-rouge-anselmet',
    name: 'Valle d\'Aosta Rouge',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Villeneuve',
    grapeVariety: 'Petit Rouge, Fumin',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 22,
    producers: ['Anselmet'],
    aliases: ['Anselmet Rouge']
  },
  {
    id: 'vda-rouge-di-barro',
    name: 'Valle d\'Aosta Rouge',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Petit Rouge, Cornalin',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 20,
    producers: ['Di Barrò'],
    aliases: ['Di Barrò Rouge']
  },
  {
    id: 'vda-rouge-la-crotta-di-vegneron',
    name: 'Valle d\'Aosta Rouge',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Nus',
    grapeVariety: 'Petit Rouge, Vien de Nus',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['La Crotta di Vegneron'],
    aliases: ['La Crotta Rouge']
  },
  
  // ADDITIONAL PRODUCER SELECTIONS
  {
    id: 'vda-ermes-pavese-prie-blanc',
    name: 'Valle d\'Aosta Prié Blanc',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Morgex',
    grapeVariety: 'Prié Blanc',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 22,
    producers: ['Ermes Pavese'],
    aliases: ['Ermes Pavese Prié Blanc']
  },
  {
    id: 'vda-ermes-pavese-chardonnay',
    name: 'Valle d\'Aosta Chardonnay',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Morgex',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 20,
    producers: ['Ermes Pavese'],
    aliases: ['Ermes Pavese Chardonnay']
  },
  {
    id: 'vda-cave-cooperative-donnas-rouge',
    name: 'Valle d\'Aosta Rouge',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Donnas',
    grapeVariety: 'Nebbiolo, Freisa',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Cave Cooperative de Donnas'],
    aliases: ['Donnas Rouge']
  },
  
  // FREISA (Indigenous red)
  {
    id: 'vda-freisa-grosjean',
    name: 'Valle d\'Aosta Freisa',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Freisa',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 22,
    producers: ['Grosjean'],
    aliases: ['Grosjean Freisa']
  },
  {
    id: 'vda-freisa-cave-des-onze-communes',
    name: 'Valle d\'Aosta Freisa',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Freisa',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 20,
    producers: ['Cave des Onze Communes'],
    aliases: ['Cave des Onze Communes Freisa']
  },
  
  // ADDITIONAL DESSERT WINES
  {
    id: 'vda-petite-arvine-passito-les-cretes',
    name: 'Petite Arvine Passito Valle d\'Aosta DOC',
    type: 'Dessert',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Morgex',
    grapeVariety: 'Petite Arvine',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 55,
    producers: ['Les Cretes'],
    aliases: ['Petite Arvine Passito']
  },
  {
    id: 'vda-petite-arvine-passito-grosjean',
    name: 'Petite Arvine Passito Valle d\'Aosta DOC',
    type: 'Dessert',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Petite Arvine',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 52,
    producers: ['Grosjean'],
    aliases: ['Grosjean Petite Arvine Passito']
  },
  {
    id: 'vda-chambave-muscat-fletri-grosjean',
    name: 'Chambave Muscat Fletri Valle d\'Aosta DOC',
    type: 'Dessert',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Muscat Petit Grain',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 48,
    producers: ['Grosjean'],
    aliases: ['Chambave Muscat Fletri']
  },
  
  // ADDITIONAL SPARKLING WINES
  {
    id: 'vda-spumante-grosjean-brut',
    name: 'Valle d\'Aosta Spumante Brut',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 28,
    producers: ['Grosjean'],
    aliases: ['Grosjean Spumante']
  },
  {
    id: 'vda-spumante-cave-des-onze-communes-brut',
    name: 'Valle d\'Aosta Spumante Brut',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Chardonnay, Pinot Noir',
    classification: 'DOC',
    minVintage: 2014,
    avgPrice: 26,
    producers: ['Cave des Onze Communes'],
    aliases: ['Cave des Onze Communes Spumante']
  },
  
  // FINAL PREMIUM SELECTIONS
  {
    id: 'vda-les-cretes-vigne-la-tour',
    name: 'Vigne La Tour Valle d\'Aosta DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Fumin',
    classification: 'DOC',
    minVintage: 2014,
    avgPrice: 48,
    producers: ['Les Cretes'],
    aliases: ['Vigne La Tour']
  },
  {
    id: 'vda-grosjean-vigne-du-paradis',
    name: 'Vigne du Paradis Valle d\'Aosta DOC',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Petite Arvine',
    classification: 'DOC',
    minVintage: 2014,
    avgPrice: 45,
    producers: ['Grosjean'],
    aliases: ['Vigne du Paradis']
  },
  {
    id: 'vda-anselmet-grand-cuvee',
    name: 'Grand Cuvée Valle d\'Aosta DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Villeneuve',
    grapeVariety: 'Fumin, Cornalin, Petit Rouge',
    classification: 'DOC',
    minVintage: 2016,
    avgPrice: 52,
    producers: ['Anselmet'],
    aliases: ['Grand Cuvée']
  },
  {
    id: 'vda-di-barro-selezione-speciale',
    name: 'Selezione Speciale Valle d\'Aosta DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Fumin',
    classification: 'DOC',
    minVintage: 2016,
    avgPrice: 48,
    producers: ['Di Barrò'],
    aliases: ['Selezione Speciale']
  },
  {
    id: 'vda-la-crotta-di-vegneron-premium',
    name: 'Premium Selection Valle d\'Aosta DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Nus',
    grapeVariety: 'Vien de Nus, Fumin',
    classification: 'DOC',
    minVintage: 2016,
    avgPrice: 42,
    producers: ['La Crotta di Vegneron'],
    aliases: ['La Crotta Premium']
  },
  {
    id: 'vda-cave-du-vin-blanc-cuvee-prestige',
    name: 'Cuvée Prestige Blanc de Morgex et de La Salle',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Morgex',
    grapeVariety: 'Prié Blanc',
    classification: 'DOC',
    minVintage: 2016,
    avgPrice: 42,
    producers: ['Cave du Vin Blanc de Morgex et de La Salle'],
    aliases: ['Cuvée Prestige']
  },
  {
    id: 'vda-ermes-pavese-premium',
    name: 'Premium Selection Blanc de Morgex',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Morgex',
    grapeVariety: 'Prié Blanc',
    classification: 'DOC',
    minVintage: 2016,
    avgPrice: 38,
    producers: ['Ermes Pavese'],
    aliases: ['Ermes Pavese Premium']
  },
  {
    id: 'vda-cave-cooperative-donnas-riserva',
    name: 'Donnas Riserva Valle d\'Aosta DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Donnas',
    grapeVariety: 'Nebbiolo (Picotendro)',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 35,
    producers: ['Cave Cooperative de Donnas'],
    aliases: ['Donnas Riserva']
  },
  {
    id: 'vda-les-cretes-cuvee-speciale',
    name: 'Cuvée Spéciale Valle d\'Aosta DOC',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Petite Arvine, Chardonnay',
    classification: 'DOC',
    minVintage: 2018,
    avgPrice: 48,
    producers: ['Les Cretes'],
    aliases: ['Cuvée Spéciale']
  },
  {
    id: 'vda-grosjean-tradition',
    name: 'Tradition Valle d\'Aosta DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Petit Rouge, Mayolet, Cornalin',
    classification: 'DOC',
    minVintage: 2018,
    avgPrice: 45,
    producers: ['Grosjean'],
    aliases: ['Grosjean Tradition']
  },
];
