import { WineTemplate } from '@/types/wineDatabase';

/**
 * SICILY WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Marsala, Passito di Pantelleria, Malvasia
 * Updated: January 2025
 */

export const sicilyPart3: WineTemplate[] = [
  // MARSALA DOC (Fortified)
  {
    id: 'marsala-florio-terre-arse',
    name: 'Marsala Superiore Riserva Terre Arse',
    type: 'Fortified',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Marsala',
    grapeVariety: 'Grillo, Catarratto, Inzolia',
    classification: 'DOC',
    minVintage: 1833,
    avgPrice: 32,
    producers: ['Florio'],
    aliases: ['Terre Arse']
  },
  {
    id: 'marsala-florio-vecchioflorio',
    name: 'Marsala Superiore Vecchioflorio',
    type: 'Fortified',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Marsala',
    grapeVariety: 'Grillo, Catarratto',
    classification: 'DOC',
    minVintage: 1833,
    avgPrice: 18,
    producers: ['Florio'],
    aliases: ['Vecchioflorio']
  },
  {
    id: 'marsala-florio-vergine',
    name: 'Marsala Vergine',
    type: 'Fortified',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Marsala',
    grapeVariety: 'Grillo',
    classification: 'DOC',
    minVintage: 1833,
    avgPrice: 45,
    producers: ['Florio'],
    aliases: ['Florio Vergine']
  },
  {
    id: 'marsala-pellegrino-garibaldi-dolce',
    name: 'Marsala Superiore Garibaldi Dolce',
    type: 'Fortified',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Marsala',
    grapeVariety: 'Grillo, Catarratto',
    classification: 'DOC',
    minVintage: 1880,
    avgPrice: 16,
    producers: ['Carlo Pellegrino'],
    aliases: ['Garibaldi Dolce']
  },
  {
    id: 'marsala-pellegrino-rubino',
    name: 'Marsala Rubino Dolce',
    type: 'Fortified',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Marsala',
    grapeVariety: 'Nero d\'Avola, Nerello Mascalese',
    classification: 'DOC',
    minVintage: 1880,
    avgPrice: 18,
    producers: ['Carlo Pellegrino'],
    aliases: ['Rubino']
  },
  {
    id: 'marsala-de-bartoli-vecchio-samperi',
    name: 'Vecchio Samperi Perpetuo',
    type: 'Fortified',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Marsala',
    grapeVariety: 'Grillo',
    classification: 'Vino',
    minVintage: 1980,
    avgPrice: 55,
    producers: ['Marco De Bartoli'],
    aliases: ['Vecchio Samperi']
  },
  {
    id: 'marsala-de-bartoli-vigna-la-miccia',
    name: 'Marsala Superiore Vigna La Miccia',
    type: 'Fortified',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Marsala',
    grapeVariety: 'Grillo',
    classification: 'DOC',
    minVintage: 1986,
    avgPrice: 65,
    producers: ['Marco De Bartoli'],
    aliases: ['Vigna La Miccia']
  },
  {
    id: 'marsala-de-bartoli-ventennale',
    name: 'Marsala Superiore Riserva 20 Anni',
    type: 'Fortified',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Marsala',
    grapeVariety: 'Grillo',
    classification: 'DOC',
    minVintage: 1986,
    avgPrice: 95,
    producers: ['Marco De Bartoli'],
    aliases: ['Ventennale']
  },
  {
    id: 'marsala-martinez',
    name: 'Marsala Superiore',
    type: 'Fortified',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Marsala',
    grapeVariety: 'Grillo, Catarratto',
    classification: 'DOC',
    minVintage: 1850,
    avgPrice: 22,
    producers: ['Martinez'],
    aliases: ['Martinez Marsala']
  },
  
  // PASSITO DI PANTELLERIA DOC (Dessert)
  {
    id: 'passito-pantelleria-donnafugata-ben-rye',
    name: 'Ben Ryé Passito di Pantelleria',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Pantelleria',
    grapeVariety: 'Zibibbo (Moscato d\'Alessandria)',
    classification: 'DOC',
    minVintage: 1989,
    avgPrice: 45,
    producers: ['Donnafugata'],
    aliases: ['Ben Ryé']
  },
  {
    id: 'passito-pantelleria-de-bartoli-bukkuram',
    name: 'Bukkuram Passito di Pantelleria',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Pantelleria',
    grapeVariety: 'Zibibbo',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 52,
    producers: ['Marco De Bartoli'],
    aliases: ['Bukkuram']
  },
  {
    id: 'passito-pantelleria-pellegrino',
    name: 'Passito di Pantelleria',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Pantelleria',
    grapeVariety: 'Zibibbo',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 32,
    producers: ['Carlo Pellegrino'],
    aliases: ['Pellegrino Passito']
  },
  {
    id: 'passito-pantelleria-salvatore-murana',
    name: 'Passito di Pantelleria Mueggen',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Pantelleria',
    grapeVariety: 'Zibibbo',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 42,
    producers: ['Salvatore Murana'],
    aliases: ['Mueggen']
  },
  {
    id: 'passito-pantelleria-murana-martingana',
    name: 'Passito di Pantelleria Martingana',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Pantelleria',
    grapeVariety: 'Zibibbo',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 65,
    producers: ['Salvatore Murana'],
    aliases: ['Martingana']
  },
  
  // MOSCATO DI NOTO DOC (Dessert/Sparkling)
  {
    id: 'moscato-noto-planeta',
    name: 'Moscato di Noto',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Noto',
    grapeVariety: 'Moscato Bianco',
    classification: 'DOC',
    minVintage: 2002,
    avgPrice: 28,
    producers: ['Planeta'],
    aliases: ['Planeta Moscato']
  },
  
  // MALVASIA DELLE LIPARI DOC (Dessert)
  {
    id: 'malvasia-lipari-hauner',
    name: 'Malvasia delle Lipari Passito',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Lipari',
    grapeVariety: 'Malvasia',
    classification: 'DOC',
    minVintage: 1963,
    avgPrice: 48,
    producers: ['Hauner'],
    aliases: ['Hauner Malvasia']
  },
  {
    id: 'malvasia-lipari-hauner-naturale',
    name: 'Malvasia delle Lipari Naturale',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Lipari',
    grapeVariety: 'Malvasia',
    classification: 'DOC',
    minVintage: 1963,
    avgPrice: 28,
    producers: ['Hauner'],
    aliases: ['Malvasia Naturale']
  },
  {
    id: 'malvasia-lipari-fenech',
    name: 'Malvasia delle Lipari',
    type: 'Dessert',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Lipari',
    grapeVariety: 'Malvasia',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 38,
    producers: ['Fenech'],
    aliases: ['Fenech Malvasia']
  },
  
  // ADDITIONAL SICILIAN WINES
  {
    id: 'sicily-donnafugata-sul-vulcano',
    name: 'Sul Vulcano Etna Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2011,
    avgPrice: 32,
    producers: ['Donnafugata'],
    aliases: ['Sul Vulcano']
  },
  {
    id: 'sicily-donnafugata-fragore',
    name: 'Fragore Etna Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2015,
    avgPrice: 45,
    producers: ['Donnafugata'],
    aliases: ['Fragore']
  },
  {
    id: 'sicily-tasca-cygnus',
    name: 'Cygnus Sicilia IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Regaleali',
    grapeVariety: 'Inzolia, Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 2007,
    avgPrice: 22,
    producers: ['Tasca d\'Almerita'],
    aliases: ['Cygnus']
  },
  {
    id: 'sicily-tasca-cavallo-pazze',
    name: 'Cavallo delle Fate Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Regaleali',
    grapeVariety: 'Nero d\'Avola, Cabernet Franc',
    classification: 'IGT',
    minVintage: 2007,
    avgPrice: 65,
    producers: ['Tasca d\'Almerita'],
    aliases: ['Cavallo delle Fate']
  },
  {
    id: 'sicily-planeta-alastro',
    name: 'Alastro Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Menfi',
    grapeVariety: 'Grecanico',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 16,
    producers: ['Planeta'],
    aliases: ['Alastro']
  },
  {
    id: 'sicily-planeta-didacus',
    name: 'Didacus Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Sambuca di Sicilia',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 2002,
    avgPrice: 45,
    producers: ['Planeta'],
    aliases: ['Didacus']
  },
  {
    id: 'sicily-planeta-burdese',
    name: 'Burdese Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Menfi',
    grapeVariety: 'Cabernet Sauvignon, Cabernet Franc, Petit Verdot',
    classification: 'IGT',
    minVintage: 2002,
    avgPrice: 52,
    producers: ['Planeta'],
    aliases: ['Burdese']
  },
  {
    id: 'sicily-cusumano-jalé',
    name: 'Jalé Sicilia IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Ficuzza',
    grapeVariety: 'Inzolia',
    classification: 'IGT',
    minVintage: 2006,
    avgPrice: 18,
    producers: ['Cusumano'],
    aliases: ['Jalé']
  },
  {
    id: 'sicily-firriato-santagostino',
    name: 'Santagostino Rosso Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Trapani',
    grapeVariety: 'Nero d\'Avola',
    classification: 'IGT',
    minVintage: 1999,
    avgPrice: 28,
    producers: ['Firriato'],
    aliases: ['Santagostino']
  },
  {
    id: 'sicily-firriato-ribeca',
    name: 'Ribeca Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Trapani',
    grapeVariety: 'Perricone',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 38,
    producers: ['Firriato'],
    aliases: ['Ribeca']
  },
  {
    id: 'sicily-benanti-bianco-di-caselle',
    name: 'Bianco di Caselle Etna Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Carricante',
    classification: 'DOC',
    minVintage: 2002,
    avgPrice: 28,
    producers: ['Benanti'],
    aliases: ['Bianco di Caselle']
  },
  {
    id: 'sicily-benanti-nerello-cappuccio',
    name: 'Etna Rosso Nerello Cappuccio',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Cappuccio',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Benanti'],
    aliases: ['Nerello Cappuccio']
  },
  {
    id: 'sicily-cos-rami',
    name: 'Rami Terre Siciliane IGP',
    type: 'Orange',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Grecanico',
    classification: 'IGP',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['COS'],
    aliases: ['Rami']
  },
  {
    id: 'sicily-occhipinti-sp68-bianco',
    name: 'SP68 Bianco Sicilia IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Albanello, Moscato',
    classification: 'IGT',
    minVintage: 2004,
    avgPrice: 28,
    producers: ['Arianna Occhipinti'],
    aliases: ['SP68 Bianco']
  },
  {
    id: 'sicily-frank-cornelissen-susucaru',
    name: 'Susucaru Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese, Nerello Cappuccio',
    classification: 'Vino',
    minVintage: 2005,
    avgPrice: 55,
    producers: ['Frank Cornelissen'],
    aliases: ['Susucaru']
  },
  {
    id: 'sicily-frank-cornelissen-munjebel-va',
    name: 'Munjebel VA Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'Vino',
    minVintage: 2010,
    avgPrice: 180,
    producers: ['Frank Cornelissen'],
    aliases: ['Munjebel VA']
  },
  {
    id: 'sicily-graci-quota-600',
    name: 'Etna Rosso Quota 600',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 42,
    producers: ['Graci'],
    aliases: ['Quota 600']
  },
  {
    id: 'sicily-girolamo-russo-nerina',
    name: 'Etna Bianco Nerina',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Carricante',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 38,
    producers: ['Girolamo Russo'],
    aliases: ['Nerina']
  },
  {
    id: 'sicily-pietradolce-archineri',
    name: 'Etna Rosso Archineri',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 65,
    producers: ['Pietradolce'],
    aliases: ['Archineri']
  },
  {
    id: 'sicily-tenuta-delle-terre-nere-calderara',
    name: 'Etna Rosso Calderara Sottana',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 65,
    producers: ['Tenuta delle Terre Nere'],
    aliases: ['Calderara Sottana']
  },
  {
    id: 'sicily-cottanera-diciassettesalme',
    name: 'Diciassettesalme Etna Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 55,
    producers: ['Cottanera'],
    aliases: ['Diciassettesalme']
  },
  {
    id: 'sicily-donnafugata-floramundi',
    name: 'Floramundi Cerasuolo di Vittoria',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Nero d\'Avola, Frappato',
    classification: 'DOCG',
    minVintage: 2016,
    avgPrice: 26,
    producers: ['Donnafugata'],
    aliases: ['Floramundi']
  },
  {
    id: 'sicily-gulfi-carjcanti',
    name: 'Carjcanti Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Chiaramonte Gulfi',
    grapeVariety: 'Nero d\'Avola, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 55,
    producers: ['Gulfi'],
    aliases: ['Carjcanti']
  },
  {
    id: 'sicily-valle-acate-bidis',
    name: 'Bidis Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Frappato',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Valle dell\'Acate'],
    aliases: ['Bidis']
  },
  {
    id: 'sicily-feudo-maccari-maharis',
    name: 'Maharis Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Noto',
    grapeVariety: 'Nero d\'Avola, Syrah',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Feudo Maccari'],
    aliases: ['Maharis']
  },
];
