import { WineTemplate } from '@/types/wineDatabase';

/**
 * BORDEAUX LEFT BANK - Part 5 of 6 (Wines 101-125)
 * Focus: Additional Cru Bourgeois across all Left Bank appellations
 * Updated: January 2025
 */

export const bordeauxLeftBankPart5: WineTemplate[] = [
  // HAUT-MÉDOC - CRU BOURGEOIS (continued)
  {
    id: 'bordeaux-chateau-coufran',
    name: 'Château Coufran',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1924,
    avgPrice: 35,
    producers: ['Château Coufran'],
    aliases: ['Coufran']
  },
  {
    id: 'bordeaux-chateau-arnauld',
    name: 'Château Arnauld',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1958,
    avgPrice: 28,
    producers: ['Château Arnauld'],
    aliases: ['Arnauld']
  },
  {
    id: 'bordeaux-chateau-bernadotte',
    name: 'Château Bernadotte',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1972,
    avgPrice: 38,
    producers: ['Château Bernadotte'],
    aliases: ['Bernadotte']
  },
  {
    id: 'bordeaux-chateau-caronne-ste-gemme',
    name: 'Château Caronne-Ste-Gemme',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1850,
    avgPrice: 42,
    producers: ['Château Caronne-Ste-Gemme'],
    aliases: ['Caronne-Ste-Gemme']
  },
  {
    id: 'bordeaux-chateau-lamothe-bergeron',
    name: 'Château Lamothe-Bergeron',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1850,
    avgPrice: 30,
    producers: ['Château Lamothe-Bergeron'],
    aliases: ['Lamothe-Bergeron']
  },
  {
    id: 'bordeaux-chateau-de-malleret',
    name: 'Château de Malleret',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1850,
    avgPrice: 32,
    producers: ['Château de Malleret'],
    aliases: ['de Malleret', 'Malleret']
  },
  {
    id: 'bordeaux-chateau-ramage-la-batisse',
    name: 'Château Ramage la Batisse',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1961,
    avgPrice: 28,
    producers: ['Château Ramage la Batisse'],
    aliases: ['Ramage la Batisse']
  },
  
  // MOULIS-EN-MÉDOC
  {
    id: 'bordeaux-chateau-branas-grand-poujeaux',
    name: 'Château Branas Grand Poujeaux',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Moulis-en-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1850,
    avgPrice: 32,
    producers: ['Château Branas Grand Poujeaux'],
    aliases: ['Branas Grand Poujeaux']
  },
  {
    id: 'bordeaux-chateau-brillette',
    name: 'Château Brillette',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Moulis-en-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1975,
    avgPrice: 35,
    producers: ['Château Brillette'],
    aliases: ['Brillette']
  },
  {
    id: 'bordeaux-chateau-duplessis',
    name: 'Château Duplessis',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Moulis-en-Médoc',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1850,
    avgPrice: 34,
    producers: ['Château Duplessis'],
    aliases: ['Duplessis']
  },
  {
    id: 'bordeaux-chateau-anthonic',
    name: 'Château Anthonic',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Moulis-en-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1922,
    avgPrice: 30,
    producers: ['Château Anthonic'],
    aliases: ['Anthonic']
  },
  
  // LISTRAC-MÉDOC (continued)
  {
    id: 'bordeaux-chateau-cap-leon-veyrin',
    name: 'Château Cap Léon Veyrin',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Listrac-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: 'Cru Bourgeois',
    minVintage: 1810,
    avgPrice: 28,
    producers: ['Château Cap Léon Veyrin'],
    aliases: ['Cap Léon Veyrin']
  },
  {
    id: 'bordeaux-chateau-reverdi',
    name: 'Château Reverdi',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Listrac-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1850,
    avgPrice: 26,
    producers: ['Château Reverdi'],
    aliases: ['Reverdi']
  },
  {
    id: 'bordeaux-chateau-lestage-listrac',
    name: 'Château Lestage',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Listrac-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1870,
    avgPrice: 28,
    producers: ['Château Lestage'],
    aliases: ['Lestage Listrac']
  },
  
  // MÉDOC - CRU BOURGEOIS (continued)
  {
    id: 'bordeaux-chateau-tour-haut-caussan',
    name: 'Château Tour Haut-Caussan',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1877,
    avgPrice: 32,
    producers: ['Château Tour Haut-Caussan'],
    aliases: ['Tour Haut-Caussan']
  },
  {
    id: 'bordeaux-chateau-rollan-de-by',
    name: 'Château Rollan de By',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1989,
    avgPrice: 35,
    producers: ['Château Rollan de By'],
    aliases: ['Rollan de By']
  },
  {
    id: 'bordeaux-chateau-la-cardonne',
    name: 'Château La Cardonne',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1973,
    avgPrice: 24,
    producers: ['Château La Cardonne'],
    aliases: ['La Cardonne']
  },
  {
    id: 'bordeaux-chateau-patache-d-aux',
    name: 'Château Patache d\'Aux',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1632,
    avgPrice: 30,
    producers: ['Château Patache d\'Aux'],
    aliases: ['Patache d\'Aux']
  },
  {
    id: 'bordeaux-chateau-les-ormes-sorbet',
    name: 'Château Les Ormes Sorbet',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1850,
    avgPrice: 26,
    producers: ['Château Les Ormes Sorbet'],
    aliases: ['Les Ormes Sorbet']
  },
  {
    id: 'bordeaux-chateau-laujac',
    name: 'Château Laujac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1852,
    avgPrice: 22,
    producers: ['Château Laujac'],
    aliases: ['Laujac']
  },
  {
    id: 'bordeaux-chateau-lousteauneuf',
    name: 'Château Lousteauneuf',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1862,
    avgPrice: 24,
    producers: ['Château Lousteauneuf'],
    aliases: ['Lousteauneuf']
  },
  {
    id: 'bordeaux-chateau-preuillac',
    name: 'Château Preuillac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1998,
    avgPrice: 26,
    producers: ['Château Preuillac'],
    aliases: ['Preuillac']
  },
  {
    id: 'bordeaux-chateau-ramafort',
    name: 'Château Ramafort',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1850,
    avgPrice: 22,
    producers: ['Château Ramafort'],
    aliases: ['Ramafort']
  },
  {
    id: 'bordeaux-chateau-vieux-robin',
    name: 'Château Vieux Robin',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1856,
    avgPrice: 24,
    producers: ['Château Vieux Robin'],
    aliases: ['Vieux Robin']
  },
];
