import { WineTemplate } from '@/types/wineDatabase';

/**
 * BORDEAUX RIGHT BANK - Part 2 of 6 (Wines 26-50)
 * Focus: Saint-Émilion Grand Cru Classé, Additional Pomerol estates
 * Updated: January 2025
 */

export const bordeauxRightBankPart2: WineTemplate[] = [
  // SAINT-ÉMILION - PREMIER GRAND CRU CLASSÉ B (continued)
  {
    id: 'bordeaux-clos-fourtet',
    name: 'Clos Fourtet',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'Premier Grand Cru Classé B',
    minVintage: 1880,
    avgPrice: 160,
    producers: ['Clos Fourtet'],
    aliases: ['Fourtet']
  },
  {
    id: 'bordeaux-chateau-la-mondotte',
    name: 'Château La Mondotte',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Premier Grand Cru Classé B',
    minVintage: 1996,
    avgPrice: 320,
    producers: ['Château La Mondotte'],
    aliases: ['La Mondotte']
  },
  
  // SAINT-ÉMILION - GRAND CRU CLASSÉ
  {
    id: 'bordeaux-chateau-la-dominique',
    name: 'Château La Dominique',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Grand Cru Classé',
    minVintage: 1855,
    avgPrice: 85,
    producers: ['Château La Dominique'],
    aliases: ['La Dominique']
  },
  {
    id: 'bordeaux-chateau-bellevue',
    name: 'Château Bellevue',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Grand Cru Classé',
    minVintage: 1850,
    avgPrice: 110,
    producers: ['Château Bellevue'],
    aliases: ['Bellevue Saint-Émilion']
  },
  {
    id: 'bordeaux-chateau-tertre-roteboeuf',
    name: 'Château Le Tertre Roteboeuf',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Grand Cru',
    minVintage: 1978,
    avgPrice: 220,
    producers: ['Château Le Tertre Roteboeuf'],
    aliases: ['Tertre Roteboeuf']
  },
  {
    id: 'bordeaux-chateau-faugeres',
    name: 'Château Faugères',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Grand Cru Classé',
    minVintage: 1823,
    avgPrice: 75,
    producers: ['Château Faugères'],
    aliases: ['Faugères']
  },
  {
    id: 'bordeaux-chateau-de-pressac',
    name: 'Château de Pressac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon, Malbec',
    classification: 'Grand Cru Classé',
    minVintage: 1453,
    avgPrice: 70,
    producers: ['Château de Pressac'],
    aliases: ['de Pressac']
  },
  {
    id: 'bordeaux-chateau-fleur-cardinale',
    name: 'Château Fleur Cardinale',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Grand Cru Classé',
    minVintage: 2001,
    avgPrice: 80,
    producers: ['Château Fleur Cardinale'],
    aliases: ['Fleur Cardinale']
  },
  {
    id: 'bordeaux-chateau-grand-corbin-despagne',
    name: 'Château Grand Corbin-Despagne',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Grand Cru Classé',
    minVintage: 1812,
    avgPrice: 75,
    producers: ['Château Grand Corbin-Despagne'],
    aliases: ['Grand Corbin-Despagne']
  },
  {
    id: 'bordeaux-chateau-larmande',
    name: 'Château Larmande',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Grand Cru Classé',
    minVintage: 1860,
    avgPrice: 70,
    producers: ['Château Larmande'],
    aliases: ['Larmande']
  },
  {
    id: 'bordeaux-chateau-la-serre',
    name: 'Château La Serre',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Grand Cru Classé',
    minVintage: 1850,
    avgPrice: 75,
    producers: ['Château La Serre'],
    aliases: ['La Serre']
  },
  {
    id: 'bordeaux-chateau-monbousquet',
    name: 'Château Monbousquet',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Grand Cru Classé',
    minVintage: 1540,
    avgPrice: 90,
    producers: ['Château Monbousquet'],
    aliases: ['Monbousquet']
  },
  {
    id: 'bordeaux-chateau-moulin-du-cadet',
    name: 'Château Moulin du Cadet',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Grand Cru Classé',
    minVintage: 1850,
    avgPrice: 65,
    producers: ['Château Moulin du Cadet'],
    aliases: ['Moulin du Cadet']
  },
  {
    id: 'bordeaux-chateau-non-plus-ultra',
    name: 'Château Non Plus Ultra',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Grand Cru',
    minVintage: 1990,
    avgPrice: 110,
    producers: ['Château Non Plus Ultra'],
    aliases: ['Non Plus Ultra']
  },
  
  // POMEROL - ADDITIONAL ESTATES
  {
    id: 'bordeaux-chateau-gazin',
    name: 'Château Gazin',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1772,
    avgPrice: 120,
    producers: ['Château Gazin'],
    aliases: ['Gazin']
  },
  {
    id: 'bordeaux-chateau-nenin',
    name: 'Château Nenin',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1847,
    avgPrice: 95,
    producers: ['Château Nenin'],
    aliases: ['Nenin']
  },
  {
    id: 'bordeaux-chateau-petit-village',
    name: 'Château Petit-Village',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1785,
    avgPrice: 140,
    producers: ['Château Petit-Village'],
    aliases: ['Petit-Village']
  },
  {
    id: 'bordeaux-chateau-la-pointe',
    name: 'Château La Pointe',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1868,
    avgPrice: 85,
    producers: ['Château La Pointe'],
    aliases: ['La Pointe']
  },
  {
    id: 'bordeaux-chateau-beauregard',
    name: 'Château Beauregard',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1794,
    avgPrice: 80,
    producers: ['Château Beauregard'],
    aliases: ['Beauregard Pomerol']
  },
  {
    id: 'bordeaux-chateau-bon-pasteur',
    name: 'Château Le Bon Pasteur',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1920,
    avgPrice: 90,
    producers: ['Château Le Bon Pasteur'],
    aliases: ['Le Bon Pasteur']
  },
  {
    id: 'bordeaux-chateau-la-croix-de-gay',
    name: 'Château La Croix de Gay',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Pomerol',
    minVintage: 1850,
    avgPrice: 75,
    producers: ['Château La Croix de Gay'],
    aliases: ['La Croix de Gay']
  },
  {
    id: 'bordeaux-chateau-la-grave-trigant-de-boisset',
    name: 'Château La Grave à Pomerol',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1850,
    avgPrice: 75,
    producers: ['Château La Grave'],
    aliases: ['La Grave à Pomerol']
  },
  {
    id: 'bordeaux-chateau-feytit-clinet',
    name: 'Château Feytit-Clinet',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1850,
    avgPrice: 95,
    producers: ['Château Feytit-Clinet'],
    aliases: ['Feytit-Clinet']
  },
  {
    id: 'bordeaux-chateau-hosanna',
    name: 'Château Hosanna',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1999,
    avgPrice: 180,
    producers: ['Château Hosanna'],
    aliases: ['Hosanna']
  },
  {
    id: 'bordeaux-chateau-latour-a-pomerol',
    name: 'Château Latour à Pomerol',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1917,
    avgPrice: 140,
    producers: ['Château Latour à Pomerol'],
    aliases: ['Latour à Pomerol']
  },
];
