import { WineTemplate } from '@/types/wineDatabase';

/**
 * BORDEAUX LEFT BANK - Part 4 of 6 (Wines 76-100)
 * Focus: Premium Cru Bourgeois, Second Wines of First Growths
 * Updated: January 2025
 */

export const bordeauxLeftBankPart4: WineTemplate[] = [
  // SECOND WINES OF FIRST GROWTHS
  {
    id: 'bordeaux-carruades-de-lafite',
    name: 'Carruades de Lafite',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Second Vin',
    minVintage: 1974,
    avgPrice: 220,
    producers: ['Château Lafite Rothschild'],
    aliases: ['Carruades']
  },
  {
    id: 'bordeaux-les-forts-de-latour',
    name: 'Les Forts de Latour',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Second Vin',
    minVintage: 1966,
    avgPrice: 250,
    producers: ['Château Latour'],
    aliases: ['Forts de Latour']
  },
  {
    id: 'bordeaux-le-petit-mouton',
    name: 'Le Petit Mouton de Mouton Rothschild',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Second Vin',
    minVintage: 1993,
    avgPrice: 180,
    producers: ['Château Mouton Rothschild'],
    aliases: ['Petit Mouton']
  },
  {
    id: 'bordeaux-pavillon-rouge',
    name: 'Pavillon Rouge du Château Margaux',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot, Cabernet Franc',
    classification: 'Second Vin',
    minVintage: 1908,
    avgPrice: 200,
    producers: ['Château Margaux'],
    aliases: ['Pavillon Rouge']
  },
  
  // SECOND WINES OF SUPER SECONDS
  {
    id: 'bordeaux-reserve-de-la-comtesse',
    name: 'Réserve de la Comtesse',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Second Vin',
    minVintage: 1973,
    avgPrice: 70,
    producers: ['Château Pichon Lalande'],
    aliases: ['Réserve Comtesse']
  },
  {
    id: 'bordeaux-les-tourelles-de-longueville',
    name: 'Les Tourelles de Longueville',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Second Vin',
    minVintage: 1986,
    avgPrice: 65,
    producers: ['Château Pichon Baron'],
    aliases: ['Tourelles de Longueville']
  },
  {
    id: 'bordeaux-le-petit-lion',
    name: 'Le Petit Lion du Marquis de Las Cases',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Julien',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: 'Second Vin',
    minVintage: 2007,
    avgPrice: 85,
    producers: ['Château Léoville Las Cases'],
    aliases: ['Petit Lion']
  },
  {
    id: 'bordeaux-clos-du-marquis',
    name: 'Clos du Marquis',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Julien',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Second Vin',
    minVintage: 1902,
    avgPrice: 90,
    producers: ['Château Léoville Las Cases'],
    aliases: ['Clos Marquis']
  },
  {
    id: 'bordeaux-la-dame-de-montrose',
    name: 'La Dame de Montrose',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Second Vin',
    minVintage: 1986,
    avgPrice: 70,
    producers: ['Château Montrose'],
    aliases: ['Dame de Montrose']
  },
  {
    id: 'bordeaux-les-pagodes-de-cos',
    name: 'Les Pagodes de Cos',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Second Vin',
    minVintage: 1994,
    avgPrice: 75,
    producers: ['Château Cos d\'Estournel'],
    aliases: ['Pagodes de Cos']
  },
  {
    id: 'bordeaux-echo-de-lynch-bages',
    name: 'Echo de Lynch-Bages',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Second Vin',
    minVintage: 2008,
    avgPrice: 55,
    producers: ['Château Lynch-Bages'],
    aliases: ['Echo Lynch-Bages']
  },
  {
    id: 'bordeaux-alter-ego-de-palmer',
    name: 'Alter Ego de Palmer',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot',
    classification: 'Second Vin',
    minVintage: 1998,
    avgPrice: 95,
    producers: ['Château Palmer'],
    aliases: ['Alter Ego']
  },
  
  // PREMIUM CRU BOURGEOIS - PAUILLAC
  {
    id: 'bordeaux-chateau-pibran',
    name: 'Château Pibran',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1880,
    avgPrice: 42,
    producers: ['Château Pibran'],
    aliases: ['Pibran']
  },
  {
    id: 'bordeaux-chateau-haut-bages-liberal',
    name: 'Château Haut-Bages Libéral',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 68,
    producers: ['Château Haut-Bages Libéral'],
    aliases: ['Haut-Bages Libéral']
  },
  {
    id: 'bordeaux-chateau-grand-puy-ducasse',
    name: 'Château Grand-Puy Ducasse',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 62,
    producers: ['Château Grand-Puy Ducasse'],
    aliases: ['Grand-Puy Ducasse']
  },
  {
    id: 'bordeaux-chateau-lynch-moussas',
    name: 'Château Lynch-Moussas',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 58,
    producers: ['Château Lynch-Moussas'],
    aliases: ['Lynch-Moussas']
  },
  
  // PREMIUM CRU BOURGEOIS - MARGAUX
  {
    id: 'bordeaux-chateau-siran',
    name: 'Château Siran',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot, Cabernet Franc',
    classification: 'Cru Bourgeois Exceptionnel',
    minVintage: 1428,
    avgPrice: 48,
    producers: ['Château Siran'],
    aliases: ['Siran']
  },
  {
    id: 'bordeaux-chateau-labégorce',
    name: 'Château Labégorce',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1865,
    avgPrice: 42,
    producers: ['Château Labégorce'],
    aliases: ['Labégorce']
  },
  {
    id: 'bordeaux-chateau-mongravey',
    name: 'Château Mongravey',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1970,
    avgPrice: 38,
    producers: ['Château Mongravey'],
    aliases: ['Mongravey']
  },
  {
    id: 'bordeaux-chateau-deyrem-valentin',
    name: 'Château Deyrem Valentin',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1850,
    avgPrice: 35,
    producers: ['Château Deyrem Valentin'],
    aliases: ['Deyrem Valentin']
  },
  
  // PREMIUM CRU BOURGEOIS - SAINT-JULIEN
  {
    id: 'bordeaux-chateau-gloria',
    name: 'Château Gloria',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Julien',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Exceptionnel',
    minVintage: 1942,
    avgPrice: 52,
    producers: ['Château Gloria'],
    aliases: ['Gloria']
  },
  {
    id: 'bordeaux-chateau-du-glana',
    name: 'Château du Glana',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Julien',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1961,
    avgPrice: 40,
    producers: ['Château du Glana'],
    aliases: ['du Glana']
  },
  {
    id: 'bordeaux-chateau-lalande-borie',
    name: 'Château Lalande-Borie',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Julien',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 1970,
    avgPrice: 38,
    producers: ['Château Lalande-Borie'],
    aliases: ['Lalande-Borie']
  },
  
  // PREMIUM CRU BOURGEOIS - HAUT-MÉDOC
  {
    id: 'bordeaux-chateau-beaumont',
    name: 'Château Beaumont',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1824,
    avgPrice: 32,
    producers: ['Château Beaumont'],
    aliases: ['Beaumont']
  },
  {
    id: 'bordeaux-chateau-d-agassac',
    name: 'Château d\'Agassac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois Exceptionnel',
    minVintage: 1289,
    avgPrice: 40,
    producers: ['Château d\'Agassac'],
    aliases: ['d\'Agassac']
  },
];
