import { WineTemplate } from '@/types/wineDatabase';

/**
 * BORDEAUX LEFT BANK - Part 3 of 6 (Wines 51-75)
 * Focus: Saint-Estèphe Cru Classés, Haut-Médoc
 * Updated: January 2025
 */

export const bordeauxLeftBankPart3: WineTemplate[] = [
  // SAINT-ESTÈPHE - THIRD TO FIFTH GROWTHS
  {
    id: 'bordeaux-chateau-calon-segur',
    name: 'Château Calon-Ségur',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '3ème Cru Classé',
    minVintage: 1855,
    avgPrice: 130,
    producers: ['Château Calon-Ségur'],
    aliases: ['Calon-Ségur']
  },
  {
    id: 'bordeaux-chateau-lafon-rochet',
    name: 'Château Lafon-Rochet',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '4ème Cru Classé',
    minVintage: 1855,
    avgPrice: 65,
    producers: ['Château Lafon-Rochet'],
    aliases: ['Lafon-Rochet']
  },
  {
    id: 'bordeaux-chateau-cos-labory',
    name: 'Château Cos Labory',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 55,
    producers: ['Château Cos Labory'],
    aliases: ['Cos Labory']
  },
  {
    id: 'bordeaux-chateau-phélan-ségur',
    name: 'Château Phélan Ségur',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Exceptionnel',
    minVintage: 1810,
    avgPrice: 50,
    producers: ['Château Phélan Ségur'],
    aliases: ['Phélan Ségur']
  },
  {
    id: 'bordeaux-chateau-de-pez',
    name: 'Château de Pez',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Exceptionnel',
    minVintage: 1452,
    avgPrice: 45,
    producers: ['Château de Pez'],
    aliases: ['de Pez']
  },
  {
    id: 'bordeaux-chateau-meyney',
    name: 'Château Meyney',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1662,
    avgPrice: 40,
    producers: ['Château Meyney'],
    aliases: ['Meyney']
  },
  {
    id: 'bordeaux-chateau-ormes-de-pez',
    name: 'Château Les Ormes de Pez',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1800,
    avgPrice: 42,
    producers: ['Château Les Ormes de Pez'],
    aliases: ['Les Ormes de Pez', 'Ormes de Pez']
  },
  {
    id: 'bordeaux-chateau-haut-marbuzet',
    name: 'Château Haut-Marbuzet',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois Exceptionnel',
    minVintage: 1952,
    avgPrice: 55,
    producers: ['Château Haut-Marbuzet'],
    aliases: ['Haut-Marbuzet']
  },
  {
    id: 'bordeaux-chateau-lilian-ladouys',
    name: 'Château Lilian Ladouys',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Estèphe',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot, Cabernet Franc',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1564,
    avgPrice: 35,
    producers: ['Château Lilian Ladouys'],
    aliases: ['Lilian Ladouys']
  },
  
  // HAUT-MÉDOC - CRU CLASSÉS
  {
    id: 'bordeaux-chateau-la-lagune',
    name: 'Château La Lagune',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot',
    classification: '3ème Cru Classé',
    minVintage: 1855,
    avgPrice: 75,
    producers: ['Château La Lagune'],
    aliases: ['La Lagune']
  },
  {
    id: 'bordeaux-chateau-la-tour-carnet',
    name: 'Château La Tour Carnet',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '4ème Cru Classé',
    minVintage: 1855,
    avgPrice: 55,
    producers: ['Château La Tour Carnet'],
    aliases: ['La Tour Carnet']
  },
  {
    id: 'bordeaux-chateau-belgrave',
    name: 'Château Belgrave',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 45,
    producers: ['Château Belgrave'],
    aliases: ['Belgrave']
  },
  {
    id: 'bordeaux-chateau-de-camensac',
    name: 'Château de Camensac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 42,
    producers: ['Château de Camensac'],
    aliases: ['de Camensac', 'Camensac']
  },
  {
    id: 'bordeaux-chateau-cantemerle',
    name: 'Château Cantemerle',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 50,
    producers: ['Château Cantemerle'],
    aliases: ['Cantemerle']
  },
  {
    id: 'bordeaux-chateau-sociando-mallet',
    name: 'Château Sociando-Mallet',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Haut-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois Exceptionnel',
    minVintage: 1969,
    avgPrice: 60,
    producers: ['Château Sociando-Mallet'],
    aliases: ['Sociando-Mallet']
  },
  {
    id: 'bordeaux-chateau-chasse-spleen',
    name: 'Château Chasse-Spleen',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Moulis-en-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot',
    classification: 'Cru Bourgeois Exceptionnel',
    minVintage: 1822,
    avgPrice: 48,
    producers: ['Château Chasse-Spleen'],
    aliases: ['Chasse-Spleen']
  },
  {
    id: 'bordeaux-chateau-poujeaux',
    name: 'Château Poujeaux',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Moulis-en-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Exceptionnel',
    minVintage: 1544,
    avgPrice: 45,
    producers: ['Château Poujeaux'],
    aliases: ['Poujeaux']
  },
  {
    id: 'bordeaux-chateau-maucaillou',
    name: 'Château Maucaillou',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Moulis-en-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot, Cabernet Franc',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1875,
    avgPrice: 35,
    producers: ['Château Maucaillou'],
    aliases: ['Maucaillou']
  },
  
  // LISTRAC-MÉDOC
  {
    id: 'bordeaux-chateau-fourcas-hosten',
    name: 'Château Fourcas-Hosten',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Listrac-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Exceptionnel',
    minVintage: 1810,
    avgPrice: 38,
    producers: ['Château Fourcas-Hosten'],
    aliases: ['Fourcas-Hosten']
  },
  {
    id: 'bordeaux-chateau-clarke',
    name: 'Château Clarke',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Listrac-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1771,
    avgPrice: 42,
    producers: ['Château Clarke'],
    aliases: ['Clarke']
  },
  {
    id: 'bordeaux-chateau-fonreaud',
    name: 'Château Fonréaud',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Listrac-Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois Supérieur',
    minVintage: 1962,
    avgPrice: 32,
    producers: ['Château Fonréaud'],
    aliases: ['Fonréaud']
  },
  
  // MÉDOC - CRU BOURGEOIS
  {
    id: 'bordeaux-chateau-potensac',
    name: 'Château Potensac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'Cru Bourgeois Exceptionnel',
    minVintage: 1964,
    avgPrice: 38,
    producers: ['Château Potensac'],
    aliases: ['Potensac']
  },
  {
    id: 'bordeaux-chateau-greysac',
    name: 'Château Greysac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'Cru Bourgeois',
    minVintage: 1972,
    avgPrice: 25,
    producers: ['Château Greysac'],
    aliases: ['Greysac']
  },
  {
    id: 'bordeaux-chateau-les-grands-chenes',
    name: 'Château Les Grands Chênes',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'Cru Bourgeois',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Château Les Grands Chênes'],
    aliases: ['Les Grands Chênes']
  },
];
