import { WineTemplate } from '@/types/wineDatabase';

/**
 * BORDEAUX RIGHT BANK - Part 1 of 6 (Wines 1-25)
 * Focus: Pomerol Top Estates, Saint-Émilion Premier Grand Cru Classé A & B
 * Updated: January 2025
 */

export const bordeauxRightBankPart1: WineTemplate[] = [
  // POMEROL - ICONIC ESTATES
  {
    id: 'bordeaux-chateau-petrus',
    name: 'Pétrus',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot',
    classification: 'Pomerol',
    minVintage: 1925,
    avgPrice: 3500,
    producers: ['Pétrus'],
    aliases: ['Petrus']
  },
  {
    id: 'bordeaux-le-pin',
    name: 'Le Pin',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot',
    classification: 'Pomerol',
    minVintage: 1979,
    avgPrice: 3200,
    producers: ['Le Pin'],
    aliases: ['Pin']
  },
  {
    id: 'bordeaux-chateau-lafleur',
    name: 'Château Lafleur',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1872,
    avgPrice: 850,
    producers: ['Château Lafleur'],
    aliases: ['Lafleur']
  },
  {
    id: 'bordeaux-vieux-chateau-certan',
    name: 'Vieux Château Certan',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Pomerol',
    minVintage: 1924,
    avgPrice: 350,
    producers: ['Vieux Château Certan'],
    aliases: ['VCC']
  },
  {
    id: 'bordeaux-chateau-la-conseillante',
    name: 'Château La Conseillante',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1871,
    avgPrice: 280,
    producers: ['Château La Conseillante'],
    aliases: ['La Conseillante']
  },
  {
    id: 'bordeaux-chateau-l-evangile',
    name: 'Château L\'Évangile',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1741,
    avgPrice: 320,
    producers: ['Château L\'Évangile'],
    aliases: ['L\'Évangile', 'Evangile']
  },
  {
    id: 'bordeaux-chateau-la-fleur-petrus',
    name: 'Château La Fleur-Pétrus',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1953,
    avgPrice: 320,
    producers: ['Château La Fleur-Pétrus'],
    aliases: ['La Fleur-Pétrus']
  },
  {
    id: 'bordeaux-chateau-trotanoy',
    name: 'Château Trotanoy',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1953,
    avgPrice: 340,
    producers: ['Château Trotanoy'],
    aliases: ['Trotanoy']
  },
  {
    id: 'bordeaux-chateau-clinet',
    name: 'Château Clinet',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1850,
    avgPrice: 180,
    producers: ['Château Clinet'],
    aliases: ['Clinet']
  },
  {
    id: 'bordeaux-chateau-l-eglise-clinet',
    name: 'Château L\'Église-Clinet',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pomerol',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Pomerol',
    minVintage: 1882,
    avgPrice: 220,
    producers: ['Château L\'Église-Clinet'],
    aliases: ['L\'Église-Clinet', 'Eglise-Clinet']
  },
  
  // SAINT-ÉMILION - PREMIER GRAND CRU CLASSÉ A
  {
    id: 'bordeaux-chateau-ausone',
    name: 'Château Ausone',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Cabernet Franc, Merlot',
    classification: 'Premier Grand Cru Classé A',
    minVintage: 1906,
    avgPrice: 850,
    producers: ['Château Ausone'],
    aliases: ['Ausone']
  },
  {
    id: 'bordeaux-chateau-cheval-blanc',
    name: 'Château Cheval Blanc',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Cabernet Franc, Merlot',
    classification: 'Premier Grand Cru Classé A',
    minVintage: 1832,
    avgPrice: 900,
    producers: ['Château Cheval Blanc'],
    aliases: ['Cheval Blanc']
  },
  {
    id: 'bordeaux-chateau-angelus',
    name: 'Château Angélus',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Premier Grand Cru Classé A',
    minVintage: 1782,
    avgPrice: 420,
    producers: ['Château Angélus'],
    aliases: ['Angélus', 'Angelus']
  },
  {
    id: 'bordeaux-chateau-pavie',
    name: 'Château Pavie',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Premier Grand Cru Classé A',
    minVintage: 1885,
    avgPrice: 450,
    producers: ['Château Pavie'],
    aliases: ['Pavie']
  },
  
  // SAINT-ÉMILION - PREMIER GRAND CRU CLASSÉ B
  {
    id: 'bordeaux-chateau-figeac',
    name: 'Château Figeac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Cabernet Sauvignon, Cabernet Franc, Merlot',
    classification: 'Premier Grand Cru Classé B',
    minVintage: 1879,
    avgPrice: 220,
    producers: ['Château Figeac'],
    aliases: ['Figeac']
  },
  {
    id: 'bordeaux-chateau-canon',
    name: 'Château Canon',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Premier Grand Cru Classé B',
    minVintage: 1760,
    avgPrice: 180,
    producers: ['Château Canon'],
    aliases: ['Canon']
  },
  {
    id: 'bordeaux-chateau-beauséjour-duffau-lagarrosse',
    name: 'Château Beauséjour (Duffau-Lagarrosse)',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Premier Grand Cru Classé B',
    minVintage: 1847,
    avgPrice: 200,
    producers: ['Château Beauséjour Duffau'],
    aliases: ['Beauséjour Duffau']
  },
  {
    id: 'bordeaux-chateau-beau-sejour-becot',
    name: 'Château Beau-Séjour Bécot',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Premier Grand Cru Classé B',
    minVintage: 1969,
    avgPrice: 150,
    producers: ['Château Beau-Séjour Bécot'],
    aliases: ['Beau-Séjour Bécot']
  },
  {
    id: 'bordeaux-chateau-belair-monange',
    name: 'Château Bélair-Monange',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'Premier Grand Cru Classé B',
    minVintage: 1850,
    avgPrice: 180,
    producers: ['Château Bélair-Monange'],
    aliases: ['Bélair-Monange']
  },
  {
    id: 'bordeaux-chateau-canon-la-gaffeliere',
    name: 'Château Canon-la-Gaffelière',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Premier Grand Cru Classé B',
    minVintage: 1971,
    avgPrice: 140,
    producers: ['Château Canon-la-Gaffelière'],
    aliases: ['Canon-la-Gaffelière']
  },
  {
    id: 'bordeaux-chateau-larcis-ducasse',
    name: 'Château Larcis Ducasse',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Premier Grand Cru Classé B',
    minVintage: 1893,
    avgPrice: 140,
    producers: ['Château Larcis Ducasse'],
    aliases: ['Larcis Ducasse']
  },
  {
    id: 'bordeaux-chateau-pavie-macquin',
    name: 'Château Pavie Macquin',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Premier Grand Cru Classé B',
    minVintage: 1887,
    avgPrice: 160,
    producers: ['Château Pavie Macquin'],
    aliases: ['Pavie Macquin']
  },
  {
    id: 'bordeaux-chateau-troplong-mondot',
    name: 'Château Troplong Mondot',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'Premier Grand Cru Classé B',
    minVintage: 1850,
    avgPrice: 170,
    producers: ['Château Troplong Mondot'],
    aliases: ['Troplong Mondot']
  },
  {
    id: 'bordeaux-chateau-trottevieille',
    name: 'Château Trottevieille',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon',
    classification: 'Premier Grand Cru Classé B',
    minVintage: 1868,
    avgPrice: 140,
    producers: ['Château Trottevieille'],
    aliases: ['Trottevieille']
  },
  {
    id: 'bordeaux-chateau-valandraud',
    name: 'Château Valandraud',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Émilion',
    grapeVariety: 'Merlot, Cabernet Franc, Cabernet Sauvignon, Malbec',
    classification: 'Premier Grand Cru Classé B',
    minVintage: 1991,
    avgPrice: 280,
    producers: ['Château Valandraud'],
    aliases: ['Valandraud']
  },
];
