import { WineTemplate } from '@/types/wineDatabase';

/**
 * BORDEAUX LEFT BANK - Part 2 of 6 (Wines 26-50)
 * Focus: Margaux Third-Fifth Growths, Saint-Julien Fourth Growths
 * Updated: January 2025
 */

export const bordeauxLeftBankPart2: WineTemplate[] = [
  // MARGAUX - THIRD GROWTHS (continued)
  {
    id: 'bordeaux-chateau-desmirail',
    name: 'Château Desmirail',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '3ème Cru Classé',
    minVintage: 1855,
    avgPrice: 60,
    producers: ['Château Desmirail'],
    aliases: ['Desmirail']
  },
  {
    id: 'bordeaux-chateau-d-issan',
    name: 'Château d\'Issan',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: '3ème Cru Classé',
    minVintage: 1855,
    avgPrice: 90,
    producers: ['Château d\'Issan'],
    aliases: ['d\'Issan', 'Issan']
  },
  {
    id: 'bordeaux-chateau-ferriere',
    name: 'Château Ferrière',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot',
    classification: '3ème Cru Classé',
    minVintage: 1855,
    avgPrice: 70,
    producers: ['Château Ferrière'],
    aliases: ['Ferrière']
  },
  {
    id: 'bordeaux-chateau-giscours',
    name: 'Château Giscours',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '3ème Cru Classé',
    minVintage: 1855,
    avgPrice: 85,
    producers: ['Château Giscours'],
    aliases: ['Giscours']
  },
  {
    id: 'bordeaux-chateau-kirwan',
    name: 'Château Kirwan',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '3ème Cru Classé',
    minVintage: 1855,
    avgPrice: 75,
    producers: ['Château Kirwan'],
    aliases: ['Kirwan']
  },
  {
    id: 'bordeaux-chateau-malescot-st-exupery',
    name: 'Château Malescot St. Exupéry',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '3ème Cru Classé',
    minVintage: 1855,
    avgPrice: 80,
    producers: ['Château Malescot St. Exupéry'],
    aliases: ['Malescot', 'Malescot St. Exupéry']
  },
  {
    id: 'bordeaux-chateau-marquis-d-alesme',
    name: 'Château Marquis d\'Alesme',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '3ème Cru Classé',
    minVintage: 1855,
    avgPrice: 65,
    producers: ['Château Marquis d\'Alesme'],
    aliases: ['Marquis d\'Alesme']
  },
  
  // SAINT-JULIEN - FOURTH GROWTHS
  {
    id: 'bordeaux-chateau-talbot',
    name: 'Château Talbot',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Julien',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot, Cabernet Franc',
    classification: '4ème Cru Classé',
    minVintage: 1855,
    avgPrice: 85,
    producers: ['Château Talbot'],
    aliases: ['Talbot']
  },
  {
    id: 'bordeaux-chateau-branaire-ducru',
    name: 'Château Branaire-Ducru',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Julien',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '4ème Cru Classé',
    minVintage: 1855,
    avgPrice: 75,
    producers: ['Château Branaire-Ducru'],
    aliases: ['Branaire-Ducru', 'Branaire']
  },
  {
    id: 'bordeaux-chateau-beychevelle',
    name: 'Château Beychevelle',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Julien',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '4ème Cru Classé',
    minVintage: 1855,
    avgPrice: 90,
    producers: ['Château Beychevelle'],
    aliases: ['Beychevelle']
  },
  {
    id: 'bordeaux-chateau-saint-pierre',
    name: 'Château Saint-Pierre',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Saint-Julien',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: '4ème Cru Classé',
    minVintage: 1855,
    avgPrice: 70,
    producers: ['Château Saint-Pierre'],
    aliases: ['Saint-Pierre']
  },
  
  // MARGAUX - FOURTH GROWTHS
  {
    id: 'bordeaux-chateau-pouget',
    name: 'Château Pouget',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: '4ème Cru Classé',
    minVintage: 1855,
    avgPrice: 60,
    producers: ['Château Pouget'],
    aliases: ['Pouget']
  },
  {
    id: 'bordeaux-chateau-prieure-lichine',
    name: 'Château Prieuré-Lichine',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot, Cabernet Franc',
    classification: '4ème Cru Classé',
    minVintage: 1855,
    avgPrice: 70,
    producers: ['Château Prieuré-Lichine'],
    aliases: ['Prieuré-Lichine']
  },
  {
    id: 'bordeaux-chateau-marquis-de-terme',
    name: 'Château Marquis de Terme',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot, Cabernet Franc',
    classification: '4ème Cru Classé',
    minVintage: 1855,
    avgPrice: 65,
    producers: ['Château Marquis de Terme'],
    aliases: ['Marquis de Terme']
  },
  
  // PAUILLAC - FIFTH GROWTHS
  {
    id: 'bordeaux-chateau-lynch-bages',
    name: 'Château Lynch-Bages',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 150,
    producers: ['Château Lynch-Bages'],
    aliases: ['Lynch-Bages']
  },
  {
    id: 'bordeaux-chateau-pontet-canet',
    name: 'Château Pontet-Canet',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 140,
    producers: ['Château Pontet-Canet'],
    aliases: ['Pontet-Canet']
  },
  {
    id: 'bordeaux-chateau-grand-puy-lacoste',
    name: 'Château Grand-Puy-Lacoste',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 100,
    producers: ['Château Grand-Puy-Lacoste'],
    aliases: ['Grand-Puy-Lacoste', 'GPL']
  },
  {
    id: 'bordeaux-chateau-batailley',
    name: 'Château Batailley',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 75,
    producers: ['Château Batailley'],
    aliases: ['Batailley']
  },
  {
    id: 'bordeaux-chateau-haut-batailley',
    name: 'Château Haut-Batailley',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 80,
    producers: ['Château Haut-Batailley'],
    aliases: ['Haut-Batailley']
  },
  {
    id: 'bordeaux-chateau-clerc-milon',
    name: 'Château Clerc Milon',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot, Carmenère',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 95,
    producers: ['Château Clerc Milon'],
    aliases: ['Clerc Milon']
  },
  {
    id: 'bordeaux-chateau-d-armailhac',
    name: 'Château d\'Armailhac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 85,
    producers: ['Château d\'Armailhac'],
    aliases: ['d\'Armailhac', 'Mouton Baronne Philippe']
  },
  {
    id: 'bordeaux-chateau-pedesclaux',
    name: 'Château Pédesclaux',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 70,
    producers: ['Château Pédesclaux'],
    aliases: ['Pédesclaux']
  },
  {
    id: 'bordeaux-chateau-croizet-bages',
    name: 'Château Croizet-Bages',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Pauillac',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 65,
    producers: ['Château Croizet-Bages'],
    aliases: ['Croizet-Bages']
  },
  
  // MARGAUX - FIFTH GROWTHS
  {
    id: 'bordeaux-chateau-du-tertre',
    name: 'Château du Tertre',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 55,
    producers: ['Château du Tertre'],
    aliases: ['du Tertre']
  },
  {
    id: 'bordeaux-chateau-dauzac',
    name: 'Château Dauzac',
    type: 'Red',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Margaux',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: '5ème Cru Classé',
    minVintage: 1855,
    avgPrice: 60,
    producers: ['Château Dauzac'],
    aliases: ['Dauzac']
  },
];
