import { WineTemplate } from '@/types/wineDatabase';

/**
 * BASILICATA WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Matera DOC, Grottino di Roccanova, White wines, Blends
 * Updated: January 2025
 */

export const basilicataPart2: WineTemplate[] = [
  // MATERA DOC (Red & White)
  {
    id: 'matera-rosso-paternoster',
    name: 'Matera Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Matera',
    grapeVariety: 'Primitivo, Sangiovese, Aglianico',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Paternoster'],
    aliases: ['Paternoster Matera Rosso']
  },
  {
    id: 'matera-rosso-grifalco',
    name: 'Matera Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Matera',
    grapeVariety: 'Primitivo, Aglianico',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Grifalco della Lucania'],
    aliases: ['Grifalco Matera Rosso']
  },
  {
    id: 'matera-rosso-terre-degli-svevi',
    name: 'Matera Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Matera',
    grapeVariety: 'Primitivo, Sangiovese',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Terre degli Svevi'],
    aliases: ['Terre degli Svevi Matera']
  },
  {
    id: 'matera-bianco-grifalco',
    name: 'Matera Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Matera',
    grapeVariety: 'Greco, Malvasia',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 14,
    producers: ['Grifalco della Lucania'],
    aliases: ['Grifalco Matera Bianco']
  },
  {
    id: 'matera-bianco-terre-degli-svevi',
    name: 'Matera Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Matera',
    grapeVariety: 'Greco, Malvasia',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 12,
    producers: ['Terre degli Svevi'],
    aliases: ['Terre degli Svevi Matera Bianco']
  },
  {
    id: 'matera-primitivo-paternoster',
    name: 'Matera Primitivo',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Matera',
    grapeVariety: 'Primitivo',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Paternoster'],
    aliases: ['Paternoster Primitivo']
  },
  {
    id: 'matera-moro',
    name: 'Matera Moro',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Matera',
    grapeVariety: 'Primitivo, Cabernet Sauvignon',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 18,
    producers: ['Cantine del Notaio'],
    aliases: ['Moro']
  },
  
  // GROTTINO DI ROCCANOVA DOC (Red)
  {
    id: 'grottino-roccanova-cantine-del-notaio',
    name: 'Grottino di Roccanova',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Roccanova',
    grapeVariety: 'Sangiovese, Malvasia Nera, Montepulciano',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Cantine del Notaio'],
    aliases: ['Notaio Grottino']
  },
  {
    id: 'grottino-roccanova-terre-degli-svevi',
    name: 'Grottino di Roccanova',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Roccanova',
    grapeVariety: 'Sangiovese, Malvasia Nera',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 14,
    producers: ['Terre degli Svevi'],
    aliases: ['Terre degli Svevi Grottino']
  },
  
  // PREMIUM WHITE WINES (Basilicata IGT)
  {
    id: 'basilicata-paternoster-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Fiano, Malvasia',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Paternoster'],
    aliases: ['Paternoster Bianco']
  },
  {
    id: 'basilicata-elena-fucci-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Fiano',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 20,
    producers: ['Elena Fucci'],
    aliases: ['Elena Fucci Bianco']
  },
  {
    id: 'basilicata-cantine-del-notaio-l-atto',
    name: 'L\'Atto Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Fiano',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 22,
    producers: ['Cantine del Notaio'],
    aliases: ['L\'Atto']
  },
  {
    id: 'basilicata-grifalco-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Malvasia',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Grifalco della Lucania'],
    aliases: ['Grifalco Bianco']
  },
  {
    id: 'basilicata-musto-carmelitano-greco',
    name: 'Greco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Musto Carmelitano'],
    aliases: ['Musto Carmelitano Greco']
  },
  
  // PREMIUM RED BLENDS (Basilicata IGT)
  {
    id: 'basilicata-paternoster-synthesi',
    name: 'Synthesi Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico, Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Paternoster'],
    aliases: ['Synthesi']
  },
  {
    id: 'basilicata-cantine-del-notaio-l-autentica',
    name: 'L\'Autentica Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 45,
    producers: ['Cantine del Notaio'],
    aliases: ['L\'Autentica']
  },
  {
    id: 'basilicata-terre-degli-svevi-violante',
    name: 'Violante Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 35,
    producers: ['Terre degli Svevi'],
    aliases: ['Violante']
  },
  {
    id: 'basilicata-grifalco-aglianico-igt',
    name: 'Aglianico Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Grifalco della Lucania'],
    aliases: ['Grifalco Aglianico IGT']
  },
  
  // PRIMITIVO (Basilicata IGT)
  {
    id: 'primitivo-basilicata-paternoster',
    name: 'Primitivo Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Matera',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Paternoster'],
    aliases: ['Paternoster Primitivo IGT']
  },
  {
    id: 'primitivo-basilicata-grifalco',
    name: 'Primitivo Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Matera',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Grifalco della Lucania'],
    aliases: ['Grifalco Primitivo']
  },
  
  // INTERNATIONAL VARIETIES
  {
    id: 'merlot-basilicata-paternoster',
    name: 'Merlot Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Paternoster'],
    aliases: ['Paternoster Merlot']
  },
  {
    id: 'cabernet-sauvignon-basilicata-terre-degli-svevi',
    name: 'Cabernet Sauvignon Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 20,
    producers: ['Terre degli Svevi'],
    aliases: ['Terre degli Svevi Cabernet']
  },
  {
    id: 'chardonnay-basilicata-paternoster',
    name: 'Chardonnay Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Paternoster'],
    aliases: ['Paternoster Chardonnay']
  },
  
  // ROSÉ WINES
  {
    id: 'rosato-basilicata-elena-fucci',
    name: 'Rosato Basilicata IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 18,
    producers: ['Elena Fucci'],
    aliases: ['Elena Fucci Rosato']
  },
  {
    id: 'rosato-basilicata-cantine-del-notaio',
    name: 'Rosato Basilicata IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Cantine del Notaio'],
    aliases: ['Notaio Rosato']
  },
  {
    id: 'rosato-basilicata-paternoster',
    name: 'Rosato Basilicata IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Paternoster'],
    aliases: ['Paternoster Rosato']
  },
  {
    id: 'rosato-basilicata-grifalco',
    name: 'Rosato Basilicata IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 14,
    producers: ['Grifalco della Lucania'],
    aliases: ['Grifalco Rosato']
  },
  {
    id: 'rosato-basilicata-terre-degli-svevi',
    name: 'Rosato Basilicata IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 13,
    producers: ['Terre degli Svevi'],
    aliases: ['Terre degli Svevi Rosato']
  },
  
  // SPARKLING WINES
  {
    id: 'spumante-basilicata-paternoster',
    name: 'Spumante Brut Basilicata IGT',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 28,
    producers: ['Paternoster'],
    aliases: ['Paternoster Spumante']
  },
  {
    id: 'spumante-basilicata-cantine-del-notaio',
    name: 'Spumante Rosé Metodo Classico',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 32,
    producers: ['Cantine del Notaio'],
    aliases: ['Notaio Spumante']
  },
  
  // ADDITIONAL WINES
  {
    id: 'basilicata-donato-d-angelo-serra-delle-querce',
    name: 'Serra delle Querce Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Aglianico, Merlot',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Donato D\'Angelo'],
    aliases: ['Serra delle Querce']
  },
  {
    id: 'basilicata-michele-laluce-fiano',
    name: 'Fiano Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Fiano',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 18,
    producers: ['Michele Laluce'],
    aliases: ['Michele Laluce Fiano']
  },
  {
    id: 'basilicata-musto-carmelitano-primitivo',
    name: 'Primitivo Basilicata IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Matera',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Musto Carmelitano'],
    aliases: ['Musto Carmelitano Primitivo']
  },
  {
    id: 'basilicata-basilisco-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Malvasia',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Basilisco'],
    aliases: ['Basilisco Bianco']
  },
  {
    id: 'basilicata-vigneti-del-vulture-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Fiano',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 14,
    producers: ['Vigneti del Vulture'],
    aliases: ['Vigneti del Vulture Bianco']
  },
  {
    id: 'basilicata-tenuta-le-querce-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Tenuta Le Querce'],
    aliases: ['Tenuta Le Querce Bianco']
  },
  {
    id: 'basilicata-eubea-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco, Malvasia',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 18,
    producers: ['Eubea'],
    aliases: ['Eubea Bianco']
  },
  {
    id: 'basilicata-macarico-bianco',
    name: 'Bianco Basilicata IGT',
    type: 'White',
    country: 'Italy',
    region: 'Basilicata',
    subRegion: 'Vulture',
    grapeVariety: 'Greco',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Macarico'],
    aliases: ['Macarico Bianco']
  },
];
