import { WineTemplate } from '@/types/wineDatabase';

/**
 * UMBRIA WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Additional red blends, Rosso dell'Umbria, Rosés, International varieties
 * Updated: January 2025
 */

export const umbriaPart3: WineTemplate[] = [
  // PREMIUM RED BLENDS (Umbria IGT)
  {
    id: 'umbria-lungarotti-giubilante',
    name: 'Giubilante Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Sangiovese, Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Lungarotti'],
    aliases: ['Giubilante']
  },
  {
    id: 'umbria-decugnano-dei-barbi-rosso',
    name: 'Rosso Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Sangiovese, Merlot, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 24,
    producers: ['Decugnano dei Barbi'],
    aliases: ['Decugnano Rosso']
  },
  {
    id: 'umbria-barberani-foresco-rosso',
    name: 'Foresco Rosso Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Sangiovese, Merlot, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Barberani'],
    aliases: ['Foresco Rosso']
  },
  {
    id: 'umbria-palazzone-rosso-dell-arringatore',
    name: 'Rosso dell\'Arringatore Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 38,
    producers: ['Palazzone'],
    aliases: ['Rosso dell\'Arringatore']
  },
  {
    id: 'umbria-tenuta-le-velette-rosso-di-spicca',
    name: 'Rosso di Spicca Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Sangiovese, Cabernet Sauvignon, Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Tenuta Le Velette'],
    aliases: ['Rosso di Spicca']
  },
  {
    id: 'umbria-cardeto-rosso',
    name: 'Rosso Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Sangiovese, Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Cardeto'],
    aliases: ['Cardeto Rosso']
  },
  
  // LAGO DI CORBARA DOC (Red)
  {
    id: 'lago-di-corbara-decugnano-dei-barbi',
    name: 'Lago di Corbara Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Sangiovese',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 22,
    producers: ['Decugnano dei Barbi'],
    aliases: ['Decugnano Lago di Corbara']
  },
  {
    id: 'lago-di-corbara-barberani',
    name: 'Lago di Corbara Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 24,
    producers: ['Barberani'],
    aliases: ['Barberani Lago di Corbara']
  },
  
  // COLLI PERUGINI DOC (Red & White)
  {
    id: 'colli-perugini-rosso-lungarotti',
    name: 'Colli Perugini Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Perugia',
    grapeVariety: 'Sangiovese, Montepulciano, Ciliegiolo',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 14,
    producers: ['Lungarotti'],
    aliases: ['Lungarotti Colli Perugini']
  },
  {
    id: 'colli-perugini-bianco-lungarotti',
    name: 'Colli Perugini Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Perugia',
    grapeVariety: 'Grechetto, Trebbiano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 12,
    producers: ['Lungarotti'],
    aliases: ['Lungarotti Colli Perugini Bianco']
  },
  
  // ROSATO (Rosé wines)
  {
    id: 'rosato-lungarotti-aurente',
    name: 'Aurente Rosato Umbria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Lungarotti'],
    aliases: ['Aurente']
  },
  {
    id: 'rosato-arnaldo-caprai',
    name: 'Rosato Umbria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Arnaldo Caprai'],
    aliases: ['Caprai Rosato']
  },
  {
    id: 'rosato-antonelli',
    name: 'Rosato Umbria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Antonelli San Marco'],
    aliases: ['Antonelli Rosato']
  },
  
  // MERLOT
  {
    id: 'merlot-arnaldo-caprai-grecante',
    name: 'Grecante Merlot Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Arnaldo Caprai'],
    aliases: ['Grecante']
  },
  {
    id: 'merlot-lungarotti',
    name: 'Merlot Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Lungarotti'],
    aliases: ['Lungarotti Merlot']
  },
  
  // CABERNET SAUVIGNON
  {
    id: 'cabernet-sauvignon-lungarotti',
    name: 'Cabernet Sauvignon Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 20,
    producers: ['Lungarotti'],
    aliases: ['Lungarotti Cabernet']
  },
  {
    id: 'cabernet-sauvignon-decugnano-dei-barbi',
    name: 'Cabernet Sauvignon Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Decugnano dei Barbi'],
    aliases: ['Decugnano Cabernet']
  },
  
  // PINOT NOIR
  {
    id: 'pinot-noir-antinori-pinot-nero-della-sala',
    name: 'Pinot Nero della Sala Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Pinot Noir',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 38,
    producers: ['Antinori', 'Castello della Sala'],
    aliases: ['Pinot Nero della Sala']
  },
  {
    id: 'pinot-noir-lungarotti',
    name: 'Pinot Nero Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Pinot Noir',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 24,
    producers: ['Lungarotti'],
    aliases: ['Lungarotti Pinot Nero']
  },
  
  // SYRAH
  {
    id: 'syrah-colpetrone',
    name: 'Syrah Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Syrah',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Colpetrone'],
    aliases: ['Colpetrone Syrah']
  },
  
  // ADDITIONAL MONTEFALCO WINES
  {
    id: 'umbria-tabarrini-adarmando',
    name: 'Adarmando Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 32,
    producers: ['Tabarrini'],
    aliases: ['Adarmando']
  },
  {
    id: 'umbria-perticaia-rosso',
    name: 'Rosso Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Perticaia'],
    aliases: ['Perticaia Rosso IGT']
  },
  {
    id: 'umbria-scacciadiavoli-rosso',
    name: 'Rosso Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Montepulciano',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Scacciadiavoli'],
    aliases: ['Scacciadiavoli Rosso IGT']
  },
  {
    id: 'umbria-adanti-rosso',
    name: 'Rosso Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Adanti'],
    aliases: ['Adanti Rosso IGT']
  },
  {
    id: 'umbria-romanelli-rosso',
    name: 'Rosso Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Romanelli'],
    aliases: ['Romanelli Rosso IGT']
  },
  {
    id: 'umbria-colpetrone-rosso',
    name: 'Rosso Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Colpetrone'],
    aliases: ['Colpetrone Rosso IGT']
  },
  
  // VIN SANTO (Sweet wine)
  {
    id: 'vin-santo-lungarotti',
    name: 'Vin Santo Umbria IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Grechetto, Trebbiano',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 38,
    producers: ['Lungarotti'],
    aliases: ['Lungarotti Vin Santo']
  },
  {
    id: 'vin-santo-adanti',
    name: 'Vin Santo Umbria IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Grechetto',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 42,
    producers: ['Adanti'],
    aliases: ['Adanti Vin Santo']
  },
  
  // SPARKLING WINES
  {
    id: 'spumante-lungarotti-brut',
    name: 'Brut Umbria Spumante',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Chardonnay, Pinot Noir',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Lungarotti'],
    aliases: ['Lungarotti Brut']
  },
  {
    id: 'spumante-arnaldo-caprai',
    name: 'Spumante Brut Umbria IGT',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Grechetto, Chardonnay',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 24,
    producers: ['Arnaldo Caprai'],
    aliases: ['Caprai Spumante']
  },
  
  // ADDITIONAL PREMIUM WINES
  {
    id: 'umbria-lungarotti-carapace',
    name: 'Carapace Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 42,
    producers: ['Lungarotti'],
    aliases: ['Carapace']
  },
  {
    id: 'umbria-paolo-bea-lapideus',
    name: 'Lapideus Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 45,
    producers: ['Paolo Bea'],
    aliases: ['Lapideus']
  },
  {
    id: 'umbria-arnaldo-caprai-umbria-rosso',
    name: 'Rosso Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Arnaldo Caprai'],
    aliases: ['Caprai Rosso Umbria']
  },
  {
    id: 'umbria-lungarotti-terre-di-giano',
    name: 'Terre di Giano Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Sangiovese, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Lungarotti'],
    aliases: ['Terre di Giano']
  },
  {
    id: 'umbria-decugnano-dei-barbi-pourriture-noble',
    name: 'Pourriture Noble Umbria IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Sauvignon Blanc, Grechetto',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 55,
    producers: ['Decugnano dei Barbi'],
    aliases: ['Pourriture Noble']
  },
  {
    id: 'umbria-barberani-villa-monticelli',
    name: 'Villa Monticelli Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Sangiovese, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 28,
    producers: ['Barberani'],
    aliases: ['Villa Monticelli']
  },
  {
    id: 'umbria-palazzone-grechetto-riserva',
    name: 'Grechetto Riserva Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 32,
    producers: ['Palazzone'],
    aliases: ['Palazzone Grechetto Riserva']
  },
  {
    id: 'umbria-antonelli-passito',
    name: 'Passito Umbria IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Grechetto, Malvasia',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 38,
    producers: ['Antonelli San Marco'],
    aliases: ['Antonelli Passito']
  },
  {
    id: 'umbria-tabarrini-rosato',
    name: 'Rosato Umbria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Tabarrini'],
    aliases: ['Tabarrini Rosato']
  },
  {
    id: 'umbria-tenuta-le-velette-calanco',
    name: 'Calanco Orvieto Classico',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Tenuta Le Velette'],
    aliases: ['Calanco']
  },
];
