import { WineTemplate } from '@/types/wineDatabase';

/**
 * EMILIA-ROMAGNA WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Lambrusco DOC (Various types)
 * Updated: January 2025
 */

export const emiliaRomagnaPart1: WineTemplate[] = [
  // LAMBRUSCO DI SORBARA DOC (Sparkling red - Emilia)
  {
    id: 'lambrusco-sorbara-cleto-chiarli-del-fondatore',
    name: 'Lambrusco di Sorbara Del Fondatore',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'DOC',
    minVintage: 1860,
    avgPrice: 18,
    producers: ['Cleto Chiarli'],
    aliases: ['Del Fondatore']
  },
  {
    id: 'lambrusco-sorbara-cleto-chiarli-vecchia-modena',
    name: 'Lambrusco di Sorbara Vecchia Modena Premium',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 22,
    producers: ['Cleto Chiarli'],
    aliases: ['Vecchia Modena Premium']
  },
  {
    id: 'lambrusco-sorbara-cavicchioli',
    name: 'Lambrusco di Sorbara',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'DOC',
    minVintage: 1928,
    avgPrice: 14,
    producers: ['Cavicchioli'],
    aliases: ['Cavicchioli Sorbara']
  },
  {
    id: 'lambrusco-sorbara-paltrinieri-radice',
    name: 'Lambrusco di Sorbara Radice',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'DOC',
    minVintage: 1926,
    avgPrice: 20,
    producers: ['Paltrinieri'],
    aliases: ['Radice']
  },
  {
    id: 'lambrusco-sorbara-paltrinieri-leclisse',
    name: 'Lambrusco di Sorbara L\'Eclisse',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Paltrinieri'],
    aliases: ['L\'Eclisse']
  },
  {
    id: 'lambrusco-sorbara-vittorio-graziano-fontana-dei-boschi',
    name: 'Lambrusco di Sorbara Fontana dei Boschi',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 22,
    producers: ['Vittorio Graziano'],
    aliases: ['Fontana dei Boschi']
  },
  {
    id: 'lambrusco-sorbara-cantina-della-volta-il-rosso-della-viola',
    name: 'Lambrusco di Sorbara Il Rosso della Viola',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 26,
    producers: ['Cantina della Volta'],
    aliases: ['Il Rosso della Viola']
  },
  
  // LAMBRUSCO GRASPAROSSA DI CASTELVETRO DOC (Sparkling red)
  {
    id: 'lambrusco-grasparossa-cleto-chiarli-centenario',
    name: 'Lambrusco Grasparossa di Castelvetro Centenario',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco Grasparossa',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 16,
    producers: ['Cleto Chiarli'],
    aliases: ['Centenario']
  },
  {
    id: 'lambrusco-grasparossa-cleto-chiarli-vigneto-cialdini',
    name: 'Lambrusco Grasparossa di Castelvetro Vigneto Cialdini',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco Grasparossa',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Cleto Chiarli'],
    aliases: ['Vigneto Cialdini']
  },
  {
    id: 'lambrusco-grasparossa-cavicchioli',
    name: 'Lambrusco Grasparossa di Castelvetro',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco Grasparossa',
    classification: 'DOC',
    minVintage: 1928,
    avgPrice: 14,
    producers: ['Cavicchioli'],
    aliases: ['Cavicchioli Grasparossa']
  },
  {
    id: 'lambrusco-grasparossa-medici-ermete-concerto',
    name: 'Lambrusco Grasparossa di Castelvetro Concerto',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco Grasparossa',
    classification: 'DOC',
    minVintage: 1890,
    avgPrice: 18,
    producers: ['Medici Ermete'],
    aliases: ['Concerto']
  },
  {
    id: 'lambrusco-grasparossa-medici-ermete-assolo',
    name: 'Lambrusco Grasparossa di Castelvetro Assolo',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco Grasparossa',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Medici Ermete'],
    aliases: ['Assolo']
  },
  {
    id: 'lambrusco-grasparossa-barbolini',
    name: 'Lambrusco Grasparossa di Castelvetro Vigna Vecchia',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco Grasparossa',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 20,
    producers: ['Barbolini'],
    aliases: ['Vigna Vecchia']
  },
  
  // LAMBRUSCO SALAMINO DI SANTA CROCE DOC (Sparkling red)
  {
    id: 'lambrusco-salamino-cavicchioli',
    name: 'Lambrusco Salamino di Santa Croce',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco Salamino',
    classification: 'DOC',
    minVintage: 1928,
    avgPrice: 14,
    producers: ['Cavicchioli'],
    aliases: ['Cavicchioli Salamino']
  },
  {
    id: 'lambrusco-salamino-cleto-chiarli',
    name: 'Lambrusco Salamino di Santa Croce',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco Salamino',
    classification: 'DOC',
    minVintage: 1860,
    avgPrice: 16,
    producers: ['Cleto Chiarli'],
    aliases: ['Chiarli Salamino']
  },
  {
    id: 'lambrusco-salamino-medici-ermete',
    name: 'Lambrusco Salamino di Santa Croce',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco Salamino',
    classification: 'DOC',
    minVintage: 1890,
    avgPrice: 16,
    producers: ['Medici Ermete'],
    aliases: ['Medici Salamino']
  },
  
  // REGGIANO LAMBRUSCO DOC
  {
    id: 'lambrusco-reggiano-medici-ermete-quercioli',
    name: 'Reggiano Lambrusco Quercioli',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Reggio Emilia',
    grapeVariety: 'Lambrusco Salamino, Lambrusco Marani',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 18,
    producers: ['Medici Ermete'],
    aliases: ['Quercioli']
  },
  {
    id: 'lambrusco-reggiano-venturini-baldini-del-cristo',
    name: 'Reggiano Lambrusco Secco del Cristo',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Reggio Emilia',
    grapeVariety: 'Lambrusco Salamino',
    classification: 'DOC',
    minVintage: 1976,
    avgPrice: 20,
    producers: ['Venturini Baldini'],
    aliases: ['Del Cristo']
  },
  {
    id: 'lambrusco-reggiano-venturini-baldini',
    name: 'Reggiano Lambrusco',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Reggio Emilia',
    grapeVariety: 'Lambrusco Salamino, Lambrusco Marani',
    classification: 'DOC',
    minVintage: 1976,
    avgPrice: 14,
    producers: ['Venturini Baldini'],
    aliases: ['Venturini Baldini Lambrusco']
  },
  
  // LAMBRUSCO DELL'EMILIA IGT (Generic)
  {
    id: 'lambrusco-emilia-riunite',
    name: 'Lambrusco dell\'Emilia',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Reggio Emilia',
    grapeVariety: 'Lambrusco',
    classification: 'IGT',
    minVintage: 1950,
    avgPrice: 10,
    producers: ['Riunite'],
    aliases: ['Riunite Lambrusco']
  },
  {
    id: 'lambrusco-emilia-cantine-ceci',
    name: 'Lambrusco dell\'Emilia',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Parma',
    grapeVariety: 'Lambrusco',
    classification: 'IGT',
    minVintage: 1938,
    avgPrice: 12,
    producers: ['Cantine Ceci'],
    aliases: ['Ceci Lambrusco']
  },
  {
    id: 'lambrusco-emilia-umberto-cesari',
    name: 'Lambrusco dell\'Emilia',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Bologna',
    grapeVariety: 'Lambrusco',
    classification: 'IGT',
    minVintage: 1964,
    avgPrice: 11,
    producers: ['Umberto Cesari'],
    aliases: ['Cesari Lambrusco']
  },
  
  // LAMBRUSCO ROSÉ (Rosato)
  {
    id: 'lambrusco-rosato-cleto-chiarli',
    name: 'Lambrusco Rosato dell\'Emilia',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 14,
    producers: ['Cleto Chiarli'],
    aliases: ['Chiarli Rosato']
  },
  {
    id: 'lambrusco-rosato-cavicchioli',
    name: 'Lambrusco Rosato dell\'Emilia',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 12,
    producers: ['Cavicchioli'],
    aliases: ['Cavicchioli Rosato']
  },
  
  // LAMBRUSCO WHITE (Bianco)
  {
    id: 'lambrusco-bianco-cleto-chiarli-nivola',
    name: 'Lambrusco Bianco Nivola',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco (vinified white)',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Cleto Chiarli'],
    aliases: ['Nivola']
  },
  
  // PREMIUM/NATURAL LAMBRUSCO
  {
    id: 'lambrusco-natural-vigneto-saetti',
    name: 'Lambrusco di Sorbara Rifermentato',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Vigneto Saetti'],
    aliases: ['Vigneto Saetti']
  },
  {
    id: 'lambrusco-natural-camillo-donati-lambrusco',
    name: 'Lambrusco dell\'Emilia Rifermentato',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Parma',
    grapeVariety: 'Lambrusco',
    classification: 'IGT',
    minVintage: 1930,
    avgPrice: 24,
    producers: ['Camillo Donati'],
    aliases: ['Camillo Donati']
  },
  {
    id: 'lambrusco-natural-vittorio-graziano-rifermentato',
    name: 'Lambrusco Rifermentato',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 26,
    producers: ['Vittorio Graziano'],
    aliases: ['Graziano Rifermentato']
  },
  {
    id: 'lambrusco-cantina-della-volta-brut-rosé',
    name: 'Lambrusco di Sorbara Brut Rosé',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 28,
    producers: ['Cantina della Volta'],
    aliases: ['Volta Brut Rosé']
  },
  {
    id: 'lambrusco-cantina-della-volta-lambrusco-bianco',
    name: 'Lambrusco Bianco Metodo Classico',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 32,
    producers: ['Cantina della Volta'],
    aliases: ['Volta Bianco']
  },
  {
    id: 'lambrusco-lini-910-metodo-classico',
    name: 'Lambrusco 910 Metodo Classico',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'DOC',
    minVintage: 1910,
    avgPrice: 35,
    producers: ['Lini 910'],
    aliases: ['Lini 910']
  },
  {
    id: 'lambrusco-lini-lambrusco-di-sorbara',
    name: 'Lambrusco di Sorbara',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'DOC',
    minVintage: 1910,
    avgPrice: 18,
    producers: ['Lini 910'],
    aliases: ['Lini Sorbara']
  },
  {
    id: 'lambrusco-il-farneto',
    name: 'Lambrusco Grasparossa di Castelvetro',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco Grasparossa',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 16,
    producers: ['Il Farneto'],
    aliases: ['Il Farneto']
  },
  {
    id: 'lambrusco-barbolini-vigna-vecchia-riserva',
    name: 'Lambrusco Grasparossa Vigna Vecchia Riserva',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco Grasparossa',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Barbolini'],
    aliases: ['Barbolini Riserva']
  },
  {
    id: 'lambrusco-paltrinieri-solco',
    name: 'Lambrusco di Sorbara Solco',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco di Sorbara',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 18,
    producers: ['Paltrinieri'],
    aliases: ['Solco']
  },
  {
    id: 'lambrusco-medici-ermete-lambrusco-bianco',
    name: 'Lambrusco Bianco Demi-Sec',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Modena',
    grapeVariety: 'Lambrusco',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Medici Ermete'],
    aliases: ['Medici Bianco']
  },
];
