import { WineTemplate } from '@/types/wineDatabase';

/**
 * PIEDMONT WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Barbera d'Asti, Barbera d'Alba, Dolcetto, Gavi, Roero Arneis
 * Updated: January 2025
 */

export const piedmontPart3: WineTemplate[] = [
  // BARBERA D'ASTI DOCG
  {
    id: 'barbera-asti-braida-bricco-uccellone',
    name: 'Barbera d\'Asti Bricco dell\'Uccellone',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Barbera',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 65,
    producers: ['Braida', 'Giacomo Bologna'],
    aliases: ['Bricco dell\'Uccellone']
  },
  {
    id: 'barbera-asti-braida-ai-suma',
    name: 'Barbera d\'Asti Ai Suma',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Barbera',
    classification: 'DOCG',
    minVintage: 1983,
    avgPrice: 38,
    producers: ['Braida'],
    aliases: ['Ai Suma']
  },
  {
    id: 'barbera-asti-coppo-pomorosso',
    name: 'Barbera d\'Asti Pomorosso',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Barbera',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 42,
    producers: ['Coppo'],
    aliases: ['Pomorosso']
  },
  {
    id: 'barbera-asti-coppo-camp-du-rouss',
    name: 'Barbera d\'Asti Camp du Rouss',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Barbera',
    classification: 'DOCG',
    minVintage: 1988,
    avgPrice: 28,
    producers: ['Coppo'],
    aliases: ['Camp du Rouss']
  },
  {
    id: 'barbera-asti-vietti-tre-vigne',
    name: 'Barbera d\'Asti Tre Vigne',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Barbera',
    classification: 'DOCG',
    minVintage: 1974,
    avgPrice: 32,
    producers: ['Vietti'],
    aliases: ['Tre Vigne']
  },
  {
    id: 'barbera-asti-vietti-la-crena',
    name: 'Barbera d\'Asti La Crena',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Barbera',
    classification: 'DOCG',
    minVintage: 1989,
    avgPrice: 45,
    producers: ['Vietti'],
    aliases: ['La Crena']
  },
  {
    id: 'barbera-asti-prunotto',
    name: 'Barbera d\'Asti',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Barbera',
    classification: 'DOCG',
    minVintage: 1923,
    avgPrice: 22,
    producers: ['Prunotto'],
    aliases: ['Prunotto Barbera']
  },
  {
    id: 'barbera-asti-prunotto-costamiole',
    name: 'Barbera d\'Asti Costamiòle',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Barbera',
    classification: 'DOCG',
    minVintage: 1987,
    avgPrice: 35,
    producers: ['Prunotto'],
    aliases: ['Costamiòle']
  },
  {
    id: 'barbera-asti-michele-chiarlo-court',
    name: 'Barbera d\'Asti La Court',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Barbera',
    classification: 'DOCG',
    minVintage: 1956,
    avgPrice: 38,
    producers: ['Michele Chiarlo'],
    aliases: ['La Court']
  },
  {
    id: 'barbera-asti-bava-stradivario',
    name: 'Barbera d\'Asti Stradivario',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Barbera',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 32,
    producers: ['Bava'],
    aliases: ['Stradivario']
  },
  
  // BARBERA D'ALBA DOC
  {
    id: 'barbera-alba-altare',
    name: 'Barbera d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Barbera',
    classification: 'DOC',
    minVintage: 1976,
    avgPrice: 30,
    producers: ['Elio Altare'],
    aliases: ['Altare Barbera']
  },
  {
    id: 'barbera-alba-aldo-conterno-conca-tre-pile',
    name: 'Barbera d\'Alba Conca Tre Pile',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Barbera',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 42,
    producers: ['Aldo Conterno'],
    aliases: ['Conca Tre Pile']
  },
  {
    id: 'barbera-alba-giacomo-conterno',
    name: 'Barbera d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Barbera',
    classification: 'DOC',
    minVintage: 1920,
    avgPrice: 38,
    producers: ['Giacomo Conterno'],
    aliases: ['Conterno Barbera']
  },
  {
    id: 'barbera-alba-sandrone',
    name: 'Barbera d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Barbera',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 35,
    producers: ['Luciano Sandrone'],
    aliases: ['Sandrone Barbera']
  },
  {
    id: 'barbera-alba-voerzio',
    name: 'Barbera d\'Alba Riserva Pozzo dell\'Annunziata',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Barbera',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 48,
    producers: ['Roberto Voerzio'],
    aliases: ['Pozzo dell\'Annunziata']
  },
  {
    id: 'barbera-alba-scavino',
    name: 'Barbera d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Barbera',
    classification: 'DOC',
    minVintage: 1921,
    avgPrice: 28,
    producers: ['Paolo Scavino'],
    aliases: ['Scavino Barbera']
  },
  {
    id: 'barbera-alba-gaja',
    name: 'Barbera d\'Alba Conteisa',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Barbera',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 45,
    producers: ['Gaja'],
    aliases: ['Conteisa Barbera']
  },
  {
    id: 'barbera-alba-ceretto',
    name: 'Barbera d\'Alba Piana',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Barbera',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 28,
    producers: ['Ceretto'],
    aliases: ['Piana']
  },
  {
    id: 'barbera-alba-vajra',
    name: 'Barbera d\'Alba Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Barbera',
    classification: 'DOC',
    minVintage: 1972,
    avgPrice: 26,
    producers: ['G.D. Vajra'],
    aliases: ['Vajra Barbera Superiore']
  },
  {
    id: 'barbera-alba-pio-cesare',
    name: 'Barbera d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Barbera',
    classification: 'DOC',
    minVintage: 1881,
    avgPrice: 24,
    producers: ['Pio Cesare'],
    aliases: ['Pio Cesare Barbera']
  },
  
  // DOLCETTO D'ALBA DOC
  {
    id: 'dolcetto-alba-altare',
    name: 'Dolcetto d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Dolcetto',
    classification: 'DOC',
    minVintage: 1976,
    avgPrice: 24,
    producers: ['Elio Altare'],
    aliases: ['Altare Dolcetto']
  },
  {
    id: 'dolcetto-alba-vajra',
    name: 'Dolcetto d\'Alba Coste & Fossati',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Dolcetto',
    classification: 'DOC',
    minVintage: 1972,
    avgPrice: 22,
    producers: ['G.D. Vajra'],
    aliases: ['Coste & Fossati']
  },
  {
    id: 'dolcetto-alba-ceretto-rossana',
    name: 'Dolcetto d\'Alba Rossana',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Dolcetto',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 20,
    producers: ['Ceretto'],
    aliases: ['Rossana']
  },
  {
    id: 'dolcetto-alba-sandrone',
    name: 'Dolcetto d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Dolcetto',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 26,
    producers: ['Luciano Sandrone'],
    aliases: ['Sandrone Dolcetto']
  },
  {
    id: 'dolcetto-alba-scavino',
    name: 'Dolcetto d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Dolcetto',
    classification: 'DOC',
    minVintage: 1921,
    avgPrice: 22,
    producers: ['Paolo Scavino'],
    aliases: ['Scavino Dolcetto']
  },
  {
    id: 'dolcetto-alba-pecchenino-bricco-botti',
    name: 'Dolcetto di Dogliani Superiore Bricco Botti',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Dogliani',
    grapeVariety: 'Dolcetto',
    classification: 'DOCG',
    minVintage: 1993,
    avgPrice: 28,
    producers: ['Pecchenino'],
    aliases: ['Bricco Botti']
  },
  {
    id: 'dolcetto-alba-abbona-papà-celso',
    name: 'Dolcetto di Dogliani Superiore Papà Celso',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Dogliani',
    grapeVariety: 'Dolcetto',
    classification: 'DOCG',
    minVintage: 1989,
    avgPrice: 26,
    producers: ['Abbona'],
    aliases: ['Papà Celso']
  },
  {
    id: 'dolcetto-alba-vietti-tre-vigne',
    name: 'Dolcetto d\'Alba Tre Vigne',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Dolcetto',
    classification: 'DOC',
    minVintage: 1974,
    avgPrice: 20,
    producers: ['Vietti'],
    aliases: ['Tre Vigne Dolcetto']
  },
  {
    id: 'dolcetto-alba-marcarini-boschi-berri',
    name: 'Dolcetto d\'Alba Boschi di Berri',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Dolcetto',
    classification: 'DOC',
    minVintage: 1958,
    avgPrice: 22,
    producers: ['Marcarini'],
    aliases: ['Boschi di Berri']
  },
  
  // GAVI DOCG (White)
  {
    id: 'gavi-la-scolca-black-label',
    name: 'Gavi dei Gavi Black Label',
    type: 'White',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Gavi',
    grapeVariety: 'Cortese',
    classification: 'DOCG',
    minVintage: 1963,
    avgPrice: 32,
    producers: ['La Scolca'],
    aliases: ['Black Label Gavi']
  },
  {
    id: 'gavi-la-scolca-etichetta-nera',
    name: 'Gavi dei Gavi Etichetta Nera',
    type: 'White',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Gavi',
    grapeVariety: 'Cortese',
    classification: 'DOCG',
    minVintage: 2010,
    avgPrice: 55,
    producers: ['La Scolca'],
    aliases: ['Etichetta Nera']
  },
  {
    id: 'gavi-la-giustiniana',
    name: 'Gavi del Comune di Gavi',
    type: 'White',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Gavi',
    grapeVariety: 'Cortese',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 22,
    producers: ['La Giustiniana'],
    aliases: ['La Giustiniana Gavi']
  },
  {
    id: 'gavi-la-giustiniana-lugarara',
    name: 'Gavi del Comune di Gavi Lugarara',
    type: 'White',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Gavi',
    grapeVariety: 'Cortese',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['La Giustiniana'],
    aliases: ['Lugarara']
  },
  {
    id: 'gavi-pio-cesare',
    name: 'Gavi',
    type: 'White',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Gavi',
    grapeVariety: 'Cortese',
    classification: 'DOCG',
    minVintage: 1995,
    avgPrice: 20,
    producers: ['Pio Cesare'],
    aliases: ['Pio Cesare Gavi']
  },
  {
    id: 'gavi-villa-sparina',
    name: 'Gavi di Gavi',
    type: 'White',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Gavi',
    grapeVariety: 'Cortese',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 24,
    producers: ['Villa Sparina'],
    aliases: ['Villa Sparina Gavi']
  },
  
  // ROERO ARNEIS DOCG (White)
  {
    id: 'roero-arneis-vietti',
    name: 'Roero Arneis',
    type: 'White',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Roero',
    grapeVariety: 'Arneis',
    classification: 'DOCG',
    minVintage: 1967,
    avgPrice: 26,
    producers: ['Vietti'],
    aliases: ['Vietti Arneis']
  },
  {
    id: 'roero-arneis-ceretto-blange',
    name: 'Roero Arneis Blangé',
    type: 'White',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Roero',
    grapeVariety: 'Arneis',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 24,
    producers: ['Ceretto'],
    aliases: ['Blangé']
  },
  {
    id: 'roero-arneis-bruno-giacosa',
    name: 'Roero Arneis',
    type: 'White',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Roero',
    grapeVariety: 'Arneis',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 28,
    producers: ['Bruno Giacosa'],
    aliases: ['Bruno Giacosa Arneis']
  },
  {
    id: 'roero-arneis-malvira',
    name: 'Roero Arneis Trinità',
    type: 'White',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Roero',
    grapeVariety: 'Arneis',
    classification: 'DOCG',
    minVintage: 1974,
    avgPrice: 22,
    producers: ['Malvirà'],
    aliases: ['Trinità']
  },
  {
    id: 'roero-arneis-negro',
    name: 'Roero Arneis Perdaudin',
    type: 'White',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Roero',
    grapeVariety: 'Arneis',
    classification: 'DOCG',
    minVintage: 1970,
    avgPrice: 20,
    producers: ['Negro'],
    aliases: ['Perdaudin']
  },
  
  // MOSCATO D'ASTI DOCG (Sparkling/Dessert)
  {
    id: 'moscato-asti-saracco',
    name: 'Moscato d\'Asti',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Moscato Bianco',
    classification: 'DOCG',
    minVintage: 1900,
    avgPrice: 18,
    producers: ['Paolo Saracco'],
    aliases: ['Saracco Moscato']
  },
  {
    id: 'moscato-asti-vietti-cascinetta',
    name: 'Moscato d\'Asti Cascinetta',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Moscato Bianco',
    classification: 'DOCG',
    minVintage: 1974,
    avgPrice: 20,
    producers: ['Vietti'],
    aliases: ['Cascinetta']
  },
  {
    id: 'moscato-asti-ceretto-santo-stefano',
    name: 'Moscato d\'Asti Santo Stefano',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Moscato Bianco',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 22,
    producers: ['Ceretto'],
    aliases: ['Santo Stefano']
  },
  {
    id: 'moscato-asti-elio-perrone-sourgal',
    name: 'Moscato d\'Asti Sourgal',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Moscato Bianco',
    classification: 'DOCG',
    minVintage: 1998,
    avgPrice: 16,
    producers: ['Elio Perrone'],
    aliases: ['Sourgal']
  },
  {
    id: 'moscato-asti-la-spinetta-bricco-quaglia',
    name: 'Moscato d\'Asti Bricco Quaglia',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Moscato Bianco',
    classification: 'DOCG',
    minVintage: 1977,
    avgPrice: 24,
    producers: ['La Spinetta'],
    aliases: ['Bricco Quaglia']
  },
  {
    id: 'moscato-asti-bera-arcese',
    name: 'Moscato d\'Asti Arcese',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Asti',
    grapeVariety: 'Moscato Bianco',
    classification: 'DOCG',
    minVintage: 1950,
    avgPrice: 18,
    producers: ['Bera'],
    aliases: ['Arcese']
  },
];
