import { WineTemplate } from '@/types/wineDatabase';

/**
 * VALLE D'AOSTA WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Indigenous Alpine varieties - Petit Rouge, Fumin, Petite Arvine
 * Updated: January 2025
 */

export const valleDaostaPart1: WineTemplate[] = [
  // VALLE D'AOSTA DOC - PETIT ROUGE (Red)
  {
    id: 'vda-petit-rouge-les-cretes-torrette',
    name: 'Valle d\'Aosta Torrette Superieur',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Torrette',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 1989,
    avgPrice: 28,
    producers: ['Les Cretes'],
    aliases: ['Torrette Superieur']
  },
  {
    id: 'vda-petit-rouge-les-cretes',
    name: 'Valle d\'Aosta Torrette',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Torrette',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 1989,
    avgPrice: 18,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Torrette']
  },
  {
    id: 'vda-petit-rouge-grosjean-torrette',
    name: 'Valle d\'Aosta Torrette',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Torrette',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 1969,
    avgPrice: 20,
    producers: ['Grosjean'],
    aliases: ['Grosjean Torrette']
  },
  {
    id: 'vda-petit-rouge-cave-des-onze-communes-torrette',
    name: 'Valle d\'Aosta Torrette',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Torrette',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 1989,
    avgPrice: 16,
    producers: ['Cave des Onze Communes'],
    aliases: ['Cave des Onze Communes Torrette']
  },
  {
    id: 'vda-petit-rouge-anselmet-torrette',
    name: 'Valle d\'Aosta Torrette',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Torrette',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 2002,
    avgPrice: 22,
    producers: ['Anselmet'],
    aliases: ['Anselmet Torrette']
  },
  {
    id: 'vda-petit-rouge-di-barro',
    name: 'Valle d\'Aosta Torrette',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Torrette',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 20,
    producers: ['Di Barrò'],
    aliases: ['Di Barrò Torrette']
  },
  {
    id: 'vda-petit-rouge-la-crotta-di-vegneron',
    name: 'Valle d\'Aosta Torrette',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Torrette',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 18,
    producers: ['La Crotta di Vegneron'],
    aliases: ['La Crotta di Vegneron Torrette']
  },
  
  // FUMIN (Red - Indigenous)
  {
    id: 'vda-fumin-les-cretes',
    name: 'Valle d\'Aosta Fumin',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Fumin',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 32,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Fumin']
  },
  {
    id: 'vda-fumin-grosjean',
    name: 'Valle d\'Aosta Fumin',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Fumin',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 35,
    producers: ['Grosjean'],
    aliases: ['Grosjean Fumin']
  },
  {
    id: 'vda-fumin-anselmet',
    name: 'Valle d\'Aosta Fumin',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Villeneuve',
    grapeVariety: 'Fumin',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 38,
    producers: ['Anselmet'],
    aliases: ['Anselmet Fumin']
  },
  {
    id: 'vda-fumin-cave-des-onze-communes',
    name: 'Valle d\'Aosta Fumin',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Fumin',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 30,
    producers: ['Cave des Onze Communes'],
    aliases: ['Cave des Onze Communes Fumin']
  },
  {
    id: 'vda-fumin-di-barro',
    name: 'Valle d\'Aosta Fumin',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Fumin',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 32,
    producers: ['Di Barrò'],
    aliases: ['Di Barrò Fumin']
  },
  {
    id: 'vda-fumin-la-crotta-di-vegneron',
    name: 'Valle d\'Aosta Fumin',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Nus',
    grapeVariety: 'Fumin',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['La Crotta di Vegneron'],
    aliases: ['La Crotta di Vegneron Fumin']
  },
  
  // PETITE ARVINE (White - Indigenous)
  {
    id: 'vda-petite-arvine-les-cretes',
    name: 'Valle d\'Aosta Petite Arvine',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Morgex',
    grapeVariety: 'Petite Arvine',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Petite Arvine']
  },
  {
    id: 'vda-petite-arvine-grosjean',
    name: 'Valle d\'Aosta Petite Arvine',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Quart',
    grapeVariety: 'Petite Arvine',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Grosjean'],
    aliases: ['Grosjean Petite Arvine']
  },
  {
    id: 'vda-petite-arvine-anselmet',
    name: 'Valle d\'Aosta Petite Arvine',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Villeneuve',
    grapeVariety: 'Petite Arvine',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Anselmet'],
    aliases: ['Anselmet Petite Arvine']
  },
  {
    id: 'vda-petite-arvine-cave-des-onze-communes',
    name: 'Valle d\'Aosta Petite Arvine',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Aymavilles',
    grapeVariety: 'Petite Arvine',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 30,
    producers: ['Cave des Onze Communes'],
    aliases: ['Cave des Onze Communes Petite Arvine']
  },
  {
    id: 'vda-petite-arvine-di-barro',
    name: 'Valle d\'Aosta Petite Arvine',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Petite Arvine',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 32,
    producers: ['Di Barrò'],
    aliases: ['Di Barrò Petite Arvine']
  },
  
  // BLANC DE MORGEX ET DE LA SALLE DOC (White - Prié Blanc)
  {
    id: 'vda-morgex-cave-du-vin-blanc',
    name: 'Blanc de Morgex et de La Salle',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Morgex',
    grapeVariety: 'Prié Blanc',
    classification: 'DOC',
    minVintage: 1983,
    avgPrice: 24,
    producers: ['Cave du Vin Blanc de Morgex et de La Salle'],
    aliases: ['Morgex Blanc']
  },
  {
    id: 'vda-morgex-cave-du-vin-blanc-rayon',
    name: 'Blanc de Morgex et de La Salle Rayon',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Morgex',
    grapeVariety: 'Prié Blanc',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Cave du Vin Blanc de Morgex et de La Salle'],
    aliases: ['Rayon']
  },
  {
    id: 'vda-morgex-ermes-pavese',
    name: 'Blanc de Morgex et de La Salle',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Morgex',
    grapeVariety: 'Prié Blanc',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Ermes Pavese'],
    aliases: ['Ermes Pavese Morgex']
  },
  {
    id: 'vda-morgex-cave-du-vin-blanc-extreme',
    name: 'Blanc de Morgex et de La Salle Extreme',
    type: 'White',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Morgex',
    grapeVariety: 'Prié Blanc',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 32,
    producers: ['Cave du Vin Blanc de Morgex et de La Salle'],
    aliases: ['Extreme']
  },
  
  // CHAMBAVE MUSCAT (Dessert)
  {
    id: 'vda-chambave-muscat-les-cretes',
    name: 'Valle d\'Aosta Chambave Muscat Passito',
    type: 'Dessert',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Muscat Petit Grain',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Chambave Muscat']
  },
  {
    id: 'vda-chambave-muscat-grosjean',
    name: 'Valle d\'Aosta Chambave Muscat',
    type: 'Dessert',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Muscat Petit Grain',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 38,
    producers: ['Grosjean'],
    aliases: ['Grosjean Chambave Muscat']
  },
  {
    id: 'vda-chambave-muscat-la-crotta-di-vegneron',
    name: 'Valle d\'Aosta Chambave Muscat',
    type: 'Dessert',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Chambave',
    grapeVariety: 'Muscat Petit Grain',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 35,
    producers: ['La Crotta di Vegneron'],
    aliases: ['La Crotta Chambave Muscat']
  },
  
  // NUS MALVOISIE (Passito - Pinot Gris)
  {
    id: 'vda-nus-malvoisie-les-cretes',
    name: 'Valle d\'Aosta Nus Malvoisie Passito',
    type: 'Dessert',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Nus',
    grapeVariety: 'Pinot Gris',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 48,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Malvoisie']
  },
  {
    id: 'vda-nus-malvoisie-grosjean',
    name: 'Valle d\'Aosta Nus Malvoisie Passito',
    type: 'Dessert',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Nus',
    grapeVariety: 'Pinot Gris',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 45,
    producers: ['Grosjean'],
    aliases: ['Grosjean Malvoisie']
  },
  {
    id: 'vda-nus-malvoisie-la-crotta-di-vegneron',
    name: 'Valle d\'Aosta Nus Malvoisie Passito',
    type: 'Dessert',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Nus',
    grapeVariety: 'Pinot Gris',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['La Crotta di Vegneron'],
    aliases: ['La Crotta Malvoisie']
  },
  
  // ARNAD-MONTJOVET (Red - Nebbiolo/Picotendro)
  {
    id: 'vda-arnad-montjovet-grosjean',
    name: 'Valle d\'Aosta Arnad-Montjovet',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Arnad',
    grapeVariety: 'Nebbiolo (Picotendro)',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 26,
    producers: ['Grosjean'],
    aliases: ['Grosjean Arnad-Montjovet']
  },
  {
    id: 'vda-arnad-montjovet-cave-des-onze-communes',
    name: 'Valle d\'Aosta Arnad-Montjovet',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Arnad',
    grapeVariety: 'Nebbiolo (Picotendro)',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Cave des Onze Communes'],
    aliases: ['Cave des Onze Communes Arnad']
  },
  {
    id: 'vda-arnad-montjovet-anselmet',
    name: 'Valle d\'Aosta Arnad-Montjovet',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Arnad',
    grapeVariety: 'Nebbiolo (Picotendro)',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 28,
    producers: ['Anselmet'],
    aliases: ['Anselmet Arnad-Montjovet']
  },
  
  // DONNAS (Red - Nebbiolo/Picotendro)
  {
    id: 'vda-donnas-cave-cooperative-donnas',
    name: 'Valle d\'Aosta Donnas',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Donnas',
    grapeVariety: 'Nebbiolo (Picotendro)',
    classification: 'DOC',
    minVintage: 1971,
    avgPrice: 24,
    producers: ['Cave Cooperative de Donnas'],
    aliases: ['Donnas Classico']
  },
  {
    id: 'vda-donnas-grosjean',
    name: 'Valle d\'Aosta Donnas',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Donnas',
    grapeVariety: 'Nebbiolo (Picotendro)',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Grosjean'],
    aliases: ['Grosjean Donnas']
  },
  {
    id: 'vda-donnas-anselmet',
    name: 'Valle d\'Aosta Donnas',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Donnas',
    grapeVariety: 'Nebbiolo (Picotendro)',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 30,
    producers: ['Anselmet'],
    aliases: ['Anselmet Donnas']
  },
  
  // ENFER D'ARVIER (Red - Petit Rouge)
  {
    id: 'vda-enfer-d-arvier-les-cretes',
    name: 'Valle d\'Aosta Enfer d\'Arvier',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Arvier',
    grapeVariety: 'Petit Rouge, Neyret',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Les Cretes'],
    aliases: ['Les Cretes Enfer d\'Arvier']
  },
  {
    id: 'vda-enfer-d-arvier-grosjean',
    name: 'Valle d\'Aosta Enfer d\'Arvier',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Arvier',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 28,
    producers: ['Grosjean'],
    aliases: ['Grosjean Enfer d\'Arvier']
  },
  {
    id: 'vda-enfer-d-arvier-anselmet',
    name: 'Valle d\'Aosta Enfer d\'Arvier',
    type: 'Red',
    country: 'Italy',
    region: 'Valle d\'Aosta',
    subRegion: 'Arvier',
    grapeVariety: 'Petit Rouge',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 30,
    producers: ['Anselmet'],
    aliases: ['Anselmet Enfer d\'Arvier']
  },
];
