import { WineTemplate } from '@/types/wineDatabase';

/**
 * VENETO WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Soave, Recioto, Valpolicella DOC
 * Updated: January 2025
 */

export const venetoPart2: WineTemplate[] = [
  // SOAVE DOCG (White)
  {
    id: 'soave-pieropan-calvarino',
    name: 'Soave Classico Calvarino',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 1980,
    avgPrice: 35,
    producers: ['Pieropan'],
    aliases: ['Calvarino']
  },
  {
    id: 'soave-pieropan-la-rocca',
    name: 'Soave Classico La Rocca',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 1971,
    avgPrice: 45,
    producers: ['Pieropan'],
    aliases: ['La Rocca']
  },
  {
    id: 'soave-pieropan-classico',
    name: 'Soave Classico',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega, Trebbiano di Soave',
    classification: 'DOCG',
    minVintage: 1968,
    avgPrice: 18,
    producers: ['Pieropan'],
    aliases: ['Pieropan Soave']
  },
  {
    id: 'soave-gini-la-frosca',
    name: 'Soave Classico La Frosca',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 1989,
    avgPrice: 32,
    producers: ['Gini'],
    aliases: ['La Frosca']
  },
  {
    id: 'soave-gini-salvarenza',
    name: 'Soave Classico Salvarenza Vecchie Vigne',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 2001,
    avgPrice: 38,
    producers: ['Gini'],
    aliases: ['Salvarenza']
  },
  {
    id: 'soave-inama-vigneti-foscarino',
    name: 'Soave Classico Vigneti di Foscarino',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 1992,
    avgPrice: 28,
    producers: ['Inama'],
    aliases: ['Vigneti di Foscarino']
  },
  {
    id: 'soave-inama-monte-grande',
    name: 'Soave Classico Vigneto du Lot',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Inama'],
    aliases: ['Vigneto du Lot']
  },
  {
    id: 'soave-prà-monte-grande',
    name: 'Soave Classico Monte Grande',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 1983,
    avgPrice: 32,
    producers: ['Prà'],
    aliases: ['Monte Grande']
  },
  {
    id: 'soave-prà-staforte',
    name: 'Soave Classico Staforte',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Prà'],
    aliases: ['Staforte']
  },
  {
    id: 'soave-coffele-ca-visco',
    name: 'Soave Classico Cà Visco',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 1970,
    avgPrice: 26,
    producers: ['Coffele'],
    aliases: ['Cà Visco']
  },
  {
    id: 'soave-anselmi-capitel-foscarino',
    name: 'Capitel Foscarino Veneto IGT',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'IGT',
    minVintage: 1978,
    avgPrice: 42,
    producers: ['Anselmi'],
    aliases: ['Capitel Foscarino']
  },
  {
    id: 'soave-anselmi-capitel-croce',
    name: 'Capitel Croce Veneto IGT',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'IGT',
    minVintage: 1988,
    avgPrice: 32,
    producers: ['Anselmi'],
    aliases: ['Capitel Croce']
  },
  {
    id: 'soave-suavia-monte-carbonare',
    name: 'Soave Classico Monte Carbonare',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 30,
    producers: ['Suavia'],
    aliases: ['Monte Carbonare']
  },
  {
    id: 'soave-tamellini-le-bine-de-costiola',
    name: 'Soave Classico Le Bine de Costiola',
    type: 'White',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 1998,
    avgPrice: 28,
    producers: ['Tamellini'],
    aliases: ['Le Bine de Costiola']
  },
  
  // RECIOTO DELLA VALPOLICELLA DOCG (Dessert)
  {
    id: 'recioto-quintarelli',
    name: 'Recioto della Valpolicella Classico',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOCG',
    minVintage: 1950,
    avgPrice: 150,
    producers: ['Giuseppe Quintarelli'],
    aliases: ['Quintarelli Recioto']
  },
  {
    id: 'recioto-dal-forno',
    name: 'Recioto della Valpolicella',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 220,
    producers: ['Dal Forno Romano'],
    aliases: ['Dal Forno Recioto']
  },
  {
    id: 'recioto-masi-mezzanella',
    name: 'Recioto della Valpolicella Classico Mezzanella',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOCG',
    minVintage: 1981,
    avgPrice: 55,
    producers: ['Masi'],
    aliases: ['Mezzanella']
  },
  {
    id: 'recioto-bertani',
    name: 'Recioto della Valpolicella Classico',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella',
    classification: 'DOCG',
    minVintage: 1958,
    avgPrice: 48,
    producers: ['Bertani'],
    aliases: ['Bertani Recioto']
  },
  {
    id: 'recioto-tedeschi',
    name: 'Recioto della Valpolicella Classico Capitel Monte Fontana',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 52,
    producers: ['Tedeschi'],
    aliases: ['Capitel Monte Fontana']
  },
  {
    id: 'recioto-speri',
    name: 'Recioto della Valpolicella Classico',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOCG',
    minVintage: 1995,
    avgPrice: 45,
    producers: ['Speri'],
    aliases: ['Speri Recioto']
  },
  {
    id: 'recioto-tommasi',
    name: 'Recioto della Valpolicella Classico',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOCG',
    minVintage: 1997,
    avgPrice: 42,
    producers: ['Tommasi'],
    aliases: ['Tommasi Recioto']
  },
  
  // RECIOTO DI SOAVE DOCG (Sweet White)
  {
    id: 'recioto-soave-pieropan',
    name: 'Recioto di Soave Le Colombare',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 65,
    producers: ['Pieropan'],
    aliases: ['Le Colombare']
  },
  {
    id: 'recioto-soave-inama',
    name: 'Recioto di Soave',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 55,
    producers: ['Inama'],
    aliases: ['Inama Recioto']
  },
  {
    id: 'recioto-soave-gini',
    name: 'Recioto di Soave Col Foscarin',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 1995,
    avgPrice: 48,
    producers: ['Gini'],
    aliases: ['Col Foscarin']
  },
  {
    id: 'recioto-soave-suavia',
    name: 'Recioto di Soave Acinatico',
    type: 'Dessert',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Soave',
    grapeVariety: 'Garganega',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 52,
    producers: ['Suavia'],
    aliases: ['Acinatico']
  },
  
  // VALPOLICELLA DOC (Regular)
  {
    id: 'valpolicella-quintarelli-classico',
    name: 'Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 42,
    producers: ['Giuseppe Quintarelli'],
    aliases: ['Quintarelli Valpolicella Classico']
  },
  {
    id: 'valpolicella-allegrini',
    name: 'Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Oseleta',
    classification: 'DOC',
    minVintage: 1854,
    avgPrice: 16,
    producers: ['Allegrini'],
    aliases: ['Allegrini Valpolicella']
  },
  {
    id: 'valpolicella-masi',
    name: 'Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOC',
    minVintage: 1772,
    avgPrice: 14,
    producers: ['Masi'],
    aliases: ['Masi Valpolicella']
  },
  {
    id: 'valpolicella-bertani',
    name: 'Valpolicella Classico Superiore Valpantena',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella',
    classification: 'DOC',
    minVintage: 1958,
    avgPrice: 18,
    producers: ['Bertani'],
    aliases: ['Valpantena']
  },
  {
    id: 'valpolicella-tommasi-classico',
    name: 'Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1902,
    avgPrice: 14,
    producers: ['Tommasi'],
    aliases: ['Tommasi Valpolicella Classico']
  },
  {
    id: 'valpolicella-zenato',
    name: 'Valpolicella Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella',
    grapeVariety: 'Corvina, Rondinella, Oseleta',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 14,
    producers: ['Zenato'],
    aliases: ['Zenato Valpolicella']
  },
  {
    id: 'valpolicella-speri-classico',
    name: 'Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOC',
    minVintage: 1874,
    avgPrice: 15,
    producers: ['Speri'],
    aliases: ['Speri Valpolicella Classico']
  },
  {
    id: 'valpolicella-tedeschi-classico',
    name: 'Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1630,
    avgPrice: 14,
    producers: ['Tedeschi'],
    aliases: ['Tedeschi Valpolicella Classico']
  },
  {
    id: 'valpolicella-brigaldara',
    name: 'Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1929,
    avgPrice: 13,
    producers: ['Brigaldara'],
    aliases: ['Brigaldara Valpolicella']
  },
  {
    id: 'valpolicella-musella',
    name: 'Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 12,
    producers: ['Musella'],
    aliases: ['Musella Valpolicella']
  },
  {
    id: 'valpolicella-corte-sant-alda',
    name: 'Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Molinara',
    classification: 'DOC',
    minVintage: 1986,
    avgPrice: 14,
    producers: ['Corte Sant\'Alda'],
    aliases: ['Corte Sant\'Alda Valpolicella']
  },
  {
    id: 'valpolicella-venturini-classico',
    name: 'Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1961,
    avgPrice: 12,
    producers: ['Venturini'],
    aliases: ['Venturini Valpolicella']
  },
  {
    id: 'valpolicella-monte-dall-ora',
    name: 'Valpolicella Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 18,
    producers: ['Monte Dall\'Ora'],
    aliases: ['Monte Dall\'Ora Valpolicella']
  },
  {
    id: 'valpolicella-sartori',
    name: 'Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella',
    classification: 'DOC',
    minVintage: 1898,
    avgPrice: 11,
    producers: ['Sartori'],
    aliases: ['Sartori Valpolicella']
  },
  {
    id: 'valpolicella-bussola-classico',
    name: 'Valpolicella Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Veneto',
    subRegion: 'Valpolicella Classico',
    grapeVariety: 'Corvina, Rondinella, Corvinone',
    classification: 'DOC',
    minVintage: 1977,
    avgPrice: 16,
    producers: ['Tommaso Bussola'],
    aliases: ['Bussola Valpolicella Classico']
  },
];
