import { WineTemplate } from '@/types/wineDatabase';

/**
 * LIGURIA WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Rossese di Dolceacqua DOC, Ormeasco di Pornassio, Red wines
 * Updated: January 2025
 */

export const liguriapart2: WineTemplate[] = [
  // ROSSESE DI DOLCEACQUA DOC (Red)
  {
    id: 'rossese-dolceacqua-terre-bianche-arcagna',
    name: 'Rossese di Dolceacqua Superiore Arcagna',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 35,
    producers: ['Terre Bianche'],
    aliases: ['Arcagna Rossese']
  },
  {
    id: 'rossese-dolceacqua-terre-bianche-bricco-arcagna',
    name: 'Rossese di Dolceacqua Superiore Bricco Arcagna',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 42,
    producers: ['Terre Bianche'],
    aliases: ['Bricco Arcagna']
  },
  {
    id: 'rossese-dolceacqua-terre-bianche',
    name: 'Rossese di Dolceacqua',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 22,
    producers: ['Terre Bianche'],
    aliases: ['Terre Bianche Rossese']
  },
  {
    id: 'rossese-dolceacqua-lupi-vignaira',
    name: 'Rossese di Dolceacqua Superiore Vignaira',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 32,
    producers: ['Lupi'],
    aliases: ['Vignaira']
  },
  {
    id: 'rossese-dolceacqua-lupi',
    name: 'Rossese di Dolceacqua',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'DOC',
    minVintage: 1968,
    avgPrice: 20,
    producers: ['Lupi'],
    aliases: ['Lupi Rossese']
  },
  {
    id: 'rossese-dolceacqua-guglierame-beragna',
    name: 'Rossese di Dolceacqua Superiore Beragna',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Guglierame'],
    aliases: ['Beragna']
  },
  {
    id: 'rossese-dolceacqua-guglierame',
    name: 'Rossese di Dolceacqua',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Guglierame'],
    aliases: ['Guglierame Rossese']
  },
  {
    id: 'rossese-dolceacqua-tenuta-giunche',
    name: 'Rossese di Dolceacqua Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Tenuta Giunche'],
    aliases: ['Tenuta Giunche Rossese']
  },
  {
    id: 'rossese-dolceacqua-nico-daneri',
    name: 'Rossese di Dolceacqua',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 22,
    producers: ['Nico Daneri'],
    aliases: ['Nico Daneri Rossese']
  },
  {
    id: 'rossese-dolceacqua-terre-rosse',
    name: 'Rossese di Dolceacqua',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Terre Rosse'],
    aliases: ['Terre Rosse Rossese']
  },
  {
    id: 'rossese-dolceacqua-cascina-praie',
    name: 'Rossese di Dolceacqua',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Cascina Praie'],
    aliases: ['Cascina Praie Rossese']
  },
  
  // ORMEASCO DI PORNASSIO DOC (Red - Dolcetto)
  {
    id: 'ormeasco-pornassio-lupi-superiore',
    name: 'Ormeasco di Pornassio Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pornassio',
    grapeVariety: 'Ormeasco (Dolcetto)',
    classification: 'DOC',
    minVintage: 1975,
    avgPrice: 24,
    producers: ['Lupi'],
    aliases: ['Lupi Ormeasco Superiore']
  },
  {
    id: 'ormeasco-pornassio-lupi',
    name: 'Ormeasco di Pornassio',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pornassio',
    grapeVariety: 'Ormeasco (Dolcetto)',
    classification: 'DOC',
    minVintage: 1968,
    avgPrice: 16,
    producers: ['Lupi'],
    aliases: ['Lupi Ormeasco']
  },
  {
    id: 'ormeasco-pornassio-cascina-nirasca-superiore',
    name: 'Ormeasco di Pornassio Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pornassio',
    grapeVariety: 'Ormeasco (Dolcetto)',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 22,
    producers: ['Cascina Nirasca'],
    aliases: ['Cascina Nirasca Ormeasco Superiore']
  },
  {
    id: 'ormeasco-pornassio-cascina-nirasca',
    name: 'Ormeasco di Pornassio',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pornassio',
    grapeVariety: 'Ormeasco (Dolcetto)',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 14,
    producers: ['Cascina Nirasca'],
    aliases: ['Cascina Nirasca Ormeasco']
  },
  {
    id: 'ormeasco-pornassio-bruna',
    name: 'Ormeasco di Pornassio',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pornassio',
    grapeVariety: 'Ormeasco (Dolcetto)',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Bruna'],
    aliases: ['Bruna Ormeasco']
  },
  
  // ORMEASCO SCIAC-TRÀ (Light red/rosé)
  {
    id: 'ormeasco-sciac-tra-lupi',
    name: 'Ormeasco Sciac-trà',
    type: 'Rosé',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pornassio',
    grapeVariety: 'Ormeasco (Dolcetto)',
    classification: 'DOC',
    minVintage: 1975,
    avgPrice: 14,
    producers: ['Lupi'],
    aliases: ['Lupi Sciac-trà']
  },
  {
    id: 'ormeasco-sciac-tra-cascina-nirasca',
    name: 'Ormeasco Sciac-trà',
    type: 'Rosé',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pornassio',
    grapeVariety: 'Ormeasco (Dolcetto)',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 14,
    producers: ['Cascina Nirasca'],
    aliases: ['Cascina Nirasca Sciac-trà']
  },
  {
    id: 'ormeasco-sciac-tra-bruna',
    name: 'Ormeasco Sciac-trà',
    type: 'Rosé',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pornassio',
    grapeVariety: 'Ormeasco (Dolcetto)',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 13,
    producers: ['Bruna'],
    aliases: ['Bruna Sciac-trà']
  },
  
  // RIVIERA LIGURE DI PONENTE ROSSESE DOC (Red)
  {
    id: 'rossese-ponente-lupi',
    name: 'Riviera Ligure di Ponente Rossese',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pieve di Teco',
    grapeVariety: 'Rossese',
    classification: 'DOC',
    minVintage: 1975,
    avgPrice: 18,
    producers: ['Lupi'],
    aliases: ['Lupi Rossese Ponente']
  },
  {
    id: 'rossese-ponente-terre-bianche',
    name: 'Riviera Ligure di Ponente Rossese',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Terre Bianche'],
    aliases: ['Terre Bianche Rossese Ponente']
  },
  
  // VAL POLCÈVERA DOC (Red & White)
  {
    id: 'val-polcevera-bianchetta-bisson',
    name: 'Val Polcèvera Bianchetta Genovese',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Genoa',
    grapeVariety: 'Bianchetta Genovese, Vermentino',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 18,
    producers: ['Bisson'],
    aliases: ['Bisson Bianchetta']
  },
  {
    id: 'val-polcevera-coronata-bisson',
    name: 'Val Polcèvera Coronata',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Genoa',
    grapeVariety: 'Bianchetta Genovese, Vermentino, Bosco',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 22,
    producers: ['Bisson'],
    aliases: ['Coronata']
  },
  {
    id: 'val-polcevera-ciliegiolo-bisson',
    name: 'Val Polcèvera Ciliegiolo',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Genoa',
    grapeVariety: 'Ciliegiolo',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 20,
    producers: ['Bisson'],
    aliases: ['Bisson Ciliegiolo']
  },
  
  // COLLINE DI LEVANTO DOC (White)
  {
    id: 'colline-levanto-bisson',
    name: 'Colline di Levanto Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Levanto',
    grapeVariety: 'Vermentino, Albarola, Bosco',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Bisson'],
    aliases: ['Bisson Colline di Levanto']
  },
  
  // PREMIUM WINES (Liguria IGT)
  {
    id: 'liguria-bisson-u-pastine',
    name: 'U Pastine Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Bianchetta Genovese',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Bisson'],
    aliases: ['U Pastine']
  },
  {
    id: 'liguria-bisson-vigna-erta',
    name: 'Vigna Erta Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Bisson'],
    aliases: ['Vigna Erta']
  },
  {
    id: 'liguria-terre-bianche-rossese-superiore-bricco',
    name: 'Bricco Arcagna Rossese Liguria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Rossese',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Terre Bianche'],
    aliases: ['Bricco Arcagna IGT']
  },
  {
    id: 'liguria-lupi-barbadirame',
    name: 'Barbadirame Liguria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pieve di Teco',
    grapeVariety: 'Rossese, Ormeasco',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Lupi'],
    aliases: ['Barbadirame']
  },
  {
    id: 'liguria-cantine-lunae-number-five',
    name: 'Number Five Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 38,
    producers: ['Cantine Lunae Bosoni'],
    aliases: ['Number Five']
  },
  {
    id: 'liguria-terenzuola-sciara',
    name: 'Sciara Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 32,
    producers: ['Terenzuola'],
    aliases: ['Sciara']
  },
  {
    id: 'liguria-vis-amoris-nebbiosu',
    name: 'Nebbiosu Liguria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ranzo',
    grapeVariety: 'Nebbiolo',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 35,
    producers: ['Vis Amoris'],
    aliases: ['Nebbiosu']
  },
  {
    id: 'liguria-durin-ormea',
    name: 'Ormea Liguria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Ortovero',
    grapeVariety: 'Ormeasco, Rossese',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Durin'],
    aliases: ['Ormea']
  },
  
  // INTERNATIONAL VARIETIES
  {
    id: 'syrah-terre-bianche',
    name: 'Syrah Liguria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Dolceacqua',
    grapeVariety: 'Syrah',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Terre Bianche'],
    aliases: ['Terre Bianche Syrah']
  },
  {
    id: 'merlot-lupi',
    name: 'Merlot Liguria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Pieve di Teco',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Lupi'],
    aliases: ['Lupi Merlot']
  },
  {
    id: 'chardonnay-bisson',
    name: 'Chardonnay Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'Sestri Levante',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Bisson'],
    aliases: ['Bisson Chardonnay']
  },
  {
    id: 'sauvignon-blanc-cantine-lunae',
    name: 'Sauvignon Blanc Liguria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Liguria',
    subRegion: 'La Spezia',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Cantine Lunae Bosoni'],
    aliases: ['Lunae Sauvignon']
  },
];
