import { WineTemplate } from '@/types/wineDatabase';

/**
 * FRIULI-VENEZIA GIULIA WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Pinot Grigio, Friulano (Tocai Friulano), Sauvignon Blanc
 * Updated: January 2025
 */

export const friuliPart1: WineTemplate[] = [
  // PINOT GRIGIO - COLLIO DOC
  {
    id: 'pinot-grigio-jermann',
    name: 'Pinot Grigio Venezia Giulia IGT',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Pinot Grigio',
    classification: 'IGT',
    minVintage: 1975,
    avgPrice: 22,
    producers: ['Jermann'],
    aliases: ['Jermann Pinot Grigio']
  },
  {
    id: 'pinot-grigio-marco-felluga',
    name: 'Pinot Grigio Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1956,
    avgPrice: 20,
    producers: ['Marco Felluga'],
    aliases: ['Marco Felluga Pinot Grigio']
  },
  {
    id: 'pinot-grigio-livio-felluga',
    name: 'Pinot Grigio Colli Orientali del Friuli',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1956,
    avgPrice: 24,
    producers: ['Livio Felluga'],
    aliases: ['Livio Felluga Pinot Grigio']
  },
  {
    id: 'pinot-grigio-venica-ronco-bernizza',
    name: 'Pinot Grigio Collio Ronco Bernizza',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1930,
    avgPrice: 32,
    producers: ['Venica & Venica'],
    aliases: ['Ronco Bernizza']
  },
  {
    id: 'pinot-grigio-venica',
    name: 'Pinot Grigio Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1930,
    avgPrice: 18,
    producers: ['Venica & Venica'],
    aliases: ['Venica Pinot Grigio']
  },
  {
    id: 'pinot-grigio-edi-keber',
    name: 'Pinot Grigio Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1957,
    avgPrice: 28,
    producers: ['Edi Keber'],
    aliases: ['Keber Pinot Grigio']
  },
  {
    id: 'pinot-grigio-gravner',
    name: 'Pinot Grigio Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Pinot Grigio',
    classification: 'IGT',
    minVintage: 1973,
    avgPrice: 85,
    producers: ['Gravner', 'Josko Gravner'],
    aliases: ['Gravner Pinot Grigio']
  },
  {
    id: 'pinot-grigio-radikon',
    name: 'Pinot Grigio Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Pinot Grigio',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 65,
    producers: ['Radikon', 'Stanko Radikon'],
    aliases: ['Radikon Pinot Grigio']
  },
  {
    id: 'pinot-grigio-vie-di-romans',
    name: 'Pinot Grigio Isonzo Dessimis',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Isonzo',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 48,
    producers: ['Vie di Romans'],
    aliases: ['Dessimis']
  },
  {
    id: 'pinot-grigio-villa-russiz',
    name: 'Pinot Grigio Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Pinot Grigio',
    classification: 'DOC',
    minVintage: 1869,
    avgPrice: 26,
    producers: ['Villa Russiz'],
    aliases: ['Villa Russiz Pinot Grigio']
  },
  
  // FRIULANO (TOCAI FRIULANO) - COLLIO & COLLI ORIENTALI
  {
    id: 'friulano-jermann',
    name: 'Friulano Venezia Giulia IGT',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Friulano',
    classification: 'IGT',
    minVintage: 1975,
    avgPrice: 20,
    producers: ['Jermann'],
    aliases: ['Jermann Friulano']
  },
  {
    id: 'friulano-venica-ronco-delle-mele',
    name: 'Friulano Collio Ronco delle Mele',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Friulano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 38,
    producers: ['Venica & Venica'],
    aliases: ['Ronco delle Mele']
  },
  {
    id: 'friulano-venica',
    name: 'Friulano Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Friulano',
    classification: 'DOC',
    minVintage: 1930,
    avgPrice: 20,
    producers: ['Venica & Venica'],
    aliases: ['Venica Friulano']
  },
  {
    id: 'friulano-livio-felluga',
    name: 'Friulano Colli Orientali del Friuli',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Friulano',
    classification: 'DOC',
    minVintage: 1956,
    avgPrice: 24,
    producers: ['Livio Felluga'],
    aliases: ['Livio Felluga Friulano']
  },
  {
    id: 'friulano-marco-felluga',
    name: 'Friulano Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Friulano',
    classification: 'DOC',
    minVintage: 1956,
    avgPrice: 22,
    producers: ['Marco Felluga'],
    aliases: ['Marco Felluga Friulano']
  },
  {
    id: 'friulano-gravner',
    name: 'Friulano Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Friulano',
    classification: 'IGT',
    minVintage: 1973,
    avgPrice: 75,
    producers: ['Gravner'],
    aliases: ['Gravner Friulano']
  },
  {
    id: 'friulano-radikon',
    name: 'Friulano Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Friulano',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 55,
    producers: ['Radikon'],
    aliases: ['Radikon Friulano']
  },
  {
    id: 'friulano-edi-keber',
    name: 'Friulano Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Friulano',
    classification: 'DOC',
    minVintage: 1957,
    avgPrice: 32,
    producers: ['Edi Keber'],
    aliases: ['Keber Friulano']
  },
  {
    id: 'friulano-vie-di-romans-piere',
    name: 'Friulano Isonzo Piere',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Isonzo',
    grapeVariety: 'Friulano',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 52,
    producers: ['Vie di Romans'],
    aliases: ['Piere']
  },
  {
    id: 'friulano-villa-russiz',
    name: 'Friulano Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Friulano',
    classification: 'DOC',
    minVintage: 1869,
    avgPrice: 28,
    producers: ['Villa Russiz'],
    aliases: ['Villa Russiz Friulano']
  },
  
  // SAUVIGNON BLANC - COLLIO & COLLI ORIENTALI
  {
    id: 'sauvignon-jermann-were-dreams',
    name: 'Were Dreams... Now It Is Just Wine Venezia Giulia IGT',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc, Chardonnay, Picolit',
    classification: 'IGT',
    minVintage: 1987,
    avgPrice: 95,
    producers: ['Jermann'],
    aliases: ['Were Dreams']
  },
  {
    id: 'sauvignon-jermann',
    name: 'Sauvignon Venezia Giulia IGT',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 1975,
    avgPrice: 24,
    producers: ['Jermann'],
    aliases: ['Jermann Sauvignon']
  },
  {
    id: 'sauvignon-venica-ronco-delle-cime',
    name: 'Sauvignon Collio Ronco delle Cime',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 42,
    producers: ['Venica & Venica'],
    aliases: ['Ronco delle Cime']
  },
  {
    id: 'sauvignon-venica',
    name: 'Sauvignon Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1930,
    avgPrice: 22,
    producers: ['Venica & Venica'],
    aliases: ['Venica Sauvignon']
  },
  {
    id: 'sauvignon-marco-felluga',
    name: 'Sauvignon Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1956,
    avgPrice: 24,
    producers: ['Marco Felluga'],
    aliases: ['Marco Felluga Sauvignon']
  },
  {
    id: 'sauvignon-livio-felluga',
    name: 'Sauvignon Colli Orientali del Friuli',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1956,
    avgPrice: 26,
    producers: ['Livio Felluga'],
    aliases: ['Livio Felluga Sauvignon']
  },
  {
    id: 'sauvignon-vie-di-romans-vieris',
    name: 'Sauvignon Isonzo Vieris',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Isonzo',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 55,
    producers: ['Vie di Romans'],
    aliases: ['Vieris']
  },
  {
    id: 'sauvignon-villa-russiz',
    name: 'Sauvignon de la Tour Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 38,
    producers: ['Villa Russiz'],
    aliases: ['Sauvignon de la Tour']
  },
  {
    id: 'sauvignon-edi-keber',
    name: 'Sauvignon Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1957,
    avgPrice: 35,
    producers: ['Edi Keber'],
    aliases: ['Keber Sauvignon']
  },
  {
    id: 'sauvignon-schiopetto',
    name: 'Sauvignon Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 32,
    producers: ['Schiopetto'],
    aliases: ['Schiopetto Sauvignon']
  },
  {
    id: 'sauvignon-russiz-superiore-collio-monte-degli-ori',
    name: 'Sauvignon Collio Monte degli Ori',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1967,
    avgPrice: 42,
    producers: ['Russiz Superiore'],
    aliases: ['Monte degli Ori']
  },
  {
    id: 'sauvignon-gravner',
    name: 'Sauvignon Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 1973,
    avgPrice: 78,
    producers: ['Gravner'],
    aliases: ['Gravner Sauvignon']
  },
  {
    id: 'sauvignon-doro-princic',
    name: 'Sauvignon Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1993,
    avgPrice: 28,
    producers: ['Doro Princic'],
    aliases: ['Princic Sauvignon']
  },
  {
    id: 'sauvignon-damijan-podversic',
    name: 'Sauvignon Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 1988,
    avgPrice: 68,
    producers: ['Damijan Podversic'],
    aliases: ['Podversic Sauvignon']
  },
  {
    id: 'sauvignon-la-castellada',
    name: 'Sauvignon Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 1985,
    avgPrice: 72,
    producers: ['La Castellada'],
    aliases: ['La Castellada Sauvignon']
  },
  {
    id: 'sauvignon-zidarich',
    name: 'Sauvignon Carso',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Carso',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1988,
    avgPrice: 35,
    producers: ['Zidarich'],
    aliases: ['Zidarich Sauvignon']
  },
  {
    id: 'sauvignon-le-vigne-di-zamo',
    name: 'Sauvignon Colli Orientali del Friuli',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 26,
    producers: ['Le Vigne di Zamò'],
    aliases: ['Zamò Sauvignon']
  },
  {
    id: 'sauvignon-ronco-del-gnemiz',
    name: 'Sauvignon Colli Orientali del Friuli',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1964,
    avgPrice: 28,
    producers: ['Ronco del Gnemiz'],
    aliases: ['Gnemiz Sauvignon']
  },
  {
    id: 'sauvignon-borgo-del-tiglio',
    name: 'Sauvignon Collio',
    type: 'White',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1981,
    avgPrice: 45,
    producers: ['Borgo del Tiglio'],
    aliases: ['Borgo del Tiglio Sauvignon']
  },
];
