import { WineTemplate } from '@/types/wineDatabase';

/**
 * MARCHE WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Verdicchio dei Castelli di Jesi DOC & DOCG
 * Updated: January 2025
 */

export const marchePart1: WineTemplate[] = [
  // VERDICCHIO DEI CASTELLI DI JESI CLASSICO SUPERIORE DOCG
  {
    id: 'verdicchio-umani-ronchi-plenio',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Plenio',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 38,
    producers: ['Umani Ronchi'],
    aliases: ['Plenio']
  },
  {
    id: 'verdicchio-umani-ronchi-casal-di-serra',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Casal di Serra',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 28,
    producers: ['Umani Ronchi'],
    aliases: ['Casal di Serra']
  },
  {
    id: 'verdicchio-umani-ronchi',
    name: 'Verdicchio dei Castelli di Jesi Classico',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1957,
    avgPrice: 14,
    producers: ['Umani Ronchi'],
    aliases: ['Umani Ronchi Verdicchio']
  },
  {
    id: 'verdicchio-bucci-villa-bucci-riserva',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Villa Bucci Riserva',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 1983,
    avgPrice: 42,
    producers: ['Bucci'],
    aliases: ['Villa Bucci Riserva']
  },
  {
    id: 'verdicchio-bucci',
    name: 'Verdicchio dei Castelli di Jesi Classico',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1983,
    avgPrice: 18,
    producers: ['Bucci'],
    aliases: ['Bucci Verdicchio']
  },
  {
    id: 'verdicchio-garofoli-podium',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Podium',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Garofoli'],
    aliases: ['Podium']
  },
  {
    id: 'verdicchio-garofoli-serra-fiorese',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Serra Fiorese',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Garofoli'],
    aliases: ['Serra Fiorese']
  },
  {
    id: 'verdicchio-garofoli',
    name: 'Verdicchio dei Castelli di Jesi Classico',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1901,
    avgPrice: 12,
    producers: ['Garofoli'],
    aliases: ['Garofoli Verdicchio']
  },
  {
    id: 'verdicchio-sartarelli-balciana',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Balciana',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 1972,
    avgPrice: 35,
    producers: ['Sartarelli'],
    aliases: ['Balciana']
  },
  {
    id: 'verdicchio-sartarelli-tralivio',
    name: 'Verdicchio dei Castelli di Jesi Classico Tralivio',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Sartarelli'],
    aliases: ['Tralivio']
  },
  {
    id: 'verdicchio-sartarelli',
    name: 'Verdicchio dei Castelli di Jesi Classico',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1972,
    avgPrice: 14,
    producers: ['Sartarelli'],
    aliases: ['Sartarelli Verdicchio']
  },
  {
    id: 'verdicchio-fazi-battaglia-san-sisto',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore San Sisto',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Fazi Battaglia'],
    aliases: ['San Sisto']
  },
  {
    id: 'verdicchio-fazi-battaglia',
    name: 'Verdicchio dei Castelli di Jesi',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1949,
    avgPrice: 12,
    producers: ['Fazi Battaglia'],
    aliases: ['Fazi Battaglia Verdicchio']
  },
  {
    id: 'verdicchio-marotti-campi-salmariano',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Salmariano',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 1999,
    avgPrice: 32,
    producers: ['Marotti Campi'],
    aliases: ['Salmariano']
  },
  {
    id: 'verdicchio-marotti-campi-albiano',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Albiano',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Marotti Campi'],
    aliases: ['Albiano']
  },
  {
    id: 'verdicchio-marotti-campi',
    name: 'Verdicchio dei Castelli di Jesi Classico',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1999,
    avgPrice: 14,
    producers: ['Marotti Campi'],
    aliases: ['Marotti Campi Verdicchio']
  },
  {
    id: 'verdicchio-monte-schiavo-pallio',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Pallio di San Floriano',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 1994,
    avgPrice: 28,
    producers: ['Monte Schiavo'],
    aliases: ['Pallio di San Floriano']
  },
  {
    id: 'verdicchio-monte-schiavo',
    name: 'Verdicchio dei Castelli di Jesi Classico',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1994,
    avgPrice: 12,
    producers: ['Monte Schiavo'],
    aliases: ['Monte Schiavo Verdicchio']
  },
  {
    id: 'verdicchio-san-lorenzo-solaria',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Solaria',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 26,
    producers: ['Fattoria San Lorenzo'],
    aliases: ['Solaria']
  },
  {
    id: 'verdicchio-san-lorenzo',
    name: 'Verdicchio dei Castelli di Jesi Classico',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 14,
    producers: ['Fattoria San Lorenzo'],
    aliases: ['San Lorenzo Verdicchio']
  },
  {
    id: 'verdicchio-santa-barbara-stefano-antonucci',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Stefano Antonucci',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Santa Barbara'],
    aliases: ['Stefano Antonucci']
  },
  {
    id: 'verdicchio-santa-barbara',
    name: 'Verdicchio dei Castelli di Jesi Classico',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 14,
    producers: ['Santa Barbara'],
    aliases: ['Santa Barbara Verdicchio']
  },
  {
    id: 'verdicchio-colonnara-cuprese',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Cuprese',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 26,
    producers: ['Colonnara'],
    aliases: ['Cuprese']
  },
  {
    id: 'verdicchio-colonnara',
    name: 'Verdicchio dei Castelli di Jesi Classico',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1959,
    avgPrice: 11,
    producers: ['Colonnara'],
    aliases: ['Colonnara Verdicchio']
  },
  {
    id: 'verdicchio-moncaro-le-vele',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Le Vele',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Moncaro'],
    aliases: ['Le Vele']
  },
  {
    id: 'verdicchio-moncaro',
    name: 'Verdicchio dei Castelli di Jesi Classico',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1964,
    avgPrice: 12,
    producers: ['Moncaro'],
    aliases: ['Moncaro Verdicchio']
  },
  {
    id: 'verdicchio-vallerosa-bonci-vigna-san-michele',
    name: 'Verdicchio dei Castelli di Jesi Classico Superiore Vigna San Michele',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 30,
    producers: ['Vallerosa Bonci'],
    aliases: ['Vigna San Michele']
  },
  {
    id: 'verdicchio-vallerosa-bonci',
    name: 'Verdicchio dei Castelli di Jesi Classico',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 14,
    producers: ['Vallerosa Bonci'],
    aliases: ['Vallerosa Bonci Verdicchio']
  },
  {
    id: 'verdicchio-vignamato',
    name: 'Verdicchio dei Castelli di Jesi Classico',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Vignamato'],
    aliases: ['Vignamato Verdicchio']
  },
  
  // VERDICCHIO DI MATELICA DOCG & DOC
  {
    id: 'verdicchio-matelica-bisci-vigneto-fogliano',
    name: 'Verdicchio di Matelica Riserva Vigneto Fogliano',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Matelica',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 38,
    producers: ['Bisci'],
    aliases: ['Vigneto Fogliano']
  },
  {
    id: 'verdicchio-matelica-bisci',
    name: 'Verdicchio di Matelica',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Matelica',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1982,
    avgPrice: 18,
    producers: ['Bisci'],
    aliases: ['Bisci Verdicchio Matelica']
  },
  {
    id: 'verdicchio-matelica-belisario-cambrugiano-riserva',
    name: 'Verdicchio di Matelica Riserva Cambrugiano',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Matelica',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 1971,
    avgPrice: 32,
    producers: ['Belisario'],
    aliases: ['Cambrugiano']
  },
  {
    id: 'verdicchio-matelica-belisario-vigneti-cambrugiano',
    name: 'Verdicchio di Matelica Vigneti Cambrugiano',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Matelica',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1971,
    avgPrice: 18,
    producers: ['Belisario'],
    aliases: ['Vigneti Cambrugiano']
  },
  {
    id: 'verdicchio-matelica-belisario',
    name: 'Verdicchio di Matelica',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Matelica',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1971,
    avgPrice: 14,
    producers: ['Belisario'],
    aliases: ['Belisario Verdicchio Matelica']
  },
  {
    id: 'verdicchio-matelica-collestefano-riserva',
    name: 'Verdicchio di Matelica Riserva',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Matelica',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 1998,
    avgPrice: 28,
    producers: ['Collestefano'],
    aliases: ['Collestefano Riserva']
  },
  {
    id: 'verdicchio-matelica-collestefano',
    name: 'Verdicchio di Matelica',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Matelica',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 16,
    producers: ['Collestefano'],
    aliases: ['Collestefano Verdicchio']
  },
  {
    id: 'verdicchio-matelica-la-monacesca-mirum',
    name: 'Verdicchio di Matelica Riserva Mirum',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Matelica',
    grapeVariety: 'Verdicchio',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['La Monacesca'],
    aliases: ['Mirum']
  },
  {
    id: 'verdicchio-matelica-la-monacesca',
    name: 'Verdicchio di Matelica',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Matelica',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['La Monacesca'],
    aliases: ['La Monacesca Verdicchio']
  },
  {
    id: 'verdicchio-matelica-borgo-paglianetto',
    name: 'Verdicchio di Matelica',
    type: 'White',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Matelica',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Borgo Paglianetto'],
    aliases: ['Borgo Paglianetto Verdicchio']
  },
  
  // VERDICCHIO PASSITO (Sweet)
  {
    id: 'verdicchio-passito-garofoli-serra-fiorese',
    name: 'Verdicchio dei Castelli di Jesi Passito Serra Fiorese',
    type: 'Dessert',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 45,
    producers: ['Garofoli'],
    aliases: ['Serra Fiorese Passito']
  },
  {
    id: 'verdicchio-passito-sartarelli',
    name: 'Verdicchio dei Castelli di Jesi Passito',
    type: 'Dessert',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['Sartarelli'],
    aliases: ['Sartarelli Passito']
  },
  {
    id: 'verdicchio-passito-bucci',
    name: 'Verdicchio dei Castelli di Jesi Passito',
    type: 'Dessert',
    country: 'Italy',
    region: 'Marche',
    subRegion: 'Castelli di Jesi',
    grapeVariety: 'Verdicchio',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 48,
    producers: ['Bucci'],
    aliases: ['Bucci Passito']
  },
];
