import { WineTemplate } from '@/types/wineDatabase';

/**
 * MOLISE WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Sparkling wines, Dessert wines, Premium blends, Additional producers
 * Updated: January 2025
 */

export const molisePart3: WineTemplate[] = [
  // SPARKLING WINES
  {
    id: 'spumante-di-maio-norante-brut',
    name: 'Spumante Brut Metodo Classico Molise IGT',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 28,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Spumante']
  },
  {
    id: 'spumante-borgo-di-colloredo-brut',
    name: 'Spumante Brut Molise IGT',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina, Greco',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 24,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Spumante']
  },
  {
    id: 'spumante-catabbo-brut',
    name: 'Spumante Brut Molise IGT',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 22,
    producers: ['Catabbo'],
    aliases: ['Catabbo Spumante']
  },
  
  // DESSERT/PASSITO WINES
  {
    id: 'moscato-passito-di-maio-norante',
    name: 'Moscato Passito Molise IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Moscato',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Moscato Passito']
  },
  {
    id: 'aglianico-passito-di-maio-norante',
    name: 'Aglianico Passito Molise IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Aglianico Passito']
  },
  {
    id: 'falanghina-passito-borgo-di-colloredo',
    name: 'Falanghina Passito Molise IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 32,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Falanghina Passito']
  },
  
  // PREMIUM BLENDS
  {
    id: 'molise-claudio-cipressi-premium',
    name: 'Premium Selection Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Aglianico, Montepulciano',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 35,
    producers: ['Claudio Cipressi'],
    aliases: ['Cipressi Premium']
  },
  {
    id: 'molise-borgo-di-colloredo-riserva',
    name: 'Riserva Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Montepulciano',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 32,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Riserva']
  },
  {
    id: 'molise-catabbo-selezione',
    name: 'Selezione Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Aglianico',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 32,
    producers: ['Catabbo'],
    aliases: ['Catabbo Selezione']
  },
  {
    id: 'molise-tenimenti-grieco-premium',
    name: 'Premium Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Montepulciano',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 35,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Premium']
  },
  
  // SANGIOVESE (Red variety)
  {
    id: 'sangiovese-di-maio-norante',
    name: 'Sangiovese Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Sangiovese']
  },
  {
    id: 'sangiovese-borgo-di-colloredo',
    name: 'Sangiovese Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Sangiovese']
  },
  
  // ADDITIONAL RED BLENDS
  {
    id: 'molise-di-maio-norante-don-luigi-bianco',
    name: 'Don Luigi Bianco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina, Greco, Fiano',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 22,
    producers: ['Di Majo Norante'],
    aliases: ['Don Luigi Bianco']
  },
  {
    id: 'molise-di-maio-norante-apianae',
    name: 'Apianae Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Moscato',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 24,
    producers: ['Di Majo Norante'],
    aliases: ['Apianae']
  },
  {
    id: 'molise-cianfagna-premium-white',
    name: 'Premium Bianco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina, Fiano',
    classification: 'IGT',
    minVintage: 2014,
    avgPrice: 20,
    producers: ['Cianfagna'],
    aliases: ['Cianfagna Premium Bianco']
  },
  {
    id: 'molise-vinica-premium-white',
    name: 'Premium Bianco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Greco, Falanghina',
    classification: 'IGT',
    minVintage: 2014,
    avgPrice: 20,
    producers: ['Vinica'],
    aliases: ['Vinica Premium Bianco']
  },
  {
    id: 'molise-fattoria-del-duca-premium-white',
    name: 'Premium Bianco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina, Greco',
    classification: 'IGT',
    minVintage: 2016,
    avgPrice: 22,
    producers: ['Fattoria del Duca'],
    aliases: ['Fattoria del Duca Premium Bianco']
  },
  {
    id: 'molise-claudio-cipressi-bianco',
    name: 'Bianco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Falanghina, Greco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Claudio Cipressi'],
    aliases: ['Cipressi Bianco']
  },
  {
    id: 'molise-cantina-sociale-tintilia',
    name: 'Tintilia Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Cantina Sociale Molise'],
    aliases: ['Cantina Sociale Tintilia IGT']
  },
  {
    id: 'molise-cantina-sociale-rosso',
    name: 'Rosso Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Aglianico',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 14,
    producers: ['Cantina Sociale Molise'],
    aliases: ['Cantina Sociale Rosso IGT']
  },
  {
    id: 'molise-cantina-sociale-bianco',
    name: 'Bianco Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Trebbiano, Falanghina',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 11,
    producers: ['Cantina Sociale Molise'],
    aliases: ['Cantina Sociale Bianco IGT']
  },
  
  // ADDITIONAL REGIONAL WINES
  {
    id: 'molise-di-maio-norante-prugnolo',
    name: 'Prugnolo Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Prugnolo',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 18,
    producers: ['Di Majo Norante'],
    aliases: ['Prugnolo']
  },
  {
    id: 'molise-claudio-cipressi-rosato',
    name: 'Rosato Molise IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 14,
    producers: ['Claudio Cipressi'],
    aliases: ['Cipressi Rosato']
  },
  {
    id: 'molise-fattoria-del-duca-rosato',
    name: 'Rosato Molise IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Montepulciano',
    classification: 'IGT',
    minVintage: 2014,
    avgPrice: 14,
    producers: ['Fattoria del Duca'],
    aliases: ['Fattoria del Duca Rosato']
  },
  {
    id: 'molise-cantina-sociale-rosato',
    name: 'Rosato Molise IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 11,
    producers: ['Cantina Sociale Molise'],
    aliases: ['Cantina Sociale Rosato IGT']
  },
  
  // TREBBIANO (White variety)
  {
    id: 'trebbiano-di-maio-norante',
    name: 'Trebbiano Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Trebbiano',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 12,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Trebbiano']
  },
  {
    id: 'trebbiano-borgo-di-colloredo',
    name: 'Trebbiano Molise IGT',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Trebbiano',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 12,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Trebbiano']
  },
  
  // ADDITIONAL PREMIUM SELECTIONS
  {
    id: 'molise-di-maio-norante-biblos',
    name: 'Biblos Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Aglianico, Montepulciano',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 32,
    producers: ['Di Majo Norante'],
    aliases: ['Biblos']
  },
  {
    id: 'molise-borgo-di-colloredo-vigna-grande',
    name: 'Vigna Grande Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 38,
    producers: ['Borgo di Colloredo'],
    aliases: ['Vigna Grande']
  },
  {
    id: 'molise-catabbo-vigna-vecchia',
    name: 'Vigna Vecchia Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2014,
    avgPrice: 35,
    producers: ['Catabbo'],
    aliases: ['Vigna Vecchia']
  },
  {
    id: 'molise-claudio-cipressi-cru',
    name: 'Cru Selection Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 42,
    producers: ['Claudio Cipressi'],
    aliases: ['Cipressi Cru']
  },
  {
    id: 'molise-tenimenti-grieco-gran-riserva',
    name: 'Gran Riserva Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Aglianico',
    classification: 'IGT',
    minVintage: 2014,
    avgPrice: 45,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Gran Riserva']
  },
  {
    id: 'molise-cianfagna-gran-selezione',
    name: 'Gran Selezione Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2016,
    avgPrice: 40,
    producers: ['Cianfagna'],
    aliases: ['Cianfagna Gran Selezione']
  },
  {
    id: 'molise-vinica-riserva-speciale',
    name: 'Riserva Speciale Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2016,
    avgPrice: 38,
    producers: ['Vinica'],
    aliases: ['Vinica Riserva Speciale']
  },
  {
    id: 'molise-fattoria-del-duca-selezione',
    name: 'Selezione Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Montepulciano',
    classification: 'IGT',
    minVintage: 2018,
    avgPrice: 35,
    producers: ['Fattoria del Duca'],
    aliases: ['Fattoria del Duca Selezione']
  },
  {
    id: 'molise-di-maio-norante-more-majorum',
    name: 'More Majorum Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Aglianico, Montepulciano',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 48,
    producers: ['Di Majo Norante'],
    aliases: ['More Majorum']
  },
  {
    id: 'molise-borgo-di-colloredo-antica-tradizione',
    name: 'Antica Tradizione Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2014,
    avgPrice: 42,
    producers: ['Borgo di Colloredo'],
    aliases: ['Antica Tradizione']
  },
  {
    id: 'molise-claudio-cipressi-vigna-antica',
    name: 'Vigna Antica Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 45,
    producers: ['Claudio Cipressi'],
    aliases: ['Vigna Antica']
  },
  {
    id: 'molise-catabbo-terroir',
    name: 'Terroir Selection Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2016,
    avgPrice: 40,
    producers: ['Catabbo'],
    aliases: ['Catabbo Terroir']
  },
  {
    id: 'molise-tenimenti-grieco-classico',
    name: 'Classico Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Montepulciano',
    classification: 'IGT',
    minVintage: 2016,
    avgPrice: 38,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Classico']
  },
  {
    id: 'molise-cianfagna-tradizione',
    name: 'Tradizione Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2018,
    avgPrice: 35,
    producers: ['Cianfagna'],
    aliases: ['Cianfagna Tradizione']
  },
  {
    id: 'molise-vinica-heritage',
    name: 'Heritage Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2018,
    avgPrice: 42,
    producers: ['Vinica'],
    aliases: ['Vinica Heritage']
  },
];
