import { WineTemplate } from '@/types/wineDatabase';

/**
 * PIEDMONT WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Barbaresco DOCG, Nebbiolo d'Alba, Langhe Nebbiolo
 * Updated: January 2025
 */

export const piedmontPart2: WineTemplate[] = [
  // BARBARESCO DOCG - Top Producers
  {
    id: 'barbaresco-gaja',
    name: 'Barbaresco',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1859,
    avgPrice: 150,
    producers: ['Gaja', 'Angelo Gaja'],
    aliases: ['Gaja Barbaresco']
  },
  {
    id: 'barbaresco-gaja-sori-san-lorenzo',
    name: 'Sori San Lorenzo Langhe Nebbiolo',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1967,
    avgPrice: 450,
    producers: ['Gaja'],
    aliases: ['Sori San Lorenzo']
  },
  {
    id: 'barbaresco-gaja-sori-tildin',
    name: 'Sori Tildin Langhe Nebbiolo',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 450,
    producers: ['Gaja'],
    aliases: ['Sori Tildin']
  },
  {
    id: 'barbaresco-gaja-costa-russi',
    name: 'Costa Russi Langhe Nebbiolo',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 450,
    producers: ['Gaja'],
    aliases: ['Costa Russi']
  },
  {
    id: 'barbaresco-bruno-giacosa-asili',
    name: 'Barbaresco Asili',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1967,
    avgPrice: 140,
    producers: ['Bruno Giacosa'],
    aliases: ['Asili']
  },
  {
    id: 'barbaresco-bruno-giacosa-asili-riserva',
    name: 'Barbaresco Asili Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 350,
    producers: ['Bruno Giacosa'],
    aliases: ['Asili Riserva', 'Red Label Asili']
  },
  {
    id: 'barbaresco-bruno-giacosa-rabaja',
    name: 'Barbaresco Rabajà Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 300,
    producers: ['Bruno Giacosa'],
    aliases: ['Rabajà']
  },
  {
    id: 'barbaresco-produttori-barbaresco-asili',
    name: 'Barbaresco Asili Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1958,
    avgPrice: 85,
    producers: ['Produttori del Barbaresco'],
    aliases: ['Asili Produttori']
  },
  {
    id: 'barbaresco-produttori-barbaresco-rabaja',
    name: 'Barbaresco Rabajà Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1967,
    avgPrice: 85,
    producers: ['Produttori del Barbaresco'],
    aliases: ['Rabajà Produttori']
  },
  {
    id: 'barbaresco-produttori-barbaresco-rio-sordo',
    name: 'Barbaresco Rio Sordo Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 80,
    producers: ['Produttori del Barbaresco'],
    aliases: ['Rio Sordo']
  },
  {
    id: 'barbaresco-produttori-barbaresco-montestefano',
    name: 'Barbaresco Montestefano Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1967,
    avgPrice: 85,
    producers: ['Produttori del Barbaresco'],
    aliases: ['Montestefano']
  },
  {
    id: 'barbaresco-produttori-barbaresco-montefico',
    name: 'Barbaresco Montefico Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 80,
    producers: ['Produttori del Barbaresco'],
    aliases: ['Montefico']
  },
  {
    id: 'barbaresco-produttori-barbaresco-pora',
    name: 'Barbaresco Porà Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1967,
    avgPrice: 85,
    producers: ['Produttori del Barbaresco'],
    aliases: ['Porà']
  },
  {
    id: 'barbaresco-roagna-asili',
    name: 'Barbaresco Asili Vecchie Viti',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1989,
    avgPrice: 220,
    producers: ['Roagna'],
    aliases: ['Asili Vecchie Viti']
  },
  {
    id: 'barbaresco-roagna-pajé',
    name: 'Barbaresco Pajé',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1953,
    avgPrice: 180,
    producers: ['Roagna'],
    aliases: ['Pajé']
  },
  {
    id: 'barbaresco-castello-verduno',
    name: 'Barbaresco Rabajà',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1909,
    avgPrice: 75,
    producers: ['Castello di Verduno'],
    aliases: ['Rabajà Verduno']
  },
  {
    id: 'barbaresco-ceretto-bricco-asili',
    name: 'Barbaresco Bricco Asili',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 120,
    producers: ['Ceretto'],
    aliases: ['Bricco Asili']
  },
  {
    id: 'barbaresco-ceretto-bernadot',
    name: 'Barbaresco Bernadot',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 85,
    producers: ['Ceretto'],
    aliases: ['Bernadot']
  },
  {
    id: 'barbaresco-marchesi-gresy-camp-gros',
    name: 'Barbaresco Camp Gros Martinenga',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1973,
    avgPrice: 90,
    producers: ['Marchesi di Grésy'],
    aliases: ['Camp Gros']
  },
  {
    id: 'barbaresco-marchesi-gresy-gaiun',
    name: 'Barbaresco Gaiun Martinenga',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 95,
    producers: ['Marchesi di Grésy'],
    aliases: ['Gaiun']
  },
  {
    id: 'barbaresco-paitin-sori-paitin',
    name: 'Barbaresco Sori Paitin',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1893,
    avgPrice: 75,
    producers: ['Paitin'],
    aliases: ['Sori Paitin']
  },
  {
    id: 'barbaresco-paitin-vecchie-viti',
    name: 'Barbaresco Vecchie Viti',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 95,
    producers: ['Paitin'],
    aliases: ['Vecchie Viti Paitin']
  },
  {
    id: 'barbaresco-sottimano-cottà',
    name: 'Barbaresco Cottà',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1977,
    avgPrice: 85,
    producers: ['Sottimano'],
    aliases: ['Cottà']
  },
  {
    id: 'barbaresco-sottimano-pajorè',
    name: 'Barbaresco Pajorè',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 90,
    producers: ['Sottimano'],
    aliases: ['Pajorè']
  },
  {
    id: 'barbaresco-pio-cesare',
    name: 'Barbaresco',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1881,
    avgPrice: 65,
    producers: ['Pio Cesare'],
    aliases: ['Pio Cesare Barbaresco']
  },
  {
    id: 'barbaresco-pio-cesare-il-bricco',
    name: 'Barbaresco Il Bricco',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 130,
    producers: ['Pio Cesare'],
    aliases: ['Il Bricco']
  },
  {
    id: 'barbaresco-albino-rocca-ronchi',
    name: 'Barbaresco Ronchi',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 65,
    producers: ['Albino Rocca'],
    aliases: ['Ronchi']
  },
  {
    id: 'barbaresco-albino-rocca-loreto',
    name: 'Barbaresco Loreto',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 70,
    producers: ['Albino Rocca'],
    aliases: ['Loreto']
  },
  {
    id: 'barbaresco-moccagatta-basarin',
    name: 'Barbaresco Basarin',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1970,
    avgPrice: 75,
    producers: ['Moccagatta'],
    aliases: ['Basarin']
  },
  {
    id: 'barbaresco-moccagatta-cole',
    name: 'Barbaresco Cole',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 80,
    producers: ['Moccagatta'],
    aliases: ['Cole']
  },
  {
    id: 'barbaresco-pelissero-vanotu',
    name: 'Barbaresco Vanotu',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1960,
    avgPrice: 65,
    producers: ['Pelissero'],
    aliases: ['Vanotu']
  },
  {
    id: 'barbaresco-bruno-rocca-rabaja',
    name: 'Barbaresco Rabajà',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 85,
    producers: ['Bruno Rocca'],
    aliases: ['Rabajà Rocca']
  },
  {
    id: 'barbaresco-bruno-rocca-coparossa',
    name: 'Barbaresco Coparossa',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Barbaresco',
    grapeVariety: 'Nebbiolo',
    classification: 'DOCG',
    minVintage: 1997,
    avgPrice: 75,
    producers: ['Bruno Rocca'],
    aliases: ['Coparossa']
  },
  
  // NEBBIOLO D'ALBA DOC
  {
    id: 'nebbiolo-alba-vietti-perbacco',
    name: 'Nebbiolo d\'Alba Perbacco',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 32,
    producers: ['Vietti'],
    aliases: ['Perbacco']
  },
  {
    id: 'nebbiolo-alba-ceretto-lantasco',
    name: 'Nebbiolo d\'Alba Lantasco',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 28,
    producers: ['Ceretto'],
    aliases: ['Lantasco']
  },
  {
    id: 'nebbiolo-alba-vajra',
    name: 'Nebbiolo d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1972,
    avgPrice: 30,
    producers: ['G.D. Vajra'],
    aliases: ['Vajra Nebbiolo']
  },
  {
    id: 'nebbiolo-alba-pelissero',
    name: 'Nebbiolo d\'Alba',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 26,
    producers: ['Pelissero'],
    aliases: ['Pelissero Nebbiolo']
  },
  {
    id: 'nebbiolo-alba-bruno-giacosa',
    name: 'Nebbiolo d\'Alba Valmaggiore',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Alba',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 45,
    producers: ['Bruno Giacosa'],
    aliases: ['Valmaggiore']
  },
  
  // LANGHE NEBBIOLO DOC
  {
    id: 'langhe-nebbiolo-giacomo-conterno',
    name: 'Langhe Nebbiolo',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Langhe',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 55,
    producers: ['Giacomo Conterno'],
    aliases: ['Conterno Langhe Nebbiolo']
  },
  {
    id: 'langhe-nebbiolo-altare',
    name: 'Langhe Nebbiolo Arborina',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Langhe',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 48,
    producers: ['Elio Altare'],
    aliases: ['Arborina']
  },
  {
    id: 'langhe-nebbiolo-sandrone-valmaggiore',
    name: 'Langhe Nebbiolo Valmaggiore',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Langhe',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 42,
    producers: ['Luciano Sandrone'],
    aliases: ['Valmaggiore Sandrone']
  },
  {
    id: 'langhe-nebbiolo-voerzio',
    name: 'Langhe Nebbiolo Ciabot della Luna',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Langhe',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 45,
    producers: ['Roberto Voerzio'],
    aliases: ['Ciabot della Luna']
  },
  {
    id: 'langhe-nebbiolo-scavino',
    name: 'Langhe Nebbiolo',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Langhe',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 38,
    producers: ['Paolo Scavino'],
    aliases: ['Scavino Langhe Nebbiolo']
  },
  {
    id: 'langhe-nebbiolo-vajra',
    name: 'Langhe Nebbiolo',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Langhe',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 35,
    producers: ['G.D. Vajra'],
    aliases: ['Vajra Langhe Nebbiolo']
  },
  {
    id: 'langhe-nebbiolo-produttori',
    name: 'Langhe Nebbiolo',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Langhe',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 28,
    producers: ['Produttori del Barbaresco'],
    aliases: ['Produttori Langhe Nebbiolo']
  },
  {
    id: 'langhe-nebbiolo-roagna',
    name: 'Langhe Nebbiolo',
    type: 'Red',
    country: 'Italy',
    region: 'Piedmont',
    subRegion: 'Langhe',
    grapeVariety: 'Nebbiolo',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 50,
    producers: ['Roagna'],
    aliases: ['Roagna Langhe Nebbiolo']
  },
];
