import { WineTemplate } from '@/types/wineDatabase';

/**
 * TRENTINO-ALTO ADIGE WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Teroldego, Lagrein, Pinot Noir, Schiava, Marzemino, Trento DOC Sparkling
 * Updated: January 2025
 */

export const trentinoAltoAdigePart3: WineTemplate[] = [
  // TEROLDEGO ROTALIANO DOC (Indigenous red - Trentino)
  {
    id: 'teroldego-foradori-granato',
    name: 'Teroldego Rotaliano Granato',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Piana Rotaliana',
    grapeVariety: 'Teroldego',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 65,
    producers: ['Foradori', 'Elisabetta Foradori'],
    aliases: ['Granato']
  },
  {
    id: 'teroldego-foradori-sgarzon',
    name: 'Teroldego Rotaliano Sgarzon',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Piana Rotaliana',
    grapeVariety: 'Teroldego',
    classification: 'DOC',
    minVintage: 2009,
    avgPrice: 45,
    producers: ['Foradori'],
    aliases: ['Sgarzon']
  },
  {
    id: 'teroldego-foradori-morei',
    name: 'Teroldego Rotaliano Morei',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Piana Rotaliana',
    grapeVariety: 'Teroldego',
    classification: 'DOC',
    minVintage: 2009,
    avgPrice: 42,
    producers: ['Foradori'],
    aliases: ['Morei']
  },
  {
    id: 'teroldego-foradori',
    name: 'Teroldego Rotaliano',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Piana Rotaliana',
    grapeVariety: 'Teroldego',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 28,
    producers: ['Foradori'],
    aliases: ['Foradori Teroldego']
  },
  {
    id: 'teroldego-endrizzi-masetto-riserva',
    name: 'Teroldego Rotaliano Masetto Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Piana Rotaliana',
    grapeVariety: 'Teroldego',
    classification: 'DOC',
    minVintage: 1885,
    avgPrice: 38,
    producers: ['Endrizzi'],
    aliases: ['Masetto']
  },
  {
    id: 'teroldego-cantina-rotaliana',
    name: 'Teroldego Rotaliano Clesurae',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Piana Rotaliana',
    grapeVariety: 'Teroldego',
    classification: 'DOC',
    minVintage: 1931,
    avgPrice: 32,
    producers: ['Cantina Rotaliana'],
    aliases: ['Clesurae']
  },
  {
    id: 'teroldego-cantina-rotaliana-riserva',
    name: 'Teroldego Rotaliano Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Piana Rotaliana',
    grapeVariety: 'Teroldego',
    classification: 'DOC',
    minVintage: 1931,
    avgPrice: 22,
    producers: ['Cantina Rotaliana'],
    aliases: ['Rotaliana Riserva']
  },
  
  // LAGREIN - ALTO ADIGE DOC (Indigenous red)
  {
    id: 'lagrein-alois-lageder-lindenburg',
    name: 'Lagrein Alto Adige Lindenburg',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Bolzano',
    grapeVariety: 'Lagrein',
    classification: 'DOC',
    minVintage: 1991,
    avgPrice: 48,
    producers: ['Alois Lageder'],
    aliases: ['Lindenburg']
  },
  {
    id: 'lagrein-alois-lageder',
    name: 'Lagrein Alto Adige',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Bolzano',
    grapeVariety: 'Lagrein',
    classification: 'DOC',
    minVintage: 1855,
    avgPrice: 26,
    producers: ['Alois Lageder'],
    aliases: ['Lageder Lagrein']
  },
  {
    id: 'lagrein-muri-gries-abtei-riserva',
    name: 'Lagrein Alto Adige Abtei Muri Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Bolzano',
    grapeVariety: 'Lagrein',
    classification: 'DOC',
    minVintage: 1845,
    avgPrice: 42,
    producers: ['Muri-Gries'],
    aliases: ['Abtei Muri']
  },
  {
    id: 'lagrein-muri-gries',
    name: 'Lagrein Alto Adige',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Bolzano',
    grapeVariety: 'Lagrein',
    classification: 'DOC',
    minVintage: 1845,
    avgPrice: 22,
    producers: ['Muri-Gries'],
    aliases: ['Muri-Gries Lagrein']
  },
  {
    id: 'lagrein-elena-walch',
    name: 'Lagrein Alto Adige Castel Ringberg',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Lagrein',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 38,
    producers: ['Elena Walch'],
    aliases: ['Castel Ringberg Lagrein']
  },
  {
    id: 'lagrein-cantina-bolzano-taber-riserva',
    name: 'Lagrein Alto Adige Taber Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Bolzano',
    grapeVariety: 'Lagrein',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 45,
    producers: ['Cantina Bolzano'],
    aliases: ['Taber']
  },
  {
    id: 'lagrein-cantina-bolzano',
    name: 'Lagrein Alto Adige',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Bolzano',
    grapeVariety: 'Lagrein',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 24,
    producers: ['Cantina Bolzano'],
    aliases: ['Bolzano Lagrein']
  },
  {
    id: 'lagrein-nals-margreid-baron-salvadori',
    name: 'Lagrein Alto Adige Baron Salvadori Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Bolzano',
    grapeVariety: 'Lagrein',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 38,
    producers: ['Nals Margreid'],
    aliases: ['Baron Salvadori']
  },
  {
    id: 'lagrein-Baron-widmann',
    name: 'Lagrein Alto Adige',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Bolzano',
    grapeVariety: 'Lagrein',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 32,
    producers: ['Baron Widmann'],
    aliases: ['Widmann Lagrein']
  },
  {
    id: 'lagrein-kretzer-muri-gries',
    name: 'Lagrein Kretzer Alto Adige',
    type: 'Rosé',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Bolzano',
    grapeVariety: 'Lagrein',
    classification: 'DOC',
    minVintage: 1845,
    avgPrice: 18,
    producers: ['Muri-Gries'],
    aliases: ['Lagrein Rosé']
  },
  
  // PINOT NERO (PINOT NOIR) - ALTO ADIGE DOC
  {
    id: 'pinot-nero-st-michael-eppan-sanct-valentin',
    name: 'Pinot Nero Alto Adige Sanct Valentin',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Appiano',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 1986,
    avgPrice: 58,
    producers: ['St. Michael-Eppan'],
    aliases: ['Sanct Valentin Pinot Nero']
  },
  {
    id: 'pinot-nero-nals-margreid-Baron-salvadori',
    name: 'Pinot Nero Alto Adige Baron Salvadori',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Mazzon',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 52,
    producers: ['Nals Margreid'],
    aliases: ['Baron Salvadori Pinot Nero']
  },
  {
    id: 'pinot-nero-nals-margreid',
    name: 'Pinot Nero Alto Adige',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Nalles-Magrè',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 1932,
    avgPrice: 28,
    producers: ['Nals Margreid'],
    aliases: ['Nals Margreid Pinot Nero']
  },
  {
    id: 'pinot-nero-alois-lageder',
    name: 'Pinot Nero Alto Adige',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 1855,
    avgPrice: 32,
    producers: ['Alois Lageder'],
    aliases: ['Lageder Pinot Nero']
  },
  {
    id: 'pinot-nero-franz-haas-schweizer',
    name: 'Pinot Nero Alto Adige Schweizer',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Montagna',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 48,
    producers: ['Franz Haas'],
    aliases: ['Schweizer']
  },
  {
    id: 'pinot-nero-hofstatter-barthenau-vigna-sant-urbano',
    name: 'Pinot Nero Alto Adige Barthenau Vigna S. Urbano',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Mazzon',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 1986,
    avgPrice: 65,
    producers: ['J. Hofstätter'],
    aliases: ['Barthenau']
  },
  
  // SCHIAVA (VERNATSCH) - ALTO ADIGE DOC
  {
    id: 'schiava-st-michael-eppan',
    name: 'Schiava Alto Adige',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Appiano',
    grapeVariety: 'Schiava',
    classification: 'DOC',
    minVintage: 1907,
    avgPrice: 16,
    producers: ['St. Michael-Eppan'],
    aliases: ['St. Michael Schiava']
  },
  {
    id: 'schiava-caldaro-cantina-kaltern',
    name: 'Caldaro Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Caldaro',
    grapeVariety: 'Schiava',
    classification: 'DOC',
    minVintage: 1906,
    avgPrice: 14,
    producers: ['Cantina Kaltern'],
    aliases: ['Lago di Caldaro']
  },
  {
    id: 'schiava-elena-walch',
    name: 'Schiava Alto Adige',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Schiava',
    classification: 'DOC',
    minVintage: 1869,
    avgPrice: 15,
    producers: ['Elena Walch'],
    aliases: ['Elena Walch Schiava']
  },
  {
    id: 'schiava-alois-lageder',
    name: 'Schiava Alto Adige',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Schiava',
    classification: 'DOC',
    minVintage: 1855,
    avgPrice: 18,
    producers: ['Alois Lageder'],
    aliases: ['Lageder Schiava']
  },
  
  // MARZEMINO - TRENTINO DOC
  {
    id: 'marzemino-concilio-maso-cervara',
    name: 'Marzemino Trentino Maso Cervara',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Volano',
    grapeVariety: 'Marzemino',
    classification: 'DOC',
    minVintage: 1966,
    avgPrice: 28,
    producers: ['Concilio'],
    aliases: ['Maso Cervara']
  },
  {
    id: 'marzemino-cavit',
    name: 'Marzemino Trentino',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Trentino',
    grapeVariety: 'Marzemino',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 16,
    producers: ['Cavit'],
    aliases: ['Cavit Marzemino']
  },
  {
    id: 'marzemino-vallarom',
    name: 'Marzemino Trentino',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Trentino',
    grapeVariety: 'Marzemino',
    classification: 'DOC',
    minVintage: 1976,
    avgPrice: 18,
    producers: ['Vallarom'],
    aliases: ['Vallarom Marzemino']
  },
  
  // TRENTO DOC - SPARKLING WINES (METODO CLASSICO)
  {
    id: 'trento-doc-ferrari-brut',
    name: 'Trento DOC Brut',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Trento',
    grapeVariety: 'Chardonnay, Pinot Noir',
    classification: 'DOC',
    minVintage: 1902,
    avgPrice: 28,
    producers: ['Ferrari'],
    aliases: ['Ferrari Brut']
  },
  {
    id: 'trento-doc-rotari-brut',
    name: 'Trento DOC Brut',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Trento',
    grapeVariety: 'Chardonnay, Pinot Noir',
    classification: 'DOC',
    minVintage: 1976,
    avgPrice: 22,
    producers: ['Rotari', 'Mezzacorona'],
    aliases: ['Rotari Brut']
  },
  {
    id: 'trento-doc-rotari-talento-riserva',
    name: 'Trento DOC Riserva Talento',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Trento',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 35,
    producers: ['Rotari'],
    aliases: ['Talento']
  },
  {
    id: 'trento-doc-cesarini-sforza',
    name: 'Trento DOC Aquila Reale Riserva',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Trento',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1974,
    avgPrice: 42,
    producers: ['Cesarini Sforza'],
    aliases: ['Aquila Reale']
  },
  {
    id: 'trento-doc-cavit-altemasi-graal',
    name: 'Trento DOC Altemasi Graal Riserva',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Trento',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 2009,
    avgPrice: 48,
    producers: ['Cavit', 'Altemasi'],
    aliases: ['Graal']
  },
  {
    id: 'trento-doc-abate-nero-balter',
    name: 'Trento DOC Abate Nero Riserva',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Trento',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 55,
    producers: ['Balter'],
    aliases: ['Abate Nero']
  },
  
  // PREMIUM RED BLENDS
  {
    id: 'cabernet-alois-lageder-cor-romigberg',
    name: 'Cabernet Alto Adige Cor Römigberg',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Cabernet Sauvignon, Cabernet Franc, Merlot',
    classification: 'DOC',
    minVintage: 1986,
    avgPrice: 62,
    producers: ['Alois Lageder'],
    aliases: ['Cor Römigberg Rosso']
  },
  {
    id: 'merlot-elena-walch-castel-ringberg',
    name: 'Merlot Alto Adige Castel Ringberg',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Alto Adige',
    grapeVariety: 'Merlot',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 42,
    producers: ['Elena Walch'],
    aliases: ['Castel Ringberg Merlot']
  },
  {
    id: 'cabernet-sauvignon-franz-haas',
    name: 'Cabernet Sauvignon Alto Adige',
    type: 'Red',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    subRegion: 'Montagna',
    grapeVariety: 'Cabernet Sauvignon',
    classification: 'DOC',
    minVintage: 1880,
    avgPrice: 38,
    producers: ['Franz Haas'],
    aliases: ['Franz Haas Cabernet']
  },
];
