import { WineTemplate } from '@/types/wineDatabase';

/**
 * EMILIA-ROMAGNA WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Albana di Romagna DOCG, Pignoletto, Trebbiano, White wines
 * Updated: January 2025
 */

export const emiliaRomagnaPart3: WineTemplate[] = [
  // ALBANA DI ROMAGNA DOCG (White - Italy's first white DOCG)
  {
    id: 'albana-romagna-fattoria-zerbina-scacco-matto',
    name: 'Albana di Romagna Passito Scacco Matto',
    type: 'Dessert',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Faenza',
    grapeVariety: 'Albana',
    classification: 'DOCG',
    minVintage: 1987,
    avgPrice: 55,
    producers: ['Fattoria Zerbina'],
    aliases: ['Scacco Matto']
  },
  {
    id: 'albana-romagna-fattoria-zerbina-arrocco',
    name: 'Albana di Romagna Secco Arrocco',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Faenza',
    grapeVariety: 'Albana',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Fattoria Zerbina'],
    aliases: ['Arrocco']
  },
  {
    id: 'albana-romagna-fattoria-zerbina',
    name: 'Albana di Romagna Secco',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Faenza',
    grapeVariety: 'Albana',
    classification: 'DOCG',
    minVintage: 1987,
    avgPrice: 16,
    producers: ['Fattoria Zerbina'],
    aliases: ['Zerbina Albana']
  },
  {
    id: 'albana-romagna-tre-monti-vigna-rocca',
    name: 'Albana di Romagna Passito Vigna Rocca',
    type: 'Dessert',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Imola',
    grapeVariety: 'Albana',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['Tre Monti'],
    aliases: ['Vigna Rocca']
  },
  {
    id: 'albana-romagna-tre-monti',
    name: 'Albana di Romagna Secco',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Imola',
    grapeVariety: 'Albana',
    classification: 'DOCG',
    minVintage: 1996,
    avgPrice: 16,
    producers: ['Tre Monti'],
    aliases: ['Tre Monti Albana']
  },
  {
    id: 'albana-romagna-san-patrignano',
    name: 'Albana di Romagna Secco',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Rimini',
    grapeVariety: 'Albana',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 14,
    producers: ['San Patrignano'],
    aliases: ['San Patrignano Albana']
  },
  {
    id: 'albana-romagna-poderi-dal-nespoli',
    name: 'Albana di Romagna Secco',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Forlì',
    grapeVariety: 'Albana',
    classification: 'DOCG',
    minVintage: 1929,
    avgPrice: 14,
    producers: ['Poderi dal Nespoli'],
    aliases: ['Dal Nespoli Albana']
  },
  {
    id: 'albana-romagna-villa-papiano',
    name: 'Albana di Romagna Secco',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Bertinoro',
    grapeVariety: 'Albana',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Villa Papiano'],
    aliases: ['Villa Papiano Albana']
  },
  {
    id: 'albana-romagna-passito-tre-monti',
    name: 'Albana di Romagna Passito',
    type: 'Dessert',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Imola',
    grapeVariety: 'Albana',
    classification: 'DOCG',
    minVintage: 1996,
    avgPrice: 32,
    producers: ['Tre Monti'],
    aliases: ['Tre Monti Passito']
  },
  {
    id: 'albana-romagna-amabile-san-patrignano',
    name: 'Albana di Romagna Amabile',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Rimini',
    grapeVariety: 'Albana',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 16,
    producers: ['San Patrignano'],
    aliases: ['San Patrignano Amabile']
  },
  
  // PIGNOLETTO DOC (White - Colli Bolognesi)
  {
    id: 'pignoletto-monte-delle-vigne',
    name: 'Colli Bolognesi Pignoletto Frizzante',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Bologna',
    grapeVariety: 'Pignoletto',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 14,
    producers: ['Monte delle Vigne'],
    aliases: ['Monte delle Vigne Pignoletto']
  },
  {
    id: 'pignoletto-bonzara',
    name: 'Colli Bolognesi Pignoletto Frizzante',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Bologna',
    grapeVariety: 'Pignoletto',
    classification: 'DOC',
    minVintage: 1974,
    avgPrice: 12,
    producers: ['Bonzara'],
    aliases: ['Bonzara Pignoletto']
  },
  {
    id: 'pignoletto-umberto-cesari',
    name: 'Colli Bolognesi Pignoletto',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Bologna',
    grapeVariety: 'Pignoletto',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 12,
    producers: ['Umberto Cesari'],
    aliases: ['Cesari Pignoletto']
  },
  {
    id: 'pignoletto-floriano-cinti',
    name: 'Colli Bolognesi Pignoletto Frizzante',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Bologna',
    grapeVariety: 'Pignoletto',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 14,
    producers: ['Floriano Cinti'],
    aliases: ['Cinti Pignoletto']
  },
  {
    id: 'pignoletto-spumante-monte-delle-vigne',
    name: 'Pignoletto Spumante Metodo Classico',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Bologna',
    grapeVariety: 'Pignoletto',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Monte delle Vigne'],
    aliases: ['Pignoletto Metodo Classico']
  },
  
  // TREBBIANO DI ROMAGNA DOC (White)
  {
    id: 'trebbiano-romagna-fattoria-zerbina',
    name: 'Trebbiano di Romagna',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Faenza',
    grapeVariety: 'Trebbiano Romagnolo',
    classification: 'DOC',
    minVintage: 1987,
    avgPrice: 12,
    producers: ['Fattoria Zerbina'],
    aliases: ['Zerbina Trebbiano']
  },
  {
    id: 'trebbiano-romagna-tre-monti',
    name: 'Trebbiano di Romagna',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Imola',
    grapeVariety: 'Trebbiano Romagnolo',
    classification: 'DOC',
    minVintage: 1996,
    avgPrice: 10,
    producers: ['Tre Monti'],
    aliases: ['Tre Monti Trebbiano']
  },
  {
    id: 'trebbiano-romagna-san-patrignano',
    name: 'Trebbiano di Romagna',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Rimini',
    grapeVariety: 'Trebbiano Romagnolo',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 10,
    producers: ['San Patrignano'],
    aliases: ['San Patrignano Trebbiano']
  },
  {
    id: 'trebbiano-romagna-poderi-dal-nespoli',
    name: 'Trebbiano di Romagna',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Forlì',
    grapeVariety: 'Trebbiano Romagnolo',
    classification: 'DOC',
    minVintage: 1929,
    avgPrice: 10,
    producers: ['Poderi dal Nespoli'],
    aliases: ['Dal Nespoli Trebbiano']
  },
  
  // PAGADEBIT DI ROMAGNA DOC (White)
  {
    id: 'pagadebit-romagna-fattoria-zerbina',
    name: 'Pagadebit di Romagna',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Faenza',
    grapeVariety: 'Bombino Bianco',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 14,
    producers: ['Fattoria Zerbina'],
    aliases: ['Zerbina Pagadebit']
  },
  {
    id: 'pagadebit-romagna-tre-monti',
    name: 'Pagadebit di Romagna',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Imola',
    grapeVariety: 'Bombino Bianco',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 12,
    producers: ['Tre Monti'],
    aliases: ['Tre Monti Pagadebit']
  },
  
  // ORTRUGO (Piacenza white)
  {
    id: 'ortrugo-la-tosa',
    name: 'Ortrugo dei Colli Piacentini',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Ortrugo',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 14,
    producers: ['La Tosa'],
    aliases: ['La Tosa Ortrugo']
  },
  {
    id: 'ortrugo-la-stoppa',
    name: 'Ortrugo dei Colli Piacentini',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Ortrugo',
    classification: 'DOC',
    minVintage: 1973,
    avgPrice: 16,
    producers: ['La Stoppa'],
    aliases: ['La Stoppa Ortrugo']
  },
  {
    id: 'ortrugo-torre-fornello',
    name: 'Ortrugo dei Colli Piacentini',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Ortrugo',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 12,
    producers: ['Torre Fornello'],
    aliases: ['Torre Fornello Ortrugo']
  },
  {
    id: 'ortrugo-frizzante-la-tosa',
    name: 'Ortrugo dei Colli Piacentini Frizzante',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Ortrugo',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 12,
    producers: ['La Tosa'],
    aliases: ['La Tosa Ortrugo Frizzante']
  },
  
  // MALVASIA (Piacenza)
  {
    id: 'malvasia-piacenza-la-stoppa-ageno',
    name: 'Malvasia Ageno',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Malvasia di Candia Aromatica',
    classification: 'IGT',
    minVintage: 1991,
    avgPrice: 42,
    producers: ['La Stoppa'],
    aliases: ['Ageno']
  },
  {
    id: 'malvasia-piacenza-la-tosa',
    name: 'Malvasia dei Colli Piacentini',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Malvasia di Candia Aromatica',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 16,
    producers: ['La Tosa'],
    aliases: ['La Tosa Malvasia']
  },
  {
    id: 'malvasia-piacenza-passito-la-tosa',
    name: 'Malvasia dei Colli Piacentini Passito',
    type: 'Dessert',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Malvasia di Candia Aromatica',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['La Tosa'],
    aliases: ['La Tosa Passito']
  },
  
  // SAUVIGNON BLANC
  {
    id: 'sauvignon-blanc-la-stoppa',
    name: 'Sauvignon Blanc Emilia IGT',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 1973,
    avgPrice: 22,
    producers: ['La Stoppa'],
    aliases: ['La Stoppa Sauvignon']
  },
  {
    id: 'sauvignon-blanc-la-tosa',
    name: 'Sauvignon Blanc Colli Piacentini',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 18,
    producers: ['La Tosa'],
    aliases: ['La Tosa Sauvignon']
  },
  
  // CHARDONNAY
  {
    id: 'chardonnay-san-patrignano',
    name: 'Chardonnay Rubicone IGT',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Rimini',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 1978,
    avgPrice: 16,
    producers: ['San Patrignano'],
    aliases: ['San Patrignano Chardonnay']
  },
  {
    id: 'chardonnay-umberto-cesari',
    name: 'Chardonnay Rubicone IGT',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Bologna',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 14,
    producers: ['Umberto Cesari'],
    aliases: ['Cesari Chardonnay']
  },
  
  // ADDITIONAL WHITE WINES
  {
    id: 'emilia-romagna-fattoria-zerbina-torre-di-ceparano',
    name: 'Torre di Ceparano Ravenna IGT',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Faenza',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Fattoria Zerbina'],
    aliases: ['Torre di Ceparano']
  },
  {
    id: 'emilia-romagna-san-patrignano-aulente',
    name: 'Aulente Rubicone IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Rimini',
    grapeVariety: 'Moscato',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['San Patrignano'],
    aliases: ['Aulente']
  },
  {
    id: 'emilia-romagna-monte-delle-vigne-luna-selvatica',
    name: 'Luna Selvatica Colli Bolognesi',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Bologna',
    grapeVariety: 'Pignoletto',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Monte delle Vigne'],
    aliases: ['Luna Selvatica']
  },
  {
    id: 'emilia-romagna-tre-monti-vitalba',
    name: 'Vitalba Romagna IGT',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Imola',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Tre Monti'],
    aliases: ['Vitalba']
  },
  {
    id: 'emilia-romagna-umberto-cesari-colle-del-re',
    name: 'Colle del Re Rubicone IGT',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Bologna',
    grapeVariety: 'Chardonnay, Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Umberto Cesari'],
    aliases: ['Colle del Re']
  },
  {
    id: 'emilia-romagna-la-stoppa-trebbiolo',
    name: 'Trebbiolo Emilia IGT',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Trebbiano, Ortrugo',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['La Stoppa'],
    aliases: ['Trebbiolo']
  },
  {
    id: 'emilia-romagna-poderi-dal-nespoli-il-nespoli-bianco',
    name: 'Il Nespoli Bianco Rubicone IGT',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Forlì',
    grapeVariety: 'Trebbiano, Chardonnay',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Poderi dal Nespoli'],
    aliases: ['Il Nespoli Bianco']
  },
  {
    id: 'emilia-romagna-villa-papiano-bianco',
    name: 'Romagna Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Bertinoro',
    grapeVariety: 'Trebbiano, Albana',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Villa Papiano'],
    aliases: ['Villa Papiano Bianco']
  },
];
