import { WineTemplate } from '@/types/wineDatabase';

/**
 * FRIULI-VENEZIA GIULIA WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Refosco dal Peduncolo Rosso, Picolit, Schioppettino, Red wines
 * Updated: January 2025
 */

export const friuliPart3: WineTemplate[] = [
  // REFOSCO DAL PEDUNCOLO ROSSO (Red)
  {
    id: 'refosco-livio-felluga',
    name: 'Refosco dal Peduncolo Rosso Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Refosco dal Peduncolo Rosso',
    classification: 'DOC',
    minVintage: 1956,
    avgPrice: 28,
    producers: ['Livio Felluga'],
    aliases: ['Livio Felluga Refosco']
  },
  {
    id: 'refosco-ronco-del-gnemiz',
    name: 'Refosco dal Peduncolo Rosso Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Refosco dal Peduncolo Rosso',
    classification: 'DOC',
    minVintage: 1964,
    avgPrice: 32,
    producers: ['Ronco del Gnemiz'],
    aliases: ['Gnemiz Refosco']
  },
  {
    id: 'refosco-le-vigne-di-zamo',
    name: 'Refosco dal Peduncolo Rosso Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Refosco dal Peduncolo Rosso',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 26,
    producers: ['Le Vigne di Zamò'],
    aliases: ['Zamò Refosco']
  },
  {
    id: 'refosco-miani',
    name: 'Refosco dal Peduncolo Rosso Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Refosco dal Peduncolo Rosso',
    classification: 'DOC',
    minVintage: 1987,
    avgPrice: 95,
    producers: ['Miani', 'Enzo Pontoni'],
    aliases: ['Miani Refosco']
  },
  {
    id: 'refosco-scarbolo',
    name: 'Refosco dal Peduncolo Rosso Grave del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Grave',
    grapeVariety: 'Refosco dal Peduncolo Rosso',
    classification: 'DOC',
    minVintage: 1982,
    avgPrice: 24,
    producers: ['Scarbolo'],
    aliases: ['Scarbolo Refosco']
  },
  {
    id: 'refosco-oscar-sturm',
    name: 'Refosco dal Peduncolo Rosso Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Refosco dal Peduncolo Rosso',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Oscar Sturm'],
    aliases: ['Sturm Refosco']
  },
  {
    id: 'refosco-vie-di-romans',
    name: 'Refosco dal Peduncolo Rosso Isonzo',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Isonzo',
    grapeVariety: 'Refosco dal Peduncolo Rosso',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 45,
    producers: ['Vie di Romans'],
    aliases: ['Vie di Romans Refosco']
  },
  {
    id: 'refosco-venica',
    name: 'Refosco dal Peduncolo Rosso Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Refosco dal Peduncolo Rosso',
    classification: 'DOC',
    minVintage: 1930,
    avgPrice: 30,
    producers: ['Venica & Venica'],
    aliases: ['Venica Refosco']
  },
  
  // SCHIOPPETTINO (Indigenous red variety)
  {
    id: 'schioppettino-miani',
    name: 'Schioppettino Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Schioppettino',
    classification: 'DOC',
    minVintage: 1987,
    avgPrice: 110,
    producers: ['Miani'],
    aliases: ['Miani Schioppettino']
  },
  {
    id: 'schioppettino-ronchi-cialla',
    name: 'Schioppettino Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Schioppettino',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 38,
    producers: ['Ronchi di Cialla'],
    aliases: ['Ronchi di Cialla Schioppettino']
  },
  {
    id: 'schioppettino-le-vigne-di-zamo',
    name: 'Schioppettino Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Schioppettino',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 32,
    producers: ['Le Vigne di Zamò'],
    aliases: ['Zamò Schioppettino']
  },
  {
    id: 'schioppettino-moschioni',
    name: 'Schioppettino Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Schioppettino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Moschioni'],
    aliases: ['Moschioni Schioppettino']
  },
  {
    id: 'schioppettino-cecchini',
    name: 'Schioppettino Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Schioppettino',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 28,
    producers: ['Cecchini'],
    aliases: ['Cecchini Schioppettino']
  },
  
  // PICOLIT DOCG (Rare sweet wine)
  {
    id: 'picolit-livio-felluga',
    name: 'Picolit Colli Orientali del Friuli',
    type: 'Dessert',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Picolit',
    classification: 'DOCG',
    minVintage: 1970,
    avgPrice: 95,
    producers: ['Livio Felluga'],
    aliases: ['Livio Felluga Picolit']
  },
  {
    id: 'picolit-ronchi-cialla',
    name: 'Picolit Colli Orientali del Friuli',
    type: 'Dessert',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Picolit',
    classification: 'DOCG',
    minVintage: 1970,
    avgPrice: 85,
    producers: ['Ronchi di Cialla'],
    aliases: ['Ronchi di Cialla Picolit']
  },
  {
    id: 'picolit-le-vigne-di-zamo',
    name: 'Picolit Colli Orientali del Friuli',
    type: 'Dessert',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Picolit',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 72,
    producers: ['Le Vigne di Zamò'],
    aliases: ['Zamò Picolit']
  },
  {
    id: 'picolit-dorigo',
    name: 'Picolit Colli Orientali del Friuli',
    type: 'Dessert',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Picolit',
    classification: 'DOCG',
    minVintage: 1970,
    avgPrice: 78,
    producers: ['Girolamo Dorigo'],
    aliases: ['Dorigo Picolit']
  },
  
  // PINOT NERO (Pinot Noir)
  {
    id: 'pinot-nero-jermann',
    name: 'Pinot Nero Venezia Giulia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Pinot Noir',
    classification: 'IGT',
    minVintage: 1975,
    avgPrice: 42,
    producers: ['Jermann'],
    aliases: ['Jermann Pinot Nero']
  },
  {
    id: 'pinot-nero-livio-felluga',
    name: 'Pinot Nero Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 1956,
    avgPrice: 38,
    producers: ['Livio Felluga'],
    aliases: ['Livio Felluga Pinot Nero']
  },
  {
    id: 'pinot-nero-marco-felluga',
    name: 'Pinot Nero Collio',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Pinot Noir',
    classification: 'DOC',
    minVintage: 1956,
    avgPrice: 35,
    producers: ['Marco Felluga'],
    aliases: ['Marco Felluga Pinot Nero']
  },
  
  // MERLOT & CABERNET
  {
    id: 'merlot-miani-filip',
    name: 'Merlot Filip Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Merlot',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 125,
    producers: ['Miani'],
    aliases: ['Filip']
  },
  {
    id: 'merlot-livio-felluga',
    name: 'Merlot Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Merlot',
    classification: 'DOC',
    minVintage: 1956,
    avgPrice: 28,
    producers: ['Livio Felluga'],
    aliases: ['Livio Felluga Merlot']
  },
  {
    id: 'merlot-vie-di-romans',
    name: 'Merlot Isonzo Vieris',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Isonzo',
    grapeVariety: 'Merlot',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 48,
    producers: ['Vie di Romans'],
    aliases: ['Merlot Vieris']
  },
  {
    id: 'cabernet-sauvignon-vie-di-romans',
    name: 'Cabernet Sauvignon Isonzo Vieris',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Isonzo',
    grapeVariety: 'Cabernet Sauvignon',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 45,
    producers: ['Vie di Romans'],
    aliases: ['Cabernet Vieris']
  },
  {
    id: 'cabernet-franc-vie-di-romans',
    name: 'Cabernet Franc Isonzo Vieris',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Isonzo',
    grapeVariety: 'Cabernet Franc',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 42,
    producers: ['Vie di Romans'],
    aliases: ['Cabernet Franc Vieris']
  },
  
  // PIGNOLO (Indigenous red variety)
  {
    id: 'pignolo-miani',
    name: 'Pignolo Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Pignolo',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 120,
    producers: ['Miani'],
    aliases: ['Miani Pignolo']
  },
  {
    id: 'pignolo-livio-felluga',
    name: 'Pignolo Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Pignolo',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 52,
    producers: ['Livio Felluga'],
    aliases: ['Livio Felluga Pignolo']
  },
  {
    id: 'pignolo-le-vigne-di-zamo',
    name: 'Pignolo Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Pignolo',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 45,
    producers: ['Le Vigne di Zamò'],
    aliases: ['Zamò Pignolo']
  },
  {
    id: 'pignolo-ronchi-cialla',
    name: 'Pignolo Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Pignolo',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 48,
    producers: ['Ronchi di Cialla'],
    aliases: ['Ronchi di Cialla Pignolo']
  },
  
  // TAZZELENGHE (Indigenous red variety)
  {
    id: 'tazzelenghe-ronchi-cialla',
    name: 'Tazzelenghe Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Tazzelenghe',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 38,
    producers: ['Ronchi di Cialla'],
    aliases: ['Ronchi di Cialla Tazzelenghe']
  },
  {
    id: 'tazzelenghe-le-vigne-di-zamo',
    name: 'Tazzelenghe Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Tazzelenghe',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 32,
    producers: ['Le Vigne di Zamò'],
    aliases: ['Zamò Tazzelenghe']
  },
  
  // ORANGE WINE BLENDS
  {
    id: 'orange-blend-gravner-breg',
    name: 'Breg Anfora Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Friulano, Sauvignon Blanc, Pinot Grigio, Riesling',
    classification: 'IGT',
    minVintage: 2001,
    avgPrice: 125,
    producers: ['Gravner'],
    aliases: ['Breg Anfora']
  },
  {
    id: 'orange-blend-radikon-rs',
    name: 'RS Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Chardonnay, Pinot Grigio, Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 2003,
    avgPrice: 95,
    producers: ['Radikon'],
    aliases: ['RS']
  },
  {
    id: 'orange-blend-radikon-oslavje',
    name: 'Oslavje Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Chardonnay, Friulano, Pinot Grigio',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 105,
    producers: ['Radikon'],
    aliases: ['Oslavje']
  },
  {
    id: 'orange-blend-damijan-podversic-kaplja',
    name: 'Kaplja Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Chardonnay, Sauvignon Blanc, Malvasia, Friulano',
    classification: 'IGT',
    minVintage: 2001,
    avgPrice: 85,
    producers: ['Damijan Podversic'],
    aliases: ['Kaplja']
  },
  {
    id: 'orange-blend-la-castellada-bianco',
    name: 'Bianco della Castellada Venezia Giulia IGT',
    type: 'Orange',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Friulano, Sauvignon Blanc, Chardonnay, Pinot Grigio',
    classification: 'IGT',
    minVintage: 1985,
    avgPrice: 92,
    producers: ['La Castellada'],
    aliases: ['Bianco della Castellada']
  },
  
  // TERRANO (Carso specialty)
  {
    id: 'terrano-zidarich',
    name: 'Terrano Carso',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Carso',
    grapeVariety: 'Terrano',
    classification: 'DOC',
    minVintage: 1988,
    avgPrice: 42,
    producers: ['Zidarich'],
    aliases: ['Zidarich Terrano']
  },
  {
    id: 'terrano-skerk',
    name: 'Terrano Carso',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Carso',
    grapeVariety: 'Terrano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 45,
    producers: ['Skerk'],
    aliases: ['Skerk Terrano']
  },
  {
    id: 'terrano-vodopivec',
    name: 'Terrano Venezia Giulia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Carso',
    grapeVariety: 'Terrano',
    classification: 'IGT',
    minVintage: 1997,
    avgPrice: 75,
    producers: ['Vodopivec'],
    aliases: ['Vodopivec Terrano']
  },
  {
    id: 'terrano-kante',
    name: 'Terrano Carso',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Carso',
    grapeVariety: 'Terrano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 38,
    producers: ['Kante', 'Edi Kante'],
    aliases: ['Kante Terrano']
  },
  
  // ADDITIONAL PREMIUM WINES
  {
    id: 'friuli-schiopetto-rivarossa',
    name: 'Rivarossa Collio Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Merlot, Cabernet Franc, Refosco',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 55,
    producers: ['Schiopetto'],
    aliases: ['Rivarossa']
  },
  {
    id: 'friuli-villa-russiz-graf-de-la-tour',
    name: 'Graf de la Tour Collio Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Collio',
    grapeVariety: 'Merlot, Cabernet Franc',
    classification: 'DOC',
    minVintage: 1975,
    avgPrice: 52,
    producers: ['Villa Russiz'],
    aliases: ['Graf de la Tour']
  },
  {
    id: 'friuli-ronco-del-gnemiz-rosso-sot-lis-rivis',
    name: 'Rosso Sot Lis Rivis Colli Orientali del Friuli',
    type: 'Red',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    subRegion: 'Colli Orientali',
    grapeVariety: 'Refosco, Schioppettino, Pignolo',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 48,
    producers: ['Ronco del Gnemiz'],
    aliases: ['Rosso Sot Lis Rivis']
  },
];
