import { WineTemplate } from '@/types/wineDatabase';

/**
 * SARDINIA WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Vermentino di Sardegna DOC, Vermentino di Gallura DOCG
 * Updated: January 2025
 */

export const sardiniaPart2: WineTemplate[] = [
  // VERMENTINO DI GALLURA DOCG (White - Northeast Sardinia)
  {
    id: 'vermentino-gallura-capichera-vigna-ngena',
    name: 'Vermentino di Gallura Vigna \'Ngena',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 1980,
    avgPrice: 42,
    producers: ['Capichera'],
    aliases: ['Vigna \'Ngena']
  },
  {
    id: 'vermentino-gallura-capichera-vendemmia-tardiva',
    name: 'Vermentino di Gallura Vendemmia Tardiva',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 55,
    producers: ['Capichera'],
    aliases: ['Capichera Vendemmia Tardiva']
  },
  {
    id: 'vermentino-gallura-capichera',
    name: 'Vermentino di Gallura',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 1980,
    avgPrice: 22,
    producers: ['Capichera'],
    aliases: ['Capichera Vermentino']
  },
  {
    id: 'vermentino-gallura-piero-mancini-funtanaliras',
    name: 'Vermentino di Gallura Funtanaliras',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 1950,
    avgPrice: 32,
    producers: ['Piero Mancini'],
    aliases: ['Funtanaliras']
  },
  {
    id: 'vermentino-gallura-piero-mancini',
    name: 'Vermentino di Gallura',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 1950,
    avgPrice: 18,
    producers: ['Piero Mancini'],
    aliases: ['Piero Mancini Vermentino']
  },
  {
    id: 'vermentino-gallura-surrau-branu',
    name: 'Vermentino di Gallura Branu',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Cantina di Surrau'],
    aliases: ['Branu']
  },
  {
    id: 'vermentino-gallura-surrau-sciala',
    name: 'Vermentino di Gallura Sciala',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Cantina di Surrau'],
    aliases: ['Sciala']
  },
  {
    id: 'vermentino-gallura-surrau',
    name: 'Vermentino di Gallura',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Cantina di Surrau'],
    aliases: ['Surrau Vermentino']
  },
  {
    id: 'vermentino-gallura-cantina-gallura-canayli',
    name: 'Vermentino di Gallura Canayli',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 1956,
    avgPrice: 28,
    producers: ['Cantina Gallura'],
    aliases: ['Canayli']
  },
  {
    id: 'vermentino-gallura-cantina-gallura-gemellae',
    name: 'Vermentino di Gallura Gemellae',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Cantina Gallura'],
    aliases: ['Gemellae']
  },
  {
    id: 'vermentino-gallura-cantina-gallura',
    name: 'Vermentino di Gallura',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 1956,
    avgPrice: 14,
    producers: ['Cantina Gallura'],
    aliases: ['Cantina Gallura Vermentino']
  },
  {
    id: 'vermentino-gallura-vigne-surrau-limizzani',
    name: 'Vermentino di Gallura Limizzani',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Vigne Surrau'],
    aliases: ['Limizzani']
  },
  
  // VERMENTINO DI SARDEGNA DOC (White - All of Sardinia)
  {
    id: 'vermentino-sardegna-argiolas-costamolino',
    name: 'Costamolino Vermentino di Sardegna',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Argiolas'],
    aliases: ['Costamolino']
  },
  {
    id: 'vermentino-sardegna-sella-mosca-la-cala',
    name: 'La Cala Vermentino di Sardegna',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Alghero',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Sella & Mosca'],
    aliases: ['La Cala']
  },
  {
    id: 'vermentino-sardegna-sella-mosca-monteoro',
    name: 'Monteoro Vermentino di Sardegna',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Alghero',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 26,
    producers: ['Sella & Mosca'],
    aliases: ['Monteoro']
  },
  {
    id: 'vermentino-sardegna-santadi-cala-silente',
    name: 'Cala Silente Vermentino di Sardegna',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Cantina di Santadi'],
    aliases: ['Cala Silente']
  },
  {
    id: 'vermentino-sardegna-santadi-villa-solais',
    name: 'Villa Solais Vermentino di Sardegna',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Cantina di Santadi'],
    aliases: ['Villa Solais']
  },
  {
    id: 'vermentino-sardegna-mesa-vermentino',
    name: 'Vermentino di Sardegna',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sant\'Antioco',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 14,
    producers: ['Mesa'],
    aliases: ['Mesa Vermentino']
  },
  {
    id: 'vermentino-sardegna-pala-stelle',
    name: 'Stellato Vermentino di Sardegna',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Serdiana',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Pala'],
    aliases: ['Stellato']
  },
  {
    id: 'vermentino-sardegna-alberto-loi',
    name: 'Vermentino di Sardegna',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Cagliari',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 14,
    producers: ['Alberto Loi'],
    aliases: ['Alberto Loi Vermentino']
  },
  {
    id: 'vermentino-sardegna-tenute-dettori',
    name: 'Vermentino di Romangia',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Romangia',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 45,
    producers: ['Tenute Dettori'],
    aliases: ['Dettori Vermentino']
  },
  {
    id: 'vermentino-sardegna-6mura',
    name: 'Vermentino di Sardegna',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Vermentino',
    classification: 'DOC',
    minVintage: 2006,
    avgPrice: 16,
    producers: ['6Mura'],
    aliases: ['6Mura Vermentino']
  },
  
  // NURAGUS DI CAGLIARI DOC (White - indigenous variety)
  {
    id: 'nuragus-argiolas-s-elegas',
    name: 'S\'Elegas Nuragus di Cagliari',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Nuragus',
    classification: 'DOC',
    minVintage: 1938,
    avgPrice: 14,
    producers: ['Argiolas'],
    aliases: ['S\'Elegas Nuragus']
  },
  {
    id: 'nuragus-pala',
    name: 'Nuragus di Cagliari',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Serdiana',
    grapeVariety: 'Nuragus',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 12,
    producers: ['Pala'],
    aliases: ['Pala Nuragus']
  },
  {
    id: 'nuragus-alberto-loi',
    name: 'Nuragus di Cagliari',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Cagliari',
    grapeVariety: 'Nuragus',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 11,
    producers: ['Alberto Loi'],
    aliases: ['Alberto Loi Nuragus']
  },
  
  // NASCO DI CAGLIARI DOC (White - sweet/dry)
  {
    id: 'nasco-argiolas',
    name: 'Nasco di Cagliari',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Nasco',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Argiolas'],
    aliases: ['Argiolas Nasco']
  },
  
  // VERNACCIA DI ORISTANO DOC (Oxidative white - Sherry-style)
  {
    id: 'vernaccia-oristano-contini-riserva',
    name: 'Vernaccia di Oristano Riserva',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Oristano',
    grapeVariety: 'Vernaccia di Oristano',
    classification: 'DOC',
    minVintage: 1898,
    avgPrice: 38,
    producers: ['Contini'],
    aliases: ['Contini Vernaccia Riserva']
  },
  {
    id: 'vernaccia-oristano-contini-antico-gregori',
    name: 'Vernaccia di Oristano Antico Gregori',
    type: 'Fortified',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Oristano',
    grapeVariety: 'Vernaccia di Oristano',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 55,
    producers: ['Contini'],
    aliases: ['Antico Gregori']
  },
  {
    id: 'vernaccia-oristano-contini',
    name: 'Vernaccia di Oristano',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Oristano',
    grapeVariety: 'Vernaccia di Oristano',
    classification: 'DOC',
    minVintage: 1898,
    avgPrice: 24,
    producers: ['Contini'],
    aliases: ['Contini Vernaccia']
  },
  {
    id: 'vernaccia-oristano-silvio-carta',
    name: 'Vernaccia di Oristano',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Oristano',
    grapeVariety: 'Vernaccia di Oristano',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 22,
    producers: ['Silvio Carta'],
    aliases: ['Silvio Carta Vernaccia']
  },
  
  // WHITE BLENDS & PREMIUM WINES
  {
    id: 'sardinia-argiolas-is-argiolas',
    name: 'Is Argiolas Isola dei Nuraghi IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Trexenta',
    grapeVariety: 'Vermentino, Chardonnay, Nasco',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Argiolas'],
    aliases: ['Is Argiolas']
  },
  {
    id: 'sardinia-pala-esmeralda',
    name: 'Esmeralda Isola dei Nuraghi IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Serdiana',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Pala'],
    aliases: ['Esmeralda']
  },
  {
    id: 'sardinia-sella-mosca-terre-bianche',
    name: 'Terre Bianche Torbato Alghero DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Alghero',
    grapeVariety: 'Torbato',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 22,
    producers: ['Sella & Mosca'],
    aliases: ['Terre Bianche']
  },
  {
    id: 'sardinia-tenute-dettori-dettori-bianco',
    name: 'Dettori Bianco Romangia IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Romangia',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 75,
    producers: ['Tenute Dettori'],
    aliases: ['Dettori Bianco']
  },
  {
    id: 'sardinia-capichera-assaje',
    name: 'Assaje Isola dei Nuraghi IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Gallura',
    grapeVariety: 'Vermentino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 38,
    producers: ['Capichera'],
    aliases: ['Assaje']
  },
  {
    id: 'sardinia-santadi-latinia-bianco',
    name: 'Latinia Bianco Isola dei Nuraghi IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sulcis',
    grapeVariety: 'Vermentino, Chardonnay',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Cantina di Santadi'],
    aliases: ['Latinia Bianco']
  },
  {
    id: 'sardinia-mesa-chardonnay',
    name: 'Chardonnay Isola dei Nuraghi IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Sant\'Antioco',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 2004,
    avgPrice: 18,
    producers: ['Mesa'],
    aliases: ['Mesa Chardonnay']
  },
  {
    id: 'sardinia-alberto-loi-s-arai-bianco',
    name: 'S\'Arai Bianco Isola dei Nuraghi IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sardinia',
    subRegion: 'Cagliari',
    grapeVariety: 'Vermentino, Chardonnay',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Alberto Loi'],
    aliases: ['S\'Arai Bianco']
  },
];
