import { WineTemplate } from '@/types/wineDatabase';

/**
 * TUSCANY WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Super Tuscans, Bolgheri, Coastal Wines, Vernaccia
 * Updated: January 2025
 */

export const tuscanyPart3: WineTemplate[] = [
  // SUPER TUSCANS & BOLGHERI
  {
    id: 'super-tuscan-sassicaia',
    name: 'Sassicaia Bolgheri DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Cabernet Sauvignon, Cabernet Franc',
    classification: 'DOC',
    minVintage: 1968,
    avgPrice: 220,
    producers: ['Tenuta San Guido'],
    aliases: ['Sassicaia']
  },
  {
    id: 'super-tuscan-ornellaia',
    name: 'Ornellaia Bolgheri Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 250,
    producers: ['Tenuta dell\'Ornellaia'],
    aliases: ['Ornellaia']
  },
  {
    id: 'super-tuscan-masseto',
    name: 'Masseto Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 1987,
    avgPrice: 750,
    producers: ['Tenuta dell\'Ornellaia'],
    aliases: ['Masseto']
  },
  {
    id: 'super-tuscan-le-serre-nuove',
    name: 'Le Serre Nuove dell\'Ornellaia',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    classification: 'DOC',
    minVintage: 1997,
    avgPrice: 75,
    producers: ['Tenuta dell\'Ornellaia'],
    aliases: ['Le Serre Nuove']
  },
  {
    id: 'super-tuscan-poggio-alle-gazze',
    name: 'Poggio alle Gazze dell\'Ornellaia',
    type: 'White',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Sauvignon Blanc, Viognier',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 55,
    producers: ['Tenuta dell\'Ornellaia'],
    aliases: ['Poggio alle Gazze']
  },
  {
    id: 'super-tuscan-guidalberto',
    name: 'Guidalberto Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 45,
    producers: ['Tenuta San Guido'],
    aliases: ['Guidalberto']
  },
  {
    id: 'super-tuscan-le-difese',
    name: 'Le Difese Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Cabernet Sauvignon, Sangiovese',
    classification: 'IGT',
    minVintage: 2002,
    avgPrice: 28,
    producers: ['Tenuta San Guido'],
    aliases: ['Le Difese']
  },
  {
    id: 'super-tuscan-grattamacco',
    name: 'Bolgheri Rosso Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Sangiovese',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 65,
    producers: ['Grattamacco'],
    aliases: ['Grattamacco']
  },
  {
    id: 'super-tuscan-guado-al-tasso',
    name: 'Guado al Tasso Bolgheri Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Syrah',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 90,
    producers: ['Antinori'],
    aliases: ['Guado al Tasso']
  },
  {
    id: 'super-tuscan-cont-ugo',
    name: 'Cont\'Ugo Bolgheri Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Merlot, Cabernet Sauvignon',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 35,
    producers: ['Tenuta Guado al Tasso', 'Antinori'],
    aliases: ['Cont\'Ugo']
  },
  {
    id: 'super-tuscan-michele-satta',
    name: 'Bolgheri Rosso Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Syrah, Teroldego',
    classification: 'DOC',
    minVintage: 1983,
    avgPrice: 55,
    producers: ['Michele Satta'],
    aliases: ['Michele Satta']
  },
  {
    id: 'super-tuscan-le-macchiole-paleo',
    name: 'Paleo Rosso Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Cabernet Franc',
    classification: 'IGT',
    minVintage: 1989,
    avgPrice: 120,
    producers: ['Le Macchiole'],
    aliases: ['Paleo Rosso']
  },
  {
    id: 'super-tuscan-le-macchiole-messorio',
    name: 'Messorio Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 1994,
    avgPrice: 180,
    producers: ['Le Macchiole'],
    aliases: ['Messorio']
  },
  {
    id: 'super-tuscan-le-macchiole-scrio',
    name: 'Scrio Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Syrah',
    classification: 'IGT',
    minVintage: 1994,
    avgPrice: 150,
    producers: ['Le Macchiole'],
    aliases: ['Scrio']
  },
  {
    id: 'super-tuscan-ca-marcanda',
    name: 'Camarcanda Bolgheri DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Merlot, Cabernet Sauvignon, Cabernet Franc',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 110,
    producers: ['Ca\' Marcanda', 'Gaja'],
    aliases: ['Camarcanda', 'Ca\' Marcanda']
  },
  {
    id: 'super-tuscan-magari',
    name: 'Magari Bolgheri DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    grapeVariety: 'Cabernet Franc, Cabernet Sauvignon, Petit Verdot',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 50,
    producers: ['Ca\' Marcanda', 'Gaja'],
    aliases: ['Magari']
  },
  {
    id: 'super-tuscan-solaia',
    name: 'Solaia Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Cabernet Sauvignon, Sangiovese, Cabernet Franc',
    classification: 'IGT',
    minVintage: 1978,
    avgPrice: 320,
    producers: ['Antinori'],
    aliases: ['Solaia']
  },
  {
    id: 'super-tuscan-flaccianello',
    name: 'Flaccianello della Pieve Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 1981,
    avgPrice: 140,
    producers: ['Fontodi'],
    aliases: ['Flaccianello']
  },
  {
    id: 'super-tuscan-fontalloro',
    name: 'Fontalloro Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 1981,
    avgPrice: 95,
    producers: ['Felsina'],
    aliases: ['Fontalloro']
  },
  {
    id: 'super-tuscan-cepparello',
    name: 'Cepparello Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 90,
    producers: ['Isole e Olena'],
    aliases: ['Cepparello']
  },
  {
    id: 'super-tuscan-percarlo',
    name: 'Percarlo Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 1979,
    avgPrice: 110,
    producers: ['San Giusto a Rentennano'],
    aliases: ['Percarlo']
  },
  {
    id: 'super-tuscan-i-sodi-san-niccolo',
    name: 'I Sodi di San Niccolò Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese, Malvasia Nera',
    classification: 'IGT',
    minVintage: 1979,
    avgPrice: 85,
    producers: ['Castellare di Castellina'],
    aliases: ['I Sodi di San Niccolò']
  },
  {
    id: 'super-tuscan-montevertine-pergole-torte',
    name: 'Le Pergole Torte Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 1977,
    avgPrice: 180,
    producers: ['Montevertine'],
    aliases: ['Pergole Torte']
  },
  {
    id: 'super-tuscan-montevertine',
    name: 'Montevertine Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese, Canaiolo',
    classification: 'IGT',
    minVintage: 1981,
    avgPrice: 65,
    producers: ['Montevertine'],
    aliases: ['Montevertine']
  },
  {
    id: 'super-tuscan-solengo',
    name: 'Solengo Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Syrah, Petit Verdot',
    classification: 'IGT',
    minVintage: 2001,
    avgPrice: 75,
    producers: ['Argiano'],
    aliases: ['Solengo']
  },
  {
    id: 'super-tuscan-luce',
    name: 'Luce della Vite Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese, Merlot',
    classification: 'IGT',
    minVintage: 1993,
    avgPrice: 95,
    producers: ['Luce della Vite', 'Frescobaldi'],
    aliases: ['Luce']
  },
  {
    id: 'super-tuscan-lucente',
    name: 'Lucente Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese, Merlot',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 35,
    producers: ['Luce della Vite'],
    aliases: ['Lucente']
  },
  {
    id: 'super-tuscan-saffredi',
    name: 'Saffredi Maremma Toscana DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Maremma',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot',
    classification: 'DOC',
    minVintage: 1987,
    avgPrice: 90,
    producers: ['Le Pupille'],
    aliases: ['Saffredi']
  },
  
  // VERNACCIA DI SAN GIMIGNANO DOCG (White)
  {
    id: 'vernaccia-panizzi',
    name: 'Vernaccia di San Gimignano',
    type: 'White',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'San Gimignano',
    grapeVariety: 'Vernaccia',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Panizzi'],
    aliases: ['Panizzi Vernaccia']
  },
  {
    id: 'vernaccia-panizzi-riserva',
    name: 'Vernaccia di San Gimignano Riserva',
    type: 'White',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'San Gimignano',
    grapeVariety: 'Vernaccia',
    classification: 'DOCG',
    minVintage: 1997,
    avgPrice: 24,
    producers: ['Panizzi'],
    aliases: ['Panizzi Riserva']
  },
  {
    id: 'vernaccia-teruzzi-puthod',
    name: 'Vernaccia di San Gimignano',
    type: 'White',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'San Gimignano',
    grapeVariety: 'Vernaccia',
    classification: 'DOCG',
    minVintage: 1974,
    avgPrice: 14,
    producers: ['Teruzzi & Puthod'],
    aliases: ['Teruzzi Vernaccia']
  },
  {
    id: 'vernaccia-montenidoli',
    name: 'Vernaccia di San Gimignano',
    type: 'White',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'San Gimignano',
    grapeVariety: 'Vernaccia',
    classification: 'DOCG',
    minVintage: 1971,
    avgPrice: 18,
    producers: ['Montenidoli'],
    aliases: ['Montenidoli']
  },
  {
    id: 'vernaccia-cesani',
    name: 'Vernaccia di San Gimignano',
    type: 'White',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'San Gimignano',
    grapeVariety: 'Vernaccia',
    classification: 'DOCG',
    minVintage: 1964,
    avgPrice: 15,
    producers: ['Vincenzo Cesani'],
    aliases: ['Cesani']
  },
  {
    id: 'vernaccia-falchini',
    name: 'Vernaccia di San Gimignano',
    type: 'White',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'San Gimignano',
    grapeVariety: 'Vernaccia',
    classification: 'DOCG',
    minVintage: 1960,
    avgPrice: 13,
    producers: ['Falchini'],
    aliases: ['Falchini']
  },
  
  // VIN SANTO DEL CHIANTI CLASSICO DOC (Dessert)
  {
    id: 'vin-santo-isole-olena',
    name: 'Vin Santo del Chianti Classico',
    type: 'Dessert',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Trebbiano, Malvasia',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 45,
    producers: ['Isole e Olena'],
    aliases: ['Vin Santo Isole e Olena']
  },
  {
    id: 'vin-santo-fontodi',
    name: 'Vin Santo del Chianti Classico',
    type: 'Dessert',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Trebbiano, Malvasia',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 50,
    producers: ['Fontodi'],
    aliases: ['Vin Santo Fontodi']
  },
  {
    id: 'vin-santo-badia-coltibuono',
    name: 'Vin Santo del Chianti Classico',
    type: 'Dessert',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Trebbiano, Malvasia',
    classification: 'DOC',
    minVintage: 1900,
    avgPrice: 38,
    producers: ['Badia a Coltibuono'],
    aliases: ['Vin Santo Badia']
  },
  {
    id: 'vin-santo-felsina',
    name: 'Vin Santo del Chianti Classico',
    type: 'Dessert',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Trebbiano, Malvasia',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 42,
    producers: ['Felsina'],
    aliases: ['Vin Santo Felsina']
  },
  {
    id: 'vin-santo-avignonesi',
    name: 'Vin Santo di Montepulciano',
    type: 'Dessert',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montepulciano',
    grapeVariety: 'Trebbiano, Malvasia',
    classification: 'DOC',
    minVintage: 1974,
    avgPrice: 80,
    producers: ['Avignonesi'],
    aliases: ['Vin Santo Avignonesi']
  },
  {
    id: 'vin-santo-avignonesi-occhio-pernice',
    name: 'Vin Santo di Montepulciano Occhio di Pernice',
    type: 'Dessert',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montepulciano',
    grapeVariety: 'Sangiovese',
    classification: 'DOC',
    minVintage: 1988,
    avgPrice: 150,
    producers: ['Avignonesi'],
    aliases: ['Occhio di Pernice']
  },
  
  // ADDITIONAL TUSCAN WINES
  {
    id: 'rosso-toscana-san-felice-vigorello',
    name: 'Vigorello Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese, Cabernet Sauvignon, Merlot',
    classification: 'IGT',
    minVintage: 1968,
    avgPrice: 75,
    producers: ['Agricola San Felice'],
    aliases: ['Vigorello']
  },
  {
    id: 'rosso-toscana-rampolla-sammarco',
    name: 'Sammarco Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 95,
    producers: ['Castello dei Rampolla'],
    aliases: ['Sammarco']
  },
  {
    id: 'rosso-toscana-rampolla-vigna-alceo',
    name: 'Vigna d\'Alceo Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Cabernet Sauvignon, Petit Verdot',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 140,
    producers: ['Castello dei Rampolla'],
    aliases: ['Vigna d\'Alceo']
  },
  {
    id: 'rosso-toscana-petrolo-galatrona',
    name: 'Galatrona Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Arezzo',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 1994,
    avgPrice: 130,
    producers: ['Petrolo'],
    aliases: ['Galatrona']
  },
  {
    id: 'rosso-toscana-trinoro',
    name: 'Tenuta di Trinoro',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Val d\'Orcia',
    grapeVariety: 'Cabernet Franc, Cabernet Sauvignon, Merlot',
    classification: 'IGT',
    minVintage: 1992,
    avgPrice: 180,
    producers: ['Tenuta di Trinoro'],
    aliases: ['Trinoro']
  },
  {
    id: 'rosso-toscana-trinoro-palazzi',
    name: 'Palazzi Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Val d\'Orcia',
    grapeVariety: 'Cabernet Franc, Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 50,
    producers: ['Tenuta di Trinoro'],
    aliases: ['Palazzi']
  },
  {
    id: 'rosso-toscana-tua-rita-redigaffi',
    name: 'Redigaffi Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Suvereto',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 1994,
    avgPrice: 350,
    producers: ['Tua Rita'],
    aliases: ['Redigaffi']
  },
  {
    id: 'rosso-toscana-tua-rita-giusto-notri',
    name: 'Giusto di Notri Toscana IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Suvereto',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc',
    classification: 'IGT',
    minVintage: 1992,
    avgPrice: 95,
    producers: ['Tua Rita'],
    aliases: ['Giusto di Notri']
  },
  {
    id: 'rosso-toscana-castello-brolio',
    name: 'Castello di Brolio Chianti Classico Gran Selezione',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1141,
    avgPrice: 40,
    producers: ['Barone Ricasoli'],
    aliases: ['Castello di Brolio']
  },
  {
    id: 'rosso-toscana-collemassari-rigoleto',
    name: 'Rigoleto Montecucco Sangiovese Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montecucco',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1998,
    avgPrice: 45,
    producers: ['ColleMassari'],
    aliases: ['Rigoleto']
  },
];
