import { WineTemplate } from '@/types/wineDatabase';

/**
 * EMILIA-ROMAGNA WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Sangiovese di Romagna DOC, Red wines
 * Updated: January 2025
 */

export const emiliaRomagnaPart2: WineTemplate[] = [
  // SANGIOVESE DI ROMAGNA SUPERIORE DOCG
  {
    id: 'sangiovese-romagna-tre-monti-thea',
    name: 'Sangiovese di Romagna Superiore Thea',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Imola',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1996,
    avgPrice: 32,
    producers: ['Tre Monti'],
    aliases: ['Thea']
  },
  {
    id: 'sangiovese-romagna-tre-monti-petrignone',
    name: 'Sangiovese di Romagna Superiore Petrignone',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Imola',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Tre Monti'],
    aliases: ['Petrignone']
  },
  {
    id: 'sangiovese-romagna-tre-monti',
    name: 'Sangiovese di Romagna Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Imola',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1996,
    avgPrice: 16,
    producers: ['Tre Monti'],
    aliases: ['Tre Monti Sangiovese']
  },
  {
    id: 'sangiovese-romagna-san-patrignano-avi',
    name: 'Sangiovese di Romagna Superiore Avi',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Rimini',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 28,
    producers: ['San Patrignano'],
    aliases: ['Avi']
  },
  {
    id: 'sangiovese-romagna-san-patrignano-montepirolo',
    name: 'Sangiovese di Romagna Superiore Montepirolo',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Rimini',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['San Patrignano'],
    aliases: ['Montepirolo']
  },
  {
    id: 'sangiovese-romagna-san-patrignano',
    name: 'Sangiovese di Romagna Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Rimini',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 18,
    producers: ['San Patrignano'],
    aliases: ['San Patrignano Sangiovese']
  },
  {
    id: 'sangiovese-romagna-fattoria-zerbina-pietramora',
    name: 'Sangiovese di Romagna Superiore Pietramora',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Faenza',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1987,
    avgPrice: 42,
    producers: ['Fattoria Zerbina'],
    aliases: ['Pietramora']
  },
  {
    id: 'sangiovese-romagna-fattoria-zerbina-ceregio',
    name: 'Sangiovese di Romagna Superiore Ceregio',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Faenza',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 32,
    producers: ['Fattoria Zerbina'],
    aliases: ['Ceregio']
  },
  {
    id: 'sangiovese-romagna-fattoria-zerbina',
    name: 'Sangiovese di Romagna Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Faenza',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1987,
    avgPrice: 18,
    producers: ['Fattoria Zerbina'],
    aliases: ['Zerbina Sangiovese']
  },
  {
    id: 'sangiovese-romagna-la-berta',
    name: 'Sangiovese di Romagna Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Bertinoro',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1960,
    avgPrice: 22,
    producers: ['La Berta'],
    aliases: ['La Berta Sangiovese']
  },
  {
    id: 'sangiovese-romagna-poderi-dal-nespoli-il-nespoli',
    name: 'Sangiovese di Romagna Superiore Il Nespoli Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Forlì',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1929,
    avgPrice: 28,
    producers: ['Poderi dal Nespoli'],
    aliases: ['Il Nespoli']
  },
  {
    id: 'sangiovese-romagna-poderi-dal-nespoli',
    name: 'Sangiovese di Romagna Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Forlì',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1929,
    avgPrice: 16,
    producers: ['Poderi dal Nespoli'],
    aliases: ['Dal Nespoli Sangiovese']
  },
  {
    id: 'sangiovese-romagna-umberto-cesari-liano',
    name: 'Sangiovese di Romagna Superiore Liano',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Castel San Pietro',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 32,
    producers: ['Umberto Cesari'],
    aliases: ['Liano']
  },
  {
    id: 'sangiovese-romagna-umberto-cesari',
    name: 'Sangiovese di Romagna Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Castel San Pietro',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1964,
    avgPrice: 16,
    producers: ['Umberto Cesari'],
    aliases: ['Cesari Sangiovese']
  },
  {
    id: 'sangiovese-romagna-villa-papiano',
    name: 'Sangiovese di Romagna Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Bertinoro',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Villa Papiano'],
    aliases: ['Villa Papiano Sangiovese']
  },
  {
    id: 'sangiovese-romagna-casa-bacchi',
    name: 'Sangiovese di Romagna Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Faenza',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Casa Bacchi'],
    aliases: ['Casa Bacchi Sangiovese']
  },
  
  // SANGIOVESE DI ROMAGNA DOC (Regular)
  {
    id: 'sangiovese-romagna-doc-tre-monti',
    name: 'Sangiovese di Romagna',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Imola',
    grapeVariety: 'Sangiovese',
    classification: 'DOC',
    minVintage: 1996,
    avgPrice: 12,
    producers: ['Tre Monti'],
    aliases: ['Tre Monti DOC']
  },
  {
    id: 'sangiovese-romagna-doc-san-patrignano',
    name: 'Sangiovese di Romagna',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Rimini',
    grapeVariety: 'Sangiovese',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 11,
    producers: ['San Patrignano'],
    aliases: ['San Patrignano DOC']
  },
  {
    id: 'sangiovese-romagna-doc-fattoria-zerbina',
    name: 'Sangiovese di Romagna',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Faenza',
    grapeVariety: 'Sangiovese',
    classification: 'DOC',
    minVintage: 1987,
    avgPrice: 12,
    producers: ['Fattoria Zerbina'],
    aliases: ['Zerbina DOC']
  },
  {
    id: 'sangiovese-romagna-doc-poderi-dal-nespoli',
    name: 'Sangiovese di Romagna',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Forlì',
    grapeVariety: 'Sangiovese',
    classification: 'DOC',
    minVintage: 1929,
    avgPrice: 10,
    producers: ['Poderi dal Nespoli'],
    aliases: ['Dal Nespoli DOC']
  },
  
  // CAGNINA DI ROMAGNA DOC (Sweet red)
  {
    id: 'cagnina-romagna-tre-monti',
    name: 'Cagnina di Romagna',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Imola',
    grapeVariety: 'Terrano (Refosco)',
    classification: 'DOC',
    minVintage: 1996,
    avgPrice: 14,
    producers: ['Tre Monti'],
    aliases: ['Tre Monti Cagnina']
  },
  {
    id: 'cagnina-romagna-fattoria-zerbina',
    name: 'Cagnina di Romagna',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Faenza',
    grapeVariety: 'Terrano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Fattoria Zerbina'],
    aliases: ['Zerbina Cagnina']
  },
  
  // GUTTURNIO DOC (Red blend - Piacenza)
  {
    id: 'gutturnio-la-tosa-vigna-moriona',
    name: 'Gutturnio Classico Superiore Vigna Moriona Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Barbera, Bonarda',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 28,
    producers: ['La Tosa'],
    aliases: ['Vigna Moriona']
  },
  {
    id: 'gutturnio-la-tosa',
    name: 'Gutturnio Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Barbera, Bonarda',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 16,
    producers: ['La Tosa'],
    aliases: ['La Tosa Gutturnio']
  },
  {
    id: 'gutturnio-la-stoppa-stoppa',
    name: 'Gutturnio',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Barbera, Bonarda',
    classification: 'DOC',
    minVintage: 1973,
    avgPrice: 22,
    producers: ['La Stoppa'],
    aliases: ['La Stoppa Gutturnio']
  },
  {
    id: 'gutturnio-torre-fornello',
    name: 'Gutturnio Classico Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Barbera, Bonarda',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 18,
    producers: ['Torre Fornello'],
    aliases: ['Torre Fornello Gutturnio']
  },
  {
    id: 'gutturnio-valtidone',
    name: 'Gutturnio',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Barbera, Bonarda',
    classification: 'DOC',
    minVintage: 1967,
    avgPrice: 14,
    producers: ['Cantina Valtidone'],
    aliases: ['Valtidone Gutturnio']
  },
  
  // GUTTURNIO FRIZZANTE (Sparkling red)
  {
    id: 'gutturnio-frizzante-la-tosa',
    name: 'Gutturnio Frizzante',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Barbera, Bonarda',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 14,
    producers: ['La Tosa'],
    aliases: ['La Tosa Frizzante']
  },
  {
    id: 'gutturnio-frizzante-la-stoppa',
    name: 'Gutturnio Frizzante',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Barbera, Bonarda',
    classification: 'DOC',
    minVintage: 1973,
    avgPrice: 16,
    producers: ['La Stoppa'],
    aliases: ['La Stoppa Frizzante']
  },
  
  // BARBERA (Emilia-Romagna)
  {
    id: 'barbera-emilia-la-stoppa-barbera-stoppa',
    name: 'Barbera dell\'Emilia',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Barbera',
    classification: 'IGT',
    minVintage: 1973,
    avgPrice: 18,
    producers: ['La Stoppa'],
    aliases: ['La Stoppa Barbera']
  },
  {
    id: 'barbera-emilia-la-tosa',
    name: 'Barbera dell\'Emilia',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Barbera',
    classification: 'IGT',
    minVintage: 1984,
    avgPrice: 16,
    producers: ['La Tosa'],
    aliases: ['La Tosa Barbera']
  },
  
  // BONARDA (Emilia-Romagna)
  {
    id: 'bonarda-emilia-la-stoppa',
    name: 'Bonarda dell\'Emilia',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Bonarda',
    classification: 'IGT',
    minVintage: 1973,
    avgPrice: 18,
    producers: ['La Stoppa'],
    aliases: ['La Stoppa Bonarda']
  },
  
  // PREMIUM RED BLENDS
  {
    id: 'emilia-romagna-tre-monti-boldesico',
    name: 'Boldesico Emilia-Romagna IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Imola',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Tre Monti'],
    aliases: ['Boldesico']
  },
  {
    id: 'emilia-romagna-san-patrignano-noi',
    name: 'Noi Rubicone IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Rimini',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Sangiovese',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 45,
    producers: ['San Patrignano'],
    aliases: ['Noi']
  },
  {
    id: 'emilia-romagna-la-stoppa-macchiona',
    name: 'Macchiona Emilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Barbera, Bonarda',
    classification: 'IGT',
    minVintage: 1991,
    avgPrice: 38,
    producers: ['La Stoppa'],
    aliases: ['Macchiona']
  },
  {
    id: 'emilia-romagna-umberto-cesari-moma',
    name: 'Moma Rubicone IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Castel San Pietro',
    grapeVariety: 'Sangiovese, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['Umberto Cesari'],
    aliases: ['Moma']
  },
  {
    id: 'emilia-romagna-fattoria-zerbina-marzieno',
    name: 'Marzieno di Marzieno Ravenna IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Faenza',
    grapeVariety: 'Sangiovese, Ancellotta',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 38,
    producers: ['Fattoria Zerbina'],
    aliases: ['Marzieno']
  },
  {
    id: 'emilia-romagna-la-tosa-sorriso-di-cielo',
    name: 'Sorriso di Cielo Emilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Piacenza',
    grapeVariety: 'Barbera, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 35,
    producers: ['La Tosa'],
    aliases: ['Sorriso di Cielo']
  },
  {
    id: 'emilia-romagna-poderi-dal-nespoli-borgo-prugneto',
    name: 'Borgo dei Prugnoli Rubicone IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Emilia-Romagna',
    subRegion: 'Forlì',
    grapeVariety: 'Sangiovese, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Poderi dal Nespoli'],
    aliases: ['Borgo dei Prugnoli']
  },
];
