import { WineTemplate } from '@/types/wineDatabase';

/**
 * TUSCANY WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Chianti Classico, Chianti, Vino Nobile di Montepulciano
 * Updated: January 2025
 */

export const tuscanyPart2: WineTemplate[] = [
  // CHIANTI CLASSICO DOCG
  {
    id: 'chianti-classico-antinori-riserva',
    name: 'Chianti Classico Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1928,
    avgPrice: 30,
    producers: ['Antinori', 'Marchesi Antinori'],
    aliases: ['Antinori Chianti Classico']
  },
  {
    id: 'chianti-classico-antinori-tignanello',
    name: 'Tignanello',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese, Cabernet Sauvignon, Cabernet Franc',
    classification: 'IGT Toscana',
    minVintage: 1971,
    avgPrice: 120,
    producers: ['Antinori'],
    aliases: ['Tignanello']
  },
  {
    id: 'chianti-classico-isole-olena',
    name: 'Chianti Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1956,
    avgPrice: 28,
    producers: ['Isole e Olena', 'Paolo De Marchi'],
    aliases: ['Isole e Olena']
  },
  {
    id: 'chianti-classico-fontodi',
    name: 'Chianti Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1968,
    avgPrice: 32,
    producers: ['Fontodi', 'Giovanni Manetti'],
    aliases: ['Fontodi']
  },
  {
    id: 'chianti-classico-fontodi-vigna-sorbo',
    name: 'Chianti Classico Vigna del Sorbo Gran Selezione',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 85,
    producers: ['Fontodi'],
    aliases: ['Vigna del Sorbo']
  },
  {
    id: 'chianti-classico-monsanto-riserva',
    name: 'Chianti Classico Il Poggio Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1962,
    avgPrice: 45,
    producers: ['Castello di Monsanto'],
    aliases: ['Il Poggio', 'Monsanto']
  },
  {
    id: 'chianti-classico-felsina-riserva',
    name: 'Chianti Classico Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1966,
    avgPrice: 35,
    producers: ['Felsina', 'Fattoria di Felsina'],
    aliases: ['Felsina']
  },
  {
    id: 'chianti-classico-felsina-rancia',
    name: 'Chianti Classico Rancia Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1983,
    avgPrice: 60,
    producers: ['Felsina'],
    aliases: ['Rancia']
  },
  {
    id: 'chianti-classico-ruffino-riserva-ducale',
    name: 'Chianti Classico Riserva Ducale',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1927,
    avgPrice: 28,
    producers: ['Ruffino'],
    aliases: ['Riserva Ducale']
  },
  {
    id: 'chianti-classico-ruffino-ducale-oro',
    name: 'Chianti Classico Riserva Ducale Oro',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1947,
    avgPrice: 55,
    producers: ['Ruffino'],
    aliases: ['Ducale Oro']
  },
  {
    id: 'chianti-classico-querciabella',
    name: 'Chianti Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1974,
    avgPrice: 30,
    producers: ['Querciabella'],
    aliases: ['Querciabella']
  },
  {
    id: 'chianti-classico-castellare',
    name: 'Chianti Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1968,
    avgPrice: 25,
    producers: ['Castellare di Castellina'],
    aliases: ['Castellare']
  },
  {
    id: 'chianti-classico-castello-ama',
    name: 'Chianti Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1972,
    avgPrice: 32,
    producers: ['Castello di Ama'],
    aliases: ['Castello di Ama']
  },
  {
    id: 'chianti-classico-badia-coltibuono',
    name: 'Chianti Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1846,
    avgPrice: 26,
    producers: ['Badia a Coltibuono'],
    aliases: ['Badia a Coltibuono']
  },
  {
    id: 'chianti-classico-rocca-montegrossi',
    name: 'Chianti Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1977,
    avgPrice: 28,
    producers: ['Rocca di Montegrossi'],
    aliases: ['Rocca di Montegrossi']
  },
  {
    id: 'chianti-classico-san-giusto-rentennano',
    name: 'Chianti Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1957,
    avgPrice: 30,
    producers: ['San Giusto a Rentennano'],
    aliases: ['San Giusto a Rentennano']
  },
  {
    id: 'chianti-classico-castello-volpaia',
    name: 'Chianti Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1966,
    avgPrice: 27,
    producers: ['Castello di Volpaia'],
    aliases: ['Volpaia']
  },
  {
    id: 'chianti-classico-nittardi',
    name: 'Chianti Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1982,
    avgPrice: 24,
    producers: ['Fattoria Nittardi'],
    aliases: ['Nittardi']
  },
  {
    id: 'chianti-classico-lamole-lamole',
    name: 'Chianti Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 22,
    producers: ['Lamole di Lamole'],
    aliases: ['Lamole di Lamole']
  },
  {
    id: 'chianti-classico-villa-cafaggio',
    name: 'Chianti Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Chianti Classico',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1967,
    avgPrice: 25,
    producers: ['Villa Cafaggio'],
    aliases: ['Cafaggio']
  },
  
  // VINO NOBILE DI MONTEPULCIANO DOCG
  {
    id: 'vino-nobile-avignonesi',
    name: 'Vino Nobile di Montepulciano',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montepulciano',
    grapeVariety: 'Sangiovese (Prugnolo Gentile)',
    classification: 'DOCG',
    minVintage: 1950,
    avgPrice: 35,
    producers: ['Avignonesi'],
    aliases: ['Avignonesi']
  },
  {
    id: 'vino-nobile-avignonesi-grandi-annate',
    name: 'Vino Nobile di Montepulciano Grandi Annate',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montepulciano',
    grapeVariety: 'Sangiovese (Prugnolo Gentile)',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 65,
    producers: ['Avignonesi'],
    aliases: ['Grandi Annate']
  },
  {
    id: 'vino-nobile-boscarelli',
    name: 'Vino Nobile di Montepulciano',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montepulciano',
    grapeVariety: 'Sangiovese (Prugnolo Gentile)',
    classification: 'DOCG',
    minVintage: 1968,
    avgPrice: 32,
    producers: ['Boscarelli', 'Poderi Boscarelli'],
    aliases: ['Boscarelli']
  },
  {
    id: 'vino-nobile-boscarelli-nocio',
    name: 'Vino Nobile di Montepulciano Nocio dei Boscarelli',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montepulciano',
    grapeVariety: 'Sangiovese (Prugnolo Gentile)',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 75,
    producers: ['Boscarelli'],
    aliases: ['Nocio dei Boscarelli']
  },
  {
    id: 'vino-nobile-poliziano',
    name: 'Vino Nobile di Montepulciano',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montepulciano',
    grapeVariety: 'Sangiovese (Prugnolo Gentile)',
    classification: 'DOCG',
    minVintage: 1961,
    avgPrice: 28,
    producers: ['Poliziano'],
    aliases: ['Poliziano']
  },
  {
    id: 'vino-nobile-poliziano-asinone',
    name: 'Vino Nobile di Montepulciano Asinone',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montepulciano',
    grapeVariety: 'Sangiovese (Prugnolo Gentile)',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 60,
    producers: ['Poliziano'],
    aliases: ['Asinone']
  },
  {
    id: 'vino-nobile-dei',
    name: 'Vino Nobile di Montepulciano',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montepulciano',
    grapeVariety: 'Sangiovese (Prugnolo Gentile)',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 25,
    producers: ['Dei'],
    aliases: ['Dei']
  },
  {
    id: 'vino-nobile-salcheto',
    name: 'Vino Nobile di Montepulciano',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montepulciano',
    grapeVariety: 'Sangiovese (Prugnolo Gentile)',
    classification: 'DOCG',
    minVintage: 1997,
    avgPrice: 24,
    producers: ['Salcheto'],
    aliases: ['Salcheto']
  },
  {
    id: 'vino-nobile-contucci',
    name: 'Vino Nobile di Montepulciano',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montepulciano',
    grapeVariety: 'Sangiovese (Prugnolo Gentile)',
    classification: 'DOCG',
    minVintage: 1700,
    avgPrice: 26,
    producers: ['Contucci'],
    aliases: ['Contucci']
  },
  {
    id: 'vino-nobile-trerose',
    name: 'Vino Nobile di Montepulciano',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montepulciano',
    grapeVariety: 'Sangiovese (Prugnolo Gentile)',
    classification: 'DOCG',
    minVintage: 1973,
    avgPrice: 22,
    producers: ['Tenuta Trerose'],
    aliases: ['Trerose']
  },
  
  // CHIANTI RUFINA DOCG
  {
    id: 'chianti-rufina-selvapiana',
    name: 'Chianti Rufina',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Rufina',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1827,
    avgPrice: 20,
    producers: ['Selvapiana'],
    aliases: ['Selvapiana']
  },
  {
    id: 'chianti-rufina-selvapiana-bucerchiale',
    name: 'Chianti Rufina Bucerchiale Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Rufina',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1979,
    avgPrice: 42,
    producers: ['Selvapiana'],
    aliases: ['Bucerchiale']
  },
  {
    id: 'chianti-rufina-frescobaldi-nipozzano',
    name: 'Chianti Rufina Nipozzano Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Rufina',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1855,
    avgPrice: 24,
    producers: ['Frescobaldi', 'Marchesi de\' Frescobaldi'],
    aliases: ['Nipozzano']
  },
  {
    id: 'chianti-rufina-frescobaldi-montesodi',
    name: 'Chianti Rufina Montesodi',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Rufina',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1974,
    avgPrice: 48,
    producers: ['Frescobaldi'],
    aliases: ['Montesodi']
  },
  {
    id: 'chianti-rufina-pomino',
    name: 'Chianti Rufina Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Rufina',
    grapeVariety: 'Sangiovese',
    classification: 'DOCG',
    minVintage: 1976,
    avgPrice: 22,
    producers: ['Fattoria di Pomino', 'Frescobaldi'],
    aliases: ['Pomino Rufina']
  },
  
  // CARMIGNANO DOCG
  {
    id: 'carmignano-villa-capezzana',
    name: 'Carmignano',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Carmignano',
    grapeVariety: 'Sangiovese, Cabernet Sauvignon',
    classification: 'DOCG',
    minVintage: 1925,
    avgPrice: 28,
    producers: ['Tenuta di Capezzana', 'Villa Capezzana'],
    aliases: ['Capezzana']
  },
  {
    id: 'carmignano-villa-capezzana-riserva',
    name: 'Carmignano Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Carmignano',
    grapeVariety: 'Sangiovese, Cabernet Sauvignon',
    classification: 'DOCG',
    minVintage: 1975,
    avgPrice: 45,
    producers: ['Tenuta di Capezzana'],
    aliases: ['Capezzana Riserva']
  },
  {
    id: 'carmignano-ambra',
    name: 'Carmignano',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Carmignano',
    grapeVariety: 'Sangiovese, Cabernet Sauvignon',
    classification: 'DOCG',
    minVintage: 1925,
    avgPrice: 22,
    producers: ['Fattoria Ambra'],
    aliases: ['Ambra']
  },
  {
    id: 'carmignano-ambra-vigna-alta',
    name: 'Carmignano Vigna di Montalbiolo Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Carmignano',
    grapeVariety: 'Sangiovese, Cabernet Sauvignon',
    classification: 'DOCG',
    minVintage: 1988,
    avgPrice: 38,
    producers: ['Fattoria Ambra'],
    aliases: ['Vigna Alta']
  },
  {
    id: 'carmignano-piaggia',
    name: 'Carmignano Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Carmignano',
    grapeVariety: 'Sangiovese, Cabernet Sauvignon',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 35,
    producers: ['Piaggia'],
    aliases: ['Piaggia']
  },
  
  // MORELLINO DI SCANSANO DOCG
  {
    id: 'morellino-moris-farms',
    name: 'Morellino di Scansano',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Scansano',
    grapeVariety: 'Sangiovese (Morellino)',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 18,
    producers: ['Moris Farms'],
    aliases: ['Moris Farms']
  },
  {
    id: 'morellino-moris-farms-riserva',
    name: 'Morellino di Scansano Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Scansano',
    grapeVariety: 'Sangiovese (Morellino)',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 28,
    producers: ['Moris Farms'],
    aliases: ['Moris Farms Riserva']
  },
  {
    id: 'morellino-le-pupille',
    name: 'Morellino di Scansano',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Scansano',
    grapeVariety: 'Sangiovese (Morellino)',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 16,
    producers: ['Le Pupille'],
    aliases: ['Le Pupille']
  },
  {
    id: 'morellino-le-pupille-poggio-valente',
    name: 'Morellino di Scansano Poggio Valente Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Scansano',
    grapeVariety: 'Sangiovese (Morellino)',
    classification: 'DOCG',
    minVintage: 1995,
    avgPrice: 32,
    producers: ['Le Pupille'],
    aliases: ['Poggio Valente']
  },
  {
    id: 'morellino-roccapesta',
    name: 'Morellino di Scansano',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Scansano',
    grapeVariety: 'Sangiovese (Morellino)',
    classification: 'DOCG',
    minVintage: 1998,
    avgPrice: 14,
    producers: ['Roccapesta'],
    aliases: ['Roccapesta']
  },
  {
    id: 'morellino-mantellassi',
    name: 'Morellino di Scansano',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Scansano',
    grapeVariety: 'Sangiovese (Morellino)',
    classification: 'DOCG',
    minVintage: 1960,
    avgPrice: 12,
    producers: ['Fattoria Le Pupille', 'Mantellassi'],
    aliases: ['Mantellassi']
  },
];
