import { WineTemplate } from '@/types/wineDatabase';

/**
 * TUSCANY WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Brunello di Montalcino, Rosso di Montalcino
 * Updated: January 2025
 */

export const tuscanyPart1: WineTemplate[] = [
  // BRUNELLO DI MONTALCINO DOCG
  {
    id: 'brunello-biondi-santi',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1888,
    avgPrice: 120,
    producers: ['Biondi Santi'],
    aliases: ['Biondi Santi Brunello']
  },
  {
    id: 'brunello-biondi-santi-riserva',
    name: 'Brunello di Montalcino Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1891,
    avgPrice: 350,
    producers: ['Biondi Santi'],
    aliases: ['Biondi Santi Riserva']
  },
  {
    id: 'brunello-soldera-case-basse',
    name: 'Brunello di Montalcino Case Basse',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1972,
    avgPrice: 450,
    producers: ['Soldera', 'Case Basse'],
    aliases: ['Soldera', 'Case Basse']
  },
  {
    id: 'brunello-soldera-intistieti',
    name: 'Brunello di Montalcino Intistieti',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 2006,
    avgPrice: 500,
    producers: ['Soldera'],
    aliases: ['Intistieti']
  },
  {
    id: 'brunello-poggio-di-sotto',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1989,
    avgPrice: 180,
    producers: ['Poggio di Sotto'],
    aliases: ['Poggio di Sotto']
  },
  {
    id: 'brunello-salvioni',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 200,
    producers: ['Salvioni', 'La Cerbaiola'],
    aliases: ['Salvioni']
  },
  {
    id: 'brunello-valdicava',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1953,
    avgPrice: 90,
    producers: ['Valdicava'],
    aliases: ['Valdicava']
  },
  {
    id: 'brunello-valdicava-madonna-piano',
    name: 'Brunello di Montalcino Madonna del Piano Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1977,
    avgPrice: 250,
    producers: ['Valdicava'],
    aliases: ['Madonna del Piano']
  },
  {
    id: 'brunello-casanova-neri',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1971,
    avgPrice: 75,
    producers: ['Casanova di Neri'],
    aliases: ['Casanova di Neri']
  },
  {
    id: 'brunello-casanova-tenuta-nuova',
    name: 'Brunello di Montalcino Tenuta Nuova',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1993,
    avgPrice: 180,
    producers: ['Casanova di Neri'],
    aliases: ['Tenuta Nuova']
  },
  {
    id: 'brunello-casanova-cerretalto',
    name: 'Brunello di Montalcino Cerretalto',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1999,
    avgPrice: 220,
    producers: ['Casanova di Neri'],
    aliases: ['Cerretalto']
  },
  {
    id: 'brunello-siro-pacenti',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1988,
    avgPrice: 110,
    producers: ['Siro Pacenti'],
    aliases: ['Pacenti']
  },
  {
    id: 'brunello-il-poggione',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1964,
    avgPrice: 65,
    producers: ['Il Poggione'],
    aliases: ['Poggione']
  },
  {
    id: 'brunello-mastrojanni',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1975,
    avgPrice: 70,
    producers: ['Mastrojanni'],
    aliases: ['Mastrojanni']
  },
  {
    id: 'brunello-mastrojanni-schiena-asino',
    name: 'Brunello di Montalcino Schiena d\'Asino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1997,
    avgPrice: 140,
    producers: ['Mastrojanni'],
    aliases: ['Schiena d\'Asino']
  },
  {
    id: 'brunello-ciacci-piccolomini',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 75,
    producers: ['Ciacci Piccolomini d\'Aragona'],
    aliases: ['Ciacci']
  },
  {
    id: 'brunello-ciacci-pianrosso',
    name: 'Brunello di Montalcino Pianrosso',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 120,
    producers: ['Ciacci Piccolomini d\'Aragona'],
    aliases: ['Pianrosso']
  },
  {
    id: 'brunello-altesino',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1970,
    avgPrice: 60,
    producers: ['Altesino'],
    aliases: ['Altesino']
  },
  {
    id: 'brunello-altesino-montosoli',
    name: 'Brunello di Montalcino Montosoli',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1975,
    avgPrice: 95,
    producers: ['Altesino'],
    aliases: ['Montosoli']
  },
  {
    id: 'brunello-caparzo',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1970,
    avgPrice: 55,
    producers: ['Caparzo'],
    aliases: ['Caparzo']
  },
  {
    id: 'brunello-caparzo-la-casa',
    name: 'Brunello di Montalcino La Casa',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1977,
    avgPrice: 150,
    producers: ['Caparzo'],
    aliases: ['La Casa']
  },
  {
    id: 'brunello-banfi',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1978,
    avgPrice: 50,
    producers: ['Banfi', 'Castello Banfi'],
    aliases: ['Banfi']
  },
  {
    id: 'brunello-col-dorcia',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1973,
    avgPrice: 60,
    producers: ['Col d\'Orcia'],
    aliases: ['Col d\'Orcia']
  },
  {
    id: 'brunello-conti-costanti',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1865,
    avgPrice: 90,
    producers: ['Conti Costanti'],
    aliases: ['Costanti']
  },
  {
    id: 'brunello-fuligni',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1972,
    avgPrice: 70,
    producers: ['Fuligni'],
    aliases: ['Fuligni']
  },
  {
    id: 'brunello-lisini',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1967,
    avgPrice: 65,
    producers: ['Lisini'],
    aliases: ['Lisini']
  },
  {
    id: 'brunello-lisini-ugolaia',
    name: 'Brunello di Montalcino Ugolaia',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1987,
    avgPrice: 120,
    producers: ['Lisini'],
    aliases: ['Ugolaia']
  },
  {
    id: 'brunello-pian-vigne',
    name: 'Brunello di Montalcino Pian delle Vigne',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1995,
    avgPrice: 55,
    producers: ['Pian delle Vigne', 'Antinori'],
    aliases: ['Pian delle Vigne']
  },
  {
    id: 'brunello-poggio-antico',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1977,
    avgPrice: 65,
    producers: ['Poggio Antico'],
    aliases: ['Poggio Antico']
  },
  {
    id: 'brunello-talenti',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1980,
    avgPrice: 60,
    producers: ['Talenti'],
    aliases: ['Talenti']
  },
  {
    id: 'brunello-argiano',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1992,
    avgPrice: 55,
    producers: ['Argiano'],
    aliases: ['Argiano']
  },
  {
    id: 'brunello-barbi',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1892,
    avgPrice: 50,
    producers: ['Barbi', 'Fattoria dei Barbi'],
    aliases: ['Barbi']
  },
  {
    id: 'brunello-canalicchio-sopra',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1966,
    avgPrice: 70,
    producers: ['Canalicchio di Sopra'],
    aliases: ['Canalicchio']
  },
  {
    id: 'brunello-castiglion-bosco',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 2003,
    avgPrice: 75,
    producers: ['Castiglion del Bosco'],
    aliases: ['Castiglion del Bosco']
  },
  {
    id: 'brunello-fanti',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 55,
    producers: ['Fanti'],
    aliases: ['Fanti']
  },
  {
    id: 'brunello-la-gerla',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1976,
    avgPrice: 60,
    producers: ['La Gerla'],
    aliases: ['La Gerla']
  },
  {
    id: 'brunello-le-potazzine',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1993,
    avgPrice: 80,
    producers: ['Le Potazzine'],
    aliases: ['Le Potazzine']
  },
  {
    id: 'brunello-pieve-restituta',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1994,
    avgPrice: 65,
    producers: ['Pieve Santa Restituta', 'Gaja'],
    aliases: ['Pieve Santa Restituta']
  },
  {
    id: 'brunello-san-filippo',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1972,
    avgPrice: 55,
    producers: ['San Filippo'],
    aliases: ['San Filippo']
  },
  {
    id: 'brunello-uccelliera',
    name: 'Brunello di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOCG',
    minVintage: 1986,
    avgPrice: 75,
    producers: ['Uccelliera'],
    aliases: ['Uccelliera']
  },
  
  // ROSSO DI MONTALCINO DOC
  {
    id: 'rosso-montalcino-biondi-santi',
    name: 'Rosso di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOC',
    minVintage: 1984,
    avgPrice: 40,
    producers: ['Biondi Santi'],
    aliases: ['Rosso Biondi Santi']
  },
  {
    id: 'rosso-montalcino-casanova-neri',
    name: 'Rosso di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 30,
    producers: ['Casanova di Neri'],
    aliases: ['Rosso Casanova']
  },
  {
    id: 'rosso-montalcino-il-poggione',
    name: 'Rosso di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOC',
    minVintage: 1975,
    avgPrice: 25,
    producers: ['Il Poggione'],
    aliases: ['Rosso Poggione']
  },
  {
    id: 'rosso-montalcino-altesino',
    name: 'Rosso di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOC',
    minVintage: 1975,
    avgPrice: 22,
    producers: ['Altesino'],
    aliases: ['Rosso Altesino']
  },
  {
    id: 'rosso-montalcino-valdicava',
    name: 'Rosso di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 35,
    producers: ['Valdicava'],
    aliases: ['Rosso Valdicava']
  },
  {
    id: 'rosso-montalcino-ciacci',
    name: 'Rosso di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Ciacci Piccolomini d\'Aragona'],
    aliases: ['Rosso Ciacci']
  },
  {
    id: 'rosso-montalcino-mastrojanni',
    name: 'Rosso di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 26,
    producers: ['Mastrojanni'],
    aliases: ['Rosso Mastrojanni']
  },
  {
    id: 'rosso-montalcino-pian-vigne',
    name: 'Rosso di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Pian delle Vigne', 'Antinori'],
    aliases: ['Rosso Pian delle Vigne']
  },
  {
    id: 'rosso-montalcino-banfi',
    name: 'Rosso di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 18,
    producers: ['Banfi'],
    aliases: ['Rosso Banfi']
  },
  {
    id: 'rosso-montalcino-canalicchio',
    name: 'Rosso di Montalcino',
    type: 'Red',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Montalcino',
    grapeVariety: 'Sangiovese Grosso',
    classification: 'DOC',
    minVintage: 1975,
    avgPrice: 24,
    producers: ['Canalicchio di Sopra'],
    aliases: ['Rosso Canalicchio']
  },
];
