import { WineTemplate } from '@/types/wineDatabase';

/**
 * LAZIO WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Cori DOC, Additional blends, Sparkling wines, Regional varieties
 * Updated: January 2025
 */

export const lazioPart3: WineTemplate[] = [
  // CORI DOC (Red & White)
  {
    id: 'cori-rosso-cincinnato',
    name: 'Cori Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Cori',
    grapeVariety: 'Montepulciano, Nero Buono, Cesanese',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 14,
    producers: ['Cincinnato'],
    aliases: ['Cincinnato Cori Rosso']
  },
  {
    id: 'cori-bianco-cincinnato',
    name: 'Cori Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Cori',
    grapeVariety: 'Bellone, Trebbiano, Malvasia',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 12,
    producers: ['Cincinnato'],
    aliases: ['Cincinnato Cori Bianco']
  },
  
  // VELLETRI DOC (Red & White)
  {
    id: 'velletri-rosso-fontana-candida',
    name: 'Velletri Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Velletri',
    grapeVariety: 'Sangiovese, Montepulciano, Cesanese',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 14,
    producers: ['Fontana Candida'],
    aliases: ['Fontana Candida Velletri Rosso']
  },
  {
    id: 'velletri-bianco-fontana-candida',
    name: 'Velletri Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Velletri',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 11,
    producers: ['Fontana Candida'],
    aliases: ['Fontana Candida Velletri Bianco']
  },
  
  // COLLI ALBANI DOC (White)
  {
    id: 'colli-albani-fontana-candida',
    name: 'Colli Albani',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Colli Albani',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 11,
    producers: ['Fontana Candida'],
    aliases: ['Fontana Candida Colli Albani']
  },
  {
    id: 'colli-albani-castel-de-paolis',
    name: 'Colli Albani',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Colli Albani',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 12,
    producers: ['Castel De Paolis'],
    aliases: ['Castel De Paolis Colli Albani']
  },
  
  // COLLI LANUVINI DOC (White)
  {
    id: 'colli-lanuvini-fontana-candida',
    name: 'Colli Lanuvini',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Lanuvio',
    grapeVariety: 'Malvasia Puntinata, Trebbiano, Bellone',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 11,
    producers: ['Fontana Candida'],
    aliases: ['Fontana Candida Colli Lanuvini']
  },
  
  // SPARKLING WINES
  {
    id: 'spumante-fontana-candida-brut',
    name: 'Spumante Brut',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Fontana Candida'],
    aliases: ['Fontana Candida Spumante']
  },
  {
    id: 'spumante-casale-del-giglio-brut',
    name: 'Spumante Brut Metodo Classico',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Chardonnay, Pinot Noir',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Metodo Classico']
  },
  {
    id: 'spumante-poggio-le-volpi-brut',
    name: 'Spumante Brut',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 20,
    producers: ['Poggio Le Volpi'],
    aliases: ['Poggio Le Volpi Spumante']
  },
  
  // ADDITIONAL PREMIUM WINES
  {
    id: 'lazio-falesco-tellus',
    name: 'Tellus Syrah Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Viterbo',
    grapeVariety: 'Syrah',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Falesco'],
    aliases: ['Tellus']
  },
  {
    id: 'lazio-falesco-famiglia-cotarella',
    name: 'Famiglia Cotarella Merlot Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Viterbo',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 24,
    producers: ['Falesco'],
    aliases: ['Famiglia Cotarella']
  },
  {
    id: 'lazio-casale-del-giglio-antinoo',
    name: 'Antinoo Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Cabernet Sauvignon, Petit Verdot',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Casale del Giglio'],
    aliases: ['Antinoo']
  },
  {
    id: 'lazio-cincinnato-echo',
    name: 'Echo Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Cori',
    grapeVariety: 'Bellone',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Cincinnato'],
    aliases: ['Echo']
  },
  {
    id: 'lazio-poggio-le-volpi-donnaluce',
    name: 'Donnaluce Frascati Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Greco',
    classification: 'DOCG',
    minVintage: 2008,
    avgPrice: 20,
    producers: ['Poggio Le Volpi'],
    aliases: ['Donnaluce']
  },
  {
    id: 'lazio-sergio-mottura-tragugnano',
    name: 'Tragugnano Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Viterbo',
    grapeVariety: 'Grechetto, Procanico',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Sergio Mottura'],
    aliases: ['Tragugnano']
  },
  {
    id: 'lazio-villa-simone-cannellino-riserva',
    name: 'Cannellino di Frascati Riserva',
    type: 'Dessert',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata',
    classification: 'DOCG',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Villa Simone'],
    aliases: ['Villa Simone Cannellino Riserva']
  },
  {
    id: 'lazio-colle-picchioni-etichetta-oro',
    name: 'Marino Superiore Etichetta Oro',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Marino',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 22,
    producers: ['Colle Picchioni'],
    aliases: ['Etichetta Oro']
  },
  {
    id: 'lazio-casale-del-giglio-mater-matuta-riserva',
    name: 'Mater Matuta Riserva Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Petit Verdot',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 58,
    producers: ['Casale del Giglio'],
    aliases: ['Mater Matuta Riserva']
  },
  {
    id: 'lazio-damiano-ciolli-colle-ticchio',
    name: 'Colle Ticchio Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Piglio',
    grapeVariety: 'Cesanese',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 28,
    producers: ['Damiano Ciolli'],
    aliases: ['Colle Ticchio']
  },
  {
    id: 'lazio-casale-della-ioria-romanico',
    name: 'Romanico Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Piglio',
    grapeVariety: 'Cesanese, Syrah',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Casale della Ioria'],
    aliases: ['Romanico']
  },
  {
    id: 'lazio-falesco-vitiano',
    name: 'Vitiano Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Viterbo',
    grapeVariety: 'Sangiovese, Merlot, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 1998,
    avgPrice: 14,
    producers: ['Falesco'],
    aliases: ['Vitiano']
  },
  {
    id: 'lazio-falesco-roscetto',
    name: 'Roscetto Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Viterbo',
    grapeVariety: 'Roscetto',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Falesco'],
    aliases: ['Falesco Roscetto']
  },
  {
    id: 'lazio-fontana-candida-terre-dei-grifi',
    name: 'Terre dei Grifi Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Montepulciano, Syrah',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Fontana Candida'],
    aliases: ['Terre dei Grifi']
  },
  {
    id: 'lazio-cincinnato-moro',
    name: 'Moro Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Cori',
    grapeVariety: 'Syrah',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 24,
    producers: ['Cincinnato'],
    aliases: ['Moro']
  },
  {
    id: 'lazio-coletti-conti-torre-del-piano',
    name: 'Torre del Piano Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Piglio',
    grapeVariety: 'Cabernet Sauvignon, Cesanese',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Coletti Conti'],
    aliases: ['Torre del Piano']
  },
  {
    id: 'lazio-casale-del-giglio-aphrodisium',
    name: 'Aphrodisium Passito Lazio IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Aleatico',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 42,
    producers: ['Casale del Giglio'],
    aliases: ['Aphrodisium']
  },
  {
    id: 'lazio-poggio-le-volpi-armoso',
    name: 'Armoso Passito Lazio IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 38,
    producers: ['Poggio Le Volpi'],
    aliases: ['Armoso']
  },
  {
    id: 'lazio-castel-de-paolis-selene',
    name: 'Selene Lazio IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Castel De Paolis'],
    aliases: ['Selene']
  },
  {
    id: 'lazio-gotto-d-oro-rosso',
    name: 'Rosso Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Sangiovese, Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Gotto d\'Oro'],
    aliases: ['Gotto d\'Oro Rosso']
  },
  {
    id: 'lazio-conte-zandotti-rosso',
    name: 'Rosso Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Sangiovese, Montepulciano',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Conte Zandotti'],
    aliases: ['Conte Zandotti Rosso']
  },
  {
    id: 'lazio-san-marco-rosso',
    name: 'Rosso Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Sangiovese, Cesanese',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['San Marco'],
    aliases: ['San Marco Rosso']
  },
  {
    id: 'lazio-merumalia-rosso',
    name: 'Rosso Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Sangiovese, Montepulciano',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 20,
    producers: ['Merumalia'],
    aliases: ['Merumalia Rosso']
  },
  {
    id: 'lazio-terenzi-rosso',
    name: 'Rosso Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Piglio',
    grapeVariety: 'Cesanese, Sangiovese',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Terenzi'],
    aliases: ['Terenzi Rosso']
  },
  {
    id: 'lazio-casale-del-giglio-tempranillo',
    name: 'Tempranillo Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Tempranillo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Tempranillo']
  },
  {
    id: 'lazio-casale-del-giglio-sangiovese',
    name: 'Sangiovese Lazio IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Sangiovese',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 18,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Sangiovese']
  },
];
