import { WineTemplate } from '@/types/wineDatabase';

/**
 * CALABRIA WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Additional producers, Blends, Regional varieties, Dessert wines
 * Updated: January 2025
 */

export const calabriaPart3: WineTemplate[] = [
  // ADDITIONAL PREMIUM BLENDS
  {
    id: 'calabria-librandi-duca-san-felice-igt',
    name: 'Duca San Felice Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Librandi'],
    aliases: ['Duca San Felice IGT']
  },
  {
    id: 'calabria-ippolito-colli-del-mancuso-igt',
    name: 'Colli del Mancuso Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 24,
    producers: ['Ippolito 1845'],
    aliases: ['Colli del Mancuso IGT']
  },
  {
    id: 'calabria-sergio-arcuri-rosso-blend',
    name: 'Rosso Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 32,
    producers: ['Sergio Arcuri'],
    aliases: ['Sergio Arcuri Rosso Blend']
  },
  {
    id: 'calabria-cataldo-calabretta-vino-rosso',
    name: 'Vino Rosso Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo, Nerello, Greco Nero',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 26,
    producers: ['Cataldo Calabretta'],
    aliases: ['Calabretta Vino Rosso']
  },
  
  // GRECO NERO (Indigenous variety)
  {
    id: 'greco-nero-librandi',
    name: 'Greco Nero Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Nero',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Librandi'],
    aliases: ['Librandi Greco Nero']
  },
  {
    id: 'greco-nero-odoardi',
    name: 'Greco Nero Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Savuto',
    grapeVariety: 'Greco Nero',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 20,
    producers: ['Odoardi'],
    aliases: ['Odoardi Greco Nero']
  },
  
  // ADDITIONAL DESSERT WINES
  {
    id: 'passito-librandi',
    name: 'Passito Calabria IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco, Mantonico',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 38,
    producers: ['Librandi'],
    aliases: ['Librandi Passito']
  },
  {
    id: 'passito-ippolito',
    name: 'Passito Calabria IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 35,
    producers: ['Ippolito 1845'],
    aliases: ['Ippolito Passito']
  },
  {
    id: 'moscato-passito-odoardi',
    name: 'Moscato Passito Calabria IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Savuto',
    grapeVariety: 'Moscato',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 32,
    producers: ['Odoardi'],
    aliases: ['Odoardi Moscato Passito']
  },
  
  // ADDITIONAL WHITE VARIETIES
  {
    id: 'pecorello-librandi',
    name: 'Pecorello Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Pecorello',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 20,
    producers: ['Librandi'],
    aliases: ['Librandi Pecorello']
  },
  {
    id: 'malvasia-bianca-odoardi',
    name: 'Malvasia Bianca Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Savuto',
    grapeVariety: 'Malvasia',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Odoardi'],
    aliases: ['Odoardi Malvasia']
  },
  
  // ADDITIONAL REGIONAL PRODUCERS
  {
    id: 'calabria-cantine-lento-gaglioppo',
    name: 'Gaglioppo Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 24,
    producers: ['Cantine Lento'],
    aliases: ['Lento Gaglioppo']
  },
  {
    id: 'calabria-cantine-lento-greco-bianco',
    name: 'Greco Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Cantine Lento'],
    aliases: ['Lento Greco Bianco']
  },
  {
    id: 'calabria-ceraudo-gaglioppo',
    name: 'Gaglioppo Val di Neto IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 26,
    producers: ['Ceraudo'],
    aliases: ['Ceraudo Gaglioppo']
  },
  {
    id: 'calabria-ceraudo-greco-bianco',
    name: 'Greco Bianco Val di Neto IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Ceraudo'],
    aliases: ['Ceraudo Greco Bianco']
  },
  {
    id: 'calabria-statti-gaglioppo',
    name: 'Gaglioppo Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Lamezia',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 1975,
    avgPrice: 18,
    producers: ['Statti'],
    aliases: ['Statti Gaglioppo']
  },
  {
    id: 'calabria-statti-greco-bianco',
    name: 'Greco Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Lamezia',
    grapeVariety: 'Greco Bianco',
    classification: 'IGT',
    minVintage: 1975,
    avgPrice: 14,
    producers: ['Statti'],
    aliases: ['Statti Greco Bianco']
  },
  {
    id: 'calabria-ferrocinto-gaglioppo',
    name: 'Gaglioppo Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 22,
    producers: ['Ferrocinto'],
    aliases: ['Ferrocinto Gaglioppo']
  },
  {
    id: 'calabria-vivacqua-gaglioppo',
    name: 'Gaglioppo Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 20,
    producers: ['Vivacqua'],
    aliases: ['Vivacqua Gaglioppo']
  },
  
  // ADDITIONAL ROSÉ WINES
  {
    id: 'calabria-ceraudo-rosato',
    name: 'Rosato Calabria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 14,
    producers: ['Ceraudo'],
    aliases: ['Ceraudo Rosato']
  },
  {
    id: 'calabria-statti-rosato',
    name: 'Rosato Calabria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Lamezia',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 12,
    producers: ['Statti'],
    aliases: ['Statti Rosato']
  },
  {
    id: 'calabria-cantine-lento-rosato',
    name: 'Rosato Calabria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 14,
    producers: ['Cantine Lento'],
    aliases: ['Lento Rosato']
  },
  {
    id: 'calabria-cantine-viola-rosato',
    name: 'Rosato Calabria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Pollino',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Cantine Viola'],
    aliases: ['Viola Rosato']
  },
  
  // ADDITIONAL WHITE BLENDS
  {
    id: 'calabria-sergio-arcuri-bianco-blend',
    name: 'Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco, Chardonnay',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 20,
    producers: ['Sergio Arcuri'],
    aliases: ['Sergio Arcuri Bianco Blend']
  },
  {
    id: 'calabria-cataldo-calabretta-bianco',
    name: 'Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco, Mantonico',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 20,
    producers: ['Cataldo Calabretta'],
    aliases: ['Calabretta Bianco']
  },
  {
    id: 'calabria-ferrocinto-bianco',
    name: 'Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 16,
    producers: ['Ferrocinto'],
    aliases: ['Ferrocinto Bianco']
  },
  {
    id: 'calabria-vivacqua-bianco',
    name: 'Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'IGT',
    minVintage: 2014,
    avgPrice: 14,
    producers: ['Vivacqua'],
    aliases: ['Vivacqua Bianco']
  },
  {
    id: 'calabria-cantine-viola-bianco',
    name: 'Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Pollino',
    grapeVariety: 'Greco Bianco, Malvasia',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Cantine Viola'],
    aliases: ['Viola Bianco']
  },
  
  // ADDITIONAL RED WINES
  {
    id: 'calabria-ceraudo-rosso',
    name: 'Rosso Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 28,
    producers: ['Ceraudo'],
    aliases: ['Ceraudo Rosso']
  },
  {
    id: 'calabria-statti-rosso',
    name: 'Rosso Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Lamezia',
    grapeVariety: 'Gaglioppo, Magliocco',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Statti'],
    aliases: ['Statti Rosso']
  },
  {
    id: 'calabria-cantine-lento-rosso',
    name: 'Rosso Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo, Greco Nero',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 26,
    producers: ['Cantine Lento'],
    aliases: ['Lento Rosso']
  },
  {
    id: 'calabria-ferrocinto-rosso',
    name: 'Rosso Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 24,
    producers: ['Ferrocinto'],
    aliases: ['Ferrocinto Rosso']
  },
  {
    id: 'calabria-vivacqua-rosso',
    name: 'Rosso Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2014,
    avgPrice: 22,
    producers: ['Vivacqua'],
    aliases: ['Vivacqua Rosso']
  },
  
  // ADDITIONAL PREMIUM SELECTIONS
  {
    id: 'calabria-librandi-critone-riserva',
    name: 'Critone Riserva Val di Neto IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco, Mantonico',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Librandi'],
    aliases: ['Critone Riserva']
  },
  {
    id: 'calabria-ippolito-gaglioppo-riserva',
    name: 'Gaglioppo Riserva Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 35,
    producers: ['Ippolito 1845'],
    aliases: ['Ippolito Gaglioppo Riserva']
  },
  {
    id: 'calabria-odoardi-vigna-mortilla',
    name: 'Vigna Mortilla Terre di Cosenza IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Savuto',
    grapeVariety: 'Gaglioppo, Magliocco',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 42,
    producers: ['Odoardi'],
    aliases: ['Vigna Mortilla']
  },
  {
    id: 'calabria-sergio-arcuri-superior',
    name: 'Superior Selection Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 48,
    producers: ['Sergio Arcuri'],
    aliases: ['Sergio Arcuri Superior']
  },
  {
    id: 'calabria-cataldo-calabretta-vino-bianco',
    name: 'Vino Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco, Mantonico, Malvasia',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 24,
    producers: ['Cataldo Calabretta'],
    aliases: ['Calabretta Vino Bianco']
  },
  {
    id: 'calabria-a-vita-rosso-riserva',
    name: 'Rosso Riserva Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 38,
    producers: ['A Vita'],
    aliases: ['A Vita Riserva']
  },
  {
    id: 'calabria-ceraudo-imyr',
    name: 'Imyr Val di Neto IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 42,
    producers: ['Ceraudo'],
    aliases: ['Imyr']
  },
  {
    id: 'calabria-statti-lamezia-rosso',
    name: 'Lamezia Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Lamezia',
    grapeVariety: 'Gaglioppo, Greco Nero, Magliocco',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Statti'],
    aliases: ['Statti Lamezia']
  },
  {
    id: 'calabria-statti-lamezia-bianco',
    name: 'Lamezia Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Lamezia',
    grapeVariety: 'Greco Bianco, Malvasia, Trebbiano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 13,
    producers: ['Statti'],
    aliases: ['Statti Lamezia Bianco']
  },
  {
    id: 'calabria-tenuta-del-conte-premium',
    name: 'Premium Selection Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 32,
    producers: ['Tenuta del Conte'],
    aliases: ['Tenuta del Conte Premium']
  },
];
