import { WineTemplate } from '@/types/wineDatabase';

/**
 * LAZIO WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Frascati DOCG & DOC, Est! Est!! Est!!! di Montefiascone
 * Updated: January 2025
 */

export const lazioPart1: WineTemplate[] = [
  // FRASCATI SUPERIORE DOCG (White)
  {
    id: 'frascati-villa-simone-vigneto-filonardi',
    name: 'Frascati Superiore Vigneto Filonardi',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOCG',
    minVintage: 1960,
    avgPrice: 28,
    producers: ['Villa Simone'],
    aliases: ['Vigneto Filonardi']
  },
  {
    id: 'frascati-villa-simone',
    name: 'Frascati Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Trebbiano, Greco',
    classification: 'DOCG',
    minVintage: 1960,
    avgPrice: 16,
    producers: ['Villa Simone'],
    aliases: ['Villa Simone Frascati']
  },
  {
    id: 'frascati-castel-de-paolis-campo-vecchio',
    name: 'Frascati Superiore Campo Vecchio',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Bombino',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 32,
    producers: ['Castel De Paolis'],
    aliases: ['Campo Vecchio']
  },
  {
    id: 'frascati-castel-de-paolis',
    name: 'Frascati Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Bombino, Bellone',
    classification: 'DOCG',
    minVintage: 1985,
    avgPrice: 18,
    producers: ['Castel De Paolis'],
    aliases: ['Castel De Paolis Frascati']
  },
  {
    id: 'frascati-fontana-candida-santa-teresa',
    name: 'Frascati Superiore Santa Teresa',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOCG',
    minVintage: 1958,
    avgPrice: 22,
    producers: ['Fontana Candida'],
    aliases: ['Santa Teresa']
  },
  {
    id: 'frascati-fontana-candida',
    name: 'Frascati Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOCG',
    minVintage: 1958,
    avgPrice: 14,
    producers: ['Fontana Candida'],
    aliases: ['Fontana Candida Frascati']
  },
  {
    id: 'frascati-gotto-d-oro',
    name: 'Frascati Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOCG',
    minVintage: 1958,
    avgPrice: 14,
    producers: ['Gotto d\'Oro'],
    aliases: ['Gotto d\'Oro Frascati']
  },
  {
    id: 'frascati-conte-zandotti',
    name: 'Frascati Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Conte Zandotti'],
    aliases: ['Conte Zandotti Frascati']
  },
  {
    id: 'frascati-san-marco',
    name: 'Frascati Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOCG',
    minVintage: 1998,
    avgPrice: 16,
    producers: ['San Marco'],
    aliases: ['San Marco Frascati']
  },
  {
    id: 'frascati-merumalia',
    name: 'Frascati Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Merumalia'],
    aliases: ['Merumalia Frascati']
  },
  
  // FRASCATI DOC (Regular)
  {
    id: 'frascati-doc-fontana-candida',
    name: 'Frascati',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOC',
    minVintage: 1958,
    avgPrice: 10,
    producers: ['Fontana Candida'],
    aliases: ['Fontana Candida DOC']
  },
  {
    id: 'frascati-doc-gotto-d-oro',
    name: 'Frascati',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOC',
    minVintage: 1958,
    avgPrice: 10,
    producers: ['Gotto d\'Oro'],
    aliases: ['Gotto d\'Oro DOC']
  },
  {
    id: 'frascati-doc-villa-simone',
    name: 'Frascati',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 11,
    producers: ['Villa Simone'],
    aliases: ['Villa Simone DOC']
  },
  
  // EST! EST!! EST!!! DI MONTEFIASCONE DOC (White)
  {
    id: 'est-est-est-falesco',
    name: 'Est! Est!! Est!!! di Montefiascone',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Montefiascone',
    grapeVariety: 'Trebbiano, Malvasia',
    classification: 'DOC',
    minVintage: 1979,
    avgPrice: 12,
    producers: ['Falesco'],
    aliases: ['Falesco Est Est Est']
  },
  {
    id: 'est-est-est-mazziotti',
    name: 'Est! Est!! Est!!! di Montefiascone',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Montefiascone',
    grapeVariety: 'Trebbiano, Malvasia, Rossetto',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 11,
    producers: ['Mazziotti'],
    aliases: ['Mazziotti Est Est Est']
  },
  {
    id: 'est-est-est-cantina-montefiascone',
    name: 'Est! Est!! Est!!! di Montefiascone',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Montefiascone',
    grapeVariety: 'Trebbiano, Malvasia',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 10,
    producers: ['Cantina di Montefiascone'],
    aliases: ['Montefiascone Est Est Est']
  },
  
  // CANNELLINO DI FRASCATI DOCG (Sweet)
  {
    id: 'cannellino-villa-simone',
    name: 'Cannellino di Frascati',
    type: 'Dessert',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Villa Simone'],
    aliases: ['Villa Simone Cannellino']
  },
  {
    id: 'cannellino-fontana-candida',
    name: 'Cannellino di Frascati',
    type: 'Dessert',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Fontana Candida'],
    aliases: ['Fontana Candida Cannellino']
  },
  
  // MARINO DOC (White - similar to Frascati)
  {
    id: 'marino-colle-picchioni-oro',
    name: 'Marino Superiore Oro',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Marino',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 18,
    producers: ['Colle Picchioni'],
    aliases: ['Oro']
  },
  {
    id: 'marino-colle-picchioni',
    name: 'Marino',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Marino',
    grapeVariety: 'Malvasia Puntinata, Trebbiano, Bellone',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 12,
    producers: ['Colle Picchioni'],
    aliases: ['Colle Picchioni Marino']
  },
  {
    id: 'marino-fontana-candida',
    name: 'Marino',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Marino',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 11,
    producers: ['Fontana Candida'],
    aliases: ['Fontana Candida Marino']
  },
  
  // MONTECOMPATRI COLONNA DOC (White)
  {
    id: 'montecompatri-villa-simone',
    name: 'Montecompatri Colonna',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Montecompatri',
    grapeVariety: 'Malvasia Puntinata, Trebbiano, Bellone',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 14,
    producers: ['Villa Simone'],
    aliases: ['Villa Simone Montecompatri']
  },
  
  // ZAGAROLO DOC (White)
  {
    id: 'zagarolo-villa-simone',
    name: 'Zagarolo',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Zagarolo',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 14,
    producers: ['Villa Simone'],
    aliases: ['Villa Simone Zagarolo']
  },
  
  // ORVIETO CLASSICO DOC (White - partially in Lazio)
  {
    id: 'orvieto-lazio-barberani',
    name: 'Orvieto Classico',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 14,
    producers: ['Barberani'],
    aliases: ['Barberani Orvieto Lazio']
  },
  
  // PREMIUM WHITE BLENDS (Lazio IGT)
  {
    id: 'lazio-castel-de-paolis-muffo-della-riserva',
    name: 'Muffo della Riserva Lazio IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Sémillon, Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 65,
    producers: ['Castel De Paolis'],
    aliases: ['Muffo della Riserva']
  },
  {
    id: 'lazio-falesco-ferentano',
    name: 'Ferentano Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Viterbo',
    grapeVariety: 'Grechetto, Roscetto',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Falesco'],
    aliases: ['Ferentano']
  },
  {
    id: 'lazio-villa-simone-vigna-dei-cavalieri',
    name: 'Vigna dei Cavalieri Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Villa Simone'],
    aliases: ['Vigna dei Cavalieri']
  },
  {
    id: 'lazio-castel-de-paolis-i-quattro-mori',
    name: 'I Quattro Mori Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Sauvignon Blanc, Sémillon, Viognier',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Castel De Paolis'],
    aliases: ['I Quattro Mori']
  },
  {
    id: 'lazio-fontana-candida-luna-mater',
    name: 'Luna Mater Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Greco',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Fontana Candida'],
    aliases: ['Luna Mater']
  },
  {
    id: 'lazio-poggio-le-volpi-baccarossa',
    name: 'Baccarossa Frascati Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 26,
    producers: ['Poggio Le Volpi'],
    aliases: ['Baccarossa']
  },
  {
    id: 'lazio-poggio-le-volpi-frascati',
    name: 'Frascati Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Frascati',
    grapeVariety: 'Malvasia Puntinata, Trebbiano',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Poggio Le Volpi'],
    aliases: ['Poggio Le Volpi Frascati']
  },
  {
    id: 'lazio-sergio-mottura-grechetto',
    name: 'Grechetto Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Viterbo',
    grapeVariety: 'Grechetto',
    classification: 'IGT',
    minVintage: 1998,
    avgPrice: 18,
    producers: ['Sergio Mottura'],
    aliases: ['Sergio Mottura Grechetto']
  },
  {
    id: 'lazio-sergio-mottura-latour-a-civitella',
    name: 'Latour a Civitella Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Viterbo',
    grapeVariety: 'Grechetto',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Sergio Mottura'],
    aliases: ['Latour a Civitella']
  },
  {
    id: 'lazio-casale-del-giglio-bellone',
    name: 'Bellone Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Bellone',
    classification: 'IGT',
    minVintage: 1967,
    avgPrice: 16,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Bellone']
  },
  {
    id: 'lazio-casale-del-giglio-petit-manseng',
    name: 'Petit Manseng Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Petit Manseng',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Casale del Giglio'],
    aliases: ['Casale del Giglio Petit Manseng']
  },
  {
    id: 'lazio-casale-del-giglio-faro-della-guardia',
    name: 'Faro della Guardia Lazio IGT',
    type: 'White',
    country: 'Italy',
    region: 'Lazio',
    subRegion: 'Agro Pontino',
    grapeVariety: 'Viognier',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Casale del Giglio'],
    aliases: ['Faro della Guardia']
  },
];
