import { WineTemplate } from '@/types/wineDatabase';

/**
 * CALABRIA WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Greco di Bianco DOC, Savuto DOC, Pollino DOC, Other regional wines
 * Updated: January 2025
 */

export const calabriaPart2: WineTemplate[] = [
  // GRECO DI BIANCO DOC (Sweet white - passito)
  {
    id: 'greco-di-bianco-umberto-ceratti',
    name: 'Greco di Bianco',
    type: 'Dessert',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Bianco',
    grapeVariety: 'Greco Bianco',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 45,
    producers: ['Umberto Ceratti'],
    aliases: ['Ceratti Greco di Bianco']
  },
  {
    id: 'greco-di-bianco-manuela-benvenuto',
    name: 'Greco di Bianco',
    type: 'Dessert',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Bianco',
    grapeVariety: 'Greco Bianco',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 48,
    producers: ['Manuela Benvenuto'],
    aliases: ['Benvenuto Greco di Bianco']
  },
  {
    id: 'greco-di-bianco-antonio-murace',
    name: 'Greco di Bianco',
    type: 'Dessert',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Bianco',
    grapeVariety: 'Greco Bianco',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 42,
    producers: ['Antonio Murace'],
    aliases: ['Murace Greco di Bianco']
  },
  
  // SAVUTO DOC (Red)
  {
    id: 'savuto-odoardi',
    name: 'Savuto Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Savuto',
    grapeVariety: 'Gaglioppo, Magliocco, Greco Nero',
    classification: 'DOC',
    minVintage: 1991,
    avgPrice: 18,
    producers: ['Odoardi'],
    aliases: ['Odoardi Savuto']
  },
  {
    id: 'savuto-ippolito',
    name: 'Savuto',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Savuto',
    grapeVariety: 'Gaglioppo, Magliocco',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 14,
    producers: ['Ippolito 1845'],
    aliases: ['Ippolito Savuto']
  },
  
  // POLLINO DOC (Red)
  {
    id: 'pollino-cantine-viola',
    name: 'Pollino Superiore',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Pollino',
    grapeVariety: 'Gaglioppo, Greco Nero',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Cantine Viola'],
    aliases: ['Viola Pollino']
  },
  {
    id: 'pollino-cantine-del-notaio-calabria',
    name: 'Pollino',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Pollino',
    grapeVariety: 'Gaglioppo',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Cantine del Notaio'],
    aliases: ['Notaio Pollino']
  },
  
  // MELISSA DOC (Red & White)
  {
    id: 'melissa-rosso-librandi',
    name: 'Melissa Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Melissa',
    grapeVariety: 'Gaglioppo, Greco Nero',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 14,
    producers: ['Librandi'],
    aliases: ['Librandi Melissa Rosso']
  },
  {
    id: 'melissa-bianco-librandi',
    name: 'Melissa Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Melissa',
    grapeVariety: 'Greco Bianco, Trebbiano',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 12,
    producers: ['Librandi'],
    aliases: ['Librandi Melissa Bianco']
  },
  
  // TERRE DI COSENZA DOC (Various)
  {
    id: 'terre-di-cosenza-rosso-odoardi',
    name: 'Terre di Cosenza Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cosenza',
    grapeVariety: 'Gaglioppo, Magliocco',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Odoardi'],
    aliases: ['Odoardi Terre di Cosenza']
  },
  {
    id: 'terre-di-cosenza-bianco-odoardi',
    name: 'Terre di Cosenza Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cosenza',
    grapeVariety: 'Greco Bianco, Malvasia',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 14,
    producers: ['Odoardi'],
    aliases: ['Odoardi Terre di Cosenza Bianco']
  },
  
  // PREMIUM WHITE WINES (Calabria IGT)
  {
    id: 'calabria-librandi-critone',
    name: 'Critone Val di Neto IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco, Mantonico',
    classification: 'IGT',
    minVintage: 1998,
    avgPrice: 22,
    producers: ['Librandi'],
    aliases: ['Critone']
  },
  {
    id: 'calabria-librandi-efeso',
    name: 'Efeso Val di Neto IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Mantonico',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Librandi'],
    aliases: ['Efeso']
  },
  {
    id: 'calabria-ippolito-aris',
    name: 'Aris Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Ippolito 1845'],
    aliases: ['Aris']
  },
  {
    id: 'calabria-odoardi-bianco-igt',
    name: 'Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Savuto',
    grapeVariety: 'Greco Bianco, Malvasia',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Odoardi'],
    aliases: ['Odoardi Bianco IGT']
  },
  {
    id: 'calabria-sergio-arcuri-bianco',
    name: 'Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 18,
    producers: ['Sergio Arcuri'],
    aliases: ['Sergio Arcuri Bianco IGT']
  },
  
  // MANTONICO (Indigenous white variety)
  {
    id: 'mantonico-librandi',
    name: 'Mantonico Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Mantonico',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Librandi'],
    aliases: ['Librandi Mantonico']
  },
  {
    id: 'mantonico-passito-librandi',
    name: 'Mantonico Passito Calabria IGT',
    type: 'Dessert',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Mantonico',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Librandi'],
    aliases: ['Librandi Mantonico Passito']
  },
  
  // MAGLIOCCO (Indigenous red variety)
  {
    id: 'magliocco-librandi',
    name: 'Magliocco Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Magliocco Canino',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Librandi'],
    aliases: ['Librandi Magliocco']
  },
  {
    id: 'magliocco-odoardi',
    name: 'Magliocco Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Savuto',
    grapeVariety: 'Magliocco',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Odoardi'],
    aliases: ['Odoardi Magliocco']
  },
  
  // INTERNATIONAL VARIETIES
  {
    id: 'cabernet-sauvignon-librandi',
    name: 'Cabernet Sauvignon Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 1995,
    avgPrice: 18,
    producers: ['Librandi'],
    aliases: ['Librandi Cabernet']
  },
  {
    id: 'merlot-ippolito',
    name: 'Merlot Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Merlot',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Ippolito 1845'],
    aliases: ['Ippolito Merlot']
  },
  {
    id: 'chardonnay-librandi',
    name: 'Chardonnay Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Librandi'],
    aliases: ['Librandi Chardonnay']
  },
  {
    id: 'sauvignon-blanc-odoardi',
    name: 'Sauvignon Blanc Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Savuto',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Odoardi'],
    aliases: ['Odoardi Sauvignon']
  },
  
  // ROSÉ WINES
  {
    id: 'rosato-calabria-librandi',
    name: 'Rosato Calabria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Librandi'],
    aliases: ['Librandi Rosato IGT']
  },
  {
    id: 'rosato-calabria-ippolito',
    name: 'Rosato Calabria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 12,
    producers: ['Ippolito 1845'],
    aliases: ['Ippolito Rosato IGT']
  },
  {
    id: 'rosato-calabria-odoardi',
    name: 'Rosato Calabria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Savuto',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 14,
    producers: ['Odoardi'],
    aliases: ['Odoardi Rosato IGT']
  },
  {
    id: 'rosato-calabria-caparra-siciliani',
    name: 'Rosato Calabria IGT',
    type: 'Rosé',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 12,
    producers: ['Caparra & Siciliani'],
    aliases: ['Caparra Rosato IGT']
  },
  
  // SPARKLING WINES
  {
    id: 'spumante-librandi',
    name: 'Spumante Brut Calabria IGT',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 24,
    producers: ['Librandi'],
    aliases: ['Librandi Spumante']
  },
  {
    id: 'spumante-ippolito',
    name: 'Spumante Brut Calabria IGT',
    type: 'Sparkling',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 22,
    producers: ['Ippolito 1845'],
    aliases: ['Ippolito Spumante']
  },
  
  // ADDITIONAL REGIONAL WINES
  {
    id: 'calabria-cataldo-calabretta-rosso',
    name: 'Rosso Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo, Greco Nero',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Cataldo Calabretta'],
    aliases: ['Calabretta Rosso']
  },
  {
    id: 'calabria-a-vita-bianco',
    name: 'Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco, Mantonico',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['A Vita'],
    aliases: ['A Vita Bianco IGT']
  },
  {
    id: 'calabria-santa-venere-rosso',
    name: 'Rosso Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Gaglioppo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Santa Venere'],
    aliases: ['Santa Venere Rosso IGT']
  },
  {
    id: 'calabria-santa-venere-bianco',
    name: 'Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Santa Venere'],
    aliases: ['Santa Venere Bianco IGT']
  },
  {
    id: 'calabria-tenuta-del-conte-bianco',
    name: 'Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Tenuta del Conte'],
    aliases: ['Tenuta del Conte Bianco']
  },
  {
    id: 'calabria-tramontana-bianco',
    name: 'Bianco Calabria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Cirò',
    grapeVariety: 'Greco Bianco',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 14,
    producers: ['Tramontana'],
    aliases: ['Tramontana Bianco']
  },
  {
    id: 'calabria-cantine-viola-rosso',
    name: 'Rosso Calabria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Calabria',
    subRegion: 'Pollino',
    grapeVariety: 'Gaglioppo, Greco Nero',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 20,
    producers: ['Cantine Viola'],
    aliases: ['Viola Rosso']
  },
];
