import { WineTemplate } from '@/types/wineDatabase';

/**
 * MOLISE WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Biferno DOC, Tintilia del Molise DOC
 * Updated: January 2025
 */

export const molisePart1: WineTemplate[] = [
  // TINTILIA DEL MOLISE DOC (Red - Indigenous variety)
  {
    id: 'tintilia-di-maio-norante-don-luigi',
    name: 'Tintilia del Molise Don Luigi Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'DOC',
    minVintage: 1968,
    avgPrice: 32,
    producers: ['Di Majo Norante'],
    aliases: ['Don Luigi']
  },
  {
    id: 'tintilia-di-maio-norante',
    name: 'Tintilia del Molise',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'DOC',
    minVintage: 1968,
    avgPrice: 18,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Tintilia']
  },
  {
    id: 'tintilia-claudio-cipressi',
    name: 'Tintilia del Molise',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Claudio Cipressi'],
    aliases: ['Cipressi Tintilia']
  },
  {
    id: 'tintilia-borgo-di-colloredo',
    name: 'Tintilia del Molise',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Tintilia']
  },
  {
    id: 'tintilia-catabbo',
    name: 'Tintilia del Molise',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 24,
    producers: ['Catabbo'],
    aliases: ['Catabbo Tintilia']
  },
  {
    id: 'tintilia-cianfagna',
    name: 'Tintilia del Molise',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 22,
    producers: ['Cianfagna'],
    aliases: ['Cianfagna Tintilia']
  },
  {
    id: 'tintilia-tenimenti-grieco',
    name: 'Tintilia del Molise',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 26,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Tintilia']
  },
  {
    id: 'tintilia-vinica',
    name: 'Tintilia del Molise',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 20,
    producers: ['Vinica'],
    aliases: ['Vinica Tintilia']
  },
  {
    id: 'tintilia-cantina-sociale-molise',
    name: 'Tintilia del Molise',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Cantina Sociale Molise'],
    aliases: ['Cantina Sociale Tintilia']
  },
  {
    id: 'tintilia-fattoria-del-duca',
    name: 'Tintilia del Molise',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'DOC',
    minVintage: 2012,
    avgPrice: 24,
    producers: ['Fattoria del Duca'],
    aliases: ['Fattoria del Duca Tintilia']
  },
  
  // BIFERNO DOC ROSSO (Red)
  {
    id: 'biferno-rosso-di-maio-norante-riserva',
    name: 'Biferno Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Aglianico',
    classification: 'DOC',
    minVintage: 1968,
    avgPrice: 24,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Biferno Riserva']
  },
  {
    id: 'biferno-rosso-di-maio-norante',
    name: 'Biferno Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Aglianico',
    classification: 'DOC',
    minVintage: 1968,
    avgPrice: 14,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Biferno']
  },
  {
    id: 'biferno-rosso-borgo-di-colloredo',
    name: 'Biferno Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Aglianico',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Biferno']
  },
  {
    id: 'biferno-rosso-catabbo',
    name: 'Biferno Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Aglianico',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Catabbo'],
    aliases: ['Catabbo Biferno']
  },
  {
    id: 'biferno-rosso-cianfagna',
    name: 'Biferno Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Aglianico',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Cianfagna'],
    aliases: ['Cianfagna Biferno']
  },
  {
    id: 'biferno-rosso-tenimenti-grieco',
    name: 'Biferno Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Aglianico',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Biferno']
  },
  {
    id: 'biferno-rosso-cantina-sociale',
    name: 'Biferno Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Aglianico',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 12,
    producers: ['Cantina Sociale Molise'],
    aliases: ['Cantina Sociale Biferno']
  },
  
  // BIFERNO DOC BIANCO (White)
  {
    id: 'biferno-bianco-di-maio-norante',
    name: 'Biferno Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Trebbiano, Bombino Bianco',
    classification: 'DOC',
    minVintage: 1968,
    avgPrice: 12,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Biferno Bianco']
  },
  {
    id: 'biferno-bianco-borgo-di-colloredo',
    name: 'Biferno Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Trebbiano, Bombino Bianco',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 12,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Biferno Bianco']
  },
  {
    id: 'biferno-bianco-catabbo',
    name: 'Biferno Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Trebbiano, Bombino Bianco',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 13,
    producers: ['Catabbo'],
    aliases: ['Catabbo Biferno Bianco']
  },
  {
    id: 'biferno-bianco-tenimenti-grieco',
    name: 'Biferno Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Trebbiano, Bombino Bianco',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 13,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Biferno Bianco']
  },
  
  // BIFERNO DOC ROSATO (Rosé)
  {
    id: 'biferno-rosato-di-maio-norante',
    name: 'Biferno Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Aglianico',
    classification: 'DOC',
    minVintage: 1968,
    avgPrice: 12,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Rosato']
  },
  {
    id: 'biferno-rosato-borgo-di-colloredo',
    name: 'Biferno Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Aglianico',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 12,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo di Colloredo Rosato']
  },
  {
    id: 'biferno-rosato-catabbo',
    name: 'Biferno Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 13,
    producers: ['Catabbo'],
    aliases: ['Catabbo Rosato']
  },
  {
    id: 'biferno-rosato-tenimenti-grieco',
    name: 'Biferno Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 13,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Rosato']
  },
  
  // PENTRO DI ISERNIA DOC (Red, White, Rosé)
  {
    id: 'pentro-isernia-rosso-di-maio-norante',
    name: 'Pentro di Isernia Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Isernia',
    grapeVariety: 'Montepulciano, Sangiovese',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 14,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Pentro Rosso']
  },
  {
    id: 'pentro-isernia-bianco-di-maio-norante',
    name: 'Pentro di Isernia Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Isernia',
    grapeVariety: 'Trebbiano, Bombino Bianco',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 12,
    producers: ['Di Majo Norante'],
    aliases: ['Di Majo Norante Pentro Bianco']
  },
  
  // PREMIUM WINES (Molise IGT)
  {
    id: 'molise-di-maio-norante-don-luigi-igt',
    name: 'Don Luigi Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Tintilia',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Di Majo Norante'],
    aliases: ['Don Luigi IGT']
  },
  {
    id: 'molise-di-maio-norante-moli',
    name: 'Moli Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Di Majo Norante'],
    aliases: ['Moli']
  },
  {
    id: 'molise-di-maio-norante-ramitello',
    name: 'Ramitello Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Montepulciano, Aglianico',
    classification: 'IGT',
    minVintage: 1998,
    avgPrice: 26,
    producers: ['Di Majo Norante'],
    aliases: ['Ramitello']
  },
  {
    id: 'molise-borgo-di-colloredo-premium',
    name: 'Premium Selection Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Montepulciano',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 28,
    producers: ['Borgo di Colloredo'],
    aliases: ['Borgo Premium']
  },
  {
    id: 'molise-claudio-cipressi-rosso',
    name: 'Rosso Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Aglianico',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Claudio Cipressi'],
    aliases: ['Cipressi Rosso']
  },
  {
    id: 'molise-catabbo-rosso-igt',
    name: 'Rosso Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Montepulciano',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 24,
    producers: ['Catabbo'],
    aliases: ['Catabbo Rosso IGT']
  },
  {
    id: 'molise-cianfagna-rosso-igt',
    name: 'Rosso Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 26,
    producers: ['Cianfagna'],
    aliases: ['Cianfagna Rosso IGT']
  },
  {
    id: 'molise-tenimenti-grieco-rosso-igt',
    name: 'Rosso Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Aglianico',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 28,
    producers: ['Tenimenti Grieco'],
    aliases: ['Tenimenti Grieco Rosso IGT']
  },
  {
    id: 'molise-vinica-rosso-igt',
    name: 'Rosso Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia',
    classification: 'IGT',
    minVintage: 2012,
    avgPrice: 24,
    producers: ['Vinica'],
    aliases: ['Vinica Rosso IGT']
  },
  {
    id: 'molise-fattoria-del-duca-rosso-igt',
    name: 'Rosso Molise IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Molise',
    subRegion: 'Campomarino',
    grapeVariety: 'Tintilia, Montepulciano',
    classification: 'IGT',
    minVintage: 2014,
    avgPrice: 26,
    producers: ['Fattoria del Duca'],
    aliases: ['Fattoria del Duca Rosso IGT']
  },
];
