import { WineTemplate } from '@/types/wineDatabase';

/**
 * ABRUZZO WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Montepulciano d'Abruzzo DOC & DOCG
 * Updated: January 2025
 */

export const abruzzoPart1: WineTemplate[] = [
  // MONTEPULCIANO D'ABRUZZO COLLINE TERAMANE DOCG
  {
    id: 'montepulciano-valentini',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Loreto Aprutino',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1650,
    avgPrice: 85,
    producers: ['Valentini', 'Edoardo Valentini'],
    aliases: ['Valentini Montepulciano']
  },
  {
    id: 'montepulciano-emidio-pepe',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Torano Nuovo',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1964,
    avgPrice: 75,
    producers: ['Emidio Pepe'],
    aliases: ['Emidio Pepe']
  },
  {
    id: 'montepulciano-tiberio-fonte-canale',
    name: 'Montepulciano d\'Abruzzo Colline Teramane Fonte Canale',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Cugnoli',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['Tiberio'],
    aliases: ['Fonte Canale']
  },
  {
    id: 'montepulciano-tiberio',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Cugnoli',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Tiberio'],
    aliases: ['Tiberio Montepulciano']
  },
  {
    id: 'montepulciano-masciarelli-villa-gemma',
    name: 'Montepulciano d\'Abruzzo Villa Gemma',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'San Martino sulla Marrucina',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1981,
    avgPrice: 48,
    producers: ['Masciarelli'],
    aliases: ['Villa Gemma']
  },
  {
    id: 'montepulciano-masciarelli-marina-cvetic',
    name: 'Montepulciano d\'Abruzzo Marina Cvetic',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'San Martino sulla Marrucina',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1991,
    avgPrice: 38,
    producers: ['Masciarelli'],
    aliases: ['Marina Cvetic']
  },
  {
    id: 'montepulciano-masciarelli',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'San Martino sulla Marrucina',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1981,
    avgPrice: 16,
    producers: ['Masciarelli'],
    aliases: ['Masciarelli Montepulciano']
  },
  {
    id: 'montepulciano-illuminati-zanna',
    name: 'Montepulciano d\'Abruzzo Zanna',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Controguerra',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1890,
    avgPrice: 28,
    producers: ['Illuminati'],
    aliases: ['Zanna']
  },
  {
    id: 'montepulciano-illuminati-riparosso',
    name: 'Montepulciano d\'Abruzzo Riparosso',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Controguerra',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1890,
    avgPrice: 18,
    producers: ['Illuminati'],
    aliases: ['Riparosso']
  },
  {
    id: 'montepulciano-torre-zambra-terra-dazzano',
    name: 'Montepulciano d\'Abruzzo Colline Teramane Terra d\'Aligi',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Teramo',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2001,
    avgPrice: 38,
    producers: ['Torre Zambra'],
    aliases: ['Terra d\'Aligi']
  },
  {
    id: 'montepulciano-nicodemi-notari',
    name: 'Montepulciano d\'Abruzzo Colline Teramane Notari',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Notaresco',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 1960,
    avgPrice: 32,
    producers: ['Nicodemi'],
    aliases: ['Notari']
  },
  {
    id: 'montepulciano-nicodemi',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Notaresco',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 16,
    producers: ['Nicodemi'],
    aliases: ['Nicodemi Montepulciano']
  },
  {
    id: 'montepulciano-valle-reale-vigna-del-convento',
    name: 'Montepulciano d\'Abruzzo Vigna del Convento',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Popoli',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 35,
    producers: ['Valle Reale'],
    aliases: ['Vigna del Convento']
  },
  {
    id: 'montepulciano-valle-reale-san-calisto',
    name: 'Montepulciano d\'Abruzzo San Calisto',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Popoli',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Valle Reale'],
    aliases: ['San Calisto']
  },
  {
    id: 'montepulciano-valle-reale',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Popoli',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Valle Reale'],
    aliases: ['Valle Reale Montepulciano']
  },
  {
    id: 'montepulciano-cataldi-madonna-malandrino',
    name: 'Montepulciano d\'Abruzzo Malandrino',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ofena',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1920,
    avgPrice: 32,
    producers: ['Cataldi Madonna'],
    aliases: ['Malandrino']
  },
  {
    id: 'montepulciano-cataldi-madonna-toni',
    name: 'Montepulciano d\'Abruzzo Toni',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ofena',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 38,
    producers: ['Cataldi Madonna'],
    aliases: ['Toni']
  },
  {
    id: 'montepulciano-cataldi-madonna',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ofena',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1920,
    avgPrice: 18,
    producers: ['Cataldi Madonna'],
    aliases: ['Cataldi Madonna Montepulciano']
  },
  {
    id: 'montepulciano-de-fermo-vigna-san-giacomo',
    name: 'Montepulciano d\'Abruzzo Colline Teramane Vigna San Giacomo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Teramo',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2006,
    avgPrice: 35,
    producers: ['De Fermo'],
    aliases: ['Vigna San Giacomo']
  },
  {
    id: 'montepulciano-cornacchia-poggio-varano',
    name: 'Montepulciano d\'Abruzzo Colline Teramane Poggio Varano',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Torano Nuovo',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 1970,
    avgPrice: 32,
    producers: ['Cornacchia'],
    aliases: ['Poggio Varano']
  },
  {
    id: 'montepulciano-cornacchia',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Torano Nuovo',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 16,
    producers: ['Cornacchia'],
    aliases: ['Cornacchia Montepulciano']
  },
  {
    id: 'montepulciano-praesidium',
    name: 'Montepulciano d\'Abruzzo Colline Teramane',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Teramo',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Praesidium'],
    aliases: ['Praesidium']
  },
  {
    id: 'montepulciano-orlandi-contucci-ponno',
    name: 'Montepulciano d\'Abruzzo Marina Cvetic',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Roseto degli Abruzzi',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1964,
    avgPrice: 24,
    producers: ['Orlandi Contucci Ponno'],
    aliases: ['Orlandi Contucci Ponno']
  },
  {
    id: 'montepulciano-dora-sarchese-montepagano',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Roseto degli Abruzzi',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1973,
    avgPrice: 20,
    producers: ['Dora Sarchese'],
    aliases: ['Dora Sarchese']
  },
  {
    id: 'montepulciano-filomusi-guelfi',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 18,
    producers: ['Filomusi Guelfi'],
    aliases: ['Filomusi Guelfi']
  },
  {
    id: 'montepulciano-agriverde-orsetto-oro',
    name: 'Montepulciano d\'Abruzzo Orsetto Oro',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Teramo',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 22,
    producers: ['Agriverde'],
    aliases: ['Orsetto Oro']
  },
  {
    id: 'montepulciano-jasci',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Alanno',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 16,
    producers: ['Jasci'],
    aliases: ['Jasci Montepulciano']
  },
  {
    id: 'montepulciano-cantina-tollo-cagiolo',
    name: 'Montepulciano d\'Abruzzo Cagiolo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Tollo',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 18,
    producers: ['Cantina Tollo'],
    aliases: ['Cagiolo']
  },
  {
    id: 'montepulciano-cantina-tollo',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Tollo',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 12,
    producers: ['Cantina Tollo'],
    aliases: ['Tollo Montepulciano']
  },
  {
    id: 'montepulciano-farnese-casale-vecchio',
    name: 'Montepulciano d\'Abruzzo Casale Vecchio',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ortona',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1994,
    avgPrice: 22,
    producers: ['Farnese'],
    aliases: ['Casale Vecchio']
  },
  {
    id: 'montepulciano-farnese',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ortona',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1994,
    avgPrice: 11,
    producers: ['Farnese'],
    aliases: ['Farnese Montepulciano']
  },
  {
    id: 'montepulciano-zaccagnini-san-clemente',
    name: 'Montepulciano d\'Abruzzo San Clemente',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Bolognano',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 28,
    producers: ['Zaccagnini'],
    aliases: ['San Clemente']
  },
  {
    id: 'montepulciano-zaccagnini',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Bolognano',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 14,
    producers: ['Zaccagnini'],
    aliases: ['Zaccagnini Montepulciano']
  },
  {
    id: 'montepulciano-casal-thaulero',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Roseto degli Abruzzi',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 12,
    producers: ['Casal Thaulero'],
    aliases: ['Casal Thaulero']
  },
  {
    id: 'montepulciano-umani-ronchi-jorio',
    name: 'Montepulciano d\'Abruzzo Jorio',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Roseto degli Abruzzi',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 24,
    producers: ['Umani Ronchi'],
    aliases: ['Jorio']
  },
  {
    id: 'montepulciano-umani-ronchi',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Roseto degli Abruzzi',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1957,
    avgPrice: 14,
    producers: ['Umani Ronchi'],
    aliases: ['Umani Ronchi Montepulciano']
  },
  {
    id: 'montepulciano-monti',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Controguerra',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1988,
    avgPrice: 15,
    producers: ['Monti'],
    aliases: ['Monti Montepulciano']
  },
  {
    id: 'montepulciano-lepore',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Alanno',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 16,
    producers: ['Lepore'],
    aliases: ['Lepore Montepulciano']
  },
  {
    id: 'montepulciano-spinelli',
    name: 'Montepulciano d\'Abruzzo Colline Teramane',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Atri',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2002,
    avgPrice: 28,
    producers: ['Spinelli'],
    aliases: ['Spinelli']
  },
  {
    id: 'montepulciano-monti-vigna-corvino',
    name: 'Montepulciano d\'Abruzzo Vigna Corvino',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Controguerra',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Monti'],
    aliases: ['Vigna Corvino']
  },
  {
    id: 'montepulciano-marramiero-inferi',
    name: 'Montepulciano d\'Abruzzo Inferi',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Rosciano',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 32,
    producers: ['Marramiero'],
    aliases: ['Inferi']
  },
  {
    id: 'montepulciano-marramiero',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Rosciano',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Marramiero'],
    aliases: ['Marramiero Montepulciano']
  },
  {
    id: 'montepulciano-barone-cornacchia-vigna-le-coste',
    name: 'Montepulciano d\'Abruzzo Colline Teramane Vigna Le Coste',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Torano Nuovo',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 35,
    producers: ['Barone Cornacchia'],
    aliases: ['Vigna Le Coste']
  },
  {
    id: 'montepulciano-pasetti-testarossa',
    name: 'Montepulciano d\'Abruzzo Testarossa',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Francavilla al Mare',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 24,
    producers: ['Pasetti'],
    aliases: ['Testarossa']
  },
  {
    id: 'montepulciano-pasetti',
    name: 'Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Francavilla al Mare',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 14,
    producers: ['Pasetti'],
    aliases: ['Pasetti Montepulciano']
  },
];
