import { WineTemplate } from '@/types/wineDatabase';

/**
 * PUGLIA WINES - Part 3 of 3 (Wines 101-150)
 * Focus: White wines (Verdeca, Fiano, Bombino Bianco), Castel del Monte, Blends
 * Updated: January 2025
 */

export const pugliaPart3: WineTemplate[] = [
  // CASTEL DEL MONTE DOCG & DOC (Red - Nero di Troia/Uva di Troia)
  {
    id: 'castel-del-monte-rivera-il-falcone',
    name: 'Castel del Monte Rosso Riserva Il Falcone',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Nero di Troia',
    classification: 'DOCG',
    minVintage: 1998,
    avgPrice: 32,
    producers: ['Rivera'],
    aliases: ['Il Falcone']
  },
  {
    id: 'castel-del-monte-rivera',
    name: 'Castel del Monte Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Nero di Troia, Montepulciano',
    classification: 'DOC',
    minVintage: 1949,
    avgPrice: 14,
    producers: ['Rivera'],
    aliases: ['Rivera Castel del Monte']
  },
  {
    id: 'castel-del-monte-torrevento-vigna-pedale',
    name: 'Castel del Monte Rosso Riserva Vigna Pedale',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Nero di Troia',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Torrevento'],
    aliases: ['Vigna Pedale']
  },
  {
    id: 'castel-del-monte-torrevento',
    name: 'Castel del Monte Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Nero di Troia, Aglianico',
    classification: 'DOC',
    minVintage: 1987,
    avgPrice: 12,
    producers: ['Torrevento'],
    aliases: ['Torrevento Castel']
  },
  {
    id: 'castel-del-monte-santa-lucia-bocca-di-lupo',
    name: 'Castel del Monte Rosso Riserva Bocca di Lupo',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Nero di Troia',
    classification: 'DOCG',
    minVintage: 2001,
    avgPrice: 26,
    producers: ['Santa Lucia'],
    aliases: ['Bocca di Lupo']
  },
  {
    id: 'castel-del-monte-rivera-cappellaccio',
    name: 'Castel del Monte Rosso Cappellaccio',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Nero di Troia, Montepulciano',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Rivera'],
    aliases: ['Cappellaccio']
  },
  {
    id: 'castel-del-monte-d-araprì',
    name: 'Castel del Monte Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Nero di Troia',
    classification: 'DOCG',
    minVintage: 1998,
    avgPrice: 24,
    producers: ['D\'Araprì'],
    aliases: ['D\'Araprì']
  },
  
  // CASTEL DEL MONTE ROSÉ & WHITE
  {
    id: 'castel-del-monte-rosato-rivera-rosato',
    name: 'Castel del Monte Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Bombino Nero',
    classification: 'DOC',
    minVintage: 1949,
    avgPrice: 12,
    producers: ['Rivera'],
    aliases: ['Rivera Rosato']
  },
  {
    id: 'castel-del-monte-bianco-rivera',
    name: 'Castel del Monte Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Pampanuto, Chardonnay',
    classification: 'DOC',
    minVintage: 1949,
    avgPrice: 11,
    producers: ['Rivera'],
    aliases: ['Rivera Bianco']
  },
  {
    id: 'castel-del-monte-bianco-torrevento',
    name: 'Castel del Monte Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Pampanuto, Chardonnay, Bombino Bianco',
    classification: 'DOC',
    minVintage: 1987,
    avgPrice: 10,
    producers: ['Torrevento'],
    aliases: ['Torrevento Bianco']
  },
  
  // LOCOROTONDO DOC (White)
  {
    id: 'locorotondo-cantele',
    name: 'Locorotondo',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Locorotondo',
    grapeVariety: 'Verdeca, Bianco d\'Alessano',
    classification: 'DOC',
    minVintage: 1979,
    avgPrice: 11,
    producers: ['Cantele'],
    aliases: ['Cantele Locorotondo']
  },
  {
    id: 'locorotondo-masseria-li-veli',
    name: 'Locorotondo',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Locorotondo',
    grapeVariety: 'Verdeca, Bianco d\'Alessano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 12,
    producers: ['Masseria Li Veli'],
    aliases: ['Li Veli Locorotondo']
  },
  {
    id: 'locorotondo-polvanera',
    name: 'Locorotondo',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Locorotondo',
    grapeVariety: 'Verdeca, Bianco d\'Alessano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 13,
    producers: ['Polvanera'],
    aliases: ['Polvanera Locorotondo']
  },
  {
    id: 'locorotondo-schola-sarmenti',
    name: 'Locorotondo',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Locorotondo',
    grapeVariety: 'Verdeca, Bianco d\'Alessano, Fiano',
    classification: 'DOC',
    minVintage: 2003,
    avgPrice: 11,
    producers: ['Schola Sarmenti'],
    aliases: ['Schola Locorotondo']
  },
  
  // FIANO (Puglia IGT)
  {
    id: 'fiano-tormaresca-pietrabianca',
    name: 'Pietrabianca Puglia Fiano',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Fiano',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Tormaresca', 'Antinori'],
    aliases: ['Pietrabianca']
  },
  {
    id: 'fiano-cantele',
    name: 'Fiano Salento',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Fiano',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Cantele'],
    aliases: ['Cantele Fiano']
  },
  {
    id: 'fiano-masseria-li-veli',
    name: 'Fiano Salento',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Fiano',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Masseria Li Veli'],
    aliases: ['Li Veli Fiano']
  },
  
  // VERDECA & OTHER WHITE VARIETIES
  {
    id: 'verdeca-cantele',
    name: 'Verdeca Salento',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Verdeca',
    classification: 'IGT',
    minVintage: 1979,
    avgPrice: 12,
    producers: ['Cantele'],
    aliases: ['Cantele Verdeca']
  },
  {
    id: 'bombino-bianco-torrevento-torre-rosso',
    name: 'Bombino Bianco Puglia',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Murge',
    grapeVariety: 'Bombino Bianco',
    classification: 'IGT',
    minVintage: 1987,
    avgPrice: 10,
    producers: ['Torrevento'],
    aliases: ['Torrevento Bombino']
  },
  {
    id: 'chardonnay-rivera-castel-del-monte',
    name: 'Castel del Monte Chardonnay',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 14,
    producers: ['Rivera'],
    aliases: ['Rivera Chardonnay']
  },
  {
    id: 'greco-conti-zecca',
    name: 'Greco Salento',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Greco',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 13,
    producers: ['Conti Zecca'],
    aliases: ['Conti Zecca Greco']
  },
  
  // BLENDS & PREMIUM WINES
  {
    id: 'puglia-leone-de-castris-salice-salentino-rosso-riserva',
    name: 'Salice Salentino Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 1925,
    avgPrice: 16,
    producers: ['Leone de Castris'],
    aliases: ['Leone Riserva']
  },
  {
    id: 'puglia-agricole-vallone-graticciaia',
    name: 'Graticciaia Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'IGT',
    minVintage: 1985,
    avgPrice: 48,
    producers: ['Agricole Vallone'],
    aliases: ['Graticciaia']
  },
  {
    id: 'puglia-tormaresca-bocca-di-lupo',
    name: 'Bocca di Lupo Castel del Monte Aglianico',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Tormaresca'],
    aliases: ['Bocca di Lupo Aglianico']
  },
  {
    id: 'puglia-conti-zecca-donna-marzia',
    name: 'Donna Marzia Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Cabernet Sauvignon, Malvasia Nera',
    classification: 'IGT',
    minVintage: 1991,
    avgPrice: 35,
    producers: ['Conti Zecca'],
    aliases: ['Donna Marzia']
  },
  {
    id: 'puglia-apollonio-copertino-riserva',
    name: 'Copertino Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Copertino',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 18,
    producers: ['Apollonio'],
    aliases: ['Apollonio Copertino Riserva']
  },
  {
    id: 'puglia-masseria-li-veli-orion',
    name: 'Orion Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo, Negroamaro, Malvasia Nera',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Masseria Li Veli'],
    aliases: ['Orion']
  },
  {
    id: 'puglia-san-marzano-f',
    name: 'F Negroamaro Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 22,
    producers: ['San Marzano'],
    aliases: ['F Negroamaro']
  },
  {
    id: 'puglia-san-marzano-tramari',
    name: 'Tramari Primitivo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['San Marzano'],
    aliases: ['Tramari']
  },
  {
    id: 'puglia-polvanera-aglianico',
    name: 'Aglianico Puglia',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Gioia del Colle',
    grapeVariety: 'Aglianico',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Polvanera'],
    aliases: ['Polvanera Aglianico']
  },
  {
    id: 'puglia-rivera-triusco',
    name: 'Triusco Castel del Monte',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Nero di Troia, Montepulciano, Aglianico',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Rivera'],
    aliases: ['Triusco']
  },
  {
    id: 'puglia-torrevento-castel-del-monte-nero-di-troia',
    name: 'Castel del Monte Nero di Troia Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Nero di Troia',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Torrevento'],
    aliases: ['Torrevento Nero di Troia']
  },
  {
    id: 'puglia-cantele-rohesia',
    name: 'Rohesia Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Primitivo',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 32,
    producers: ['Cantele'],
    aliases: ['Rohesia']
  },
  {
    id: 'puglia-alberto-longo-etichetta-bianca',
    name: 'Etichetta Bianca Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Primitivo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Alberto Longo'],
    aliases: ['Etichetta Bianca']
  },
  {
    id: 'puglia-tenute-rubino-jaddico',
    name: 'Jaddico Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Brindisi',
    grapeVariety: 'Primitivo, Negroamaro, Susumaniello',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 26,
    producers: ['Tenute Rubino'],
    aliases: ['Jaddico']
  },
  {
    id: 'puglia-masseria-altemura-sasseo',
    name: 'Sasseo Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Primitivo, Negroamaro',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Masseria Altemura'],
    aliases: ['Sasseo']
  },
  {
    id: 'puglia-coppi-aglianico',
    name: 'Aglianico Gioia del Colle',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Gioia del Colle',
    grapeVariety: 'Aglianico',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 24,
    producers: ['Coppi'],
    aliases: ['Coppi Aglianico']
  },
  {
    id: 'puglia-tormaresca-chardonnay',
    name: 'Chardonnay Puglia',
    type: 'White',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Tormaresca'],
    aliases: ['Tormaresca Chardonnay']
  },
  {
    id: 'puglia-schola-sarmenti-malvasia-nera',
    name: 'Malvasia Nera Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Malvasia Nera',
    classification: 'IGT',
    minVintage: 2003,
    avgPrice: 18,
    producers: ['Schola Sarmenti'],
    aliases: ['Schola Malvasia']
  },
  {
    id: 'puglia-rivera-puer-apuliae',
    name: 'Puer Apuliae Castel del Monte',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Nero di Troia',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 22,
    producers: ['Rivera'],
    aliases: ['Puer Apuliae']
  },
];
