import { WineTemplate } from '@/types/wineDatabase';

/**
 * PUGLIA WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Negroamaro, Salice Salentino DOC
 * Updated: January 2025
 */

export const pugliaPart2: WineTemplate[] = [
  // NEGROAMARO (Salento IGT & Various DOCs)
  {
    id: 'negroamaro-taurino-patriglione',
    name: 'Patriglione Salento Negroamaro',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 1974,
    avgPrice: 42,
    producers: ['Taurino'],
    aliases: ['Patriglione']
  },
  {
    id: 'negroamaro-taurino-notarpanaro',
    name: 'Notarpanaro Salento Negroamaro',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 1972,
    avgPrice: 24,
    producers: ['Taurino'],
    aliases: ['Notarpanaro']
  },
  {
    id: 'negroamaro-leone-de-castris-maiana',
    name: 'Maiana Salento Negroamaro',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 2002,
    avgPrice: 26,
    producers: ['Leone de Castris'],
    aliases: ['Maiana']
  },
  {
    id: 'negroamaro-leone-de-castris',
    name: 'Negroamaro Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 1925,
    avgPrice: 12,
    producers: ['Leone de Castris'],
    aliases: ['Leone de Castris Negroamaro']
  },
  {
    id: 'negroamaro-apollonio-divoto',
    name: 'Divoto Salento Negroamaro',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Apollonio'],
    aliases: ['Divoto']
  },
  {
    id: 'negroamaro-apollonio-mozzafiato',
    name: 'Mozzafiato Salento Negroamaro',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Apollonio'],
    aliases: ['Mozzafiato']
  },
  {
    id: 'negroamaro-tormaresca-neprica',
    name: 'Neprica Salento Negroamaro',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Tormaresca', 'Antinori'],
    aliases: ['Neprica']
  },
  {
    id: 'negroamaro-masseria-li-veli-pezzo-morgana',
    name: 'Pezzo Morgana Salento Negroamaro',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Masseria Li Veli'],
    aliases: ['Pezzo Morgana']
  },
  {
    id: 'negroamaro-feudi-di-guagnano',
    name: 'Negroamaro Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 2002,
    avgPrice: 11,
    producers: ['Feudi di Guagnano'],
    aliases: ['Feudi Negroamaro']
  },
  {
    id: 'negroamaro-cantele-amativo',
    name: 'Amativo Salento Negroamaro',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Cantele'],
    aliases: ['Amativo']
  },
  {
    id: 'negroamaro-cantele',
    name: 'Negroamaro Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 1979,
    avgPrice: 13,
    producers: ['Cantele'],
    aliases: ['Cantele Negroamaro']
  },
  {
    id: 'negroamaro-conti-zecca-nero',
    name: 'Nero Salento Negroamaro',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 1935,
    avgPrice: 18,
    producers: ['Conti Zecca'],
    aliases: ['Nero']
  },
  {
    id: 'negroamaro-alberto-longo',
    name: 'Negroamaro Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 14,
    producers: ['Alberto Longo'],
    aliases: ['Alberto Longo Negroamaro']
  },
  {
    id: 'negroamaro-varvaglione',
    name: 'Negroamaro Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 1921,
    avgPrice: 11,
    producers: ['Varvaglione'],
    aliases: ['Varvaglione Negroamaro']
  },
  {
    id: 'negroamaro-schola-sarmenti',
    name: 'Negroamaro Salento',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 2003,
    avgPrice: 12,
    producers: ['Schola Sarmenti'],
    aliases: ['Schola Negroamaro']
  },
  
  // SALICE SALENTINO DOC
  {
    id: 'salice-salentino-taurino',
    name: 'Salice Salentino Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 1972,
    avgPrice: 18,
    producers: ['Taurino'],
    aliases: ['Taurino Salice']
  },
  {
    id: 'salice-salentino-leone-de-castris',
    name: 'Salice Salentino Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 1925,
    avgPrice: 16,
    producers: ['Leone de Castris'],
    aliases: ['Leone Salice']
  },
  {
    id: 'salice-salentino-candido',
    name: 'Salice Salentino Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 1928,
    avgPrice: 14,
    producers: ['Candido'],
    aliases: ['Candido Salice']
  },
  {
    id: 'salice-salentino-candido-cappello-prete',
    name: 'Cappello di Prete Salice Salentino Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'DOC',
    minVintage: 1950,
    avgPrice: 24,
    producers: ['Candido'],
    aliases: ['Cappello di Prete']
  },
  {
    id: 'salice-salentino-apollonio',
    name: 'Salice Salentino Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 1870,
    avgPrice: 12,
    producers: ['Apollonio'],
    aliases: ['Apollonio Salice']
  },
  {
    id: 'salice-salentino-conti-zecca',
    name: 'Salice Salentino Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 1935,
    avgPrice: 16,
    producers: ['Conti Zecca'],
    aliases: ['Conti Zecca Salice']
  },
  {
    id: 'salice-salentino-due-palme',
    name: 'Salice Salentino Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 1989,
    avgPrice: 14,
    producers: ['Cantine Due Palme'],
    aliases: ['Due Palme Salice']
  },
  {
    id: 'salice-salentino-alberto-longo',
    name: 'Salice Salentino Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 13,
    producers: ['Alberto Longo'],
    aliases: ['Alberto Longo Salice']
  },
  {
    id: 'salice-salentino-cantele',
    name: 'Salice Salentino Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 1979,
    avgPrice: 15,
    producers: ['Cantele'],
    aliases: ['Cantele Salice']
  },
  
  // COPERTINO DOC
  {
    id: 'copertino-cupertinum-monaci',
    name: 'Copertino Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Copertino',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 16,
    producers: ['Cupertinum Monaci'],
    aliases: ['Cupertinum']
  },
  {
    id: 'copertino-feudi-di-guagnano',
    name: 'Copertino Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Copertino',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 2002,
    avgPrice: 13,
    producers: ['Feudi di Guagnano'],
    aliases: ['Feudi Copertino']
  },
  
  // SQUINZANO DOC
  {
    id: 'squinzano-agricole-vallone',
    name: 'Squinzano Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Squinzano',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 1934,
    avgPrice: 18,
    producers: ['Agricole Vallone'],
    aliases: ['Vallone Squinzano']
  },
  {
    id: 'squinzano-conti-zecca',
    name: 'Squinzano Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Squinzano',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'DOC',
    minVintage: 1935,
    avgPrice: 14,
    producers: ['Conti Zecca'],
    aliases: ['Conti Zecca Squinzano']
  },
  
  // BRINDISI DOC
  {
    id: 'brindisi-leone-de-castris',
    name: 'Brindisi Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Brindisi',
    grapeVariety: 'Negroamaro, Montepulciano',
    classification: 'DOC',
    minVintage: 1925,
    avgPrice: 16,
    producers: ['Leone de Castris'],
    aliases: ['Leone Brindisi']
  },
  {
    id: 'brindisi-agricole-vallone-vigna-flaminio',
    name: 'Brindisi Rosso Vigna Flaminio',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Brindisi',
    grapeVariety: 'Negroamaro',
    classification: 'DOC',
    minVintage: 1999,
    avgPrice: 28,
    producers: ['Agricole Vallone'],
    aliases: ['Vigna Flaminio']
  },
  {
    id: 'brindisi-tenute-rubino',
    name: 'Brindisi Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Brindisi',
    grapeVariety: 'Negroamaro, Montepulciano, Malvasia Nera',
    classification: 'DOC',
    minVintage: 1999,
    avgPrice: 18,
    producers: ['Tenute Rubino'],
    aliases: ['Rubino Brindisi']
  },
  {
    id: 'brindisi-tenute-rubino-torre-testa',
    name: 'Torre Testa Brindisi Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Brindisi',
    grapeVariety: 'Negroamaro, Susumaniello',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Tenute Rubino'],
    aliases: ['Torre Testa']
  },
  
  // SUSUMANIELLO (Rare variety)
  {
    id: 'susumaniello-tenute-rubino',
    name: 'Susumaniello Salento IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Susumaniello',
    classification: 'IGT',
    minVintage: 1999,
    avgPrice: 24,
    producers: ['Tenute Rubino'],
    aliases: ['Rubino Susumaniello']
  },
  {
    id: 'susumaniello-masseria-li-veli',
    name: 'Susumaniello Salento IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Susumaniello',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Masseria Li Veli'],
    aliases: ['Li Veli Susumaniello']
  },
  
  // ROSÉ WINES (FIVE ROSES & OTHERS)
  {
    id: 'rosato-leone-de-castris-five-roses',
    name: 'Five Roses Salento Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Malvasia Nera',
    classification: 'IGT',
    minVintage: 1943,
    avgPrice: 14,
    producers: ['Leone de Castris'],
    aliases: ['Five Roses']
  },
  {
    id: 'rosato-salice-salentino-taurino',
    name: 'Salice Salentino Rosato',
    type: 'Rosé',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'DOC',
    minVintage: 1972,
    avgPrice: 12,
    producers: ['Taurino'],
    aliases: ['Taurino Rosato']
  },
  {
    id: 'rosato-tormaresca-calafuria',
    name: 'Calafuria Rosato Salento',
    type: 'Rosé',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro, Primitivo',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Tormaresca'],
    aliases: ['Calafuria']
  },
  {
    id: 'rosato-cantele',
    name: 'Rosato Salento',
    type: 'Rosé',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 1979,
    avgPrice: 12,
    producers: ['Cantele'],
    aliases: ['Cantele Rosato']
  },
  {
    id: 'rosato-varvaglione',
    name: 'Papale Rosato Salento',
    type: 'Rosé',
    country: 'Italy',
    region: 'Puglia',
    subRegion: 'Salento',
    grapeVariety: 'Negroamaro',
    classification: 'IGT',
    minVintage: 1921,
    avgPrice: 11,
    producers: ['Varvaglione'],
    aliases: ['Papale Rosato']
  },
];
