import { WineTemplate } from '@/types/wineDatabase';

/**
 * SICILY WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Cerasuolo di Vittoria, Frappato, Grillo
 * Updated: January 2025
 */

export const sicilyPart2: WineTemplate[] = [
  // CERASUOLO DI VITTORIA DOCG
  {
    id: 'cerasuolo-vittoria-cos',
    name: 'Cerasuolo di Vittoria',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Nero d\'Avola, Frappato',
    classification: 'DOCG',
    minVintage: 1980,
    avgPrice: 32,
    producers: ['COS'],
    aliases: ['COS Cerasuolo']
  },
  {
    id: 'cerasuolo-vittoria-cos-pithos',
    name: 'Cerasuolo di Vittoria Pithos',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Nero d\'Avola, Frappato',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 55,
    producers: ['COS'],
    aliases: ['Pithos Cerasuolo']
  },
  {
    id: 'cerasuolo-vittoria-arianna-occhipinti',
    name: 'Cerasuolo di Vittoria Grotte Alte',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Nero d\'Avola, Frappato',
    classification: 'DOCG',
    minVintage: 2004,
    avgPrice: 48,
    producers: ['Arianna Occhipinti'],
    aliases: ['Grotte Alte']
  },
  {
    id: 'cerasuolo-vittoria-planeta-dorilli',
    name: 'Cerasuolo di Vittoria Dorilli',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Nero d\'Avola, Frappato',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 35,
    producers: ['Planeta'],
    aliases: ['Dorilli']
  },
  {
    id: 'cerasuolo-vittoria-gulfi',
    name: 'Cerasuolo di Vittoria Classico',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Nero d\'Avola, Frappato',
    classification: 'DOCG',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Gulfi'],
    aliases: ['Gulfi Cerasuolo']
  },
  {
    id: 'cerasuolo-vittoria-valle-galfina',
    name: 'Cerasuolo di Vittoria',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Nero d\'Avola, Frappato',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 26,
    producers: ['Valle dell\'Acate'],
    aliases: ['Valle dell\'Acate']
  },
  
  // FRAPPATO (Sicilia DOC & IGT)
  {
    id: 'frappato-arianna-occhipinti-sp68',
    name: 'SP68 Rosso Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Frappato, Nero d\'Avola',
    classification: 'IGT',
    minVintage: 2004,
    avgPrice: 32,
    producers: ['Arianna Occhipinti'],
    aliases: ['SP68']
  },
  {
    id: 'frappato-arianna-occhipinti-il-frappato',
    name: 'Il Frappato Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Frappato',
    classification: 'IGT',
    minVintage: 2004,
    avgPrice: 28,
    producers: ['Arianna Occhipinti'],
    aliases: ['Il Frappato']
  },
  {
    id: 'frappato-cos',
    name: 'Frappato Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Frappato',
    classification: 'IGT',
    minVintage: 1980,
    avgPrice: 24,
    producers: ['COS'],
    aliases: ['COS Frappato']
  },
  {
    id: 'frappato-valle-acate',
    name: 'Frappato Vittoria DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Vittoria',
    grapeVariety: 'Frappato',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Valle dell\'Acate'],
    aliases: ['Valle dell\'Acate Frappato']
  },
  
  // GRILLO (White - Sicilia DOC)
  {
    id: 'grillo-planeta',
    name: 'Grillo Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Menfi',
    grapeVariety: 'Grillo',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 16,
    producers: ['Planeta'],
    aliases: ['Planeta Grillo']
  },
  {
    id: 'grillo-donnafugata-anthilia',
    name: 'Anthilia Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Contessa Entellina',
    grapeVariety: 'Grillo, Catarratto',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 14,
    producers: ['Donnafugata'],
    aliases: ['Anthilia']
  },
  {
    id: 'grillo-donnafugata-lighea',
    name: 'Lighea Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Pantelleria',
    grapeVariety: 'Grillo',
    classification: 'DOC',
    minVintage: 2006,
    avgPrice: 18,
    producers: ['Donnafugata'],
    aliases: ['Lighea']
  },
  {
    id: 'grillo-cusumano',
    name: 'Grillo Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Alcamo',
    grapeVariety: 'Grillo',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 12,
    producers: ['Cusumano'],
    aliases: ['Cusumano Grillo']
  },
  {
    id: 'grillo-feudo-arancio',
    name: 'Grillo Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Sambuca di Sicilia',
    grapeVariety: 'Grillo',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 11,
    producers: ['Feudo Arancio'],
    aliases: ['Feudo Arancio Grillo']
  },
  {
    id: 'grillo-firriato-altavilla',
    name: 'Altavilla della Corte Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Trapani',
    grapeVariety: 'Grillo',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Firriato'],
    aliases: ['Altavilla della Corte']
  },
  
  // CATARRATTO (White)
  {
    id: 'catarratto-tasca-leone',
    name: 'Leone Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Regaleali',
    grapeVariety: 'Catarratto',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 14,
    producers: ['Tasca d\'Almerita'],
    aliases: ['Leone']
  },
  {
    id: 'catarratto-cusumano-cubìa',
    name: 'Cubìa Sicilia IGT',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Partinico',
    grapeVariety: 'Catarratto, Inzolia',
    classification: 'IGT',
    minVintage: 2002,
    avgPrice: 16,
    producers: ['Cusumano'],
    aliases: ['Cubìa']
  },
  {
    id: 'catarratto-firriato-le-sabbie',
    name: 'Le Sabbie dell\'Etna Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Catarratto',
    classification: 'IGT',
    minVintage: 2009,
    avgPrice: 22,
    producers: ['Firriato'],
    aliases: ['Le Sabbie dell\'Etna']
  },
  
  // INZOLIA/ANSONICA (White)
  {
    id: 'inzolia-planeta',
    name: 'Inzolia Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Menfi',
    grapeVariety: 'Inzolia',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 14,
    producers: ['Planeta'],
    aliases: ['Planeta Inzolia']
  },
  {
    id: 'inzolia-donnafugata-chiaranda',
    name: 'Chiarandà del Merlo Contessa Entellina DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Contessa Entellina',
    grapeVariety: 'Inzolia, Chardonnay',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 28,
    producers: ['Donnafugata'],
    aliases: ['Chiarandà']
  },
  
  // FIANO (White)
  {
    id: 'fiano-planeta',
    name: 'Fiano Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Menfi',
    grapeVariety: 'Fiano',
    classification: 'DOC',
    minVintage: 2007,
    avgPrice: 18,
    producers: ['Planeta'],
    aliases: ['Planeta Fiano']
  },
  {
    id: 'fiano-tasca',
    name: 'Fiano Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Regaleali',
    grapeVariety: 'Fiano',
    classification: 'DOC',
    minVintage: 2010,
    avgPrice: 16,
    producers: ['Tasca d\'Almerita'],
    aliases: ['Tasca Fiano']
  },
  
  // CHARDONNAY & INTERNATIONAL VARIETIES
  {
    id: 'chardonnay-planeta',
    name: 'Chardonnay Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Menfi',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 18,
    producers: ['Planeta'],
    aliases: ['Planeta Chardonnay']
  },
  {
    id: 'chardonnay-tasca-cometa',
    name: 'Chardonnay Cometa Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Regaleali',
    grapeVariety: 'Chardonnay',
    classification: 'DOC',
    minVintage: 1986,
    avgPrice: 38,
    producers: ['Tasca d\'Almerita'],
    aliases: ['Cometa']
  },
  {
    id: 'syrah-planeta',
    name: 'Syrah Sicilia DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Menfi',
    grapeVariety: 'Syrah',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 22,
    producers: ['Planeta'],
    aliases: ['Planeta Syrah']
  },
  {
    id: 'syrah-tasca-rosso',
    name: 'Rosso Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Regaleali',
    grapeVariety: 'Syrah, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 24,
    producers: ['Tasca d\'Almerita'],
    aliases: ['Tasca Rosso']
  },
  {
    id: 'cabernet-sauvignon-donnafugata-sedara',
    name: 'Sedara Sicilia DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Menfi',
    grapeVariety: 'Nero d\'Avola, Cabernet Sauvignon, Merlot, Syrah',
    classification: 'DOC',
    minVintage: 1998,
    avgPrice: 14,
    producers: ['Donnafugata'],
    aliases: ['Sedara']
  },
  
  // PERRICONE (Red)
  {
    id: 'perricone-tasca',
    name: 'Perricone Sicilia DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Regaleali',
    grapeVariety: 'Perricone',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Tasca d\'Almerita'],
    aliases: ['Tasca Perricone']
  },
  {
    id: 'perricone-firriato',
    name: 'Perricone Sicilia DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Trapani',
    grapeVariety: 'Perricone',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Firriato'],
    aliases: ['Firriato Perricone']
  },
  
  // NERELLO MASCALESE (Outside Etna)
  {
    id: 'nerello-mascalese-planeta',
    name: 'Nerello Mascalese Sicilia DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 28,
    producers: ['Planeta'],
    aliases: ['Planeta Nerello Mascalese']
  },
  {
    id: 'nerello-mascalese-tasca',
    name: 'Nerello Mascalese Sicilia DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 2007,
    avgPrice: 26,
    producers: ['Tasca d\'Almerita'],
    aliases: ['Tasca Nerello']
  },
  
  // ADDITIONAL SICILIAN PRODUCERS
  {
    id: 'sicily-cusumano-benuara',
    name: 'Benuara Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Partinico',
    grapeVariety: 'Nero d\'Avola, Merlot',
    classification: 'IGT',
    minVintage: 2003,
    avgPrice: 22,
    producers: ['Cusumano'],
    aliases: ['Benuara']
  },
  {
    id: 'sicily-firriato-camelot',
    name: 'Camelot Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Trapani',
    grapeVariety: 'Nero d\'Avola, Merlot, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2001,
    avgPrice: 38,
    producers: ['Firriato'],
    aliases: ['Camelot']
  },
  {
    id: 'sicily-feudo-montoni-vrucara',
    name: 'Vrucara Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Cammarata',
    grapeVariety: 'Nero d\'Avola',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Feudo Montoni'],
    aliases: ['Vrucara']
  },
  {
    id: 'sicily-palari-faro',
    name: 'Faro DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Messina',
    grapeVariety: 'Nerello Mascalese, Nerello Cappuccio, Nocera',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 55,
    producers: ['Palari'],
    aliases: ['Palari Faro']
  },
  {
    id: 'sicily-bonavita-mamertino',
    name: 'Mamertino di Milazzo DOC',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Messina',
    grapeVariety: 'Nero d\'Avola, Nocera',
    classification: 'DOC',
    minVintage: 2004,
    avgPrice: 28,
    producers: ['Bonavita'],
    aliases: ['Mamertino']
  },
  {
    id: 'sicily-abbazia-santa-anastasia-litra',
    name: 'Litra Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Castelbuono',
    grapeVariety: 'Nero d\'Avola',
    classification: 'IGT',
    minVintage: 2001,
    avgPrice: 35,
    producers: ['Abbazia Santa Anastasia'],
    aliases: ['Litra']
  },
  {
    id: 'sicily-tenuta-gorghi-tondi-kheirè',
    name: 'Kheirè Sicilia DOC',
    type: 'White',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Mazara del Vallo',
    grapeVariety: 'Grillo, Catarratto',
    classification: 'DOC',
    minVintage: 2006,
    avgPrice: 16,
    producers: ['Tenuta Gorghi Tondi'],
    aliases: ['Kheirè']
  },
  {
    id: 'sicily-cottanera-barbazzale',
    name: 'Barbazzale Rosso Sicilia IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Merlot, Syrah',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 42,
    producers: ['Cottanera'],
    aliases: ['Barbazzale']
  },
  {
    id: 'sicilly-barone-villagrande-etna-rosso',
    name: 'Etna Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Sicily',
    subRegion: 'Etna',
    grapeVariety: 'Nerello Mascalese',
    classification: 'DOC',
    minVintage: 1727,
    avgPrice: 28,
    producers: ['Barone di Villagrande'],
    aliases: ['Villagrande']
  },
];
