import { WineTemplate } from '@/types/wineDatabase';

/**
 * ABRUZZO WINES - Part 3 of 3 (Wines 101-150)
 * Focus: Trebbiano d'Abruzzo DOC, Blends, Other varieties
 * Updated: January 2025
 */

export const abruzzoPart3: WineTemplate[] = [
  // TREBBIANO D'ABRUZZO DOC (White)
  {
    id: 'trebbiano-valentini',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Loreto Aprutino',
    grapeVariety: 'Trebbiano Abruzzese, Bombino Bianco',
    classification: 'DOC',
    minVintage: 1650,
    avgPrice: 75,
    producers: ['Valentini'],
    aliases: ['Valentini Trebbiano']
  },
  {
    id: 'trebbiano-emidio-pepe',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Torano Nuovo',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 1964,
    avgPrice: 62,
    producers: ['Emidio Pepe'],
    aliases: ['Emidio Pepe Trebbiano']
  },
  {
    id: 'trebbiano-tiberio',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Cugnoli',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 22,
    producers: ['Tiberio'],
    aliases: ['Tiberio Trebbiano']
  },
  {
    id: 'trebbiano-masciarelli',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'San Martino sulla Marrucina',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 1981,
    avgPrice: 14,
    producers: ['Masciarelli'],
    aliases: ['Masciarelli Trebbiano']
  },
  {
    id: 'trebbiano-valle-reale',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Popoli',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Valle Reale'],
    aliases: ['Valle Reale Trebbiano']
  },
  {
    id: 'trebbiano-cataldi-madonna',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ofena',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 1920,
    avgPrice: 16,
    producers: ['Cataldi Madonna'],
    aliases: ['Cataldi Madonna Trebbiano']
  },
  {
    id: 'trebbiano-illuminati',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Controguerra',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 1890,
    avgPrice: 12,
    producers: ['Illuminati'],
    aliases: ['Illuminati Trebbiano']
  },
  {
    id: 'trebbiano-nicodemi',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Notaresco',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 13,
    producers: ['Nicodemi'],
    aliases: ['Nicodemi Trebbiano']
  },
  {
    id: 'trebbiano-zaccagnini',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Bolognano',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 11,
    producers: ['Zaccagnini'],
    aliases: ['Zaccagnini Trebbiano']
  },
  {
    id: 'trebbiano-cantina-tollo',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Tollo',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 10,
    producers: ['Cantina Tollo'],
    aliases: ['Tollo Trebbiano']
  },
  {
    id: 'trebbiano-farnese',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ortona',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 1994,
    avgPrice: 9,
    producers: ['Farnese'],
    aliases: ['Farnese Trebbiano']
  },
  {
    id: 'trebbiano-cornacchia',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Torano Nuovo',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 1970,
    avgPrice: 13,
    producers: ['Cornacchia'],
    aliases: ['Cornacchia Trebbiano']
  },
  {
    id: 'trebbiano-marramiero',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Rosciano',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 12,
    producers: ['Marramiero'],
    aliases: ['Marramiero Trebbiano']
  },
  {
    id: 'trebbiano-jasci',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Alanno',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 11,
    producers: ['Jasci'],
    aliases: ['Jasci Trebbiano']
  },
  {
    id: 'trebbiano-torre-zambra',
    name: 'Trebbiano d\'Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Teramo',
    grapeVariety: 'Trebbiano Abruzzese',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 14,
    producers: ['Torre Zambra'],
    aliases: ['Torre Zambra Trebbiano']
  },
  
  // RED BLENDS & PREMIUM WINES
  {
    id: 'montepulciano-blend-illuminati-riparosso-riserva',
    name: 'Montepulciano d\'Abruzzo Riparosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Controguerra',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 28,
    producers: ['Illuminati'],
    aliases: ['Riparosso Riserva']
  },
  {
    id: 'montepulciano-blend-illuminati-lumen',
    name: 'Lumen Colline Teramane',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Controguerra',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Illuminati'],
    aliases: ['Lumen']
  },
  {
    id: 'montepulciano-blend-masciarelli-iskra',
    name: 'Iskra Abruzzo IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'San Martino sulla Marrucina',
    grapeVariety: 'Montepulciano, Cabernet Sauvignon, Merlot',
    classification: 'IGT',
    minVintage: 2003,
    avgPrice: 65,
    producers: ['Masciarelli'],
    aliases: ['Iskra']
  },
  {
    id: 'montepulciano-blend-cataldi-madonna-malandrino-riserva',
    name: 'Montepulciano d\'Abruzzo Malandrino Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ofena',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 48,
    producers: ['Cataldi Madonna'],
    aliases: ['Malandrino Riserva']
  },
  {
    id: 'montepulciano-blend-valle-reale-vigne-nuove',
    name: 'Montepulciano d\'Abruzzo Vigne Nuove',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Popoli',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Valle Reale'],
    aliases: ['Vigne Nuove']
  },
  
  // CONTROGUERRA DOC (Various varieties)
  {
    id: 'controguerra-rosso-illuminati',
    name: 'Controguerra Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Controguerra',
    grapeVariety: 'Montepulciano, Cabernet Sauvignon, Merlot',
    classification: 'DOC',
    minVintage: 1890,
    avgPrice: 18,
    producers: ['Illuminati'],
    aliases: ['Illuminati Controguerra']
  },
  {
    id: 'controguerra-bianco-illuminati',
    name: 'Controguerra Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Controguerra',
    grapeVariety: 'Trebbiano, Passerina',
    classification: 'DOC',
    minVintage: 1890,
    avgPrice: 14,
    producers: ['Illuminati'],
    aliases: ['Illuminati Controguerra Bianco']
  },
  
  // ADDITIONAL VARIETIES & EXPERIMENTS
  {
    id: 'abruzzo-montepulciano-blend-farnese-opi',
    name: 'Opi Montepulciano d\'Abruzzo',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ortona',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Farnese'],
    aliases: ['Opi']
  },
  {
    id: 'abruzzo-montepulciano-blend-farnese-edizione',
    name: 'Edizione Cinque Autoctoni Abruzzo IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ortona',
    grapeVariety: 'Montepulciano, Primitivo, Negroamaro, Nero d\'Avola, Malvasia Nera',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 28,
    producers: ['Farnese'],
    aliases: ['Edizione Cinque Autoctoni']
  },
  {
    id: 'abruzzo-zaccagnini-cronos',
    name: 'Cronos Abruzzo IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Bolognano',
    grapeVariety: 'Montepulciano',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 42,
    producers: ['Zaccagnini'],
    aliases: ['Cronos']
  },
  {
    id: 'abruzzo-marramiero-fonte-cupa',
    name: 'Fonte Cupa Abruzzo IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Rosciano',
    grapeVariety: 'Montepulciano, Cabernet Sauvignon',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 48,
    producers: ['Marramiero'],
    aliases: ['Fonte Cupa']
  },
  {
    id: 'abruzzo-cataldi-madonna-kainos',
    name: 'Kainos Abruzzo IGT',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ofena',
    grapeVariety: 'Trebbiano, Pecorino, Passerina',
    classification: 'IGT',
    minVintage: 2010,
    avgPrice: 28,
    producers: ['Cataldi Madonna'],
    aliases: ['Kainos']
  },
  {
    id: 'abruzzo-jasci-riserva',
    name: 'Montepulciano d\'Abruzzo Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Alanno',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 24,
    producers: ['Jasci'],
    aliases: ['Jasci Riserva']
  },
  {
    id: 'abruzzo-nicodemi-riserva',
    name: 'Montepulciano d\'Abruzzo Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Notaresco',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 22,
    producers: ['Nicodemi'],
    aliases: ['Nicodemi Riserva']
  },
  {
    id: 'abruzzo-cornacchia-le-coste-riserva',
    name: 'Montepulciano d\'Abruzzo Le Coste Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Torano Nuovo',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 28,
    producers: ['Cornacchia'],
    aliases: ['Le Coste Riserva']
  },
  {
    id: 'abruzzo-agriverde-riserva',
    name: 'Montepulciano d\'Abruzzo Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Teramo',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 26,
    producers: ['Agriverde'],
    aliases: ['Agriverde Riserva']
  },
  {
    id: 'abruzzo-dora-sarchese-riserva',
    name: 'Montepulciano d\'Abruzzo Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Roseto degli Abruzzi',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Dora Sarchese'],
    aliases: ['Dora Sarchese Riserva']
  },
  {
    id: 'abruzzo-pasetti-plateo',
    name: 'Plateo Abruzzo IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Francavilla al Mare',
    grapeVariety: 'Montepulciano',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 32,
    producers: ['Pasetti'],
    aliases: ['Plateo']
  },
  {
    id: 'abruzzo-monti-rosso',
    name: 'Controguerra Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Controguerra',
    grapeVariety: 'Montepulciano, Cabernet Sauvignon',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 26,
    producers: ['Monti'],
    aliases: ['Monti Controguerra Riserva']
  },
  {
    id: 'abruzzo-filomusi-guelfi-riserva',
    name: 'Montepulciano d\'Abruzzo Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Castel del Monte',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 26,
    producers: ['Filomusi Guelfi'],
    aliases: ['Filomusi Guelfi Riserva']
  },
  {
    id: 'abruzzo-orlandi-contucci-ponno-riserva',
    name: 'Montepulciano d\'Abruzzo Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Roseto degli Abruzzi',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 32,
    producers: ['Orlandi Contucci Ponno'],
    aliases: ['Orlandi Contucci Ponno Riserva']
  },
  {
    id: 'abruzzo-praesidium-riserva',
    name: 'Montepulciano d\'Abruzzo Colline Teramane Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Teramo',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2008,
    avgPrice: 38,
    producers: ['Praesidium'],
    aliases: ['Praesidium Riserva']
  },
  {
    id: 'abruzzo-de-fermo-riserva',
    name: 'Montepulciano d\'Abruzzo Colline Teramane Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Teramo',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2010,
    avgPrice: 45,
    producers: ['De Fermo'],
    aliases: ['De Fermo Riserva']
  },
  {
    id: 'abruzzo-spinelli-riserva',
    name: 'Montepulciano d\'Abruzzo Colline Teramane Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Atri',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 2008,
    avgPrice: 42,
    producers: ['Spinelli'],
    aliases: ['Spinelli Riserva']
  },
  {
    id: 'abruzzo-lepore-riserva',
    name: 'Montepulciano d\'Abruzzo Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Alanno',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Lepore'],
    aliases: ['Lepore Riserva']
  },
  {
    id: 'abruzzo-barone-cornacchia-riserva',
    name: 'Montepulciano d\'Abruzzo Colline Teramane Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Torano Nuovo',
    grapeVariety: 'Montepulciano',
    classification: 'DOCG',
    minVintage: 1995,
    avgPrice: 45,
    producers: ['Barone Cornacchia'],
    aliases: ['Barone Cornacchia Riserva']
  },
];
