import { WineTemplate } from '@/types/wineDatabase';

/**
 * UMBRIA WINES - Part 1 of 3 (Wines 1-50)
 * Focus: Sagrantino di Montefalco DOCG, Montefalco Rosso DOC
 * Updated: January 2025
 */

export const umbriaPart1: WineTemplate[] = [
  // SAGRANTINO DI MONTEFALCO DOCG (Red)
  {
    id: 'sagrantino-arnaldo-caprai-25-anni',
    name: 'Sagrantino di Montefalco 25 Anni',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1988,
    avgPrice: 95,
    producers: ['Arnaldo Caprai'],
    aliases: ['25 Anni']
  },
  {
    id: 'sagrantino-arnaldo-caprai-collepiano',
    name: 'Sagrantino di Montefalco Collepiano',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1988,
    avgPrice: 65,
    producers: ['Arnaldo Caprai'],
    aliases: ['Collepiano']
  },
  {
    id: 'sagrantino-arnaldo-caprai',
    name: 'Sagrantino di Montefalco',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1971,
    avgPrice: 42,
    producers: ['Arnaldo Caprai'],
    aliases: ['Caprai Sagrantino']
  },
  {
    id: 'sagrantino-paolo-bea-pagliaro',
    name: 'Sagrantino di Montefalco Pagliaro',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1980,
    avgPrice: 85,
    producers: ['Paolo Bea'],
    aliases: ['Pagliaro']
  },
  {
    id: 'sagrantino-paolo-bea',
    name: 'Sagrantino di Montefalco',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1980,
    avgPrice: 58,
    producers: ['Paolo Bea'],
    aliases: ['Paolo Bea Sagrantino']
  },
  {
    id: 'sagrantino-perticaia',
    name: 'Sagrantino di Montefalco',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1974,
    avgPrice: 48,
    producers: ['Perticaia'],
    aliases: ['Perticaia Sagrantino']
  },
  {
    id: 'sagrantino-scacciadiavoli',
    name: 'Sagrantino di Montefalco',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1884,
    avgPrice: 42,
    producers: ['Scacciadiavoli'],
    aliases: ['Scacciadiavoli Sagrantino']
  },
  {
    id: 'sagrantino-adanti',
    name: 'Sagrantino di Montefalco',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1969,
    avgPrice: 45,
    producers: ['Adanti'],
    aliases: ['Adanti Sagrantino']
  },
  {
    id: 'sagrantino-antonelli-san-marco',
    name: 'Sagrantino di Montefalco',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1881,
    avgPrice: 48,
    producers: ['Antonelli San Marco'],
    aliases: ['Antonelli Sagrantino']
  },
  {
    id: 'sagrantino-tabarrini-colle-alle-macchie',
    name: 'Sagrantino di Montefalco Colle alle Macchie',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1972,
    avgPrice: 75,
    producers: ['Tabarrini'],
    aliases: ['Colle alle Macchie']
  },
  {
    id: 'sagrantino-tabarrini-campo-alla-cerqua',
    name: 'Sagrantino di Montefalco Campo alla Cerqua',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 68,
    producers: ['Tabarrini'],
    aliases: ['Campo alla Cerqua']
  },
  {
    id: 'sagrantino-tabarrini',
    name: 'Sagrantino di Montefalco',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1972,
    avgPrice: 42,
    producers: ['Tabarrini'],
    aliases: ['Tabarrini Sagrantino']
  },
  {
    id: 'sagrantino-romanelli',
    name: 'Sagrantino di Montefalco',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1960,
    avgPrice: 38,
    producers: ['Romanelli'],
    aliases: ['Romanelli Sagrantino']
  },
  {
    id: 'sagrantino-colpetrone',
    name: 'Sagrantino di Montefalco',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1995,
    avgPrice: 45,
    producers: ['Colpetrone'],
    aliases: ['Colpetrone Sagrantino']
  },
  {
    id: 'sagrantino-lungarotti',
    name: 'Sagrantino di Montefalco',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 2005,
    avgPrice: 42,
    producers: ['Lungarotti'],
    aliases: ['Lungarotti Sagrantino']
  },
  
  // SAGRANTINO DI MONTEFALCO PASSITO DOCG (Sweet)
  {
    id: 'sagrantino-passito-paolo-bea',
    name: 'Sagrantino di Montefalco Passito',
    type: 'Dessert',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1980,
    avgPrice: 75,
    producers: ['Paolo Bea'],
    aliases: ['Paolo Bea Passito']
  },
  {
    id: 'sagrantino-passito-adanti',
    name: 'Sagrantino di Montefalco Passito',
    type: 'Dessert',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 55,
    producers: ['Adanti'],
    aliases: ['Adanti Passito']
  },
  {
    id: 'sagrantino-passito-scacciadiavoli',
    name: 'Sagrantino di Montefalco Passito',
    type: 'Dessert',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sagrantino',
    classification: 'DOCG',
    minVintage: 1990,
    avgPrice: 52,
    producers: ['Scacciadiavoli'],
    aliases: ['Scacciadiavoli Passito']
  },
  
  // MONTEFALCO ROSSO DOC (Red blend)
  {
    id: 'montefalco-rosso-paolo-bea-rosso-de-veo',
    name: 'Montefalco Rosso Rosso de Veo',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino, Montepulciano',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 42,
    producers: ['Paolo Bea'],
    aliases: ['Rosso de Veo']
  },
  {
    id: 'montefalco-rosso-paolo-bea',
    name: 'Montefalco Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino, Montepulciano',
    classification: 'DOC',
    minVintage: 1980,
    avgPrice: 28,
    producers: ['Paolo Bea'],
    aliases: ['Paolo Bea Rosso']
  },
  {
    id: 'montefalco-rosso-arnaldo-caprai',
    name: 'Montefalco Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino, Merlot',
    classification: 'DOC',
    minVintage: 1971,
    avgPrice: 20,
    producers: ['Arnaldo Caprai'],
    aliases: ['Caprai Rosso']
  },
  {
    id: 'montefalco-rosso-perticaia',
    name: 'Montefalco Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino, Merlot',
    classification: 'DOC',
    minVintage: 1974,
    avgPrice: 22,
    producers: ['Perticaia'],
    aliases: ['Perticaia Rosso']
  },
  {
    id: 'montefalco-rosso-scacciadiavoli',
    name: 'Montefalco Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino',
    classification: 'DOC',
    minVintage: 1884,
    avgPrice: 18,
    producers: ['Scacciadiavoli'],
    aliases: ['Scacciadiavoli Rosso']
  },
  {
    id: 'montefalco-rosso-adanti',
    name: 'Montefalco Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino, Merlot',
    classification: 'DOC',
    minVintage: 1969,
    avgPrice: 20,
    producers: ['Adanti'],
    aliases: ['Adanti Rosso']
  },
  {
    id: 'montefalco-rosso-antonelli',
    name: 'Montefalco Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino, Merlot',
    classification: 'DOC',
    minVintage: 1881,
    avgPrice: 22,
    producers: ['Antonelli San Marco'],
    aliases: ['Antonelli Rosso']
  },
  {
    id: 'montefalco-rosso-tabarrini',
    name: 'Montefalco Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino, Merlot',
    classification: 'DOC',
    minVintage: 1972,
    avgPrice: 20,
    producers: ['Tabarrini'],
    aliases: ['Tabarrini Rosso']
  },
  {
    id: 'montefalco-rosso-romanelli',
    name: 'Montefalco Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 16,
    producers: ['Romanelli'],
    aliases: ['Romanelli Rosso']
  },
  {
    id: 'montefalco-rosso-colpetrone',
    name: 'Montefalco Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino, Merlot',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 18,
    producers: ['Colpetrone'],
    aliases: ['Colpetrone Rosso']
  },
  {
    id: 'montefalco-rosso-lungarotti',
    name: 'Montefalco Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino, Merlot',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Lungarotti'],
    aliases: ['Lungarotti Rosso']
  },
  
  // MONTEFALCO ROSSO RISERVA DOC
  {
    id: 'montefalco-rosso-riserva-arnaldo-caprai',
    name: 'Montefalco Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino, Merlot',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 32,
    producers: ['Arnaldo Caprai'],
    aliases: ['Caprai Rosso Riserva']
  },
  {
    id: 'montefalco-rosso-riserva-perticaia',
    name: 'Montefalco Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino, Merlot',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 35,
    producers: ['Perticaia'],
    aliases: ['Perticaia Riserva']
  },
  {
    id: 'montefalco-rosso-riserva-antonelli',
    name: 'Montefalco Rosso Riserva',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Sangiovese, Sagrantino, Merlot',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 32,
    producers: ['Antonelli San Marco'],
    aliases: ['Antonelli Riserva']
  },
  
  // TORGIANO ROSSO RISERVA DOCG
  {
    id: 'torgiano-rosso-riserva-lungarotti-vigna-monticchio',
    name: 'Torgiano Rosso Riserva Vigna Monticchio',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Sangiovese, Canaiolo',
    classification: 'DOCG',
    minVintage: 1974,
    avgPrice: 55,
    producers: ['Lungarotti'],
    aliases: ['Vigna Monticchio']
  },
  {
    id: 'torgiano-rosso-riserva-lungarotti',
    name: 'Torgiano Rosso Riserva Rubesco',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Sangiovese, Canaiolo',
    classification: 'DOCG',
    minVintage: 1962,
    avgPrice: 32,
    producers: ['Lungarotti'],
    aliases: ['Rubesco Riserva']
  },
  
  // TORGIANO ROSSO DOC
  {
    id: 'torgiano-rosso-lungarotti',
    name: 'Torgiano Rosso',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Sangiovese, Canaiolo',
    classification: 'DOC',
    minVintage: 1962,
    avgPrice: 16,
    producers: ['Lungarotti'],
    aliases: ['Lungarotti Rosso']
  },
  
  // PREMIUM RED BLENDS (Umbria IGT)
  {
    id: 'umbria-arnaldo-caprai-outsider',
    name: 'Outsider Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Cabernet Sauvignon, Merlot',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 38,
    producers: ['Arnaldo Caprai'],
    aliases: ['Outsider']
  },
  {
    id: 'umbria-lungarotti-san-giorgio',
    name: 'San Giorgio Umbria IGT',
    type: 'Red',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Cabernet Sauvignon, Canaiolo',
    classification: 'IGT',
    minVintage: 1977,
    avgPrice: 45,
    producers: ['Lungarotti'],
    aliases: ['San Giorgio']
  },
  {
    id: 'umbria-antinori-cervaro-della-sala',
    name: 'Cervaro della Sala Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Chardonnay, Grechetto',
    classification: 'IGT',
    minVintage: 1985,
    avgPrice: 65,
    producers: ['Antinori', 'Castello della Sala'],
    aliases: ['Cervaro della Sala']
  },
  {
    id: 'umbria-paolo-bea-arboreus',
    name: 'Arboreus Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Trebbiano Spoletino',
    classification: 'IGT',
    minVintage: 1998,
    avgPrice: 52,
    producers: ['Paolo Bea'],
    aliases: ['Arboreus']
  },
  {
    id: 'umbria-paolo-bea-santa-chiara',
    name: 'Santa Chiara Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Grechetto, Malvasia, Garganega',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 48,
    producers: ['Paolo Bea'],
    aliases: ['Santa Chiara']
  },
  {
    id: 'umbria-antonelli-grechetto',
    name: 'Grechetto Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Grechetto',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Antonelli San Marco'],
    aliases: ['Antonelli Grechetto']
  },
];
