import { WineTemplate } from '@/types/wineDatabase';

/**
 * UMBRIA WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Orvieto DOC, Orvieto Classico Superiore, Grechetto, White wines
 * Updated: January 2025
 */

export const umbriaPart2: WineTemplate[] = [
  // ORVIETO CLASSICO SUPERIORE DOC (White)
  {
    id: 'orvieto-antinori-castello-della-sala',
    name: 'Orvieto Classico Superiore Castello della Sala',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico, Chardonnay',
    classification: 'DOC',
    minVintage: 1940,
    avgPrice: 22,
    producers: ['Antinori', 'Castello della Sala'],
    aliases: ['Castello della Sala']
  },
  {
    id: 'orvieto-barberani-calcaia',
    name: 'Orvieto Classico Superiore Calcaia',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico, Verdello',
    classification: 'DOC',
    minVintage: 1961,
    avgPrice: 28,
    producers: ['Barberani'],
    aliases: ['Calcaia']
  },
  {
    id: 'orvieto-barberani-castagnolo',
    name: 'Orvieto Classico Superiore Castagnolo',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 24,
    producers: ['Barberani'],
    aliases: ['Castagnolo']
  },
  {
    id: 'orvieto-barberani',
    name: 'Orvieto Classico',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico, Verdello',
    classification: 'DOC',
    minVintage: 1961,
    avgPrice: 14,
    producers: ['Barberani'],
    aliases: ['Barberani Orvieto']
  },
  {
    id: 'orvieto-palazzone-campo-del-guardiano',
    name: 'Orvieto Classico Superiore Campo del Guardiano',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico, Verdello',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 32,
    producers: ['Palazzone'],
    aliases: ['Campo del Guardiano']
  },
  {
    id: 'orvieto-palazzone',
    name: 'Orvieto Classico Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Palazzone'],
    aliases: ['Palazzone Orvieto']
  },
  {
    id: 'orvieto-decugnano-dei-barbi-il-bianco',
    name: 'Orvieto Classico Superiore Il Bianco',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico',
    classification: 'DOC',
    minVintage: 1973,
    avgPrice: 24,
    producers: ['Decugnano dei Barbi'],
    aliases: ['Il Bianco']
  },
  {
    id: 'orvieto-decugnano-dei-barbi',
    name: 'Orvieto Classico',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico',
    classification: 'DOC',
    minVintage: 1973,
    avgPrice: 16,
    producers: ['Decugnano dei Barbi'],
    aliases: ['Decugnano Orvieto']
  },
  {
    id: 'orvieto-tenuta-le-velette',
    name: 'Orvieto Classico Superiore',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico, Verdello',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 16,
    producers: ['Tenuta Le Velette'],
    aliases: ['Le Velette Orvieto']
  },
  {
    id: 'orvieto-cardeto',
    name: 'Orvieto Classico',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 14,
    producers: ['Cardeto'],
    aliases: ['Cardeto Orvieto']
  },
  
  // ORVIETO VENDEMMIA TARDIVA (Late Harvest)
  {
    id: 'orvieto-barberani-calcaia-vendemmia-tardiva',
    name: 'Orvieto Classico Superiore Calcaia Vendemmia Tardiva',
    type: 'Dessert',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 45,
    producers: ['Barberani'],
    aliases: ['Calcaia Vendemmia Tardiva']
  },
  {
    id: 'orvieto-palazzone-muffa-nobile',
    name: 'Orvieto Classico Superiore Muffa Nobile',
    type: 'Dessert',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Procanico',
    classification: 'DOC',
    minVintage: 1995,
    avgPrice: 55,
    producers: ['Palazzone'],
    aliases: ['Muffa Nobile']
  },
  {
    id: 'orvieto-antinori-muffato-della-sala',
    name: 'Muffato della Sala',
    type: 'Dessert',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Sauvignon Blanc, Grechetto, Traminer, Sémillon',
    classification: 'IGT',
    minVintage: 1987,
    avgPrice: 75,
    producers: ['Antinori', 'Castello della Sala'],
    aliases: ['Muffato della Sala']
  },
  {
    id: 'orvieto-barberani-pulicchio',
    name: 'Orvieto Classico Superiore Pulicchio Muffa Nobile',
    type: 'Dessert',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Sauvignon Blanc',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 62,
    producers: ['Barberani'],
    aliases: ['Pulicchio']
  },
  
  // GRECHETTO (Umbria IGT)
  {
    id: 'grechetto-arnaldo-caprai',
    name: 'Grechetto Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Grechetto',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Arnaldo Caprai'],
    aliases: ['Caprai Grechetto']
  },
  {
    id: 'grechetto-adanti',
    name: 'Grechetto Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Grechetto',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Adanti'],
    aliases: ['Adanti Grechetto']
  },
  {
    id: 'grechetto-perticaia',
    name: 'Grechetto Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Grechetto',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 16,
    producers: ['Perticaia'],
    aliases: ['Perticaia Grechetto']
  },
  {
    id: 'grechetto-tabarrini',
    name: 'Grechetto Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Grechetto',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Tabarrini'],
    aliases: ['Tabarrini Grechetto']
  },
  {
    id: 'grechetto-palazzone-terre-vineate',
    name: 'Terre Vineate Grechetto Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 24,
    producers: ['Palazzone'],
    aliases: ['Terre Vineate']
  },
  
  // TREBBIANO SPOLETINO (Indigenous white variety)
  {
    id: 'trebbiano-spoletino-tabarrini',
    name: 'Trebbiano Spoletino Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Trebbiano Spoletino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 22,
    producers: ['Tabarrini'],
    aliases: ['Tabarrini Trebbiano Spoletino']
  },
  {
    id: 'trebbiano-spoletino-perticaia',
    name: 'Trebbiano Spoletino Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Trebbiano Spoletino',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Perticaia'],
    aliases: ['Perticaia Trebbiano Spoletino']
  },
  {
    id: 'trebbiano-spoletino-adanti',
    name: 'Trebbiano Spoletino Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Trebbiano Spoletino',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Adanti'],
    aliases: ['Adanti Trebbiano Spoletino']
  },
  
  // CHARDONNAY
  {
    id: 'chardonnay-lungarotti-miralduolo',
    name: 'Chardonnay Miralduolo Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 28,
    producers: ['Lungarotti'],
    aliases: ['Miralduolo']
  },
  {
    id: 'chardonnay-antinori-bramito-del-cervo',
    name: 'Bramito del Cervo Chardonnay Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 24,
    producers: ['Antinori', 'Castello della Sala'],
    aliases: ['Bramito del Cervo']
  },
  {
    id: 'chardonnay-arnaldo-caprai',
    name: 'Chardonnay Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 18,
    producers: ['Arnaldo Caprai'],
    aliases: ['Caprai Chardonnay']
  },
  
  // SAUVIGNON BLANC
  {
    id: 'sauvignon-blanc-antinori-conte-della-vipera',
    name: 'Conte della Vipera Sauvignon Blanc Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Sauvignon Blanc, Sémillon',
    classification: 'IGT',
    minVintage: 1997,
    avgPrice: 32,
    producers: ['Antinori', 'Castello della Sala'],
    aliases: ['Conte della Vipera']
  },
  {
    id: 'sauvignon-blanc-palazzone',
    name: 'Sauvignon Blanc Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Palazzone'],
    aliases: ['Palazzone Sauvignon']
  },
  
  // TORGIANO BIANCO DOC
  {
    id: 'torgiano-bianco-lungarotti-torre-di-giano',
    name: 'Torgiano Bianco Torre di Giano',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Trebbiano, Grechetto',
    classification: 'DOC',
    minVintage: 1968,
    avgPrice: 18,
    producers: ['Lungarotti'],
    aliases: ['Torre di Giano']
  },
  {
    id: 'torgiano-bianco-lungarotti-torre-di-giano-riserva',
    name: 'Torgiano Bianco Torre di Giano Riserva Vigna Il Pino',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Torgiano',
    grapeVariety: 'Trebbiano, Grechetto',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 32,
    producers: ['Lungarotti'],
    aliases: ['Torre di Giano Riserva']
  },
  
  // COLLI MARTANI DOC (White)
  {
    id: 'colli-martani-grechetto-arnaldo-caprai',
    name: 'Colli Martani Grechetto',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Colli Martani',
    grapeVariety: 'Grechetto',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 14,
    producers: ['Arnaldo Caprai'],
    aliases: ['Caprai Colli Martani']
  },
  {
    id: 'colli-martani-grechetto-adanti',
    name: 'Colli Martani Grechetto',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Colli Martani',
    grapeVariety: 'Grechetto',
    classification: 'DOC',
    minVintage: 1985,
    avgPrice: 14,
    producers: ['Adanti'],
    aliases: ['Adanti Colli Martani']
  },
  
  // ADDITIONAL PREMIUM WHITE WINES
  {
    id: 'umbria-decugnano-dei-barbi-l',
    name: 'L\' Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Chardonnay, Grechetto, Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 35,
    producers: ['Decugnano dei Barbi'],
    aliases: ['L\'']
  },
  {
    id: 'umbria-barberani-foresco',
    name: 'Foresco Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Chardonnay, Sauvignon Blanc',
    classification: 'IGT',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Barberani'],
    aliases: ['Foresco']
  },
  {
    id: 'umbria-antonelli-bianco',
    name: 'Bianco Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Grechetto, Trebbiano Spoletino',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Antonelli San Marco'],
    aliases: ['Antonelli Bianco']
  },
  {
    id: 'umbria-colpetrone-grechetto',
    name: 'Grechetto Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Grechetto',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Colpetrone'],
    aliases: ['Colpetrone Grechetto']
  },
  {
    id: 'umbria-romanelli-bianco',
    name: 'Bianco Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Grechetto',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 14,
    producers: ['Romanelli'],
    aliases: ['Romanelli Bianco']
  },
  {
    id: 'umbria-scacciadiavoli-bianco',
    name: 'Grechetto Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Montefalco',
    grapeVariety: 'Grechetto',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 14,
    producers: ['Scacciadiavoli'],
    aliases: ['Scacciadiavoli Grechetto']
  },
  {
    id: 'umbria-tenuta-le-velette-bianco',
    name: 'Bianco Umbria IGT',
    type: 'White',
    country: 'Italy',
    region: 'Umbria',
    subRegion: 'Orvieto',
    grapeVariety: 'Grechetto, Chardonnay',
    classification: 'IGT',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Tenuta Le Velette'],
    aliases: ['Le Velette Bianco']
  },
];
