import { WineTemplate } from '@/types/wineDatabase';

/**
 * ABRUZZO WINES - Part 2 of 3 (Wines 51-100)
 * Focus: Cerasuolo d'Abruzzo, Pecorino, Passerina
 * Updated: January 2025
 */

export const abruzzoPart2: WineTemplate[] = [
  // CERASUOLO D'ABRUZZO DOC (Rosé from Montepulciano)
  {
    id: 'cerasuolo-valentini',
    name: 'Cerasuolo d\'Abruzzo',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Loreto Aprutino',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1650,
    avgPrice: 65,
    producers: ['Valentini'],
    aliases: ['Valentini Cerasuolo']
  },
  {
    id: 'cerasuolo-emidio-pepe',
    name: 'Cerasuolo d\'Abruzzo',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Torano Nuovo',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1964,
    avgPrice: 58,
    producers: ['Emidio Pepe'],
    aliases: ['Emidio Pepe Cerasuolo']
  },
  {
    id: 'cerasuolo-tiberio-fonte-canale',
    name: 'Cerasuolo d\'Abruzzo Fonte Canale',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Cugnoli',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 32,
    producers: ['Tiberio'],
    aliases: ['Fonte Canale Cerasuolo']
  },
  {
    id: 'cerasuolo-tiberio',
    name: 'Cerasuolo d\'Abruzzo',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Cugnoli',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Tiberio'],
    aliases: ['Tiberio Cerasuolo']
  },
  {
    id: 'cerasuolo-masciarelli',
    name: 'Cerasuolo d\'Abruzzo',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'San Martino sulla Marrucina',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1981,
    avgPrice: 14,
    producers: ['Masciarelli'],
    aliases: ['Masciarelli Cerasuolo']
  },
  {
    id: 'cerasuolo-valle-reale',
    name: 'Cerasuolo d\'Abruzzo',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Popoli',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 16,
    producers: ['Valle Reale'],
    aliases: ['Valle Reale Cerasuolo']
  },
  {
    id: 'cerasuolo-cataldi-madonna',
    name: 'Cerasuolo d\'Abruzzo Pie delle Vigne',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ofena',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1920,
    avgPrice: 18,
    producers: ['Cataldi Madonna'],
    aliases: ['Pie delle Vigne']
  },
  {
    id: 'cerasuolo-illuminati',
    name: 'Cerasuolo d\'Abruzzo',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Controguerra',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1890,
    avgPrice: 14,
    producers: ['Illuminati'],
    aliases: ['Illuminati Cerasuolo']
  },
  {
    id: 'cerasuolo-nicodemi',
    name: 'Cerasuolo d\'Abruzzo',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Notaresco',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 14,
    producers: ['Nicodemi'],
    aliases: ['Nicodemi Cerasuolo']
  },
  {
    id: 'cerasuolo-zaccagnini',
    name: 'Cerasuolo d\'Abruzzo',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Bolognano',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1978,
    avgPrice: 12,
    producers: ['Zaccagnini'],
    aliases: ['Zaccagnini Cerasuolo']
  },
  {
    id: 'cerasuolo-farnese',
    name: 'Cerasuolo d\'Abruzzo',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ortona',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1994,
    avgPrice: 10,
    producers: ['Farnese'],
    aliases: ['Farnese Cerasuolo']
  },
  {
    id: 'cerasuolo-cantina-tollo',
    name: 'Cerasuolo d\'Abruzzo',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Tollo',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1960,
    avgPrice: 11,
    producers: ['Cantina Tollo'],
    aliases: ['Tollo Cerasuolo']
  },
  {
    id: 'cerasuolo-marramiero',
    name: 'Cerasuolo d\'Abruzzo Dama',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Rosciano',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 1990,
    avgPrice: 14,
    producers: ['Marramiero'],
    aliases: ['Dama']
  },
  {
    id: 'cerasuolo-torre-zambra',
    name: 'Cerasuolo d\'Abruzzo',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Teramo',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 16,
    producers: ['Torre Zambra'],
    aliases: ['Torre Zambra Cerasuolo']
  },
  {
    id: 'cerasuolo-jasci',
    name: 'Cerasuolo d\'Abruzzo',
    type: 'Rosé',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Alanno',
    grapeVariety: 'Montepulciano',
    classification: 'DOC',
    minVintage: 2001,
    avgPrice: 13,
    producers: ['Jasci'],
    aliases: ['Jasci Cerasuolo']
  },
  
  // PECORINO - ABRUZZO DOC (White)
  {
    id: 'pecorino-tiberio',
    name: 'Pecorino Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Cugnoli',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 24,
    producers: ['Tiberio'],
    aliases: ['Tiberio Pecorino']
  },
  {
    id: 'pecorino-valle-reale',
    name: 'Pecorino Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Popoli',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Valle Reale'],
    aliases: ['Valle Reale Pecorino']
  },
  {
    id: 'pecorino-masciarelli-marina-cvetic',
    name: 'Pecorino Abruzzo Marina Cvetic',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'San Martino sulla Marrucina',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 28,
    producers: ['Masciarelli'],
    aliases: ['Marina Cvetic Pecorino']
  },
  {
    id: 'pecorino-masciarelli',
    name: 'Pecorino Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'San Martino sulla Marrucina',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 1981,
    avgPrice: 16,
    producers: ['Masciarelli'],
    aliases: ['Masciarelli Pecorino']
  },
  {
    id: 'pecorino-illuminati',
    name: 'Pecorino Colline Teramane',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Controguerra',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Illuminati'],
    aliases: ['Illuminati Pecorino']
  },
  {
    id: 'pecorino-nicodemi',
    name: 'Pecorino Colline Teramane',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Notaresco',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Nicodemi'],
    aliases: ['Nicodemi Pecorino']
  },
  {
    id: 'pecorino-cataldi-madonna',
    name: 'Pecorino Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ofena',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 20,
    producers: ['Cataldi Madonna'],
    aliases: ['Cataldi Madonna Pecorino']
  },
  {
    id: 'pecorino-zaccagnini',
    name: 'Pecorino Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Bolognano',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Zaccagnini'],
    aliases: ['Zaccagnini Pecorino']
  },
  {
    id: 'pecorino-farnese',
    name: 'Pecorino Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ortona',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 12,
    producers: ['Farnese'],
    aliases: ['Farnese Pecorino']
  },
  {
    id: 'pecorino-cantina-tollo',
    name: 'Pecorino Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Tollo',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 11,
    producers: ['Cantina Tollo'],
    aliases: ['Tollo Pecorino']
  },
  {
    id: 'pecorino-marramiero',
    name: 'Pecorino Abruzzo Altare',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Rosciano',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Marramiero'],
    aliases: ['Altare']
  },
  {
    id: 'pecorino-jasci',
    name: 'Pecorino Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Alanno',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Jasci'],
    aliases: ['Jasci Pecorino']
  },
  {
    id: 'pecorino-torre-zambra',
    name: 'Pecorino Colline Teramane',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Teramo',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Torre Zambra'],
    aliases: ['Torre Zambra Pecorino']
  },
  {
    id: 'pecorino-cornacchia',
    name: 'Pecorino Colline Teramane',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Torano Nuovo',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Cornacchia'],
    aliases: ['Cornacchia Pecorino']
  },
  {
    id: 'pecorino-agriverde',
    name: 'Pecorino Colline Teramane',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Teramo',
    grapeVariety: 'Pecorino',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 18,
    producers: ['Agriverde'],
    aliases: ['Agriverde Pecorino']
  },
  
  // PASSERINA - ABRUZZO DOC (White)
  {
    id: 'passerina-cataldi-madonna',
    name: 'Passerina Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ofena',
    grapeVariety: 'Passerina',
    classification: 'DOC',
    minVintage: 2000,
    avgPrice: 18,
    producers: ['Cataldi Madonna'],
    aliases: ['Cataldi Madonna Passerina']
  },
  {
    id: 'passerina-valle-reale',
    name: 'Passerina Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Popoli',
    grapeVariety: 'Passerina',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 16,
    producers: ['Valle Reale'],
    aliases: ['Valle Reale Passerina']
  },
  {
    id: 'passerina-illuminati',
    name: 'Passerina Controguerra',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Controguerra',
    grapeVariety: 'Passerina',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Illuminati'],
    aliases: ['Illuminati Passerina']
  },
  {
    id: 'passerina-marramiero',
    name: 'Passerina Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Rosciano',
    grapeVariety: 'Passerina',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 14,
    producers: ['Marramiero'],
    aliases: ['Marramiero Passerina']
  },
  {
    id: 'passerina-jasci',
    name: 'Passerina Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Alanno',
    grapeVariety: 'Passerina',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 13,
    producers: ['Jasci'],
    aliases: ['Jasci Passerina']
  },
  {
    id: 'passerina-zaccagnini',
    name: 'Passerina Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Bolognano',
    grapeVariety: 'Passerina',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 12,
    producers: ['Zaccagnini'],
    aliases: ['Zaccagnini Passerina']
  },
  {
    id: 'passerina-farnese',
    name: 'Passerina Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ortona',
    grapeVariety: 'Passerina',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 11,
    producers: ['Farnese'],
    aliases: ['Farnese Passerina']
  },
  
  // COCOCCIOLA (White - rare variety)
  {
    id: 'cococciola-cataldi-madonna',
    name: 'Cococciola Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Ofena',
    grapeVariety: 'Cococciola',
    classification: 'DOC',
    minVintage: 2005,
    avgPrice: 20,
    producers: ['Cataldi Madonna'],
    aliases: ['Cataldi Madonna Cococciola']
  },
  {
    id: 'cococciola-valle-reale',
    name: 'Cococciola Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Popoli',
    grapeVariety: 'Cococciola',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 18,
    producers: ['Valle Reale'],
    aliases: ['Valle Reale Cococciola']
  },
  {
    id: 'cococciola-jasci',
    name: 'Cococciola Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Alanno',
    grapeVariety: 'Cococciola',
    classification: 'DOC',
    minVintage: 2008,
    avgPrice: 16,
    producers: ['Jasci'],
    aliases: ['Jasci Cococciola']
  },
  
  // CHARDONNAY & INTERNATIONAL VARIETIES
  {
    id: 'chardonnay-masciarelli-marina-cvetic',
    name: 'Chardonnay Abruzzo Marina Cvetic',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'San Martino sulla Marrucina',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 1991,
    avgPrice: 32,
    producers: ['Masciarelli'],
    aliases: ['Marina Cvetic Chardonnay']
  },
  {
    id: 'chardonnay-valentini',
    name: 'Chardonnay Abruzzo',
    type: 'White',
    country: 'Italy',
    region: 'Abruzzo',
    subRegion: 'Loreto Aprutino',
    grapeVariety: 'Chardonnay',
    classification: 'IGT',
    minVintage: 1990,
    avgPrice: 45,
    producers: ['Valentini'],
    aliases: ['Valentini Chardonnay']
  },
];
